### ISSUE TITLE
Ambiguous Nucleotides

### ISSUE THREAD

**Issue by gedankenstuecke** [bbuchfink/diamond#10]
Hey, 
I was a bit puzzled when DIAMOND kept crashing for me on a new sequence data set, because it worked fine all the time before. Digging into the reason it seems that the problem is the translation table when using the BLASTX setting. 

Your translation lookup table in src/basic/translate.h) is only 5x5, so I assume that besides ATGC DIAMOND will work fine with Ns as well, but the other ambiguous positions (such as R,W,Y,S,etc.) will lead to crashes. 

While it's possible to replace those characters by Ns it would be nicer if DIAMOND could take care of it right away. Either by replacing those itself or by even making use of the information and extending the translation table. 

Cheers,
Bastian

**Comment by bbuchfink** [comment]
Sorry for the late reply but I'm having serious health issues right now. Hopefully support will be available again soon.

**Comment by gedankenstuecke** [comment]
No worries, and get well soon! And thanks for thinking about adding the support!

**Comment by nekrut** [comment]
Probably related to #25 as well

**Comment by gedankenstuecke** [comment]
I think this is fixed in the latest version. Will close for now. 👍
