### ISSUE TITLE
Name space conflict with other diamond project

### ISSUE THREAD

**Issue by tillea** [bbuchfink/diamond#100]
Hi,
I'm a member of the Debian Med team and have created a package from diamond for the official Debian distribution.  It needs some time to pass the new queue but after this it will be distributed with Debian and its derivatives (Ubuntu etc.)
When doing the packaging I needed to rename it since there is another project [Diamond](https://github.com/python-diamond/Diamond).  I have choosen the name **diamond-aligner**.  The Debian Med team has to deal from time to time with this kind of name space conflicts and thus we are providing the binary also in /usr/lib/debian-med/bin to enable users using original names if using this in their PATH - but in the long run it is better not to conflict with unrelated projects' names and thus I'd recommend to find a different name.
Kind regards and thanks for providing diamond as free software
    Andreas.

**Comment by bbuchfink** [comment]
Hi,
I'll think about if and when I'm going to rename the software.
Thanks for your efforts in distributing diamond. May I ask you to keep up with my updates, it is very important to me that users use the latest version of the program.

Benjamin

**Comment by tillea** [comment]
Hi,

On Mon, Jan 09, 2017 at 06:31:20AM -0800, bbuchfink wrote:
> May I ask you to keep up with my updates, it is very important to me that users use the latest version of the program.

That's definitely the plan.  Usually we are watching release tags but if
you want to be very sure to get some response in the next couple of days
feel free to write an e-mail to debian-med-packaging@lists.alioth.debian.org.
Kind regards, Andreas.


-- 
http://fam-tille.de
