### ISSUE TITLE
Requesting DAA output causes "illegal instruction" error, while all other output formats end fine

### ISSUE THREAD

**Issue by lucventurini** [bbuchfink/diamond#102]
DIAMOND v0.8.31 (latest at the time of this writing), against Araport11. I tested all possible other output formats (compressed and not compressed), and DIAMOND always completed without a glitch.

**Comment by bbuchfink** [comment]
This error means that you need to compile diamond from source on your
system. Please see the manual for details.

2017-01-12 11:15 GMT+01:00 Luca Venturini <notifications@github.com>:

**Comment by lucventurini** [comment]
That indeed did the trick. Thanks, closing.

**Comment by ReneKat** [comment]
DIAMOND v0.9.26.127 build hf79dc1e_0 
MacOSX Mojave 10.14.6
Same error as lucventurini "Illegal instruction: 4"
I used the guide to install from source as was recommended:
 ```
wget http://github.com/bbuchfink/diamond/archive/v0.9.26.tar.gz
     tar xzf v0.9.26.tar.gz
     cd diamond-0.9.26
     mkdir bin
     cd bin
     cmake ..
     make install
```
I am a newbie and usually use conda to install packages. So, I put this file into my miniconda3; then reinstalled diamond to my environment. Which it said it was already up to date. 
Running my code again:
`diamond blastx -p 8 -d nr_20190923.dmnd -q MH_Default.contigs.fa --long-reads -f 100 --more-sensitive
`
I get the same error. Any direction would be appreciated. Thank you!
