### ISSUE TITLE
query coverage error

### ISSUE THREAD

**Issue by SirExpie** [bbuchfink/diamond#105]
I'm trying to run diamond from a website where you can give parameters such as output and query coverage. While the parameter '-o' is working, '--query-cover' gives an error:

"Error: Invalid parameter count for option '--query-cover'"

My question is what kind of input does it need, it suggests in the manual you need just a simple number "#" but the input I give is a number. Perhaps it needs a '%' symbol? When I delete the query coverage as a parameter it will run fine.

Greetings,

Patrick

**Comment by bbuchfink** [comment]
This option only takes a single number. The source of this error is
probably on the website. What site is it if I may ask?

2017-01-19 14:55 GMT+01:00 Patrick Boersma <notifications@github.com>:

**Comment by SirExpie** [comment]
I'm sorry for my late reaction. The error fixed itself somehow. Thanks for your respond.
