### ISSUE TITLE
diamond 0.8.31 dies on AMD CPUs with SIGILL

### ISSUE THREAD

**Issue by kblin** [bbuchfink/diamond#106]
Hi there,

When running DIAMOND on AMD CPUs, it seems to trigger an invalid opcode and gets terminated by SIGILL. I'm observing this on two different generations of AMD CPUs (AMD Opteron(tm) Processor 8431 and AMD Opteron(tm) Processor 6376, according to /proc/cpuinfo) when running under a current Debian jessie. The exact same binary runs fine on Intel CPUs, both Debian jessie and Ubuntu 16.04.

See below for the command line and corresponding crash.

```
diamond blastp --db /antismash-dev/antismash/generic_modules/knownclusterblast/knownclusterprots --threads 8 --query input.fasta --compress 0 --max-target-seqs 10000 --evalue 1e-05 --daa matches.daa --tmpdir /tmp
diamond v0.8.31.93 | by Benjamin Buchfink <buchfink@gmail.com>
Check http://github.com/bbuchfink/diamond for updates.

#CPU threads: 8
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
Illegal instruction (core dumped)
```

The kernel log lists `traps: diamond[3298] trap invalid opcode ip:41875b sp:7ffe9a02b670 error:0 in diamond[400000+2bc000]` when this happens.

Running diamond in gdb produces the following backtrace:

```
(gdb) bt
#0  0x000000000041875b in Config::Config(int, char const**) ()
#1  0x0000000000400f49 in main ()
```

I'm happy to provide the core dump file or the input file and database.

**Comment by bbuchfink** [comment]
Hi,
is that using the downloaded binary or was it built from source?

**Comment by kblin** [comment]
This is a static binary built from source from the 5011eaf 0-8-31-release tag.

**Comment by bbuchfink** [comment]
Was it built using cmake on the same computer where the error occurs?

**Comment by kblin** [comment]
It was build using cmake, but on an intel machine, not on either of the systems where the error occurs.

**Comment by kblin** [comment]
It does seem to work with the binary from github, so I take the error was on my side. Sorry for the noise.

**Comment by bbuchfink** [comment]
This is due to the compiler using instructions that are not available on
AMD CPUs. For best performance you should always compile it on the system
that it will run on.

**Comment by kblin** [comment]
Sure, I just have a mixed environment without build tools, and deploy docker containers.

**Comment by kblin** [comment]
Anyway, user error, thanks a lot for the fast response. I've changed my packaging script to download the binary from github instead of using a self-compiled one.
