### ISSUE TITLE
Does not build on 32bit architectures

### ISSUE THREAD

**Issue by tillea** [bbuchfink/diamond#107]
Hi,
after the package diamond-aligner was accepted in Debian it received a bug report that it [assumes uint32_t and unsigned aren't size_t](https://bugs.debian.org/852752).  Even if the main target architecture of diamond are 64bit architectures it would be nice to enable clean builds on 32bit architectures.
Kind regards, Andreas.

**Comment by bbuchfink** [comment]
Hi,
ok, I'll try to look into this.

**Comment by tillea** [comment]
Thanks

**Comment by bbuchfink** [comment]
The latest version should compile on 32 bit systems now.

**Comment by tillea** [comment]
On Fri, Feb 03, 2017 at 09:04:08AM -0800, bbuchfink wrote:
> The latest version should compile on 32 bit systems now.
Uploaded to Debian - seems to build nicely (at least for i386, slower archs need to catch up but it looks good)
Thanks a lot, Andreas.

-- 
http://fam-tille.de
