### ISSUE TITLE
Temporary file creation issue on Winserver 2012

### ISSUE THREAD

**Issue by blaize1st** [bbuchfink/diamond#108]
Hi,

Opening / creating temporary files gives an error message: "Error temporary file creation" above DIAMOND v0.8.31 version on Windows server 2012. (0.8.31 is the last working ver. on winserver). Run halted with 0 bytes temp files.

Best regards: Blaize

**Comment by bbuchfink** [comment]
Hi,
this probably has something to do with the number of open files. Please try
the parameter --bin 4 and see if that works.

**Comment by blaize1st** [comment]
Thanks, she's running smootlhy now :)

B
