### ISSUE TITLE
Default Parameter Values

### ISSUE THREAD

**Issue by adityabandla** [bbuchfink/diamond#110]
Hi,

If the following parameter values are not explicitly supplied via the command line, are any default values assumed for them?

--query cover, --id, --min-score, --evalue, --subject-cover

Best,
Aditya

**Comment by bbuchfink** [comment]
Hi,

the default behaviour is that alignments are not filtered by query cover,
id%, bit score, or subject cover, but just by evalue.

**Comment by adityabandla** [comment]
Hi Benjamin

Thank you for the reply. I assume the default e-value threshold is 0.001, as is given on the overview page

Best,
Aditya
