### ISSUE TITLE
Gene Length Normalisation

### ISSUE THREAD

**Issue by adityabandla** [bbuchfink/diamond#111]
Hi Benjamin

After aligning my reads against NR using DIAMOND, I want to normalise the counts based on gene length. Since this information is already available in the alignment output as "Subject Sequence Length", I would like to make use of it, prior to mapping the accession numbers to KEGG or SEED ID's. Thus, is it possible to extract the raw counts table from the .daa file, showing the ID of the top match, length and counts?

Best,
Aditya

**Comment by bbuchfink** [comment]
Hi,

I'm not sure what you mean. Do you need a table of all genes with their
length and the count of how many reads aligned to that gene?

2017-02-16 21:44 GMT+01:00 Aditya Bandla <notifications@github.com>:

**Comment by adityabandla** [comment]
Hi Benjamin 

Yes. I essentially want to correct for the gene length bias i.e. genes that are longer are expected to have higher counts.

**Comment by bbuchfink** [comment]
Diamond can't directly produce that kind of output for you. The way to do
it would probably be to use diamond view to generate blast tabular format
that also includes the subject length, then input this into some script
that generates the output you need.

**Comment by adityabandla** [comment]
Thanks!
