### ISSUE TITLE
missing hit

### ISSUE THREAD

**Issue by wdingx** [bbuchfink/diamond#112]
Without enabling --no-self-hits, one self-hit is surprisingly not present in the m8 file. When testing with only the related sequence as query and reference, the self-hit can be found.

The testing files are sent via Email.
GCs9_00034900608.faa
subproblem_finalRound2.faa

The same command line:
blastp --sensitive -p 32 -e 0.00001 --id 30 --query-cover 30 --subject-cover 30 -k 600 ...

**Comment by bbuchfink** [comment]
I didn't get the files by email, could you please send them?

**Comment by wdingx** [comment]
It should be delivered now.

**Comment by bbuchfink** [comment]
The problem is that this sequence appears very often as a substring in your
subject file and the program masks seeds based on their frequency. If you
use the option --more-sensitive it will mask less seeds and find the
alignments.

**Comment by wdingx** [comment]
Thanks.  The issue is that the real file's huge and --more-sensitive might really slow down the computation.
1. It could be useful to mention this masking behavior in the manual;
2. What about the speed testing and benchmarking with --more-sensitive? There is no information on this option.

**Comment by bbuchfink** [comment]
1. Yes that would be good, I also plan to replace the masking with
something better that does not depend on the frequency.
2. It should not be that much slower. If it's too slow you can try to
reduce the number of seed shapes with the -s option (16 by default).
