### ISSUE TITLE
DAA output (-f 100) not working?

### ISSUE THREAD

**Issue by yuisato** [bbuchfink/diamond#113]
I started using Diamond v0.8.36.98 with the following command:
diamond blastx -p 1 -d test_db.dmnd -q seqs.fasta --max-target-seqs 50  --more-sensitive -e 0.001 -f100

This will always display lines of error massages like these other than results:
"
.....
Processing query chunk 0, reference chunk 0, shape 15, index chunk 2.
Building reference index...  [0.000381s]
Building query index...  [0.000549s]
Building seed filter...  [0.000211s]
Searching alignments...  [0.001874s]
Processing query chunk 0, reference chunk 0, shape 15, index chunk 3.
Building reference index...  [0.000373s]
Building query index...  [0.00054s]
Building seed filter...  [0.000201s]
Searching alignments...  [0.001907s]
Deallocating buffers...  [2.7e-05s]
Computing alignments...  [0.035681s]
Deallocating reference...  [8e-06s]
Loading reference sequences...  [9e-06s]
Deallocating buffers...  [7e-06s]
Deallocating queries...  [1.9e-05s]
Loading query sequences...  [3e-05s]
Closing the input file...  [1.3e-05s]
Closing the output file... Illegal instruction
"

-f 0, 5, 6, or 101 setting will display results. What am I doing wrong? 

Thanks!!

**Comment by bbuchfink** [comment]
Please try to compile diamond from source on your system. Instructions are
in the manual.

**Comment by yuisato** [comment]
Compiled from source, she works fine now, thank you!
