### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by bioinfo17** [bbuchfink/diamond#114]
Hi, 
I get this error while running diamond blastx, command used: 

diamond blastx -d nr -q genes.fasta --sensitive -f 5 -o diamond.nr.genes.m5 --log

error:
#CPU threads: 4
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
Min_diag_score=16 space_penalty=0.757446
SEG masking = 1
SSSE3 enabled.
Reduction: [RNDQEK][C][G][H][M][F][Y][ILV][W][P][AST]
Seed frequency SD: 10
Shape configuration: 1111011111,111001101111,11101100101011,11010010111011,111010100001111,1110100011001011,11100010100101011,11011000001100111,1101010010000010111,11100001000100100111,110110000100010001101,1110000100001000101011,1101010000010001001011,1101001001000010000111,1101000100100000100000111,1110001000100000001010011
#Target sequences to report alignments for: 25
Temporary directory: 
Opening the database...  [0.00318s]
Reference = nr.dmnd
Sequences = 115041592
Letters = 42171959272
Block size = 2000000000
Opening the input file...  [0.00375s]
Opening the output file...  [0.005835s]
Loading query sequences...  [0.134052s]
Sequences = 6492, letters = 6952874, average length = 1070
Running complexity filter...  [1.41462s]
Building query histograms... Query len bounds 68 8351
Search parameters 48 29 0
 [0.373729s]
Allocating buffers...  [0.003325s]
Loading reference sequences...  [29.6313s]
Building reference histograms...  [101.373s]
Allocating buffers...  [0.003675s]
Initializing temporary storage... Async_buffer() 1082,68
 [0.847315s]
Processing query chunk 0, reference chunk 0, shape 0, index chunk 0.
Building reference index... Computing limits...  [0.003212s]
Building seed list...  [19.2879s]
Sorting seed list...  [10.989s]
 [30.3163s]
Building query index... Computing limits...  [0.002893s]
Building seed list...  [0.044651s]
Sorting seed list...  [0.03007s]
 [0.098501s]
Building seed filter... Seed frequency mean (reference) = 14.1859, SD = 229.364
Seed frequency mean (query) = 1.4627, SD = 1.81182
Masked positions = 71695130
 [1.08908s]
Searching alignments...  [5.90118s]
Processing query chunk 0, reference chunk 0, shape 0, index chunk 1.
Building reference index... Computing limits...  [0.002921s]
Building seed list...  [13.5501s]
Sorting seed list...  [11.2788s]
 [24.8564s]
Building query index... Computing limits...  [0.002844s]
Building seed list...  [0.048465s]
Sorting seed list...  [0.032061s]
 [0.107988s]
Building seed filter... Seed frequency mean (reference) = 14.0825, SD = 192.033
Seed frequency mean (query) = 1.46026, SD = 1.76257
Masked positions = 77785975
 [1.08152s]
Searching alignments...  [5.48322s]
Processing query chunk 0, reference chunk 0, shape 0, index chunk 2.
Building reference index... Computing limits...  [0.002823s]
Building seed list...  [13.945s]
Sorting seed list...  [10.7502s]
 [24.7258s]
Building query index... Computing limits...  [0.004391s]
Building seed list...  [0.048307s]
Sorting seed list...  [0.030492s]
 [0.107709s]
Building seed filter... Seed frequency mean (reference) = 13.8256, SD = 170.18
Seed frequency mean (query) = 1.44529, SD = 1.63168
Masked positions = 75332912
 [1.05321s]

Diamond version 0.0.36

Please advise, thanks

**Comment by bbuchfink** [comment]
Hi,

what is your operating system?

**Comment by bioinfo17** [comment]
RedHat Linux 6.8, 6 nodes, 96 GB RAM each, 16 cores each. Have also tried it on CentOS Linux 6.8 64 bit with 64 GB of RAM and 4 CPUSs, get the same error.

**Comment by bbuchfink** [comment]
Not sure what's the problem there, do you think you could email me your
query file? buchfink@gmail.com

**Comment by bioinfo17** [comment]
email id please?

**Comment by bbuchfink** [comment]
buchfink@gmail.com

**Comment by bbuchfink** [comment]
I'm running your data against the nr now on my system but no crash so far.
Can you tell me about your CPU, ie run `cat /proc/cpuinfo`?

**Comment by bioinfo17** [comment]
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 37
model name	: Intel(R) Xeon(R) CPU E7- 4870  @ 2.40GHz
stepping	: 1
microcode	: 55
cpu MHz		: 2397.400
cache size	: 30720 KB
physical id	: 0
siblings	: 4
core id		: 0
cpu cores	: 4
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 11
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts mmx fxsr sse sse2 ss ht syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts xtopology tsc_reliable nonstop_tsc aperfmperf unfair_spinlock pni pclmulqdq ssse3 cx16 sse4_1 sse4_2 popcnt aes hypervisor lahf_lm ida arat epb dtherm
bogomips	: 4794.80
clflush size	: 64
cache_alignment	: 64
address sizes	: 40 bits physical, 48 bits virtual
power management:

processor	: 1
vendor_id	: GenuineIntel
cpu family	: 6
model		: 37
model name	: Intel(R) Xeon(R) CPU E7- 4870  @ 2.40GHz
stepping	: 1
microcode	: 55
cpu MHz		: 2397.400
cache size	: 30720 KB
physical id	: 0
siblings	: 4
core id		: 1
cpu cores	: 4
apicid		: 1
initial apicid	: 1
fpu		: yes
fpu_exception	: yes
cpuid level	: 11
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts mmx fxsr sse sse2 ss ht syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts xtopology tsc_reliable nonstop_tsc aperfmperf unfair_spinlock pni pclmulqdq ssse3 cx16 sse4_1 sse4_2 popcnt aes hypervisor lahf_lm ida arat epb dtherm
bogomips	: 4794.80
clflush size	: 64
cache_alignment	: 64
address sizes	: 40 bits physical, 48 bits virtual
power management:

processor	: 2
vendor_id	: GenuineIntel
cpu family	: 6
model		: 37
model name	: Intel(R) Xeon(R) CPU E7- 4870  @ 2.40GHz
stepping	: 1
microcode	: 55
cpu MHz		: 2397.400
cache size	: 30720 KB
physical id	: 0
siblings	: 4
core id		: 2
cpu cores	: 4
apicid		: 2
initial apicid	: 2
fpu		: yes
fpu_exception	: yes
cpuid level	: 11
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts mmx fxsr sse sse2 ss ht syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts xtopology tsc_reliable nonstop_tsc aperfmperf unfair_spinlock pni pclmulqdq ssse3 cx16 sse4_1 sse4_2 popcnt aes hypervisor lahf_lm ida arat epb dtherm
bogomips	: 4794.80
clflush size	: 64
cache_alignment	: 64
address sizes	: 40 bits physical, 48 bits virtual
power management:

processor	: 3
vendor_id	: GenuineIntel
cpu family	: 6
model		: 37
model name	: Intel(R) Xeon(R) CPU E7- 4870  @ 2.40GHz
stepping	: 1
microcode	: 55
cpu MHz		: 2397.400
cache size	: 30720 KB
physical id	: 0
siblings	: 4
core id		: 3
cpu cores	: 4
apicid		: 3
initial apicid	: 3
fpu		: yes
fpu_exception	: yes
cpuid level	: 11
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts mmx fxsr sse sse2 ss ht syscall nx rdtscp lm constant_tsc arch_perfmon pebs bts xtopology tsc_reliable nonstop_tsc aperfmperf unfair_spinlock pni pclmulqdq ssse3 cx16 sse4_1 sse4_2 popcnt aes hypervisor lahf_lm ida arat epb dtherm
bogomips	: 4794.80
clflush size	: 64
cache_alignment	: 64
address sizes	: 40 bits physical, 48 bits virtual
power management:

**Comment by bbuchfink** [comment]
I've completed running your data but still no crash. Have you tried
compiling diamond from source on your system?

**Comment by bioinfo17** [comment]
yes I did try compiling diamond from source and it still showed the same error.

**Comment by bioinfo17** [comment]
Did you get the same line: Sequences = 6492, letters = 6952874, average length = 1070, thanks

**Comment by bioinfo17** [comment]
It works now, thanks :)

**Comment by bbuchfink** [comment]
Yes that is normal, it refers to the number of translated sequences. How
did you get it to work, what changed?

**Comment by bioinfo17** [comment]
changed location of cmake install to somewhere that I had access to and reduced the no. of threads to work on and I didn't see any segmentation fault error. Thanks for looking at it.  

    On Friday, 3 March 2017, 9:59, bbuchfink <notifications@github.com> wrote:
 

 Yes that is normal, it refers to the number of translated sequences. How
did you get it to work, what changed?
