### ISSUE TITLE
Error: error opening file nr.dmnd

### ISSUE THREAD

**Issue by AsmaTahir** [bbuchfink/diamond#115]
I am encountering an error while generating a database file. I have downloaded the FASTA .gz file (BLAST) from NCBI. The file name is nr.gz. When I am trying to make diamond database, I encounter the following error: 

"Error: Error opening file nr.dmnd"

Looking forward for your support.

**Comment by bbuchfink** [comment]
Do you have write permissions to the target directory containing the
nr.dmnd file and sufficient disk space?

**Comment by AsmaTahir** [comment]
Just added sudo before the command and it did the trick... Thank you!
