### ISSUE TITLE
OS X  v0.8.36.98  makedb error

### ISSUE THREAD

**Issue by jjv5** [bbuchfink/diamond#116]
jv5$ ./diamond makedb --in small.fa --db small
diamond v0.8.36.98 | by Benjamin Buchfink <buchfink@gmail.com>
Check http://github.com/bbuchfink/diamond for updates.

#CPU threads: 4
Database file: small.fa
Opening the database file...  [0.003038s]
Error: std::exception

Input file is very small fast protein sequences:

jjv5$ ls -l small.fa 
-rw-r--r--@ 1 jjv5  staff  1644 Mar 13 13:52 small.fa
jjv5$ head small.fa 
3546>pdb|4DG7|H Chain H, Low Resolution Structure Of Drosophila Translin
MGSSHHHHHHSSGLVPRGSHMSNFVNLDIFSNYQKYIDNEQEVRENIRIVVREIEHLSKEAQIKLQIIHS
DLSQISAACGLARKQVELCAQKYQKLAELVPAGQYYRYSDHWTFITQRLIFIIALVIYLEAGFLVTRETV
AEMLGLKISQSEGFHLDVEDYLLGILQLASELSRFATNSVTMGDYERPLNISHFIGDLNTGFRLLNLKND
GLRKRFDALKYDVKKIEEVVYDVSIRGLSSKEKDQQEEPAVPATE
>pdb|4DG7|G Chain G, Low Resolution Structure Of Drosophila Translin
MGSSHHHHHHSSGLVPRGSHMSNFVNLDIFSNYQKYIDNEQEVRENIRIVVREIEHLSKEAQIKLQIIHS
DLSQISAACGLARKQVELCAQKYQKLAELVPAGQYYRYSDHWTFITQRLIFIIALVIYLEAGFLVTRETV
AEMLGLKISQSEGFHLDVEDYLLGILQLASELSRFATNSVTMGDYERPLNISHFIGDLNTGFRLLNLKND
GLRKRFDALKYDVKKIEEVVYDVSIRGLSSKEKDQQEEPAVPATE

**Comment by bbuchfink** [comment]
Your file seems to have the string 3546 before the fasta begins with >,
please try to remove that.

**Comment by jjv5** [comment]
egad
sorry about that
works fine now
