### ISSUE TITLE
is it possible to used a nucleotide database for diamond?

### ISSUE THREAD

**Issue by ghost** [bbuchfink/diamond#117]
i know diamond was design for blastp and blastx , and it works fine for me.
is it possible to format a nucleotide database and do blastn for diamond?

**Comment by bbuchfink** [comment]
No sorry, that is not possible at the moment.

**Comment by Ferrisx4** [comment]
Is this going to be a planned feature?

**Comment by bbuchfink** [comment]
Planned yes but it's not going to be available in the near future.

**Comment by tkchafin** [comment]
I'm wondering if this was ever added? Is there any documentation on using diamond as a blastn alternative?

**Comment by bbuchfink** [comment]
> I'm wondering if this was ever added? Is there any documentation on using diamond as a blastn alternative?

We had two students develop an early prototype but it's not really scheduled for an imminent release at the moment. There are other DNA aligners available, where do you see them lacking?

**Comment by tkchafin** [comment]
We are using blastn now which is struggling with larger inputs, I was just looking into alternatives and came across this issue which was marked as completed -- since we are already using diamond for blastp/x I just thought I would check if it has been released :)
