### ISSUE TITLE
diamond view fails with `Error: Unexpected end of file.` when input .daa file contains no HSPs

### ISSUE THREAD

**Issue by kblin** [bbuchfink/diamond#119]
This is with the current 0.8.36 linux binary here from github.

When running `diamond blastp --daa output.daa --query foo.fasta --db bar` , and that produces no hits like this:

```
Reported 0 pairwise alignments, 0 HSSPs.
0 queries aligned.
```

running `diamond view --daa output.daa --out output.tab` errors out with `Error: Unexpected end of file.`.

This breaks a pipeline I'm running this workflow in. I've moved (back) to generating the tabular output from `diamond blastp` directly, which creates an empty file just as I would expect.

**Comment by bbuchfink** [comment]
Ok, will be fixed in the next release.

**Comment by bbuchfink** [comment]
Should be fixed now.
