### ISSUE TITLE
Inflate error while loading taxonomy

### ISSUE THREAD

**Issue by jregalad** [bbuchfink/diamond#120]
Hi, 
I get the following error when specifying the --taxonmap flag:

Normal diamond log
....
....
Block size = 16000000000
Loading taxonomy...  [0.005381s]
Error: Inflate error.

I use the prot_acc2tax-Nov2016.abin file provided in the MEGAN webpage. 

best, 
Julian

**Comment by bbuchfink** [comment]
Hi,
that is not the correct file, it needs to be this file from ncbi:
ftp://ftp.ncbi.nlm.nih.gov/pub/taxonomy/accession2taxid/prot.accession2taxid.gz

best regards,
Benjamin

**Comment by jregalad** [comment]
thanks!!!
