### ISSUE TITLE
makedb and fifo

### ISSUE THREAD

**Issue by rec3141** [bbuchfink/diamond#121]
Hey there, do you know why diamond won't accept input from a named pipe to makedb? It would be convenient to do 

```
mkfifo diamond-in
blastdbcmd blah blah > diamond-in &
diamond makedb --in diamond-in
```

so that I don't have to write large chunks of sequence to the disk before feeding it to diamond, but that doesn't seem to work [Error: std::exception].

thanks for any help

**Comment by bbuchfink** [comment]
Ok, I'll look into it if I can provide this feature in the next version.

**Comment by bbuchfink** [comment]
Named pipes are now supported in the latest version.
