### ISSUE TITLE
Blast2Go format issue

### ISSUE THREAD

**Issue by githubgig** [bbuchfink/diamond#122]
Hello,

I'm having an issue trying to get diamond .xml output into Blast2Go. Below is the NCBI standalone Blastp output acceptable to Blast2Go (i.e., Hit_id is populated by Accession Number and Hit_def includes description and taxonomy).
Blastp Output:
<Hit>
  <Hit_num>6</Hit_num>
  <Hit_id>XP_003217493.3</Hit_id>
  **<Hit_def>PREDICTED: glutathione peroxidase 3 [Anolis carolinensis]</Hit_def>**
  <Hit_accession>XP_003217493.3</Hit_accession>
  <Hit_len>223</Hit_len>
  <Hit_hsps>
    <Hsp>

This next section gives the Diamond output executed with --salltitles. Note that the Accession Number is integrated into the Hit_def field ahead of the description and taxonomy. This is causing issues with correctly populating the description field in Blast2Go when the .xml file is loaded. The Accession Number formats are quite variable so editing the file via command line is cumbersome and I could still end up missing out something. Is it in option to move the Accession Number to the Hit_id field?
Diamond Output:
<Hit_num>6</Hit_num>
  <Hit_id>gnl|BL_ORD_ID|87336120</Hit_id>
  **<Hit_def>XP_003217493.3 PREDICTED: glutathione peroxidase 3 [Anolis carolinensis]</Hit_def>** 
  <Hit_accession>87336120</Hit_accession>
  <Hit_len>223</Hit_len>
  <Hit_hsps>
    <Hsp>

Thanks.

**Comment by bbuchfink** [comment]
Hi,

I tried this using the latest version of BLAST and the nr database, but I
get the same format from blast than I get with diamond. Are you using the
-outfmt 5 option of blast?

  <Hit_num>1</Hit_num>
  <Hit_id>gnl|BL_ORD_ID|61806751</Hit_id>
  <Hit_def>NP_524898.1 accessory gland protein 95EF [Drosophila
melanogaster] P16548.2 RecName: Full=Accessory gland-specific peptide 95EF;
AltName: Full=Male accessory gland secretory protein 316; Flags: Precursor
AAF56263.2 accessory gland protein 95EF [Drosophila melanogaster]
ANY27729.1 GEO10212p1, partial [Drosophila melanogaster] AOQ02837.1
Acp95EF-RA, partial [synthetic construct] AOQ15218.1 Acp95EF-PA [synthetic
construct]</Hit_def>
  <Hit_accession>61806751</Hit_accession>

**Comment by githubgig** [comment]
Hi,

Thanks for the reply. Are you able to load your results into Blast2Go and get it to fully populate the Description field correctly?  

I'm using BLAST 2.2.28+ with -outfmt 5 option. This puts the Accession No. and Description in separate fields. When I load these blastp results into Blast2Go, the Description field loads entirely in the Blast2Go Description field, i.e., "PREDICTED: glutathione peroxidase 3". I was under the impression this was because in blastp output, Hit_def only contains the Description but not the Accession No. I thought the problem was with importing diamond .xml output into Blast2Go. I'm using space as a separator between Accession No. and Description. However, Blast2Go Description fields are only getting populated up to the first word, i.e., it only shows up as "PREDICTED". 

Thanks.

**Comment by bbuchfink** [comment]
I have imported the file into blast2go and the description field gets
populated correctly for me. I'll try to run diamond on the same file and
see if the import works.

**Comment by bbuchfink** [comment]
Ok, I also don't get the diamond file imported correctly. I'll work on
providing a fix for this.

**Comment by githubgig** [comment]
Thanks for taking this up, let me know if I can provide any more info that could help. Is it an idea to get diamond to put a pipe character "|" between the Accession No. and the Description? Then we could use pipe as a separator in Blast2Go.

**Comment by bbuchfink** [comment]
I changed the sequence title formatting in the latest release, blast2go
import seems to work for me now.

**Comment by yplee614** [comment]
I use the latest diamond, but the result can't import into blast2go

**Comment by yplee614** [comment]
which version of blast2go do you use?

**Comment by yplee614** [comment]
when I import the xml result to blast2go, the error output: Parse error for this part of the blast XML document: Error on line 7: Attribute name "description" associated with an element type "unknown" must be followed by the ' = ' character.

**Comment by githubgig** [comment]
Hi  Benjamin, could you please share the command you successfully used? I downloaded version 8.38 and tried blastp and then remade the database and did another blastp, but having the same original space issue with importing into Blast2Go...

**Comment by bbuchfink** [comment]
There's no particular command involved. Could you prepare a small example
that shows this problem, like one query and one database sequence only and
send it to me?

**Comment by githubgig** [comment]
Here is the example query, database, and result that I get...
[SampleFiles.zip](https://github.com/bbuchfink/diamond/files/957249/SampleFiles.zip)

**Comment by bbuchfink** [comment]
When I load the diamond file into blast2go, I get the same result as for
the blastp output file. It says "60S ribosomal protein L26 isoform X1" in
the description field. How is this different for you?
