### ISSUE TITLE
Influence of --max-target-seqs/-k on top hits returned

### ISSUE THREAD

**Issue by flopezo** [bbuchfink/diamond#123]
Dear Benjamin,

A while ago I read that BLASTP can return very different top hits depending on the number specified for -max_target_seqs. According to the NCBI, the reason for this behavior is the following: "We don't consider this a bug, but I agree that we should document this possibility better. This can happen because limits, including max target sequences, are applied in an early ungapped phase of the algorithm, as well as later. In some cases a final HSP will improve enough in the later gapped phase to rise to the top hits. In your case, relaxing the limit to 200 appears to have allowed hits that would have been excluded in the ungapped phase at 100 max target sequences to rise." Here is the link to the gist describing the unexpected behavior of BLASTP: 
https://gist.github.com/sujaikumar/504b3b7024eaf3a04ef5

In DIAMOND's manual it is suggested to set "the -k parameter (number of target sequences to report alignments for) as low as possible" to improve performance. I was wondering, however, if changing the --max-target-seqs/-k option in DIAMOND may affect the top hits returned in a similar way to what happens with BLASTP. Any help is greatly appreciated.

Federico

**Comment by bbuchfink** [comment]
Hi Federico,

the same effect can happen in Diamond because it uses similar heuristics
than Blast, in fact this is the main reason why setting a lower -k improves
performance. You can turn off this heuristic by setting --rank-ratio 0
without changing the -k parameter.

Best regards,

Benjamin

**Comment by flopezo** [comment]
Hi Benjamin,

Thank you for your answer. Just to be clear, that means that with --rank-ratio 0 the top hits returned would be the same regardless of the value set for -k (e.g., 2, 10, 25, 100)?

Best,

Federico

**Comment by bbuchfink** [comment]
Yes, exactly.

**Comment by flopezo** [comment]
Thank you!
