### ISSUE TITLE
Missing hits

### ISSUE THREAD

**Issue by Alexamk** [bbuchfink/diamond#124]
Hi,

Recently I've been using diamond to blast a large amount of proteins, but there seem to be some hits missing when comparing the output to NCBI's blast. 
I've already seen this issue raised a few times before, but even with the --sensitive and the --more-sensitive options, not all the same hits are found.
For example, I've made a database of 41 different lactobacillus genomes, and then looked how many hits were found for ftsQ, which should be highly conserved. Using the same e-values, NCBI found 60 hits from all 41 genomes. Diamond's default setting found only 7 hits, while the sensitive and more-sensitive settings both found 34 hits.
For my purpose I need to find all completely conserved proteins, so even missing a single hit is problematic. Is there a way to make the program even more sensitive or is it simply not the right program for this purpose?

Hope you can help,
Alex

**Comment by bbuchfink** [comment]
Hi Alex,

could you send me your data so I can look into this problem? If you contact
me by email (buchfink@gmail.com) I'll give you a login to my server so you
can use SCP to transfer.

Best regards,

Benjamin

**Comment by bbuchfink** [comment]
I looked at your data and the answer is that Diamond is simply not
sensitive enough for this kind of search. You are looking for twilight zone
matches down to 20% identity and bit scores as low as 28. Diamond is
designed to find signifcant hits for big database searches which means bit
scores > 50 and even then it does not have full sensitivity for twilight
zone alignments. For this kind of sensitivity blast or smith waterman tools
like ssearch or swipe are pretty much your only options.

**Comment by Alexamk** [comment]
Thats unfortunate. But thanks for looking into in and for your suggestions.

Cheers,
Alexander
________________________________
Van: bbuchfink [notifications@github.com]
Verzonden: vrijdag 14 april 2017 20:01
Aan: bbuchfink/diamond
CC: Kloosterman, A.M.; Author
Onderwerp: Re: [bbuchfink/diamond] Missing hits (#124)

I looked at your data and the answer is that Diamond is simply not
sensitive enough for this kind of search. You are looking for twilight zone
matches down to 20% identity and bit scores as low as 28. Diamond is
designed to find signifcant hits for big database searches which means bit
scores > 50 and even then it does not have full sensitivity for twilight
zone alignments. For this kind of sensitivity blast or smith waterman tools
like ssearch or swipe are pretty much your only options.
