### ISSUE TITLE
Error making NR database with Diamond BLASTx

### ISSUE THREAD

**Issue by alvizain786** [bbuchfink/diamond#125]
Hi,

Foremost, thank you for making Diamond BLASTx. Its an amazing tool use and its been a pleasure to use it for the past few years since its publication. I just noticed today that whenever I try to create the diamond BLASTx database using the compressed nr.gz file based on today's released NR database, I get returned with the following error: 

> Error: std::exception

I used the following command: 

> $ diamond makedb --in nr.gz -d nr

This error goes away if ungunzip the nr database and then try to create the database. I was wondering why is this case? 

PS: I tried it on multiple Linux machines and it has resulted in the same error. 

Also it is not due to the new version of Diamond BLASTx either from what I have checked, which is strange. I checked this on versions: (v0.8.37.99 and v0.8.36.98)

Any insight on how to work with the error is really appreciated. 

Thank you again in advance.

**Comment by bbuchfink** [comment]
Hi,

can you tell me the Linux distribution and version you are using. Also, are
you using the binary downloaded from the diamond homepage or something else?

**Comment by alvizain786** [comment]
Hi,

Yes, I have been using the binary versions of diamond blastx. Also Linux distributions and versions that it was tested on were: 

Ubuntu 14.04 LTS
Centos 6.8

I hope this helps with the diagnosis of the issue.

**Comment by bbuchfink** [comment]
I tested this with the latest nr and didn't get an error. Can you try
redownloading the file, maybe it was corrupted.

The latest diamond version fixes the unclear std::exception errors.

**Comment by alvizain786** [comment]
Hi,

Thank you for getting back. 

I double checked all the versions of diamond blastx with the updated nr database. It seems the error is gone. 

I believe, there must of have been some kind of error on NCBI's side for this to occur, which is strange. I had md5sum checked the old nr files too and everything seemed to be fine. 

Actually, I wrote a script to double check for the latest nr database in fasta format from NCBI and then create diamond BlastX database from it.  It has worked fairly well so far. 

Thank you again for checking on this.

**Comment by nick-youngblut** [comment]
I'm getting the same error when running `diamond makedb` on a custom database:

```
...
Loading sequence data (40100000 sequences processed)...  [0.537399s]
Loading sequence data (40200000 sequences processed)...  [0.524429s]
Loading sequence data (40300000 sequences processed)...  [0.53602s]
Loading sequence data (40400000 sequences processed)...  [0.526601s]
Loading sequence data (40500000 sequences processed)...  [3.3541s]
Error: std::exception
```

I've verified the formatting of the input fasta file with multiple different programs. Everything checks out. The `Error: std::exception` is really not helpful for determining what the actual problem is. Better error reporting would be super useful here.


I'm running diamond v0.8.36.98. My conda env:

```
# packages in environment at /ebio/abt3_projects/software/dev/llmgp-db/.snakemake/conda/70871121:
#
# Name                    Version                   Build  Channel
bzip2                     1.0.6             h14c3975_1002    conda-forge
diamond                   0.8.36               hdbcaa40_3    bioconda
libgcc-ng                 8.2.0                hdf63c60_1
libstdcxx-ng              8.2.0                hdf63c60_1
pigz                      2.3.4                         0    conda-forge
prodigal                  2.6.3                         1    bioconda
vsearch                   2.11.1               h76f5088_0    bioconda
zlib                      1.2.11            h14c3975_1004    conda-forge
```

Conda info:

```
     active environment : /ebio/abt3_projects/software/dev/llmgp-db/.snakemake/conda/70871121
    active env location : /ebio/abt3_projects/software/dev/llmgp-db/.snakemake/conda/70871121
            shell level : 3
       user config file : /ebio/abt3/nyoungblut/.condarc
 populated config files : /ebio/abt3_projects/software/dev/miniconda3_dev/.condarc
                          /ebio/abt3/nyoungblut/.condarc
          conda version : 4.6.13
    conda-build version : 3.11.0
         python version : 3.6.7.final.0
       base environment : /ebio/abt3_projects/software/dev/miniconda3_dev  (writable)
           channel URLs : https://conda.anaconda.org/conda-forge/linux-64
                          https://conda.anaconda.org/conda-forge/noarch
                          https://conda.anaconda.org/bioconda/linux-64
                          https://conda.anaconda.org/bioconda/noarch
                          https://repo.anaconda.com/pkgs/main/linux-64
                          https://repo.anaconda.com/pkgs/main/noarch
                          https://repo.anaconda.com/pkgs/free/linux-64
                          https://repo.anaconda.com/pkgs/free/noarch
                          https://repo.anaconda.com/pkgs/r/linux-64
                          https://repo.anaconda.com/pkgs/r/noarch
                          https://conda.anaconda.org/leylabmpi/linux-64
                          https://conda.anaconda.org/leylabmpi/noarch
                          https://conda.anaconda.org/r/linux-64
                          https://conda.anaconda.org/r/noarch
                          https://conda.anaconda.org/qiime2/linux-64
                          https://conda.anaconda.org/qiime2/noarch
          package cache : /ebio/abt3_projects/software/dev/miniconda3_dev/pkgs
                          /ebio/abt3/nyoungblut/.conda/pkgs
       envs directories : /ebio/abt3_projects/software/dev/miniconda3_dev/envs
                          /ebio/abt3/nyoungblut/.conda/envs
               platform : linux-64
             user-agent : conda/4.6.13 requests/2.18.4 CPython/3.6.7 Linux/4.9.127 ubuntu/18.04.1 glibc/2.27
                UID:GID : 6354:350
             netrc file : None
           offline mode : False
```

**Comment by bbuchfink** [comment]
If you give me the location of your input file on the cluster, I'll check it out (I'm also at MPI-EBIO).

**Comment by nick-youngblut** [comment]
I just tried uncompressing the input fasta file, and then running `diamond makedb`. This time, it worked. The `Error: std::exception` error seems to be a result of using a gzip'ed file as input.

**Comment by bbuchfink** [comment]
That's possible. The issue should be fixed in the latest version, along with the unclear error messages (I generally recommend upgrading).
