### ISSUE TITLE
Fast V. Sensitive

### ISSUE THREAD

**Issue by adityabandla** [bbuchfink/diamond#127]
Hi Benjamin

You mention in the manual, that the fast option was developed for short reads. By short, what read length do you mean?

I am a bit confused whether to go ahead with the fast or sensitive option for 250bp PE HiSeq reads

Best,
Aditya

**Comment by bbuchfink** [comment]
Hi Aditya,

I think for 250bp reads the sensitive mode would be better.

Best regards,

Benjamin

**Comment by adityabandla** [comment]
Thanks Benjamin!
