### ISSUE TITLE
Using Threads across Multiple Nodes

### ISSUE THREAD

**Issue by adityabandla** [bbuchfink/diamond#129]
Hi Benjamin

Can DIAMOND make use of multiple threads spread over multiple compute nodes? 

For instance, if I use 5 compute nodes with 24 cores each, resulting in a total of 120 cores, does mentioning -p 120 really make use of the 120 cores or does it just make 120 threads on a single node?

Cheers,
Aditya

**Comment by bbuchfink** [comment]
Hi Aditya,

that will make 120 threads on a single node, so it's not a good idea. If
you want to use 5 nodes you need to split your query file into 5 parts and
run one of them on each node.

Best regards,

Benjamin

**Comment by adityabandla** [comment]
Hi Benjamin

Thank you for the clarification! Is it advisable to split the query into smaller parts and then concatenate all the output DAA files?

Cheers,
Aditya

**Comment by bbuchfink** [comment]
DAA files cannot be concatenated, only the text-based formats.

**Comment by adityabandla** [comment]
Hi Benjamin

Thank you for the reply! Can DIAMOND be executed on GPU clusters?

Best,
Aditya

**Comment by bbuchfink** [comment]
Hi Aditya,

no Diamond does not run on GPUs.

Best regards,

Benjamin
