### ISSUE TITLE
Add a --version flag

### ISSUE THREAD

**Issue by tseemann** [bbuchfink/diamond#13]
I eventually discovered that "diamond -v" will print a version, but it wasn't obvious, as "-v" is "--verbose".

Can you add a "--version" flag?

```
% diamond --version
diamond 0.7.9
```

This will help pipelines to keep track of what version they used etc.

**Comment by bgruening** [comment]
:+1: also needed in Galaxy

**Comment by kblin** [comment]
:+1: This just made it harder to debug antiSMASH as well
