### ISSUE TITLE
concurrent jobs killed when sharing the same diamond database

### ISSUE THREAD

**Issue by grendon** [bbuchfink/diamond#130]
Hi, 

Q: does DIAMOND allow database sharing?

I was trying to run two concurrent DIAMOND jobs on the same compute node (24 CPUs and 1TB of RAM) using a single copy of the database... both jobs aborted.  BTW, I copied the database to the compute node.

**Comment by bbuchfink** [comment]
Hi,

it should be possible, I don't see how this could cause an error. What kind
of error message are you getting?

**Comment by grendon** [comment]
This is the error.

+ echo Tue Apr 25 11:04:41 CDT 2017
+ diamond blastx -p 23 -d /state/partition1/nr.dmnd -q /home/projects/..../541AC_R1.paired.fq -o 541AC_R1.paired.daa --outfmt 100 --sensitive --tmpdir /state/partition1 --evalue 1e-5 --max-target-seqs 1 -b 10.0 -v
Error: Error opening file /state/partition1/nr.dmnd
+ exitcode=1
++ date
+ echo Tue Apr 25 11:04:41 CDT 2017

I rerun it a short while ago to see if I could reproduce the error, 
but the second time it had no problems at all. 
Weird!

Thanks for the prompt reply!
