### ISSUE TITLE
Problems of the 0.8.37 and 0.8.38 version work on Ubuntu installed on VMware

### ISSUE THREAD

**Issue by DustinChen1986** [bbuchfink/diamond#131]
Hi, it's happy to report an issue here again.

Diamond work so fast that I want to try to blast some sequecnes to NR database in my PC of Windows 7, which Bio-Linux 8 (Ubuntu 14.04) was installed on VMware. The 0.8.37 and 0.8.38 version fail to work on it but 0.8.36 version still work well.

The command is "diamond blastx -q transcripts.fas -e 0.00001 --more-sensitive --salltitles -d /mnt/hgfs/E/nr_diamond/nr.dmnd -o transcripts.diamond.daa -f 100 -p 6 -t /home/manager/program/diamond". I put the database file and the query fasta file in Windows system and the temporary storage directory was set to a folder of Bio-Linux 8.

Thank you for read this and hope to provide some help to improve Diamond.

**Comment by DustinChen1986** [comment]
By the way, the Diamond 0.8.38 for Windows seems can not work well.

**Comment by bbuchfink** [comment]
Hi,

can you tell me what kind of an error message you are gettting / how the
problem presents itself?

**Comment by DustinChen1986** [comment]
If I use "diamond blastx -q transcripts.fas -e 0.00001 --more-sensitive --salltitles -d /mnt/hgfs/E/nr_diamond/nr.dmnd -o transcripts.diamond.daa -f 100 -p 6" in 0.8.36
the error message is:
Searching alignments... Error: Error writing file diamond-591d2e41-31.tmp. Disk full?
terminate called after throwing an instance of 'File_write_exception'
  what():  Error writing file diamond-591d2e41-31.tmp. Disk full?

But I still can use "diamond blastx -q transcripts.fas -e 0.00001 --more-sensitive --salltitles -d /mnt/hgfs/E/nr_diamond/nr.dmnd -o transcripts.diamond.daa -f 100 -p 6 -t /home/manager/program/diamond"

But in 0.8.37and 0.8.38, the error still can be happen with "-t".

**Comment by bbuchfink** [comment]
Not sure how this error happens. I will try to add a more detailed error
message to the next version to help track down the problem.

By the way, since there is a Windows version of diamond it would be better
to use that since running in a VM reduces performance.

**Comment by bbuchfink** [comment]
The latest version now has more detailed error messages for this, hopefully
that helps.
