### ISSUE TITLE
Diamond and paired-end reads?

### ISSUE THREAD

**Issue by casaburi** [bbuchfink/diamond#132]
Hi all,

I know Diamond does not support paired-end reads so I was wondering how do you deal with that? Is there any particular procedure that you would reccomand?

Thanks in advance,
Giorgio

**Comment by bbuchfink** [comment]
Hi,

I'm only aware of merging paired end reads, there's a lot of programs that
can do that.

Best regards,

Benjamin

**Comment by your-highness** [comment]
I would like to comment on this closed issue:

Kraken deals with read pair information by classifying each mate separately and then adding up the taxon-based classification for both mates. (Internally Kraken concatenates both mate's sequences separated by the letter "N" - Kraken does not classify k-mers containing "N")

What do you think is the best way to merge/combine the classification of two mates with DIAMOND? Especially if there are conflicting classifications.

Thanks in advance!

**Comment by bbuchfink** [comment]
It's a good question. I'm not sure what's the best way of handling paired
reads. If the classification is conflicting then you could either pick the
more specific classification, or just take the LCA of both.

**Comment by davidbio** [comment]
Taken from the manual of MEGAN6:

> This is how MEGAN honors paired reads during taxonomic assignment (currently, paired reads information
> is not used in functional analysis). Consider a pair of reads r and s. Let A and B be the taxa assigned to
> r and s by the LCA algorithm, respectively. If taxon A is undefined because r has no alignments, then we
> set A = B, and vice versa. Now assume that both A and B are defined. If A lies on or above B in the
> taxonomy, that is, if B is more specific than A, then both reads are assigned to B, and vice versa. Finally,
> if A and B are incomparable, that is, they both lie in different parts of the taxonomy, then both r and s are
> assigned to the LCA of A and B.
