### ISSUE TITLE
Problem with diamond on HPC-Cluster (binAC)

### ISSUE THREAD

**Issue by Rav8024** [bbuchfink/diamond#133]
Hello,

I am desperately trying to get diamond running on the HPC binAC. I configured the PBS script to request a full node with 28 processors with 64 GB memory. I tried diamond with -b 1 and -b 2 and --tmp /dev/shm.

Every trial ended with a segmentation fault like this:

...
Computing alignments... *** Error in `diamond': double free or corruption (fasttop): 0x00002b8a9c398b60 ***
/var/spool/torque/mom_priv/jobs/1472037.SC: line 14: 52879 Segmentation fault      diamond blastx --query NG-11936_A3_lib171480_5244_7_1.fastq.gz --db nr --daa NG-11936_A3_lib171480_5244_7_1.daa --threads 28 --tmpdir /dev/shm

Any ideas what went wrong?

Thank you

Ralf

**Comment by adityabandla** [comment]
Hi Ralf

Probably you can try setting the tmpdir to your working directory?

Regards,
Aditya

**Comment by bbuchfink** [comment]
Hi,

can you run diamond with option --log. That will create a diamond.log file
which you can send to me.

Best regards,

Benjamin

**Comment by Rav8024** [comment]
@adityabandla 
Hi Aditya,

thank you for your reply. I tried it with --tmpdir /<my_working_directory>, but that didn't work either.

Thank you,
Ralf

**Comment by Rav8024** [comment]
@bbuchfink 
Hi Benjamin,

thank you for that hint. I did the last run with --log, but diamond didn't write any "own" log-file. But I regularly get a summarized LOG-file from the "#PBS -o LOG" command which documents all my failures up to now. I'll send you this. Maybe it's helpful for your check.

Thanks,
Ralf

**Comment by davidvilanova** [comment]
I get the same problem on SGE linux cluster. 
`Error: Failed to create thread
`Also i can´t get a log file from diamond as this seems to fail without filling the log file. Looks like a problem with multiple threads.

Here is the call:
```
diamond v0.8.36.98 | by Benjamin Buchfink <buchfink@gmail.com>
Check http://github.com/bbuchfink/diamond for updates.

#CPU threads: 8
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
#Target sequences to report alignments for: 25
Temporary directory: tmp/emappertmp_dmdn_5tfhaF
Opening the database...  [0.094274s]
Opening the input file...  [0.014466s]
Opening the output file...  [0.002246s]
Loading query sequences...  [0.15366s]
Building query histograms...  [0.164861s]

Error: Failed to create thread
```

**Comment by bbuchfink** [comment]
Do other multithreaded programs work with 8 threads? It seems like the
program has no permission to create threads.

**Comment by davidvilanova** [comment]
Sure it does. Using it for 4 years now with up to 20cpus, although it is a shared cluster. What could be wrong ?

**Comment by davidvilanova** [comment]
This is the command line i´m using.
`echo "diamond blastp -d proteins.dmnd -q proteins.faa --more-sensitive --threads 8 -e 0.001000 -o analysis/emappertmp_dmdn_5tfhaF/f2f78628ce0a4dc0862fa57906fbe108 --top 3 -l diamond.log" | qsub -e err -o out -pe parallel_smp 8`

**Comment by bbuchfink** [comment]
The -l option is not correct like that, to write a log use --log without a
file name. But I don't think that's the source of this error. I have to
think about how this could happen and get back to you.

**Comment by davidvilanova** [comment]
Sorry, yes misstypo but the problem persists

**Comment by davidvilanova** [comment]
Hi found out the problem.
The database was located in a shared folder where i have read permissions. If i copy the database to my home directory everything works fine. I´m surprised as i thought that reads permissions were enough ??

**Comment by bbuchfink** [comment]
Yes read permissions to the database should be enough. Glad it works now
but I'll try to look into it.

2017-05-09 15:55 GMT+02:00 davidvilanova <notifications@github.com>:

> Hi found out the problem.
> The database was located in a shared folder where i have read permissions.
> If i copy the database to my home directory everything works fine. I´m
> surprised as i thought that reads permissions were enough ??
>

**Comment by bbuchfink** [comment]
@davidvilanova
The latest version will produce a more detailed error message in this
situation, hopefully that helps.
