### ISSUE TITLE
Thrown error invalid parameter count for option ‘—db’

### ISSUE THREAD

**Issue by LucasvdGouw** [bbuchfink/diamond#135]
Hi,

I get the following error when trying to invoke diamond blastx. Weird thing is that it does work with differnent input.

Anyone know what this error means and how to resolve it?

Kind regards, 
Lucas

**Comment by bbuchfink** [comment]
Hi,

can you give me your exact command line?

Best regards,

Benjamin

**Comment by LucasvdGouw** [comment]
Hi,

We are running diamond on a server. The exact command can not be found in the logs and this error is the only thing the user who encounterd this included. I can not replicate it.

Kind regards,
Lucas

**Comment by bbuchfink** [comment]
The message means there is some kind of error in the syntax for calling
diamond. Ask the user to check his command line, if you need my help I need
to know the exact command line.

**Comment by LucasvdGouw** [comment]
Hi,

Wouldn't the --db indicate a problem with the database selection?

Kind regards,
Lucas

2017-05-09 16:17 GMT+02:00 bbuchfink <notifications@github.com>:

**Comment by bbuchfink** [comment]
It means there's not enough or too many parameters for that option. This
needs to be the path to the database. So it's something like
--db --(other option)
--db xxx yyy

**Comment by jaidevjoshi83** [comment]
I was encountering this error because of '-daa' rather '--daa'.
