### ISSUE TITLE
Support multiple (compressed, if possible) FASTA files when building a database

### ISSUE THREAD

**Issue by terrycojones** [bbuchfink/diamond#136]
It would be great if DIAMOND could read from multiple files when making a database, and even better if compressed (gzip, ideally, at least for me) files could be handled. This would make it easy to build databases for large sequence sets that are already in that format. E.g., the NCBI bacterial refseq database comes in 385 gzipped files, occupying 12.5GB. It's a pain to decompress all that data into a single FASTA file just for DIAMOND. Thanks!

**Comment by bbuchfink** [comment]
Diamond can read gzipped files. You can also concatenate multiple gzipped
files and input that into Diamond, that will work. But I'll try to work on
supporting multiple files directly.

2017-05-12 18:39 GMT+02:00 Terry Jones <notifications@github.com>:

**Comment by terrycojones** [comment]
Ah, ok, I didn't know that (I think I tried it at one point, perhaps before it was supported, but maybe I'm just not remembering correctly). Re catting multiple files, it would be great if DIAMOND could read its database FASTA from `stdin` (I think I tried that too). Then there would be no need to cat all the `*.gz` files onto the filesystem.

Thanks!  BTW, we cited DIAMOND in a paper that was submitted a few weeks ago :-)

**Comment by bbuchfink** [comment]
Reading from stdin is now supported.

**Comment by terrycojones** [comment]
Great!

**Comment by terrycojones** [comment]
I guess this can be closed. Maybe the docs could be updated to show how to deal with multiple compressed files. Thanks a lot.
