### ISSUE TITLE
taxonmap flag returns 0 value for all staxids in output format 6

### ISSUE THREAD

**Issue by Sidkib** [bbuchfink/diamond#137]
I ran this command :
`diamond view --taxonmap prot.accession2taxid.gz --daa P8_blastx96_nr_20170515.blastx.try2.daa --out P8_blastx96_nr_20170515.blastx.outfmt6 --outfmt 6 qseqid sseqid pident staxids
`
The output file had zeros for all staxids. I realized that the program does not load the taxonomy for some reason, the stdout shows no steps to load the accession2taxid file.
stdout: 
```
diamond v0.8.37.99 | by Benjamin Buchfink <buchfink@gmail.com>
Check http://github.com/bbuchfink/diamond for updates.

#CPU threads: 16
Scoring parameters: (Matrix=custom Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 122307828
DB sequences used = 276556
DB letters = 44884498527
Generating output...  [0.445111s]
```

Furthermore, when providing the --taxonmap flag with a random path (a path that does not lead to any file) the command still ran, no errors. I have had the same results with 0.8.38 and 0.8.37, both versions compiled on my machine.

Any ideas on what might be causing this issue ?

**Comment by bbuchfink** [comment]
Sorry I should have mentioned that. The taxon mapping does not work with
the daa format, only if you directly generate the tabular output.

**Comment by Sidkib** [comment]
Thanks for the quick clarification !
