### ISSUE TITLE
Diamond on Galaxy main instance

### ISSUE THREAD

**Issue by SilviaRaineri** [bbuchfink/diamond#138]
Hello! Me and others are still experiencing a problem with the Diamond Galaxy version 
![screenshot from 2017-05-16 11-20-34](https://cloud.githubusercontent.com/assets/27766721/26208073/1a0f4414-3be1-11e7-85fd-a408ace640d5.png)
(diamond-makedb is working, but the Diamond tool itself isn't - at least, not in the main Galaxy instance). Whenever I try to run a job, the output says insufficient arguments, use diamond -h for help (see attachment). Here is what I found regarding the version of the tool:
Galaxy Tool ID: toolshed.g2.bx.psu.edu/repos/bgruening/diamond/bg_diamond/0.1.6.0 Galaxy Tool (but when you try to reach this page, it gives an error)
Version: 0.1.6.0 This tool requires diamond (Version 0.6.13)
Job dependencies diamond tool_shed_package 0.6.13

I know this problem has been discussed before @bgruening , but as I am using the main Galaxy site I don't know how to update this tool. Can anyone help?

**Comment by bgruening** [comment]
@SilviaRaineri I will take care of this. Just need some time, hopefully at the weekend.
