### ISSUE TITLE
tinythread.cpp: error: ‘runtime_error’ is not a member of ‘std’

### ISSUE THREAD

**Issue by sjackman** [bbuchfink/diamond#139]
My best guess is that `src/util/tinythread.cpp` is missing `#include <stdexcept>`
http://en.cppreference.com/w/cpp/error/runtime_error
https://github.com/bbuchfink/diamond/blob/master/src/util/tinythread.cpp#L24

```
/home/linuxbrew/.linuxbrew/Library/Homebrew/shims/linux/super/g++-4.8   -I/tmp/diamond-20170522-19452-iczlfa/diamond-0.9.1/src -I/home/linuxbrew/.linuxbrew/include  -march=native -Wall -Wno-uninitialized -Wno-deprecated-declarations -Wno-ignored-attributes -Wno-unused-variable -DNDEBUG   -o CMakeFiles/diamond.dir/src/util/tinythread.cpp.o -c /tmp/diamond-20170522-19452-iczlfa/diamond-0.9.1/src/util/tinythread.cpp
/tmp/diamond-20170522-19452-iczlfa/diamond-0.9.1/src/util/tinythread.cpp: In constructor ‘tthread::thread::thread(void (*)(void*), void*)’:
/tmp/diamond-20170522-19452-iczlfa/diamond-0.9.1/src/util/tinythread.cpp:219:23: error: ‘runtime_error’ is not a member of ‘std’
    case EAGAIN: throw std::runtime_error("pthread_create error: Insufficient resources to create another thread, or a system-imposed limit on the number of threads was encountered.");
```
https://travis-ci.org/Homebrew/homebrew-science/builds/234831366#L1974

Downstream issue: https://github.com/Homebrew/homebrew-science/pull/5733#issuecomment-303467323

**Comment by bbuchfink** [comment]
Ok, will be fixed. Sorry, these missing includes sometimes happen between
releases.

**Comment by sjackman** [comment]
No worries. You could if you like use a CI system such as TravisCI or CircleCI to test your builds with a variety of compiler versions. It's pretty easy to set up. See for example
https://github.com/bcgsc/abyss/blob/master/.travis.yml

**Comment by ilovezfs** [comment]
Gentle ping on this.

**Comment by bbuchfink** [comment]
Should be fixed now.

**Comment by ilovezfs** [comment]
@bbuchfink thanks. I've refreshed https://github.com/Homebrew/homebrew-science/pull/5733.

**Comment by bbuchfink** [comment]
By the way diamond does not depend on boost any more, that seems to be
still in there.

**Comment by ilovezfs** [comment]
@bbuchfink thanks, fixed: https://github.com/Homebrew/homebrew-science/pull/5748

**Comment by eiffelhack** [comment]
wow thank
