### ISSUE TITLE
--seg option not anymore?

### ISSUE THREAD

**Issue by beacamara** [bbuchfink/diamond#140]
Hello,
I am looking for the --seg option in this diamond version. This options when is turn on enables masking low complexity regions  of  the query sequence. I have seen in the new version of diamond this option is turn on by default.

"Low complexity masking is applied to the query and reference sequences by default. Masked
residues appear in the output as X."

 I would like to know if it is possible to deactivate it, as it was possible on the diamond version v.0.7.1

Thank you so much 

Beatriz

**Comment by bbuchfink** [comment]
Hi Beatriz,

you can turn it off using --masking 0. However certain parts of the
algorithm currently depend on the masking and performance could degrade
badly if you turn it off. You should see if it works on your data, if not
you need to use version 0.8.38 until I provide an update that fixes this
issue.

Best regards,

Benjamin

**Comment by beacamara** [comment]
Thank you so much for your answer. I will use version 0.8.38, until you can provide an update to fixex this issue.

Best regards,

Beatriz

**Comment by Stikus** [comment]
Hello, any news?
https://github.com/humanlongevity/HLA using this option as you can see [here](https://github.com/humanlongevity/HLA/blob/master/bin/align.pl#L63): 
```
open(IN, "diamond blastx -t . -C 20000 --index-mode 1 --seg no --min-score 10 --top 20 -c 1 -d $root/data/hla -q $fastq_file -f tab --quiet -o /dev/stdout |") or die $!;
```

And when I tried to update diamond to last version I found this error. As tool is not developing I can patch it locally but I need advice about better patch for this issue.
Can anyone help me?

**Comment by bbuchfink** [comment]
These parameters are for a very old version. You should remove `-C`, replace `--index-mode` with `--sensitive` and `--seg` with `--masking 0`.

**Comment by Stikus** [comment]
Thank you for answer, I'll try.
Should I remove `-С` entirely or there are any replacement?

**Comment by bbuchfink** [comment]
The `--freq-sd` parameter roughly corresponds to this. See the manual for a description, but you can probably leave this at default.
