### ISSUE TITLE
Error while makedb: Sequence of length 0

### ISSUE THREAD

**Issue by MichaelsGITIGIT** [bbuchfink/diamond#141]
I have a faa file of about 11Gb. Now I would like to generate a diamond db from it.

Version: 0.9.3.104

Call:
`diamond makedb --in in.faa -d prot`

I always encounter the following error:
`Error: File format error: sequence of length 0 at line 13213539`

But If I check this line (and its surrounding lines) I don't see anything suspicious:

```
>CYU22937.1 Uncharacterised protein [Streptococcus suis]
MAKTMISPVELYSNELAQALLETSKYRLEASVAHQIARQYASQVDFEDPILMHVGVNSIASTLIDKIKPEYFQTTS
>CYU22909.1 Uncharacterised protein [Streptococcus suis]
MDLSSKQIKNLSHNKWYHATLKRHLSSLLEGIKVDYNLGHELDFGAGFYITSDFQQAQKYINRLVEFLNTNKAGAEFLGNMDEEGIILEFELTDFPSIFTTSNYKCHYFKSHNISDDVIDFAEFVFQNRLRSKERIHDFDFIYGVQTDDNPTGLLQKYKAGLVSKADVLNEFRKPFSFKQLSIHNQEFCDIMKVTKIYLSKDGKELDQWQKQ
>CYU22888.1 membrane protein [Streptococcus suis]
MKRLFSFVRVASLVMLFSGCQTIYASSPSSEPNSQPVAISVHPQASEQSNAKGQVTENVDANNQDYEITDSVATKRQFVTFTSKSGKVFHLIIDHDKGGQNVQLLTEVSEQDLLNLVESTDTVAVKPQKVEEVVDDKPVKNEEPKQKSSAGSYIIIGLFLLGVLCVGYYIKVIKPKKEHHFEEFEEDDDYISDGEEEV
```

Now, either there is another problem or I am checking the wrong lines. However, I checked several times.

**Comment by bbuchfink** [comment]
I don't see how this error could happen unfortunately. Would it be possible
to make your file available to me?

**Comment by MichaelsGITIGIT** [comment]
I could do that. First, allow me a second question: By `line 13213539` you mean litteraly the 13213539th line of the input file and not the nth entry in the fasta file?

**Comment by bbuchfink** [comment]
Yes it refers to the line number.

**Comment by MichaelsGITIGIT** [comment]
How would you like to have the file delivered?

**Comment by MichaelsGITIGIT** [comment]
Hmmm... could it be that I have some carriage return characters? Would that maybe explain the error?

**Comment by bbuchfink** [comment]
If a line ends with carriage return, then line feed, it shouldn't be a
problem. But other than that it could cause an error yes.

Not sure how to best transfer big files if you're under linux.

**Comment by MichaelsGITIGIT** [comment]
I might upload to my own server... Let's see.

**Comment by MichaelsGITIGIT** [comment]
OK, I generated a subset of the file which triggers the error. The error occurs at the end of the file.

You can get it here:
https://thvd.net/owncloud/index.php/s/OJcRDs1KHlG13Ad

**Comment by bbuchfink** [comment]
The archive seems to be corrupted, I'm unable to unpack it.

**Comment by MichaelsGITIGIT** [comment]
Sorry, will check tomorrow.

**Comment by MichaelsGITIGIT** [comment]
There was an error during upload, apparently.
Now it should be fine, I checked:
https://thvd.net/owncloud/index.php/s/Z51eiMT505SOUvU/download

**Comment by bbuchfink** [comment]
There was a bug that caused a wrong line number to be printed. The problem
is at line 12523047 in your file where there's an empty sequence.

**Comment by MichaelsGITIGIT** [comment]
Thx a lot! Do you know when you will have a fixed version available?

**Comment by bbuchfink** [comment]
I have just commited a patch that will ignore empty sequences instead of
generating an error.
