### ISSUE TITLE
problem: src/data/taxonomy.cpp: In member function ‘void Taxonomy::load()’: src/data/taxonomy.cpp:34:57: error: ‘sscanf’ was not declared in this scope    if (sscanf(f.line.c_str(), "%*s%15s%u%*u", acc, &taxid) != 2) {

### ISSUE THREAD

**Issue by fredericokremer** [bbuchfink/diamond#143]
I'm having the error message "src/data/taxonomy.cpp: In member function ‘void Taxonomy::load()’:
src/data/taxonomy.cpp:34:57: error: ‘sscanf’ was not declared in this scope
   if (sscanf(f.line.c_str(), "%*s%15s%u%*u", acc, &taxid) != 2) {" when trying to compile the program using the build_simple.sh script. How can i fixt it?

**Comment by fredericokremer** [comment]
Obs: i'm using an Ubuntu 16.04 LTS system.

**Comment by bbuchfink** [comment]
Should be fixed in the latest version.
