### ISSUE TITLE
Issue while running Diamond within Humann2

### ISSUE THREAD

**Issue by bobems1215** [bbuchfink/diamond#145]
Hello, 
I recently switched servers and was debugging the install of humann2 but I came across this error but can not figure out what the error actually is. Just curious if anyone can shed some light on this. 
"CRITICAL ERROR: Error executing: /storage/home/rgn5011/bin/diamond blastx --query /gpfs/home/rgn5011/scratch/output/Sample_C1_R1_humann2_temp/Sample_C1_R1_bowtie2_unaligned.fa --evalue 1.0 --threads 8 --max-target-seqs 20 --outfmt 6 --db /gpfs/work/r/rgn5011/humann2-0.11.1/databases/uniref/uniref90_annotated.1.1 --out /gpfs/home/rgn5011/scratch/output/Sample_C1_R1_humann2_temp/tmpL8YFgM/diamond_m8_UGS4ze --tmpdir /gpfs/home/rgn5011/scratch/output/Sample_C1_R1_humann2_temp/tmpL8YFgM

Error message returned from diamond :
diamond v0.8.22.84 | by Benjamin Buchfink <buchfink@gmail.com>
Check http://github.com/bbuchfink/diamond for updates.

#CPU threads: 8
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
#Target sequences to report alignments for: 20
Temporary directory: /gpfs/home/rgn5011/scratch/output/Sample_C1_R1_humann2_temp/tmpL8YFgM
Opening the database...  [0.000199s]
Opening the input file...  [0.003175s]
Opening the output file...  [0.000117s]
Loading query sequences...  [47.0424s]
Running complexity filter...  [109.779s]
Building query histograms...  [5.93051s]
Allocating buffers...  [0.000561s]
Loading reference sequences...  [5.10093s]
Building reference histograms...  [9.92921s]
Allocating buffers...  [0.000312s]
Initializing temporary storage...  [0.023176s]
Processing query chunk 0, reference chunk 0, shape 0, index chunk 0.
Building reference index...  [12.482s]
Building query index... "

I was looking at other errors and usually this output ends with a description of the error but this does not have any description of the actual error. 
Thanks,
Bob

**Comment by bbuchfink** [comment]
Hi,

could you try the same thing with the latest version of diamond?

Best regards,

Benjamin

2017-06-08 17:30 GMT+02:00 bobems1215 <notifications@github.com>:

**Comment by bobems1215** [comment]
Hi Benjamin,
I updated diamond and found out that the reference database that I need to run Humann2 was built with version 0.8.22 so they are not compatible with the newest version. Also I can run this same run on a different server with the same versions and databases and It works fine.

**Comment by bbuchfink** [comment]
You can use the 0.8.22 version like:
diamond getseq -d dbfile

to get the database in fasta format then build a new database from that
with the latest version. It would help to know if the error also occurs in
the latest version.

**Comment by bobems1215** [comment]
Hi Benjamin,
I updated the database and tried to re run the sample and got the same error. 
"
CRITICAL ERROR: Error executing: /storage/home/rgn5011/bin/diamond blastx --query /gpfs/home/rgn5011/scratch/output/Sample_C1_R1_humann2_temp/Sample_C1_R1_bowtie2_unaligned.fa --evalue 1.0 --threads 8 --max-target-seqs 20 --outfmt 6 --db /gpfs/work/r/rgn5011/humann2-0.11.1/databases/uniref/uniref90_annotated.v9 --out /gpfs/home/rgn5011/scratch/output/Sample_C1_R1_humann2_temp/tmpctkW_B/diamond_m8_il4fej --tmpdir /gpfs/home/rgn5011/scratch/output/Sample_C1_R1_humann2_temp/tmpctkW_B

Error message returned from diamond :
diamond v0.9.6.107 | by Benjamin Buchfink <buchfink@gmail.com>
Licensed under the GNU AGPL <https://www.gnu.org/licenses/agpl.txt>
Check http://github.com/bbuchfink/diamond for updates.

#CPU threads: 8
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
#Target sequences to report alignments for: 20
Temporary directory: /gpfs/home/rgn5011/scratch/output/Sample_C1_R1_humann2_temp/tmpctkW_B
Opening the database...  [0.046414s]
Opening the input file...  [0.000209s]
Opening the output file...  [0.000256s]
Loading query sequences...  [17.8274s]
Masking queries...  [102.94s]
Building query seed set...  [0.088939s]
Algorithm: Double-indexed
Building query histograms...  [6.05146s]
Allocating buffers...  [0.00023s]
Loading reference sequences...  [5.96862s]
Building reference histograms...  [5.77942s]
Allocating buffers...  [5e-05s]
Initializing temporary storage...  [0.069757s]
Processing query chunk 0, reference chunk 0, shape 0, index chunk 0.
Building reference index...  [11.1121s]
Building query index... "
Thank you again for all  the help

**Comment by bbuchfink** [comment]
Hi,

could you try to run this with a debugger? Compile the program using cmake
as described in the manual, but use the command line
cmake -DCMAKE_BUILD_TYPE=Debug ..

Then run the binary like this:
gdb --args ./diamond <rest of your command line>

In gdb, type run to run diamond. When the error occurs, type bt to get a
backtrace, and send it to me.

Best regards,

Benjamin

**Comment by bobems1215** [comment]
Hey Benjamin,
When I ran it with gdb I did get an extra line at the bottom of the output saying "the program was terminated with the signal SIGKILL" and then "The program no longer exists" so when I run a backtrace it says "No Stack".
It seem like this has something to do with the server that I am using.
Thanks,
Bob

**Comment by bbuchfink** [comment]
You could try to call dmesg after it fails, to check the kernel messages
and see why it has been killed.

**Comment by bobems1215** [comment]
Ah finally, it did say I ran out of memory. I think I just need to change the directory that I was working in and move some stuff around. Thank you for all the help, I will update this if anymore issues come up. 
Thanks,
Bob

**Comment by antgomes** [comment]
Hello guys,

I tried to run Humann2 and ended up with the same CRITICAL ERROR in the `diamond blastx --query`step. 
I updated diamond to its last version and downloaded the uniref90 database, I created the dmnd file and it seems to be working now.

However, how do I go from the uniref90 database to uniref90_annotated or uniref90_ec_filtered_diamond? Also, what exactly is the difference between the files `uniref90.fasta`, `uniref90_annotated`and `uniref90_ec_filtered_diamond`?

Thank you!

**Comment by bbuchfink** [comment]
Hi,

I can't really answer that since I'm not familiar with Humann2. You should
probably ask at the Humann2 support forum.

**Comment by antgomes** [comment]
Hello bbuchfink,

Thank you for the reply! I will ask the question at Humann2 discussion group!

**Comment by Manimaran-nema** [comment]
diamond v0.9.14.115 | by Benjamin Buchfink <buchfink@gmail.com>
Licensed under the GNU AGPL <https://www.gnu.org/licenses/agpl.txt>
Check http://github.com/bbuchfink/diamond for updates.

#CPU threads: 4
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
#Target sequences to report alignments for: 25
Temporary directory: 
Opening the database...  [2.5e-05s]
Opening the input file...  [0.021681s]
Opening the output file...  [6.3e-05s]
Loading query sequences...  [2.98312s]
Masking queries...  [103.096s]
Building query seed set...  [0.104871s]
Algorithm: Double-indexed
Building query histograms...  [11.2808s]
Allocating buffers...  [9.4e-05s]
Loading reference sequences...  [30.4971s]
Building reference histograms...  [6.06886s]
Allocating buffers...  [5.9e-05s]
Initializing temporary storage...  [0.001919s]
Processing query chunk 0, reference chunk 0, shape 0, index chunk 0.
Building reference index... Killed

I am repeatedly getting this.., can you  help me in fixing this?

**Comment by bbuchfink** [comment]
Sorry for the late reply. This message likely means the program ran out of memory. You can try to reduce the block size as described here: http://www.diamondsearch.org/index.php?pages/command_line_options/#memory-performance-options

**Comment by Bon-jour** [comment]
Hello, when I was running Human3 recently, the program ran to Diamond Blastx - query and was interrupted without any error messages. My server has a running memory of 700G, storage space of 10T, CPU 112, and the Diamond version is the latest. I hope to receive your reply. The following are the log logs:

10/12/2023 08:58:28 AM - humann.humann - INFO: Running humann v3.6
10/12/2023 08:58:28 AM - humann.humann - INFO: Output files will be written to: /data/workdirV6/5.metacyc/humann2
10/12/2023 08:58:28 AM - humann.humann - INFO: Writing temp files to directory: /data/workdirV6/5.metacyc/humann2/KO-CLP2_paired_humann_temp
10/12/2023 08:58:28 AM - humann.humann - INFO: Removing spaces from identifiers in input file
10/12/2023 08:59:38 AM - humann.utilities - DEBUG: Check software, metaphlan, for required version, 3.0
10/12/2023 08:59:39 AM - humann.utilities - INFO: Using metaphlan version 3.1
10/12/2023 08:59:39 AM - humann.utilities - DEBUG: Check software, bowtie2, for required version, 2.2
10/12/2023 08:59:39 AM - humann.utilities - INFO: Using bowtie2 version 2.5
10/12/2023 08:59:39 AM - humann.utilities - DEBUG: Check software, diamond, for required version, 2.0.15
10/12/2023 08:59:39 AM - humann.utilities - INFO: Using diamond version 2.1.8
10/12/2023 08:59:39 AM - humann.config - INFO: 
Run config settings: 

DATABASE SETTINGS
nucleotide database folder = /data/db/full_chocophlan.v201901_v31
protein database folder = /data/db/uniref90_annotated_v201901b
pathways database file 1 = /root/miniconda3/envs/Rdoc/lib/python3.9/site-packages/humann/data/pathways/metacyc_reactions_level4ec_only.uniref.bz2
pathways database file 2 = /root/miniconda3/envs/Rdoc/lib/python3.9/site-packages/humann/data/pathways/metacyc_pathways_structured_filtered_v24
utility mapping database folder = /data/db/full_mapping_v201901b

RUN MODES
resume = False
verbose = False
bypass prescreen = False
bypass nucleotide index = False
bypass nucleotide search = False
bypass translated search = False
translated search = diamond
threads = 20

SEARCH MODE
search mode = uniref90
nucleotide identity threshold = 0.0
translated identity threshold = 80.0

ALIGNMENT SETTINGS
bowtie2 options = --very-sensitive
diamond options = --top 1 --outfmt 6
evalue threshold = 1.0
prescreen threshold = 0.01
translated subject coverage threshold = 50.0
translated query coverage threshold = 90.0
nucleotide subject coverage threshold = 50.0
nucleotide query coverage threshold = 90.0

PATHWAYS SETTINGS
minpath = on
xipe = off
gap fill = on

INPUT AND OUTPUT FORMATS
input file format = fastq
output file format = tsv
output max decimals = 10
remove stratified output = False
remove column description output = False
log level = DEBUG

10/12/2023 08:59:39 AM - humann.store - DEBUG: Initialize Alignments class instance to minimize memory use
10/12/2023 08:59:39 AM - humann.store - DEBUG: Initialize Reads class instance to minimize memory use
10/12/2023 09:00:05 AM - humann.humann - INFO: Load pathways database part 1: /root/miniconda3/envs/Rdoc/lib/python3.9/site-packages/humann/data/pathways/metacyc_reactions_level4ec_only.uniref.bz2
10/12/2023 09:00:05 AM - humann.humann - INFO: Load pathways database part 2: /root/miniconda3/envs/Rdoc/lib/python3.9/site-packages/humann/data/pathways/metacyc_pathways_structured_filtered_v24
10/12/2023 09:00:05 AM - humann.search.prescreen - INFO: Running metaphlan ........
10/12/2023 09:00:05 AM - humann.utilities - DEBUG: Using software: /root/miniconda3/envs/Rdoc/bin/metaphlan
10/12/2023 09:00:05 AM - humann.utilities - DEBUG: Remove file: /data/workdirV6/5.metacyc/humann2/KO-CLP2_paired_humann_temp/KO-CLP2_paired_metaphlan_bugs_list.tsv
10/12/2023 09:00:05 AM - humann.utilities - DEBUG: Remove file: /data/workdirV6/5.metacyc/humann2/KO-CLP2_paired_humann_temp/KO-CLP2_paired_metaphlan_bowtie2.txt
10/12/2023 09:00:05 AM - humann.utilities - INFO: Execute command: /root/miniconda3/envs/Rdoc/bin/metaphlan /data/workdirV6/5.metacyc/humann2/KO-CLP2_paired_humann_temp/tmpdjuiu7jk/tmph0chl_y8 -t rel_ab -o /data/workdirV6/5.metacyc/humann2/KO-CLP2_paired_humann_temp/KO-CLP2_paired_metaphlan_bugs_list.tsv --input_type fastq --bowtie2out /data/workdirV6/5.metacyc/humann2/KO-CLP2_paired_humann_temp/KO-CLP2_paired_metaphlan_bowtie2.txt --nproc 20
10/12/2023 09:07:19 AM - humann.utilities - DEBUG: b'WARNING: The metagenome profile contains clades that represent multiple species merged into a single representant.\nAn additional column listing the merged species is added to the MetaPhlAn output.\n'
10/12/2023 09:07:19 AM - humann.humann - INFO: TIMESTAMP: Completed 	prescreen 	:	 434	 seconds
10/12/2023 09:07:19 AM - humann.search.prescreen - INFO: Found g__Akkermansia.s__Akkermansia_muciniphila : 56.81% of mapped reads
10/12/2023 09:07:19 AM - humann.search.prescreen - INFO: Found g__Prevotella.s__Prevotella_sp_MGM1 : 14.02% of mapped reads
10/12/2023 09:07:19 AM - humann.search.prescreen - INFO: Found g__Muribaculaceae_unclassified.s__Muribaculaceae_bacterium_DSM_103720 : 7.54% of mapped reads
10/12/2023 09:07:19 AM - humann.search.prescreen - INFO: Found g__Muribaculum.s__Muribaculum_intestinale : 6.04% of mapped reads
10/12/2023 09:07:19 AM - humann.search.prescreen - INFO: Found g__Mucispirillum.s__Mucispirillum_schaedleri : 4.06% of mapped reads
10/12/2023 09:07:19 AM - humann.search.prescreen - INFO: Found g__Bacteroides.s__Bacteroides_caecimuris : 2.66% of mapped reads
10/12/2023 09:07:19 AM - humann.search.prescreen - INFO: Found g__Lactobacillus.s__Lactobacillus_murinus : 2.41% of mapped reads
10/12/2023 09:07:19 AM - humann.search.prescreen - INFO: Found g__Bacteroides.s__Bacteroides_uniformis : 1.90% of mapped reads
10/12/2023 09:07:19 AM - humann.search.prescreen - INFO: Found g__Bifidobacterium.s__Bifidobacterium_pseudolongum : 1.54% of mapped reads
10/12/2023 09:07:19 AM - humann.search.prescreen - INFO: Found g__Anaerotruncus.s__Anaerotruncus_sp_G3_2012 : 1.42% of mapped reads
10/12/2023 09:07:19 AM - humann.search.prescreen - INFO: Found g__Firmicutes_unclassified.s__Firmicutes_bacterium_ASF500 : 0.87% of mapped reads
10/12/2023 09:07:19 AM - humann.search.prescreen - INFO: Found g__Enterorhabdus.s__Enterorhabdus_caecimuris : 0.51% of mapped reads
10/12/2023 09:07:19 AM - humann.search.prescreen - INFO: Found g__Acutalibacter.s__Acutalibacter_muris : 0.12% of mapped reads
10/12/2023 09:07:19 AM - humann.search.prescreen - INFO: Found g__Lactobacillus.s__Lactobacillus_johnsonii : 0.05% of mapped reads
10/12/2023 09:07:19 AM - humann.search.prescreen - INFO: Found g__Lachnospiraceae_unclassified.s__Lachnospiraceae_bacterium_A4 : 0.03% of mapped reads
10/12/2023 09:07:19 AM - humann.search.prescreen - INFO: Total species selected from prescreen: 15
10/12/2023 09:07:19 AM - humann.search.prescreen - DEBUG: Adding file to database: g__Acutalibacter.s__Acutalibacter_muris.centroids.v201901_v31.ffn.gz
10/12/2023 09:07:19 AM - humann.search.prescreen - DEBUG: Adding file to database: g__Akkermansia.s__Akkermansia_muciniphila.centroids.v201901_v31.ffn.gz
10/12/2023 09:07:19 AM - humann.search.prescreen - DEBUG: Adding file to database: g__Anaerotruncus.s__Anaerotruncus_sp_G3_2012.centroids.v201901_v31.ffn.gz
10/12/2023 09:07:19 AM - humann.search.prescreen - DEBUG: Adding file to database: g__Bacteroides.s__Bacteroides_caecimuris.centroids.v201901_v31.ffn.gz
10/12/2023 09:07:19 AM - humann.search.prescreen - DEBUG: Adding file to database: g__Bacteroides.s__Bacteroides_uniformis.centroids.v201901_v31.ffn.gz
10/12/2023 09:07:19 AM - humann.search.prescreen - DEBUG: Adding file to database: g__Bifidobacterium.s__Bifidobacterium_pseudolongum.centroids.v201901_v31.ffn.gz
10/12/2023 09:07:19 AM - humann.search.prescreen - INFO: Creating custom ChocoPhlAn database ........
10/12/2023 09:07:19 AM - humann.utilities - DEBUG: Remove file: /data/workdirV6/5.metacyc/humann2/KO-CLP2_paired_humann_temp/KO-CLP2_paired_custom_chocophlan_database.ffn
10/12/2023 09:07:19 AM - humann.utilities - DEBUG: Using software: /usr/bin/gunzip
10/12/2023 09:07:19 AM - humann.utilities - INFO: Execute command: /usr/bin/gunzip -c /data/db/full_chocophlan.v201901_v31/g__Acutalibacter.s__Acutalibacter_muris.centroids.v201901_v31.ffn.gz /data/db/full_chocophlan.v201901_v31/g__Akkermansia.s__Akkermansia_muciniphila.centroids.v201901_v31.ffn.gz /data/db/full_chocophlan.v201901_v31/g__Anaerotruncus.s__Anaerotruncus_sp_G3_2012.centroids.v201901_v31.ffn.gz /data/db/full_chocophlan.v201901_v31/g__Bacteroides.s__Bacteroides_caecimuris.centroids.v201901_v31.ffn.gz /data/db/full_chocophlan.v201901_v31/g__Bacteroides.s__Bacteroides_uniformis.centroids.v201901_v31.ffn.gz /data/db/full_chocophlan.v201901_v31/g__Bifidobacterium.s__Bifidobacterium_pseudolongum.centroids.v201901_v31.ffn.gz
10/12/2023 09:07:19 AM - humann.humann - INFO: TIMESTAMP: Completed 	custom database creation 	:	 1	 seconds
10/12/2023 09:07:19 AM - humann.search.nucleotide - INFO: Running bowtie2-build ........
10/12/2023 09:07:19 AM - humann.utilities - DEBUG: Using software: /root/miniconda3/envs/Rdoc/bin/bowtie2-build
10/12/2023 09:07:19 AM - humann.utilities - DEBUG: Remove file: /data/workdirV6/5.metacyc/humann2/KO-CLP2_paired_humann_temp/KO-CLP2_paired_bowtie2_index.1.bt2
10/12/2023 09:07:19 AM - humann.utilities - DEBUG: Remove file: /data/workdirV6/5.metacyc/humann2/KO-CLP2_paired_humann_temp/KO-CLP2_paired_bowtie2_index.2.bt2
10/12/2023 09:07:19 AM - humann.utilities - DEBUG: Remove file: /data/workdirV6/5.metacyc/humann2/KO-CLP2_paired_humann_temp/KO-CLP2_paired_bowtie2_index.3.bt2
10/12/2023 09:07:19 AM - humann.utilities - DEBUG: Remove file: /data/workdirV6/5.metacyc/humann2/KO-CLP2_paired_humann_temp/KO-CLP2_paired_bowtie2_index.4.bt2
10/12/2023 09:07:19 AM - humann.utilities - DEBUG: Remove file: /data/workdirV6/5.metacyc/humann2/KO-CLP2_paired_humann_temp/KO-CLP2_paired_bowtie2_index.rev.1.bt2
10/12/2023 09:07:19 AM - humann.utilities - DEBUG: Remove file: /data/workdirV6/5.metacyc/humann2/KO-CLP2_paired_humann_temp/KO-CLP2_paired_bowtie2_index.rev.2.bt2
10/12/2023 09:07:19 AM - humann.utilities - INFO: Execute command: /root/miniconda3/envs/Rdoc/bin/bowtie2-build -f /data/workdirV6/5.metacyc/humann2/KO-CLP2_paired_humann_temp/KO-CLP2_paired_custom_chocophlan_database.ffn /data/workdirV6/5.metacyc/humann2/KO-CLP2_paired_humann_temp/KO-CLP2_paired_bowtie2_index
10/12/2023 09:08:03 AM - humann.humann - INFO: TIMESTAMP: Completed 	database index 	:	 44	 seconds
10/12/2023 09:08:03 AM - humann.search.nucleotide - DEBUG: Nucleotide input file is of type: fastq
10/12/2023 09:08:03 AM - humann.utilities - DEBUG: Using software: /root/miniconda3/envs/Rdoc/bin/bowtie2
10/12/2023 09:08:06 AM - humann.utilities - DEBUG: Remove file: /data/workdirV6/5.metacyc/humann2/KO-CLP2_paired_humann_temp/KO-CLP2_paired_bowtie2_aligned.sam
10/12/2023 09:08:06 AM - humann.utilities - INFO: Execute command: /root/miniconda3/envs/Rdoc/bin/bowtie2 -q -x /data/workdirV6/5.metacyc/humann2/KO-CLP2_paired_humann_temp/KO-CLP2_paired_bowtie2_index -U /data/workdirV6/5.metacyc/humann2/KO-CLP2_paired_humann_temp/tmpdjuiu7jk/tmph0chl_y8 -S /data/workdirV6/5.metacyc/humann2/KO-CLP2_paired_humann_temp/KO-CLP2_paired_bowtie2_aligned.sam -p 20 --very-sensitive
10/12/2023 09:10:28 AM - humann.utilities - DEBUG: b'38883128 reads; of these:\n  38883128 (100.00%) were unpaired; of these:\n    35594883 (91.54%) aligned 0 times\n    2611167 (6.72%) aligned exactly 1 time\n    677078 (1.74%) aligned >1 times\n8.46% overall alignment rate\n'
10/12/2023 09:10:28 AM - humann.humann - INFO: TIMESTAMP: Completed 	nucleotide alignment 	:	 145	 seconds
10/12/2023 09:16:36 AM - humann.utilities - DEBUG: Total alignments where percent identity is not a number: 0
10/12/2023 09:16:36 AM - humann.utilities - DEBUG: Total alignments where alignment length is not a number: 0
10/12/2023 09:16:36 AM - humann.utilities - DEBUG: Total alignments where E-value is not a number: 0
10/12/2023 09:16:36 AM - humann.utilities - DEBUG: Total alignments not included based on large e-value: 0
10/12/2023 09:16:36 AM - humann.utilities - DEBUG: Total alignments not included based on small percent identity: 0
10/12/2023 09:16:36 AM - humann.utilities - DEBUG: Total alignments not included based on small query coverage: 0
10/12/2023 09:16:51 AM - humann.search.blastx_coverage - INFO: Total alignments without coverage information: 0
10/12/2023 09:16:51 AM - humann.search.blastx_coverage - INFO: Total proteins in blastx output: 16680
10/12/2023 09:16:51 AM - humann.search.blastx_coverage - INFO: Total proteins without lengths: 0
10/12/2023 09:16:51 AM - humann.search.blastx_coverage - INFO: Proteins with coverage greater than threshold (50.0): 13562
10/12/2023 09:24:58 AM - humann.search.nucleotide - DEBUG: Total nucleotide alignments not included based on filtered genes: 57651
10/12/2023 09:24:58 AM - humann.search.nucleotide - DEBUG: Total nucleotide alignments not included based on small percent identities: 0
10/12/2023 09:24:58 AM - humann.search.nucleotide - DEBUG: Total nucleotide alignments not included based on query coverage threshold: 0
10/12/2023 09:24:58 AM - humann.search.nucleotide - DEBUG: Keeping sam file
10/12/2023 09:25:02 AM - humann.humann - INFO: TIMESTAMP: Completed 	nucleotide alignment post-processing 	:	 873 seconds
10/12/2023 09:25:02 AM - humann.humann - INFO: Total bugs from nucleotide alignment: 6
10/12/2023 09:25:02 AM - humann.humann - INFO: 
g__Akkermansia.s__Akkermansia_muciniphila: 1691152 hits
g__Bacteroides.s__Bacteroides_uniformis: 763026 hits
g__Bacteroides.s__Bacteroides_caecimuris: 565914 hits
g__Anaerotruncus.s__Anaerotruncus_sp_G3_2012: 157958 hits
g__Bifidobacterium.s__Bifidobacterium_pseudolongum: 26752 hits
g__Acutalibacter.s__Acutalibacter_muris: 25792 hits
10/12/2023 09:25:02 AM - humann.humann - INFO: Total gene families from nucleotide alignment: 13562
10/12/2023 09:25:02 AM - humann.humann - INFO: Unaligned reads after nucleotide alignment: 91.6915274923 %
10/12/2023 09:25:02 AM - humann.search.translated - INFO: Running diamond ........
10/12/2023 09:25:02 AM - humann.search.translated - INFO: Aligning to reference database: uniref90_201901b_full.dmnd
10/12/2023 09:25:02 AM - humann.utilities - DEBUG: Remove file: /data/workdirV6/5.metacyc/humann2/KO-CLP2_paired_humann_temp/tmpdjuiu7jk/diamond_m8_306u_70h
10/12/2023 09:25:02 AM - humann.utilities - DEBUG: Using software: /root/miniconda3/envs/Rdoc/bin/diamond
10/12/2023 09:25:02 AM - humann.utilities - INFO: Execute command: /root/miniconda3/envs/Rdoc/bin/diamond blastx --query /data/workdirV6/5.metacyc/humann2/KO-CLP2_paired_humann_temp/KO-CLP2_paired_bowtie2_unaligned.fa --evalue 1.0 --threads 20 --top 1 --outfmt 6 --db /data/db/uniref90_annotated_v201901b/uniref90_201901b_full --out /data/workdirV6/5.metacyc/humann2/KO-CLP2_paired_humann_temp/tmpdjuiu7jk/diamond_m8_306u_70h --tmpdir /data/workdirV6/5.metacyc/humann2/KO-CLP2_paired_humann_temp/tmpdjuiu7jk

**Comment by Bon-jour** [comment]
But when there are no other programs running on the server, the analysis of a single sample will not report an error,

**Comment by bbuchfink** [comment]
@Bon-jour it's hard to say without an error message. You have to try to run this diamond call in isolation without humann to get more info.
