### ISSUE TITLE
Searching alignments... Killed

### ISSUE THREAD

**Issue by internet-nobody** [bbuchfink/diamond#146]
Hi,
This is probably quite a basic question but, I've been running diamond on a batch of files (48, they are 24 paired end libraries) that have all been created as output from the same program, then converted to fasta. All the files under 300mb run through fine, but those 300-500 all stop at this point:

> Initializing temporary storage...  [0.002858s]
Processing query chunk 0, reference chunk 0, shape 0, index chunk 0.
Building reference index...  [108.398s]
Building query index...  [1.94595s]
Building seed filter...  [3.11884s]
Searching alignments... Killed

I wondered if it might be memory based, because it runs if I change -b 16 to -b 4 (I've not tried others, it just seemed logical to drop it right down in case that was the issue), system has 64gb RAM), but if I don't allocate enough then it dies with a pretty clear error about failing to allocate sufficient memory in the first place. Has anyone else experienced this/is able to shed any light on what might be going wrong for the code to die there?
Thanks

**Comment by bbuchfink** [comment]
Hi,

if it runs out of memory, there should be an error message and not just a
crash like this, so it seems like a bug. Can you tell me what version of
diamond you are using?

**Comment by internet-nobody** [comment]
Its v0.9.5.106

**Comment by bbuchfink** [comment]
Could you try to run diamond with a debugger attached? I've described here
how to do it:
https://github.com/bbuchfink/diamond/issues/145

**Comment by internet-nobody** [comment]
For reference, the original was with the precompiled binary of 0.9.5.106.

Full output:

> Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
diamond v0.9.6.107 | by Benjamin Buchfink <buchfink@gmail.com>
Licensed under the GNU AGPL <https://www.gnu.org/licenses/agpl.txt>
Check http://github.com/bbuchfink/diamond for updates.

#CPU threads: 10
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
#Target sequences to report alignments for: 25
Temporary directory: /home/ubuntu/tmp/
Opening the database...  [0.002499s]
Opening the input file...  [0.002122s]
Opening the output file...  [0.000238s]
Loading query sequences...  [7.2902s]
Masking queries... [New Thread 0x7fffecf6a700 (LWP 26167)]
[New Thread 0x7fffec769700 (LWP 26168)]
[New Thread 0x7fffebf68700 (LWP 26169)]
[New Thread 0x7fffeb767700 (LWP 26170)]
[New Thread 0x7fffeaf66700 (LWP 26171)]
[New Thread 0x7fffea765700 (LWP 26172)]
[New Thread 0x7fffe9f64700 (LWP 26173)]
[New Thread 0x7fffe9763700 (LWP 26174)]
[New Thread 0x7fffe8f62700 (LWP 26175)]
[New Thread 0x7fffe8761700 (LWP 26176)]
[Thread 0x7fffe8761700 (LWP 26176) exited]
[Thread 0x7fffe8f62700 (LWP 26175) exited]
[Thread 0x7fffe9763700 (LWP 26174) exited]
[Thread 0x7fffe9f64700 (LWP 26173) exited]
[Thread 0x7fffea765700 (LWP 26172) exited]
[Thread 0x7fffeaf66700 (LWP 26171) exited]
 [26.0599s]
Building query seed set... [Thread 0x7fffeb767700 (LWP 26170) exited]
[Thread 0x7fffebf68700 (LWP 26169) exited]
[Thread 0x7fffec769700 (LWP 26168) exited]
[Thread 0x7fffecf6a700 (LWP 26167) exited]
[New Thread 0x7fffe8761700 (LWP 26177)]
 [0.118627s]
Algorithm: Double-indexed
Building query histograms... [Thread 0x7fffe8761700 (LWP 26177) exited]
[New Thread 0x7fffe8761700 (LWP 26178)]
[New Thread 0x7fffe8f62700 (LWP 26179)]
[New Thread 0x7fffe9763700 (LWP 26180)]
[New Thread 0x7fffe9f64700 (LWP 26181)]
[New Thread 0x7fffecf6a700 (LWP 26182)]
[New Thread 0x7fffec769700 (LWP 26183)]
[New Thread 0x7fffebf68700 (LWP 26184)]
[New Thread 0x7fffeb767700 (LWP 26185)]
[New Thread 0x7fffeaf66700 (LWP 26186)]
[New Thread 0x7fffea765700 (LWP 26187)]
[Thread 0x7fffebf68700 (LWP 26184) exited]
[Thread 0x7fffeb767700 (LWP 26185) exited]
[Thread 0x7fffe9763700 (LWP 26180) exited]
[Thread 0x7fffecf6a700 (LWP 26182) exited]
[Thread 0x7fffeaf66700 (LWP 26186) exited]
[Thread 0x7fffe8761700 (LWP 26178) exited]
[Thread 0x7fffe9f64700 (LWP 26181) exited]
[Thread 0x7fffe8f62700 (LWP 26179) exited]
[Thread 0x7fffec769700 (LWP 26183) exited]
 [1.43473s]
Allocating buffers...  [0.00013s]
Loading reference sequences... [Thread 0x7fffea765700 (LWP 26187) exited]
 [205.355s]
Building reference histograms... [New Thread 0x7fffea765700 (LWP 26195)]
[New Thread 0x7fffeaf66700 (LWP 26196)]
[New Thread 0x7fffeb767700 (LWP 26197)]
[New Thread 0x7fffebf68700 (LWP 26198)]
[New Thread 0x7fffecf6a700 (LWP 26199)]
[New Thread 0x7fffec769700 (LWP 26200)]
[New Thread 0x7fffe9f64700 (LWP 26201)]
[New Thread 0x7fffe9763700 (LWP 26202)]
[New Thread 0x7fffe8f62700 (LWP 26203)]
[New Thread 0x7fffe8761700 (LWP 26204)]
[Thread 0x7fffec769700 (LWP 26200) exited]
[Thread 0x7fffe9763700 (LWP 26202) exited]
[Thread 0x7fffe8761700 (LWP 26204) exited]
[Thread 0x7fffea765700 (LWP 26195) exited]
[Thread 0x7fffecf6a700 (LWP 26199) exited]
[Thread 0x7fffe8f62700 (LWP 26203) exited]
[Thread 0x7fffeb767700 (LWP 26197) exited]
[Thread 0x7fffe9f64700 (LWP 26201) exited]
[Thread 0x7fffebf68700 (LWP 26198) exited]
[Thread 0x7fffeaf66700 (LWP 26196) exited]
 [58.8037s]
Allocating buffers...  [9.9e-05s]
Initializing temporary storage...  [0.005218s]
Processing query chunk 0, reference chunk 0, shape 0, index chunk 0.
Building reference index... [New Thread 0x7fffe8761700 (LWP 26205)]
[New Thread 0x7fffe8f62700 (LWP 26206)]
[New Thread 0x7fffe9763700 (LWP 26207)]
[New Thread 0x7fffe9f64700 (LWP 26208)]
[New Thread 0x7fffecf6a700 (LWP 26209)]
[New Thread 0x7fffec769700 (LWP 26210)]
[New Thread 0x7fffebf68700 (LWP 26211)]
[New Thread 0x7fffeb767700 (LWP 26212)]
[New Thread 0x7fffeaf66700 (LWP 26213)]
[New Thread 0x7fffea765700 (LWP 26214)]
[Thread 0x7fffebf68700 (LWP 26211) exited]
[Thread 0x7fffea765700 (LWP 26214) exited]
[Thread 0x7fffeaf66700 (LWP 26213) exited]
[Thread 0x7fffe8761700 (LWP 26205) exited]
[Thread 0x7fffec769700 (LWP 26210) exited]
[Thread 0x7fffe9763700 (LWP 26207) exited]
[Thread 0x7fffecf6a700 (LWP 26209) exited]
[Thread 0x7fffeb767700 (LWP 26212) exited]
[Thread 0x7fffe9f64700 (LWP 26208) exited]
[New Thread 0x7fffea765700 (LWP 26217)]
[Thread 0x7fffe8f62700 (LWP 26206) exited]
[New Thread 0x7fffeaf66700 (LWP 26218)]
[New Thread 0x7fffeb767700 (LWP 26219)]
[New Thread 0x7fffebf68700 (LWP 26220)]
[New Thread 0x7fffecf6a700 (LWP 26221)]
[New Thread 0x7fffec769700 (LWP 26222)]
[New Thread 0x7fffe9f64700 (LWP 26223)]
[New Thread 0x7fffe9763700 (LWP 26224)]
[New Thread 0x7fffe8f62700 (LWP 26225)]
[New Thread 0x7fffe8761700 (LWP 26226)]
[Thread 0x7fffe8761700 (LWP 26226) exited]
[Thread 0x7fffec769700 (LWP 26222) exited]
[Thread 0x7fffeb767700 (LWP 26219) exited]
[Thread 0x7fffe9f64700 (LWP 26223) exited]
[Thread 0x7fffe8f62700 (LWP 26225) exited]
[Thread 0x7fffecf6a700 (LWP 26221) exited]
[Thread 0x7fffeaf66700 (LWP 26218) exited]
[Thread 0x7fffe9763700 (LWP 26224) exited]
[Thread 0x7fffebf68700 (LWP 26220) exited]
[Thread 0x7fffea765700 (LWP 26217) exited]
 [105.205s]
Building query index... [New Thread 0x7fffe8761700 (LWP 26229)]
[New Thread 0x7fffe8f62700 (LWP 26230)]
[New Thread 0x7fffe9763700 (LWP 26231)]
[New Thread 0x7fffe9f64700 (LWP 26232)]
[New Thread 0x7fffecf6a700 (LWP 26233)]
[New Thread 0x7fffec769700 (LWP 26234)]
[New Thread 0x7fffebf68700 (LWP 26235)]
[New Thread 0x7fffeb767700 (LWP 26236)]
[New Thread 0x7fffeaf66700 (LWP 26237)]
[New Thread 0x7fffea765700 (LWP 26238)]
[Thread 0x7fffec769700 (LWP 26234) exited]
[Thread 0x7fffebf68700 (LWP 26235) exited]
[Thread 0x7fffe9f64700 (LWP 26232) exited]
[Thread 0x7fffea765700 (LWP 26238) exited]
[Thread 0x7fffecf6a700 (LWP 26233) exited]
[Thread 0x7fffe8761700 (LWP 26229) exited]
[Thread 0x7fffe8f62700 (LWP 26230) exited]
[Thread 0x7fffeaf66700 (LWP 26237) exited]
[Thread 0x7fffe9763700 (LWP 26231) exited]
[New Thread 0x7fffea765700 (LWP 26239)]
[Thread 0x7fffeb767700 (LWP 26236) exited]
[New Thread 0x7fffeaf66700 (LWP 26240)]
[New Thread 0x7fffeb767700 (LWP 26241)]
[New Thread 0x7fffebf68700 (LWP 26242)]
[New Thread 0x7fffecf6a700 (LWP 26243)]
[New Thread 0x7fffec769700 (LWP 26244)]
[New Thread 0x7fffe9f64700 (LWP 26245)]
[New Thread 0x7fffe9763700 (LWP 26246)]
[New Thread 0x7fffe8f62700 (LWP 26247)]
[New Thread 0x7fffe8761700 (LWP 26248)]
[Thread 0x7fffebf68700 (LWP 26242) exited]
[Thread 0x7fffea765700 (LWP 26239) exited]
[Thread 0x7fffe9f64700 (LWP 26245) exited]
[Thread 0x7fffecf6a700 (LWP 26243) exited]
[Thread 0x7fffe9763700 (LWP 26246) exited]
[Thread 0x7fffeb767700 (LWP 26241) exited]
[Thread 0x7fffe8761700 (LWP 26248) exited]
[Thread 0x7fffeaf66700 (LWP 26240) exited]
[Thread 0x7fffec769700 (LWP 26244) exited]
 [1.83561s]
Building seed filter... [New Thread 0x7fffe8761700 (LWP 26249)]
[Thread 0x7fffe8f62700 (LWP 26247) exited]
[New Thread 0x7fffe8f62700 (LWP 26250)]
[New Thread 0x7fffe9763700 (LWP 26251)]
[New Thread 0x7fffe9f64700 (LWP 26252)]
[New Thread 0x7fffecf6a700 (LWP 26253)]
[New Thread 0x7fffec769700 (LWP 26254)]
[New Thread 0x7fffebf68700 (LWP 26255)]
[New Thread 0x7fffeb767700 (LWP 26256)]
[New Thread 0x7fffeaf66700 (LWP 26257)]
[New Thread 0x7fffea765700 (LWP 26258)]
[Thread 0x7fffeb767700 (LWP 26256) exited]
[Thread 0x7fffec769700 (LWP 26254) exited]
[Thread 0x7fffeaf66700 (LWP 26257) exited]
[Thread 0x7fffecf6a700 (LWP 26253) exited]
[Thread 0x7fffe9f64700 (LWP 26252) exited]
[Thread 0x7fffe8761700 (LWP 26249) exited]
[Thread 0x7fffe8f62700 (LWP 26250) exited]
[Thread 0x7fffea765700 (LWP 26258) exited]
[Thread 0x7fffe9763700 (LWP 26251) exited]
[Thread 0x7fffebf68700 (LWP 26255) exited]
[New Thread 0x7fffea765700 (LWP 26259)]
[New Thread 0x7fffeaf66700 (LWP 26260)]
[New Thread 0x7fffeb767700 (LWP 26261)]
[New Thread 0x7fffebf68700 (LWP 26262)]
[New Thread 0x7fffecf6a700 (LWP 26263)]
[New Thread 0x7fffec769700 (LWP 26264)]
[New Thread 0x7fffe9f64700 (LWP 26265)]
[New Thread 0x7fffe9763700 (LWP 26266)]
[New Thread 0x7fffe8f62700 (LWP 26267)]
[New Thread 0x7fffe8761700 (LWP 26268)]
[Thread 0x7fffe9763700 (LWP 26266) exited]
[Thread 0x7fffe8f62700 (LWP 26267) exited]
[Thread 0x7fffecf6a700 (LWP 26263) exited]
[Thread 0x7fffeaf66700 (LWP 26260) exited]
[Thread 0x7fffebf68700 (LWP 26262) exited]
[Thread 0x7fffe8761700 (LWP 26268) exited]
[Thread 0x7fffea765700 (LWP 26259) exited]
[Thread 0x7fffeb767700 (LWP 26261) exited]
[Thread 0x7fffec769700 (LWP 26264) exited]
 [3.2159s]
Searching alignments... [New Thread 0x7fffe8761700 (LWP 26269)]
[Thread 0x7fffe9f64700 (LWP 26265) exited]
[New Thread 0x7fffe8f62700 (LWP 26270)]
[New Thread 0x7fffe9763700 (LWP 26271)]
[New Thread 0x7fffe9f64700 (LWP 26272)]
[New Thread 0x7fffecf6a700 (LWP 26273)]
[New Thread 0x7fffec769700 (LWP 26274)]
[New Thread 0x7fffebf68700 (LWP 26275)]
[New Thread 0x7fffeb767700 (LWP 26276)]
[New Thread 0x7fffeaf66700 (LWP 26277)]
[New Thread 0x7fffea765700 (LWP 26278)]
[Thread 0x7fffeaf66700 (LWP 26277) exited]
[Thread 0x7fffeb767700 (LWP 26276) exited]
[Thread 0x7fffebf68700 (LWP 26275) exited]
[Thread 0x7fffec769700 (LWP 26274) exited]
[Thread 0x7fffecf6a700 (LWP 26273) exited]
[Thread 0x7fffe9f64700 (LWP 26272) exited]
[Thread 0x7fffe9763700 (LWP 26271) exited]
[Thread 0x7fffe8f62700 (LWP 26270) exited]
[Thread 0x7fffe8761700 (LWP 26269) exited]
[Thread 0x7ffff7fe9800 (LWP 26162) exited]

Program terminated with signal SIGKILL, Killed.
The program no longer exists.
(gdb)

**Comment by bbuchfink** [comment]
That is still quite strange. It it possible that your system could kill a
task if it uses too much memory?

**Comment by internet-nobody** [comment]
I'm don't think so. It's a virtual server created "by me" (from a bunch of prexisting options - I went for ubuntu, 64gb ram, 8cpus) basically just to run this so should be a blank slate. 

The files that exited "properly" are around 5GB each, and they say:

> Failed to allocate sufficient memory. Please refer to the manual for instructions on memory usage.

And sorry I forgot to add the result of "bt" above:

> (gdb) bt
No stack.

**Comment by bbuchfink** [comment]
Is that a publicly available service so I could try it myself?

**Comment by internet-nobody** [comment]
It's not, but I think I can make it accessible. I'll send you an email if that's OK rather than post details publicly!

**Comment by bbuchfink** [comment]
It does get killed by the system for running out of memory. That can
happen, see here:
https://unix.stackexchange.com/questions/136291/will-linux-start-killing-my-processes-without-asking-me-if-memory-gets-short

I'll put it in the manual so users are aware of this.

**Comment by internet-nobody** [comment]
Thanks for solving the mystery :)
