### ISSUE TITLE
output with gi information

### ISSUE THREAD

**Issue by spatroca** [bbuchfink/diamond#147]
Hello,
When I run the diamond, return this information ref|WP_082962740.1| but I need some think like this gi|1178440364|ref|WP_082962740.1| with gi number.
Anybody tell me what parameter I use to return this information?
Thanks.

**Comment by bbuchfink** [comment]
Diamond does not remove the gi numbers, so it means they are not contained
in your database file. You need to build the database from a fasta file
containing gi numbers. GI numbers were phased out and are not contained in
recent databases any more though.

**Comment by spatroca** [comment]
Thanks you to answer me!
Ok, in this case I am using wrong databases. Could you send me the link where can find this databases with GI numbers in fasta file?
I tried find, but I didn't got.

**Comment by bbuchfink** [comment]
Sorry, I don't know if you can still download these old databases somewhere.

**Comment by spatroca** [comment]
I understand. Thanks you.
