### ISSUE TITLE
B2Go format issue_ <Hit_id>

### ISSUE THREAD

**Issue by lentram** [bbuchfink/diamond#148]
Hi,

I have successfully BLASTx against NR and Swiss-Prot databases with Diamond v0.9.4 and downloaded the .xml files into B2GO. But, B2Go is unable to perform the mapping process.

It seems that when formatting the database (makedb), Diamond automatically assigns the NCBI own identifiers (e.g.: <Hit_id>gnl|BL_ORD_ID|41364419</Hit_id>) and B2GO cannot find the accession ids during the mapping step and so cannot retrieve the GO terms. 

Any advice would be highly appreciated!!
Many thanks

**Comment by bbuchfink** [comment]
Hi,

I was under the impression that blast also uses these gnl|BL_ORD_ID|
identifiers in the output, so it should be compatible. Can you test to
search a single query against your database with blast and see if the
output imports correctly into blast2go?

Best regards,

Benjamin

**Comment by lentram** [comment]
Hi,

Thanks so much for your quick response.

I've tried what you have suggested but I am getting the following error:

BLAST Database error: No alias or index file found for protein database [./bin/diamond_nr] in search path [/data01/src/ncbi-blast-2.6.0+::]

I guess the binary database created by Diamond is incompatible with blast..

B2GO recommends to format the fasta database and use the makeblastdb command with the -parse_seqids parameter prior to running the local blast (https://www.blast2go.com/support/blog/22-blast2goblog/111-format-fasta-file-blast).

Should I follow similar steps with DIamond?? May I rectify the fasta database to have the correct format and then use Diamond makedb command with any special parameter to parse the ids??
Or any other possibility??

Thank you so much,

Laura

**Comment by bbuchfink** [comment]
Hi Laura,

ok, I see now that you get the accessions in the XML file if you build
blast databases with -parse_seqids. I will modify Diamond to also use that
format and provide a new release that should fix this in the next days.

Best wishes,

Benjamin

**Comment by bbuchfink** [comment]
The latest version should provide a more compatible format now.
