### ISSUE TITLE
Terminology clarification

### ISSUE THREAD

**Issue by adityabandla** [bbuchfink/diamond#150]
Hi Benjamin

I am using the blastx mode for a metagenome dataset. At the end of the log file, the summary says 12M queries aligned. So, here queries refer to the DNA sequences or the translated protein sequences?

I would assume it's the former, please correct me

As a counter check, it might be good to output the number of input queries as well in the summary. 

Regards,
Aditya

**Comment by bbuchfink** [comment]
Hi Aditya,

it refers to the number of DNA sequences. I will add the total number to
the message.

Best regards,

Benjamin

**Comment by adityabandla** [comment]
Thanks Ben!
