### ISSUE TITLE
format issue for <Hit_id>  and <Hit_def> in version 0.9.9

### ISSUE THREAD

**Issue by raphenya** [bbuchfink/diamond#153]
Reference File contains:
```
>783_3746 | model_type_id: 40292 | pass_bitscore: 500 |  pass_evalue: 1e-100 | NDM-1
MELPNIMH...
```
NCBI Blastp 2.5.0+ XML results hit:
```
   ...
  <Hit_id>gnl|BL_ORD_ID|742</Hit_id>
  <Hit_def>783_3746 | model_type_id: 40292 | pass_bitscore: 500 |  pass_evalue: 1e-100 | NDM-1</Hit_def>
   ...
```

Diamond blastp version 0.9.9 XML results hit:

```
  ...
  <Hit_id>783_3746</Hit_id>
  <Hit_def>| model_type_id: 40292 | pass_bitscore: 500 |  pass_evalue: 1e-100 | NDM-1</Hit_def>
  ...
```

Any ideas?

**Comment by bbuchfink** [comment]
It should be the same if you build the blast database with -parse_seqids. I
changed that for better compatibility with blast2go. How is the other
format relevant to you?

**Comment by raphenya** [comment]
Diamond version 0.8.36 blastp gave me the following:

```
  <Hit_id>gnl|BL_ORD_ID|908</Hit_id>
  <Hit_def>783_3746 | model_type_id: 40292 | pass_bit_score: 500</Hit_def>
```

With reference file:

```
>783_3746 | model_type_id: 40292 | pass_bitscore: 500
MELPNIMH...
```

I need the whole def line for parsing.

**Comment by raphenya** [comment]
I just tried building the db with `-parse_seqids`, I get same incomple def line.

**Comment by bbuchfink** [comment]
You can get the whole def line by concatenating Hit_id and Hit_def.

If that's not possible for you I can add an option to use the old format.

**Comment by raphenya** [comment]
Thank you, old format would be nice because the xml would be similar to ncbi blast.

**Comment by raphenya** [comment]
@bbuchfink any updates on this issue?

**Comment by bbuchfink** [comment]
Sorry, I have been very busy and forgot about this. I will try to get it
done within the next week.

**Comment by bbuchfink** [comment]
I have just commited an update that provides the option --xml-blord-format
to change to the old format. I haven't published a release yet but you can
clone the repository and compile from source to use this option.
