### ISSUE TITLE
Invalid command: -d with v 0.9.9

### ISSUE THREAD

**Issue by lentram** [bbuchfink/diamond#154]
Hello,

I get the following error when trying to blast with v.0.9.9:

Error: Invalid command: -d. To print help message: diamond help
laura@WS004966:/data01/src/Diamond/comp_b2go$ diamond help
Comando "diamond" non trovato. Forse si intendeva:
 Comando "kdiamond" dal pacchetto "kdiamond" (main)
diamond: comando non trovato

The command I'm using:
./diamond -d ./nr_b2go -q /data01/posidonia_megatranscriptome/notpool_reads/all_denovo_cdhit0.95_1000lines.fa -o /data01/posidonia_megatranscriptome/notpool_reads/diamond_compb2go/all_denovo_cdhit0.95_1000lines_nr_diamond_compb2go_15hits -f 5 --sensitive -p 28 -k 15 -e 1e-06

Previously, I've successfully created the database file:
./diamond makedb --in /data01/src/databases/nr -d nr_b2go -parse_seqids

Any ideas??
Thank so much!!
Laura

**Comment by bbuchfink** [comment]
Hi Laura,

you are missing the command, it needs to be diamond blastx or diamond
blastp depending on whether you are aligning dna or proteins.

Best regards,

Benjamin

**Comment by lentram** [comment]
upps!! so sorry
