### ISSUE TITLE
Short input DNA sequences:

### ISSUE THREAD

**Issue by EisenRa** [bbuchfink/diamond#156]
Hi,

How suitable is DIAMOND for analysing short (~50 bp) DNA sequences via BLASTX?

Thanks!

**Comment by bbuchfink** [comment]
Hi,

you probably should use the sensitive mode for those reads, then I think
it's going to work well.

**Comment by EisenRa** [comment]
Thank you for the quick response!

I was confused about the difference between MALT and DIAMOND for DNA to protein alignments (the obvious one being that MALT can do DNA to DNA alignments).

**Comment by bbuchfink** [comment]
You probably need to set a lower value for --min-score. 50 bit score is
more appropriate for 100bp reads.

By the way -b100 is very high, you should probably set that lower.

**Comment by EisenRa** [comment]
Thanks! I'll give that a try.

**Comment by EisenRa** [comment]
Hallo!

To follow up on this, is it possible for DIAMOND to have a BLASTN mode? I'm struggling to use large reference databases with MALT (index size too large to load into memory). 

Danke!

**Comment by bbuchfink** [comment]
It's possible but unlikely to happen in the near future. Have you tried
minimap2 or vsearch?
