### ISSUE TITLE
problems importing Diamond XML into Blast2go 2.8

### ISSUE THREAD

**Issue by peterthorpe5** [bbuchfink/diamond#157]
Dear Diamond,

Firstly thank you for the great tool. I use it a lot!!!!!  I am using diamond version 0.8.38. I have produced an xml output with --salltitles option (as said in another Github issue). However, when I try and import the xml file in blast2go 2.8, using the 1.2GB Java memory version (I cannot use a more modern B2G one as I dont have the rights to update Java on my work laptop, madness! And any greater memory version fails to open) I get the following output and an instant fail:

9:27   Import Blast file: Hsach_QC_RNAseq_CDS.AA.fasta_vs_nr.xml
9:27   Import parameters:
9:27   Hit description position: 5
9:27   Hit description filter: 
9:27   Hit description separator: "|"
9:27   Join Hit-ID and description: Yes
9:27   Maximum number of hits: 10
9:27   Minimum Hsp length: 33
**9:27   Read names in CLC format: null**

It does state the xml version required: xml (>version 2.2.13)

Does this error make any sense to you? Do you have any thought on how to fix this?

Regards,
Peter Thorpe

**full command to produce the xml file:**
echo "running diamond-BLAST against NR"
diam_p="$HOME/scratch/Downloads/diamond-master/diamond blastp 
		-p 12 --more-sensitive -e 0.00001 
	   -q Hsach_QC_RNAseq_CDS.AA.fasta
	   -d $HOME/scratch/blast_databases/nr.dmnd 
	   --taxonmap $HOME/scratch/blast_databases/prot.accession2taxid.gz	
	   --outfmt 5 --salltitles
	   --out Hsach_QC_RNAseq_CDS.AA.fasta_vs_nr.xml"
echo ${diam_p}
eval ${diam_p}

**XML output head:**
]$ head -n 100 Hsach_QC_RNAseq_CDS.AA.fasta_vs_nr.xml
<?xml version="1.0"?>
<!DOCTYPE BlastOutput PUBLIC "-//NCBI//NCBI BlastOutput/EN" "http://www.ncbi.nlm.nih.gov/dtd/NCBI_BlastOutput.dtd">
<BlastOutput>
  <BlastOutput_program>blastp</BlastOutput_program>
  <BlastOutput_version>diamond 0.8.38</BlastOutput_version>
  <BlastOutput_reference>Benjamin Buchfink, Xie Chao, and Daniel Huson (2015), &quot;Fast and sensitive protein alignment using DIAMOND&quot;, Nature Methods 12:59-60.</BlastOutput_reference>
  <BlastOutput_db></BlastOutput_db>
  <BlastOutput_query-ID>Query_1</BlastOutput_query-ID>
  <BlastOutput_query-def>Hsac_DN10008_c0_g2_i1|m.50805 Hsac_DN10008_c0_g2_i1|g.50805 ORF Hsac_DN10008_c0_g2_i1|g.50805 Hsac_DN10008_c0_g2_i1|m.50805 type:internal len:160 (+) Hsac_DN10008_c0_g2_i1:3-479(+)</BlastOutput_query-def>
  <BlastOutput_query-len>159</BlastOutput_query-len>
  <BlastOutput_param>
    <Parameters>
      <Parameters_matrix>blosum62</Parameters_matrix>
      <Parameters_expect>1e-05</Parameters_expect>
      <Parameters_gap-open>11</Parameters_gap-open>
      <Parameters_gap-extend>1</Parameters_gap-extend>
      <Parameters_filter></Parameters_filter>
    </Parameters>
  </BlastOutput_param>
<BlastOutput_iterations>
<Iteration>
  <Iteration_iter-num>1</Iteration_iter-num>
  <Iteration_query-ID>Query_1</Iteration_query-ID>
  <Iteration_query-def>Hsac_DN10008_c0_g2_i1|m.50805 Hsac_DN10008_c0_g2_i1|g.50805 ORF Hsac_DN10008_c0_g2_i1|g.50805 Hsac_DN10008_c0_g2_i1|m.50805 type:internal len:160 (+) Hsac_DN10008_c0_g2_i1:3-479(+)</Iteration_query-def>
  <Iteration_query-len>159</Iteration_query-len>
<Iteration_hits>
<Hit>
  <Hit_num>1</Hit_num>
  <Hit_id>gnl|BL_ORD_ID|43887459</Hit_id>
  <Hit_def>gi|685832877|emb|CEF67798.1| Laminin G domain and Concanavalin A-like lectin/glucanases superfamily domain and Concanavalin A-like lectin/glucanase, subgroup domain-containing protein [Strongyloides ratti]</Hit_def>
  <Hit_accession>43887459</Hit_accession>
  <Hit_len>958</Hit_len>
  <Hit_hsps>
    <Hsp>
      <Hsp_num>1</Hsp_num>
      <Hsp_bit-score>62.0</Hsp_bit-score>
      <Hsp_score>149</Hsp_score>
      <Hsp_evalue>1.2e-06</Hsp_evalue>
      <Hsp_query-from>22</Hsp_query-from>
      <Hsp_query-to>71</Hsp_query-to>
      <Hsp_hit-from>110</Hsp_hit-from>
      <Hsp_hit-to>158</Hsp_hit-to>
      <Hsp_query-frame>0</Hsp_query-frame>
      <Hsp_hit-frame>0</Hsp_hit-frame>
      <Hsp_identity>23</Hsp_identity>
      <Hsp_positive>38</Hsp_positive>
      <Hsp_gaps>0</Hsp_gaps>
      <Hsp_align-len>49</Hsp_align-len>

**Comment by bbuchfink** [comment]
Hi Peter,

that file does not look like it's in XML format. No idea how this error
could happen. Does the file look the same if you open it in a text editor?

Could you try this again with the latest version of diamond? Maybe use only
a small query and database file so you can quickly check if the format is
correct.

By the way, you do not need the --taxonmap parameter ,that is only used for
the tabular format with the staxids field.

Best regards,

Benjamin

**Comment by peterthorpe5** [comment]
Hi Benjamin,

I will get this done and get back to you.

Cheers,

Pete

**Comment by peterthorpe5** [comment]
Hi Benjamin,

I am sorry about the delay, I had to wait for someone else to update the NR database on our server due to privilege limitations. I know you said to test it on a smaller database, but I really want this working with NR. So, I am using an NR database updated within the last week (made the diamond database yesterday). Diamond version (diamond v0.9.9.110), this was installed yesterday.

I still get the same import error with Blast2Go 2.8 (old B2G – not allowed to update Java).

Do you have any thoughts on how to fix this? Once again, love the tool I use it all the time!!!

Cheers,

Pete

Blast2Go Log:

9:27   Import Blast file: N:\scratch\H_sac\H_sac_RNAseq_ass\renamed\Hsach_QC_RNAseq_CDS.AA.fasta_vs_nr.xml
9:27   Import parameters:
9:27   Hit description position: 5
9:27   Hit description filter:
9:27   Hit description separator: "|"
9:27   Join Hit-ID and description: Yes
9:27   Maximum number of hits: 1
9:27   Minimum Hsp length: 33
9:27   Read names in CLC format: null

Running Command:

diam_p="diamond blastp
                   -p 10 --more-sensitive -e 0.00001
                   -q Hsach_QC_RNAseq_CDS.AA.fasta
                   -d $HOME/scratch/blast_databases/nr.dmnd
                   --outfmt 5 --salltitles
                   --out Hsach_QC_RNAseq_CDS.AA.fasta_vs_nr.xml"
echo ${diam_p}
eval ${diam_p}


XML file example:

$ more Hsach_QC_RNAseq_CDS.AA.fasta_vs_nr.xml
<?xml version="1.0"?>
<!DOCTYPE BlastOutput PUBLIC "-//NCBI//NCBI BlastOutput/EN" "http://www.ncbi.nlm.nih.gov/dtd/NCBI_BlastOutput.dtd">
<BlastOutput>
  <BlastOutput_program>blastp</BlastOutput_program>
  <BlastOutput_version>diamond 0.9.9</BlastOutput_version>
  <BlastOutput_reference>Benjamin Buchfink, Xie Chao, and Daniel Huson (2015), &quot;Fast and sensitive protein alignment using DIAMOND&quot;, Nature Method
s 12:59-60.</BlastOutput_reference>
  <BlastOutput_db></BlastOutput_db>
  <BlastOutput_query-ID>Query_1</BlastOutput_query-ID>
  <BlastOutput_query-def>Hsac_DN10008_c0_g2_i1|m.50805 Hsac_DN10008_c0_g2_i1|g.50805 ORF Hsac_DN10008_c0_g2_i1|g.50805 Hsac_DN10008_c0_g2_i1|m.50805 type:in
ternal len:160 (+) Hsac_DN10008_c0_g2_i1:3-479(+)</BlastOutput_query-def>
  <BlastOutput_query-len>159</BlastOutput_query-len>
  <BlastOutput_param>
    <Parameters>
      <Parameters_matrix>blosum62</Parameters_matrix>
      <Parameters_expect>1e-05</Parameters_expect>
      <Parameters_gap-open>11</Parameters_gap-open>
      <Parameters_gap-extend>1</Parameters_gap-extend>
      <Parameters_filter></Parameters_filter>
    </Parameters>
  </BlastOutput_param>
<BlastOutput_iterations>
<Iteration>
  <Iteration_iter-num>1</Iteration_iter-num>
  <Iteration_query-ID>Query_1</Iteration_query-ID>
  <Iteration_query-def>Hsac_DN10008_c0_g2_i1|m.50805 Hsac_DN10008_c0_g2_i1|g.50805 ORF Hsac_DN10008_c0_g2_i1|g.50805 Hsac_DN10008_c0_g2_i1|m.50805 type:inte
rnal len:160 (+) Hsac_DN10008_c0_g2_i1:3-479(+)</Iteration_query-def>
  <Iteration_query-len>159</Iteration_query-len>
<Iteration_hits>
<Hit>
  <Hit_num>1</Hit_num>
  <Hit_id>gi|685832877|emb|CEF67798.1|</Hit_id>
  <Hit_def>Laminin G domain and Concanavalin A-like lectin/glucanases superfamily domain and Concanavalin A-like lectin/glucanase, subgroup domain-containin
g protein [Strongyloides ratti]</Hit_def>
  <Hit_accession>CEF67798.1</Hit_accession>
  <Hit_len>958</Hit_len>
  <Hit_hsps>
    <Hsp>
      <Hsp_num>1</Hsp_num>
      <Hsp_bit-score>62.0</Hsp_bit-score>
      <Hsp_score>149</Hsp_score>
      <Hsp_evalue>1.6e-06</Hsp_evalue>
      <Hsp_query-from>22</Hsp_query-from>
      <Hsp_query-to>71</Hsp_query-to>
      <Hsp_hit-from>110</Hsp_hit-from>
      <Hsp_hit-to>158</Hsp_hit-to>
      <Hsp_query-frame>0</Hsp_query-frame>
      <Hsp_hit-frame>0</Hsp_hit-frame>
      <Hsp_identity>23</Hsp_identity>
      <Hsp_positive>38</Hsp_positive>
      <Hsp_gaps>0</Hsp_gaps>

**Comment by bbuchfink** [comment]
Hi Peter,

I'm having trouble running blast2go 2.8 right now. The web start version
always gives me a Java security error. I have added http://www.blast2go.com
to my safe sites list. Any ideas?

Best regards,

Benjamin

**Comment by peterthorpe5** [comment]
Hi Benjamin,

For me a get a box allowing me to select allow. 

I don't think this is worth it for you maintaining your tool for older unsupported versions. 

I will try a non work based competed for this. Please mark this issue as complete. I will let you know how I get on. 

Pete 
________________________________________

**Comment by gabo-ing** [comment]
Hi:
Would it be possible for you to run Blast2go basic, then import reads and then export the project into b2g legacy format? I did that and it worked, although I still have to check if results are coherent

**Comment by bsgilgi** [comment]
Hi,
I had the same problem and manged to get it work. 
Here is what I did:
1. It is important that the nr database will be formatted properly. 
2. Adding some dummy path in the BlastOutput_db field (at the first part of the XML)
3. Adding F in the Parameters_filter field (also at the first part of the XML)

**Comment by willian88** [comment]
Hi bsgilgi,

Could you explain better the methodology or make available part of your files?
Because I've same problem and I couldn't fix it.

Best regards.

Willian

**Comment by bsgilgi** [comment]
Hi,
1. It is important that the fasta header will be formatted properly. 
I think you should have "&g;" between the descriptions of a single sequence. 
Here is an example of a header (for a single sequence) that worked for me:
>gi|489223532|ref|WP_003131952.1| 30S ribosomal protein S18 [Lactococcus lactis] &gt;gi|15674171|ref|NP_268346.1| 30S ribosomal protein S1
8 [Lactococcus lactis subsp. lactis Il1403] &gt;gi|13878750|sp|Q9CDN0.1|RS18_LACLA RecName: Full=30S ribosomal protein S18 &gt;gi|12293989
5|sp|Q02VU1.1|RS18_LACLS RecName: Full=30S ribosomal protein S18 &gt;gi|166220956|sp|A2RNZ2.1|RS18_LACLM RecName: Full=30S ribosomal prote
in S18 &gt;

Downloading the nr fasta didn't work for me. I used the blastdbcmd to convert the blastx formatted nr db (that was downloaded already as blastx db from the NCBI), and converted it to fasta:
blastdbcmd -db nr  -entry all -out nr.fasta

Then had to replace ">" inside the headers to &gt;
Can do this like that:
perl -p -i -e 's/\s\>/ &gt;/g' nr_2017-07-17.fasta

I guess you can use also the fasta, but need to get it to the write format.
Maybe there are easier ways to get the fasta file, but this worked...

2. Make a diamond db from that file, and run diamond
When running diamond,  I used the following options:
--salltitles --outfmt 5 --more-sensitive

3. At that stage I compared the blastx xml and diamond xml, until I found which difference allow to import the blastx to blast2go 2.8.
If you will look at the xml output, you will see that line 7 has:
 <BlastOutput_db></BlastOutput_db>
Just add some path there (doesn't have to be a real path). For example:
 <BlastOutput_db>my_path</BlastOutput_db>

Line 17 has:
<Parameters_filter></Parameters_filter>
Just add an F:
<Parameters_filter>F</Parameters_filter>

I hope this will help.

**Comment by bbuchfink** [comment]
Sorry this took longer. In the latest release I have adjusted the format to
hopefully fix these issues.

**Comment by peterthorpe5** [comment]
Superb, thank you! I can’t test this within the next 2 weeks. But I will do and get back to you.

Cheers!

**Comment by peterthorpe5** [comment]
I am very pleased to report back that this IS working! Great job. Thank you very much!

Pete
