### ISSUE TITLE
Diamond with very short reads

### ISSUE THREAD

**Issue by caleb-easterly** [bbuchfink/diamond#158]
Hi, 

I was wondering about the usability of DIAMOND (blastp mode) with reads under 20 aa. It seems to filter them out automatically, which I assume is due to the seed design. Is there some way to choose a different seed for very short reads? 

Thanks,

Caleb

**Comment by bbuchfink** [comment]
Hi Caleb,

it should work to map those reads if you use the sensitive mode and
probably set a higher e-value cutoff.

Best regards,

Benjamin

**Comment by caleb-easterly** [comment]
Thank you for the response. In the manual, it says that the default mode is mainly for short peptides, while the sensitive mode is for longer peptides. In which situations should the default mode be used? 

Regards,

Caleb

**Comment by bbuchfink** [comment]
I suppose it's best for 100-150bp reads or for longer sequences if you
don't need as much sensitivity.
