### ISSUE TITLE
Problem in uploading the Diamond blastx results into Blast2GO

### ISSUE THREAD

**Issue by inderjitsyadav** [bbuchfink/diamond#159]
Dear Diamond Developer 

Diamond is a good alternative of NCBI Blast as it is very fast.
I am facing a problem I have assembled the a  transcriptome  de novo with trinity. and I performed the blastx search with diamond with -f 5 option for xml like output. When I loaded the xml files into Blast2go. It loads the files partially.
I have seen the number of transcriptiome entries in my xml files are around 20,000 , but it loads around 1500 to 1800 of entries only and not the whole results.
I used the following command
 ~/Software/diamond-master/diamond blastx -d ../nr -q Query.fasta  -f 5 -o blastx-output.xml --threads 23

Will you please sort out the problem. BBlast2GO is not giving any error message. 

Regards
Inderjit

**Comment by bbuchfink** [comment]
Hi,

are you sure there are matches contained in the diamond output file for the
missing queries? Can you check the file for a missing query if there are
matches present for that query that do not get imported?

Best regards,

Benjamin

**Comment by inderjitsyadav** [comment]
Hi 
Yes the Hits are present for all queries in Diamond  blastx result . The blast2go shows the sequences which has blast hit and also the sequences without blast hit. But it load only the subset of sequences and not all file.  I am attaching the file from blast2go upload. Now I have run the diamond with --more-sensitive option still the same problem. Blast files around 400 Mb.

![screenshot from 2017-07-20 16_01_04](https://user-images.githubusercontent.com/13862344/28413657-08a886c0-6d66-11e7-9097-882bff26876b.png)

**Comment by bbuchfink** [comment]
If you send the file to me I can have a look at it.

**Comment by inderjitsyadav** [comment]
​​Hi

Hi the zipped file is bigger than the upload size.
So I am sending it as a attachemt in mail

Bests
Inderjit
​
 Query.part-01.fasta.zip
<https://drive.google.com/a/pau.edu/file/d/0BxCzipLdzjnGTUpOSXVrRW5YR2c/view?usp=drive_web>
​

**Comment by bbuchfink** [comment]
Ok thanks I got the file, I will look over it in the next days.

**Comment by bbuchfink** [comment]
I tried this myself and I don't see why blast2go is not importing this file
correctly. There is no proper error message. You should inquire with
blast2go support too and ask them what's wrong with the file.

**Comment by kgun12** [comment]
I've just noticed the same issue.. in my case, when a sequence with a hit was loaded (orange), it would then fail to load some random large number of sequences after that.  I would up using diamond to do a "first pass", then took the sequences that had hits and used them in a blastx query to get the xml to load into blast2go.  It is still much faster than feeding the entire input fasta to blastx.

**Comment by bbuchfink** [comment]
I hope the blast2go support can help with that because I have no idea
what's wrong with the format and there's no proper error message.

**Comment by ODiogoSilva** [comment]
Hi,

I stumbled upon the same issue. I had a XML file with ~22k hits and only ~3k were being loaded by blast2go. I spent some time trying to figure out why the majority of the entries were being skipped without even an error message and I noticed that there were ASCII escape characters in the `Hit_def` fields of the majority of the hits. In my case, this seemed to be the problem. When opening the XML file with sublime these characters can be seen with a `SOH` notation:

![soh](https://user-images.githubusercontent.com/1532292/30244560-153b6bf8-95b8-11e7-9e74-ce70c7306e5e.png)

Or with less:

![less](https://user-images.githubusercontent.com/1532292/30244563-3cd5b18c-95b8-11e7-88d4-cf6d194a0e4d.png)

So, I removed all escape characters:

```
sed -i 's/\x01//g' matches_genes.xml
```

And now blast2go correctly loads all entries from the XML. I am not sure how those escape characters got in there, though. Hope this helps.

Cheers,
Diogo

**Comment by bbuchfink** [comment]
Sorry this took longer. The latest release should now properly format the
sequence titles.

**Comment by inderjitsyadav** [comment]
Thanks Alot. This will be very helpfull.

With Best Regards
Inderjit

**Comment by gahoo** [comment]
We have similar issues. In our case, it's something like `<`, `>`, `&` in sequence titles which causes xml parse error. It seems latest version fix `<` and `>`, but `&` still have a issue.

I think character escape is still needed:
```
'&' --> '&amp;'
'<' --> '&lt;'
'>' --> '&gt;'
```

**Comment by bbuchfink** [comment]
Ok, I'll look into this and provide another update.

**Comment by bbuchfink** [comment]
Sorry this took longer again. The latest version now correctly escapes
characters in XML output.

**Comment by bagdevi** [comment]
Thanks for the indications of the possible issue with the file. In my case my Hit_def lines have &gt.
