### ISSUE TITLE
Clarification on --sensitive versus --more-sensitive

### ISSUE THREAD

**Issue by caleb-easterly** [bbuchfink/diamond#160]
Hi Benjamin, 
Just a clarification on the sensitivity trigger options. Are they mutually exclusive or is `--more-sensitive` used in addition to `--sensitive`? 

If only one is used at a time and they are both given  for whatever reason (`--sensitive --more-sensitive` or `--more-sensitive --sensitive`), what is the rule for deciding which one is used? 

Thanks much, 

Caleb

**Comment by bbuchfink** [comment]
Hi Caleb,

you should only use one at a time. Not sure what will happen if you use
both.

Best regards,

Benjamin

**Comment by caleb-easterly** [comment]
Thanks, good to know. That could probably be a little clearer in the manual -- "additional sensitivity" suggested that `--more-sensitive` could possibly be used in addition to `--sensitive`, at least to me). 

Regards,

Caleb
