### ISSUE TITLE
Possibility to query database version information

### ISSUE THREAD

**Issue by bachev** [bbuchfink/diamond#161]
I'm using an application relying on a downloaded diamond database. That db was built with diamond 0.8.x, I'm running 0.9.9 ... and diamond bails out with an error message:
`Error: Database was built with a different version of diamond as is incompatible.`

As a simple user, I'm left wondering which diamond version I should take to be able to use the downloaded database.

Moving on, no big deal, rebuilding that database with the new version.

But programmatically, I would like to be able to do something like
`diamond dbversion -d somedb.dmnd`

and get a version number of that database back so that I can implement checks for this in my scripts. Alternatively, a version number of the diamond version with which that db was built would also be helpful.

Best,
  Bastien

**Comment by bbuchfink** [comment]
Hi Bastien,

alright, I will include this feature in the next version.

Best regards,

Benjamin

**Comment by bachev** [comment]
Thank you so much :-)

**Comment by bbuchfink** [comment]
The dbinfo command has been added to the latest version.

**Comment by bachev** [comment]
Works.

Thank you very much, both for for this nice piece of scientific software and for the support you are giving to it.

Case closed :-)

**Comment by xiaolicbs** [comment]
Hi, I ran into a weird bug. I am using a database created with `v0.9.22.123`. 
```
diamond v0.9.22.123 | by Benjamin Buchfink <buchfink@gmail.com>
Licensed under the GNU AGPL <https://www.gnu.org/licenses/agpl.txt>
Check http://github.com/bbuchfink/diamond for updates.

Database format version = 0
Diamond build = 93
Sequences = 12032197
Letters = 4109377293
```

However, when I am using `v0.9.22.123`, I got this:
```
diamond blastx --db CAT-files/diamond_nr -q AFA_0219_57.fa -o  AFA_0219_57_1_unmapped.txt
diamond v0.9.22.123 | by Benjamin Buchfink <buchfink@gmail.com>
Licensed under the GNU AGPL <https://www.gnu.org/licenses/agpl.txt>
Check http://github.com/bbuchfink/diamond for updates.

#CPU threads: 16
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
Temporary directory:
Opening the database...  [0.05085s]
Error: Database was built with a different version of Diamond and is incompatible.
```

**Comment by bbuchfink** [comment]
Hi,

the build number refers to the last number in the version number, i.e. for
v0.9.22.123 the build number is 123.

**Comment by xiaoli0** [comment]
Thanks!

**Comment by mw55309** [comment]
Hi

Sorry I am still missing some understanding here.

If I get this from dbinfo:

```sh
Database format version = 3
Diamond build = 133
Sequences = 181252700
Letters = 61117324008
```

How do I know *which* DIAMOND version I need?

**Comment by bbuchfink** [comment]
You need >= 0.9.25 (also see here: https://github.com/bbuchfink/diamond/wiki/5.-Advanced-topics).

**Comment by mw55309** [comment]
Thanks!
