### ISSUE TITLE
diamond to blast2go erro 

### ISSUE THREAD

**Issue by fanyucai1** [bbuchfink/diamond#165]
hi, i run the diamond(v0.9.10) with parameter " --salltitles -p 20 --top 10 --outfmt 5 -e 1e-5",but the xml can not be parsed by blast2go(b2g4pipe_v2.5),that i have fixed the xml file with:
"<BlastOutput_version>BLASTX 2.2.25+</BlastOutput_version>
<BlastOutput_db>/public/land/database/nr/nr</BlastOutput_db>
 <Parameters_filter>F</Parameters_filter>"
and database with "blastdbcmd -db nr -entry all -out nr.fasta" 

when i run the blast2go the output like this:
Annotation of 0 seqs with 0 annots finished. Now searching for orfan IPRs...

**Comment by bbuchfink** [comment]
Maybe it's the same problem referenced here with the control characters: https://github.com/bbuchfink/diamond/issues/159

These characters are copied from the nr database. I will provide a fix for this shortly.

**Comment by fanyucai1** [comment]
"As of September 2016, the integer sequence identifiers known as "GIs" will no longer be included in the GenBank, GenPept, and FASTA formats supported by NCBI for the display of sequence records. In addition, the FASTA format will no longer include the database source abbreviation. Please refer to the NCBI News Announcement posting for more detail. http://www.ncbi.nlm.nih.gov/news/03-02-2016-phase-out-of-GI-numbers/"

I used the old version of nr(http://s3.amazonaws.com/matrixsciencemisc/nr.gz),the database will be parsed by  blast2go(v2.5). 

I think diamond could parse gene2accession (ftp://ftp.ncbi.nlm.nih.gov/gene/DATA/gene2accession.gz),that xml will be parse by blast2go.

**Comment by bbuchfink** [comment]
The latest release should fix some of the blast2go issues.
