### ISSUE TITLE
dyld: Symbol not found error in DIAMOND v.0.9.10.111

### ISSUE THREAD

**Issue by mhyleung** [bbuchfink/diamond#167]
Dear all

I have DIAMOND v.0.9.10.111, and I have been trying to run this code, with a demo .fasta file as input, and a UniRef50.dmnd database file as reference (as shown below):

**diamond blastx --db /Volumes/WD/Sequencing/databases/uniref/uniref_50_diamond_99/uniref_50 --query /Volumes/WD/Sequencing/databases/humann2_databases_new/demo.fasta -o /Volumes/WD/Sequencing/humann2_tut/output_new**

Unfortunately, I was met with the following error message (shown below). Has anyone come across this error. How would one go about fixing this? Thank you very much in advance

Regards

Marc

>  Computing alignments... dyld: lazy symbol binding faileddyld: lazy symbol binding faileddyld: lazy symbol binding failed: Symbol not found: __ZNSt8__det: Symbol not found: __ZNSt8__detail15_List_node_base7_M_hookEPS0ail15_List_node_base7_M_hookEPS0: Symbol not found: __ZNSt8__det_
>   Referenced from: /Users/marc_
>   Referenced from: /Users/marcail15_List_node_base7_M_hookEPS0usleung/miniconda2/lib/python2.7usleung/miniconda2/lib/python2.7_
>   Referenced from: /Users/marc/site-packages/diamond (which wa/site-packages/diamond (which wausleung/miniconda2/lib/python2.7s built for Mac OS X 10.12)
>   Exs built for Mac OS X 10.12)
>   Ex/site-packages/diamond (which wapected in: /usr/lib/libstdc++.6.pected in: /usr/lib/libstdc++.6.s built for Mac OS X 10.12)
>   Exdylib
> 
> dylib
> 
> pected in: /usr/lib/libstdc++.6.dylib
> 
> dyld: Symbol not found: __ZNSt8_dyld: Symbol not found: __ZNSt8__detail15_List_node_base7_M_hook_detail15_List_node_base7_M_hookdyld: Symbol not found: __ZNSt8_EPS0_
>   Referenced from: /Users/EPS0_
>   Referenced from: /Users/marcusleung/miniconda2/lib/pythomarcusleung/miniconda2/lib/python2.7/site-packages/diamond (whicn2.7/site-packages/diamond (which was built for Mac OS X 10.12)
> h was built for Mac OS X 10.12)
>   Expected in: /usr/lib/libstdc+  Expected in: /usr/lib/libstdc++.6.dylib
> 
> +.6.dylib
> 
> _detail15_List_node_base7_M_hookdyld: lazy symbol binding failedAbort trap: 6

**Comment by bbuchfink** [comment]
Hi,
have you tried compiling diamond from source on your system?

**Comment by mhyleung** [comment]
Thank you for your reply. I have tried compiling from source using cmake. Ran it again but still getting the following. If you can point me to the right direction in fixing this that'd be great! Thanks so much.

Marc

#CPU threads: 1
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
#Target sequences to report alignments for: 20
Temporary directory: /Volumes/WD/Sequencing/humann2_tut/output/demo_humann2_temp/tmpuVKagU
Opening the database...  [0.007231s]
Opening the input file...  [0.018811s]
Opening the output file...  [9.8e-05s]
Loading query sequences...  [0.037603s]
Running complexity filter...  [0.206594s]
Building query histograms...  [0.010945s]
Allocating buffers...  [2.3e-05s]
Loading reference sequences...  [24.0805s]
Building reference histograms...  [21.8797s]
Allocating buffers...  [4.7e-05s]
Initializing temporary storage...  [0.000638s]
Processing query chunk 0, reference chunk 0, shape 0, index chunk 0.
Building reference index...  [28.8854s]
Building query index...  [0.011688s]
Building seed filter...  [1.42515s]
Searching alignments...  [2.17172s]
Processing query chunk 0, reference chunk 0, shape 0, index chunk 1.
Building reference index...  [30.5667s]
Building query index...  [0.012713s]
Building seed filter...  [1.43737s]
Searching alignments...  [2.06788s]
Processing query chunk 0, reference chunk 0, shape 0, index chunk 2.
Building reference index...  [31.2014s]
Building query index...  [0.010977s]
Building seed filter...  [1.43308s]
Searching alignments...  [2.05601s]
Processing query chunk 0, reference chunk 0, shape 0, index chunk 3.
Building reference index...  [27.7453s]
Building query index...  [0.012594s]
Building seed filter...  [1.75196s]
Searching alignments...  [2.41928s]
Processing query chunk 0, reference chunk 0, shape 1, index chunk 0.
Building reference index...  [27.9358s]
Building query index...  [0.010154s]
Building seed filter...  [1.71578s]
Searching alignments...  [2.26756s]
Processing query chunk 0, reference chunk 0, shape 1, index chunk 1.
Building reference index...  [36.0117s]
Building query index...  [0.012254s]
Building seed filter...  [1.59137s]
Searching alignments...  [2.31214s]
Processing query chunk 0, reference chunk 0, shape 1, index chunk 2.
Building reference index...  [37.9359s]
Building query index...  [0.016096s]
Building seed filter...  [1.69686s]
Searching alignments...  [2.26077s]
Processing query chunk 0, reference chunk 0, shape 1, index chunk 3.
Building reference index...  [40.8952s]
Building query index...  [0.016145s]
Building seed filter...  [1.72108s]
Searching alignments...  [2.32194s]
Processing query chunk 0, reference chunk 0, shape 2, index chunk 0.
Building reference index...  [32.005s]
Building query index...  [0.008478s]
Building seed filter...  [1.65988s]
Searching alignments...  [2.35687s]
Processing query chunk 0, reference chunk 0, shape 2, index chunk 1.
Building reference index...  [34.9678s]
Building query index...  [0.0074s]
Building seed filter...  [1.46732s]
Searching alignments...  [3.46492s]
Processing query chunk 0, reference chunk 0, shape 2, index chunk 2.
Building reference index...  [52.4298s]
Building query index...  [0.028313s]
Building seed filter...  [1.79419s]
Searching alignments...  [3.01235s]
Processing query chunk 0, reference chunk 0, shape 2, index chunk 3.
Building reference index...  [38.7443s]
Building query index...  [0.015742s]
Building seed filter...  [2.40674s]
Searching alignments...  [4.29933s]
Processing query chunk 0, reference chunk 0, shape 3, index chunk 0.
Building reference index...  [57.9889s]
Building query index...  [0.014374s]
Building seed filter...  [2.16982s]
Searching alignments...  [3.1995s]
Processing query chunk 0, reference chunk 0, shape 3, index chunk 1.
Building reference index...  [42.4564s]
Building query index...  [0.014706s]
Building seed filter...  [1.85173s]
Searching alignments...  [2.46824s]
Processing query chunk 0, reference chunk 0, shape 3, index chunk 2.
Building reference index...  [51.7143s]
Building query index...  [0.008548s]
Building seed filter...  [2.69499s]
Searching alignments...  [3.15947s]
Processing query chunk 0, reference chunk 0, shape 3, index chunk 3.
Building reference index...  [40.4208s]
Building query index...  [0.011588s]
Building seed filter...  [1.69186s]
Searching alignments...  [2.43579s]
Deallocating buffers...  [0.178726s]
Computing alignments... dyld: lazy symbol binding failed: Symbol not found: __ZNSt8__detail15_List_node_base7_M_hookEPS0_
  Referenced from: /Volumes/WD/Sequencing/tools/diamond (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libstdc++.6.dylib

dyld: Symbol not found: __ZNSt8__detail15_List_node_base7_M_hookEPS0_
  Referenced from: /Volumes/WD/Sequencing/tools/diamond (which was built for Mac OS X 10.12)
  Expected in: /usr/lib/libstdc++.6.dylib

**Comment by bbuchfink** [comment]
Sorry but I'm out of ideas right now about this problem. You can try to
find another computer or run Diamond inside a Linux virtual machine.
