### ISSUE TITLE
Error: Accession exceeds maximum length

### ISSUE THREAD

**Issue by homeveg** [bbuchfink/diamond#169]
I am trying to annotate a de-novo metagenome assembly. 
As an input I've chosen single 300 Kbps long metagenomic bin.
  
While running the Diamond producing the following error:

Joining output blocks... Error: Accession exceeds maximum length.
terminate called after throwing an instance of 'std::runtime_error'
Error: Accession exceeds maximum length.
terminate called recursively
Error: Accession exceeds maximum length.
Error: terminate called recursively
  what():  Accession exceeds maximum length.
Error: Accession exceeds maximum length.
terminate called recursively
Accession exceeds maximum length.
Error: Error: Error: terminate called recursively
Accession exceeds maximum length.Error: Accession exceeds maximum length.Error: Accession exceeds maximum length.
Aborted

**Diamond command line:**
diamond blastx -d reference-genomes.faa -q hybrid_Kupferzell.bin.89.fa -o hybrid_Kupferzell.bin.89.tax -p 100 -f 102 --taxonmap prot.accession2taxid.tax.gz --taxonnodes nodes.dmp -v

**output:**
diamond v0.9.10.111 | by Benjamin Buchfink <buchfink@gmail.com>
Licensed under the GNU AGPL <https://www.gnu.org/licenses/agpl.txt>
Check http://github.com/bbuchfink/diamond for updates.

#CPU threads: 100
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
SSSE3 enabled.
POPCNT enabled.
Percentage range of top alignment score to report hits: 10
Temporary directory: ./Diamond
Opening the database...  [0.002197s]
Reference = /mnt/fungen/db03/OxNano_Assembly/Neo19/MetaWatt/databases/reference-genomes.faa.dmnd
Sequences = 7656076
Letters = 2575758935
Block size = 2000000000
Loading taxonomy...  [235.792s]
Loading taxonomy nodes...  [0.462684s]
Opening the input file...  [0.001301s]
Opening the output file...  [0.001088s]
Loading query sequences...  [0.048664s]
Sequences = 528, letters = 10045832, average length = 19026
Masking queries...  [0.098327s]
Building query seed set...  [0.044272s]
Algorithm: Double-indexed
Reduction: [A][RK][NDQE][C][G][H][ILMV][FWY][P][ST]
Seed frequency SD: 50
Shape configuration: 111101110111,111011010010111
Building query histograms...  [0.020422s]
Allocating buffers...  [0.001234s]
Loading reference sequences...  [4.12176s]
Sequences = 6081114, letters = 2000000831, average length = 328
Building reference histograms...  [1.07932s]
Allocating buffers...  [0.001179s]
Initializing temporary storage...  [2.37189s]
Processing query chunk 0, reference chunk 0, shape 0, index chunk 0.
Building reference index...  [2.80773s]
Building query index...  [0.051961s]
Building seed filter...  [0.327382s]
Searching alignments...  [0.267725s]
Processing query chunk 0, reference chunk 0, shape 0, index chunk 1.
Building reference index...  [2.43848s]
Building query index...  [0.046987s]
Building seed filter...  [0.328642s]
Searching alignments...  [0.18841s]
Processing query chunk 0, reference chunk 0, shape 0, index chunk 2.
Building reference index...  [2.52221s]
Building query index...  [0.046031s]
Building seed filter...  [0.323982s]
Searching alignments...  [0.173828s]
Processing query chunk 0, reference chunk 0, shape 0, index chunk 3.
Building reference index...  [2.36883s]
Building query index...  [0.046256s]
Building seed filter...  [0.326565s]
Searching alignments...  [0.180982s]
Processing query chunk 0, reference chunk 0, shape 1, index chunk 0.
Building reference index...  [2.32607s]
Building query index...  [0.054037s]
Building seed filter...  [0.32369s]
Searching alignments...  [0.176636s]
Processing query chunk 0, reference chunk 0, shape 1, index chunk 1.
Building reference index...  [2.63051s]
Building query index...  [0.046186s]
Building seed filter...  [0.32215s]
Searching alignments...  [0.176079s]
Processing query chunk 0, reference chunk 0, shape 1, index chunk 2.
Building reference index...  [2.41341s]
Building query index...  [0.045843s]
Building seed filter...  [0.322576s]
Searching alignments...  [0.178012s]
Processing query chunk 0, reference chunk 0, shape 1, index chunk 3.
Building reference index...  [2.4027s]
Building query index...  [0.046508s]
Building seed filter...  [0.321087s]
Searching alignments...  [0.176699s]
Deallocating buffers...  [0.01685s]
Opening temporary output file...  [0.002014s]
Computing alignments...  [9.21846s]
Deallocating reference...  [0.010575s]
Loading reference sequences...  [1.41949s]
Sequences = 1574962, letters = 575758104, average length = 365
Building reference histograms...  [0.369152s]
Allocating buffers...  [0.00103s]
Initializing temporary storage...  [2.40572s]
Processing query chunk 0, reference chunk 1, shape 0, index chunk 0.
Building reference index...  [0.736878s]
Building query index...  [0.043945s]
Building seed filter...  [0.07942s]
Searching alignments...  [0.085951s]
Processing query chunk 0, reference chunk 1, shape 0, index chunk 1.
Building reference index...  [0.519606s]
Building query index...  [0.039081s]
Building seed filter...  [0.078179s]
Searching alignments...  [0.049739s]
Processing query chunk 0, reference chunk 1, shape 0, index chunk 2.
Building reference index...  [0.530702s]
Building query index...  [0.0417s]
Building seed filter...  [0.077936s]
Searching alignments...  [0.050281s]
Processing query chunk 0, reference chunk 1, shape 0, index chunk 3.
Building reference index...  [0.488087s]
Building query index...  [0.037743s]
Building seed filter...  [0.078281s]
Searching alignments...  [0.04643s]
Processing query chunk 0, reference chunk 1, shape 1, index chunk 0.
Building reference index...  [0.450076s]
Building query index...  [0.03641s]
Building seed filter...  [0.076029s]
Searching alignments...  [0.045938s]
Processing query chunk 0, reference chunk 1, shape 1, index chunk 1.
Building reference index...  [0.61555s]
Building query index...  [0.042125s]
Building seed filter...  [0.078288s]
Searching alignments...  [0.050107s]
Processing query chunk 0, reference chunk 1, shape 1, index chunk 2.
Building reference index...  [0.480147s]
Building query index...  [0.038656s]
Building seed filter...  [0.076901s]
Searching alignments...  [0.046307s]
Processing query chunk 0, reference chunk 1, shape 1, index chunk 3.
Building reference index...  [0.488398s]
Building query index...  [0.035272s]
Building seed filter...  [0.076356s]
Searching alignments...  [0.045741s]
Deallocating buffers...  [0.004309s]
Opening temporary output file...  [0.001681s]
Computing alignments...  [1.79571s]
Deallocating reference...  [0.005271s]
Loading reference sequences...  [2e-05s]
Deallocating buffers...  [5e-06s]
Joining output blocks... Error: Accession exceeds maximum length.
terminate called after throwing an instance of 'std::runtime_error'
Error: Accession exceeds maximum length.
terminate called recursively
Error: Accession exceeds maximum length.
Error: terminate called recursively
  what():  Accession exceeds maximum length.
Error: Accession exceeds maximum length.
terminate called recursively
Accession exceeds maximum length.
Error: Error: Error: terminate called recursively
Accession exceeds maximum length.Error: Accession exceeds maximum length.Error: Accession exceeds maximum length.
Aborted

**Comment by bbuchfink** [comment]
The format you are using relies on every database sequence title starting
with the accession of the sequence like in the ncbi nr database. Are you
sure this is the case for your database? Can you show me an example of a
reference sequence record?

**Comment by homeveg** [comment]
Below is the output of the following command:
`
cat reference-genomes.faa  | grep ">" -A 3 | head -n30
`
>11630~YP_138535.1 Z protein [Pichinde mammarenavirus]
MGLRYSKEVRESHGDEDVVGRVPMTLNLPQGLYGRFNCKSCWFVNKGLIRCKDHYLCLGCLTKMHSRGHLCEICGHSLPT
KMEFLESPSAPPYEP
>11630~YP_138534.1 L polymerase [Pichinde mammarenavirus]
MEEYVSEFKDMVRKWVPEWEELSEQKNNVLAQVKDRAITIEGLKLLSMLVEVDSCKKHSCRHNTRMTVNAILRELKVTCP
TLPDVTPDGYCMVGDVLILLEVFVRTSQEAFEKKYNQDFLKLMQLSSDLKRQNITLVPVIDGRSSYYVEYIPDWVVERLR
WLLLKLMDGLRTSGEEVEELEYERLISSLSSLENQSLGLESLLAVKERGLPYKVRLEKALVSCINNKLTTDQCRTKIMEV
--
>11630~YP_138544.1 N protein [Pichinde mammarenavirus]
MSDNIPSFRWVQSLRRGLSNWTHPVKADVLSDTRALLSALDFHKVAQVQRMVRKDKRTDSDLTKLRDMNKEVDALMNMRS
VQRDNVLKVGGLAKEELMELASDLDKLRKKVTRTEGLSQPGVYEGNLTNTQLEQRAEILRSMGFANARPAGNRDGVVKVW
DIKDNTLLINQFGSMPALTIACMTEQGGEQLNDVVQALSALGLLYTVKFPNMTDLEKLTQQHSALKIISHEPSALNISGY
--
>11630~YP_138543.1 GPC precursor protein [Pichinde mammarenavirus]
MGQIVTLIQSIPEVLQEVFNVALIIVSVLCIVKGFVNLMRCGLFQLVTFLILSGRSCDSMMIDRRHNLTHVEFNLTRMFD
NLPQSCSKNNTHHYYKGPSNTTWGIELTLTNTSIANETSGNFSNIGSLGYGNISNCDRTREAGHTLKWLLNELHFNVLHV
TRHIGARCKTVEGAGVLIQYNLTVGDRGGEVGRHLIASLAQIIGDPKIAWVGKCFNNCSGDTCRLTNCEGGTHYNFLIIQ
--
>31750~NP_620037.1 capsid protein [Pepper ringspot virus]
MAMYDDEFDTKASDLTFSPWVEVENWKDVTTRLRAIKFALQADRDKIPGVLSDLKTNCPYSAFKRFPDKSLYSVLSKEAV
IAVAQIQSASGFKRRADEKNAVSGLVSVTPTQISQSASSSAATPVGLATVKPPRESDSAFQEDTFSYAKFDDASTAFHKA
LAYLEGLSLRPTYRRKFEKDMNVKWGGSGSAPSGAPAGGSSGSAPPTSGSSGSGAAPTPPPNP
>31750~NP_620036.1 12K protein [Pepper ringspot virus]
MTKCALPECEENTQKNQMTCSMKHANKYNRYLASKFDVKRKCECKNCGWFPAISVQPDYVEVYFCCGMKHLQKCKTDNPL
KEKRLNTPKRLFRDDVDFGLNLLFSEVC
>31750~NP_620035.1 29K protein [Pepper ringspot virus]
MENDKSLVALKKKTFELSNFSRLGSVELFVDQKRKRPKYFHRRRQVVLNNVAGSLTEHKLGAFKVEDVGRIKSYAFLRIV
AIQLVVSSHLPRDTPGHLQVDILDTRLTDGRKKNKVLQRFMAKACDNTSLIQYKFDYCVSTSENLADLWHIGTVATGVPV
VDGCFPFSVEMSLIWVATDSTTRLNPEELNSTDYLEGDFSDQSQFEEYMSLNQVKAKAIDVKFKGEYVPKLRQDRNLASL

**Comment by bbuchfink** [comment]
If you want to use the taxonomic classification output format, the db
sequence titles need to start with the accession, like this:

>YP_138535.1 Z protein [Pichinde mammarenavirus]

**Comment by homeveg** [comment]
Thanks!

**Comment by homeveg** [comment]
Thanks again, the diamond blastx step works fine. 
But now I have a problem running  `diamond view ` command - with different combinations of parameters it's always returning the following error:
`Error: Invalid parameter count for option '--db'
`
The shortest command I was trying to use:
`diamond view -daa bin.89.daa --db diamond-reference-genomes.faa
`

**Comment by bbuchfink** [comment]
The option is --daa with two dashes.
