### ISSUE TITLE
Missing results

### ISSUE THREAD

**Issue by necrolyte2** [bbuchfink/diamond#17]
It seems that diamond is missing some results sometimes

Let's say you have a DNA fasta file called `in.fasta`
Convert `in.fasta` to protein called`in.prot.fasta`
Then run blast's makeblastdb on`in.prot.fasta`and then use blastx against that database supplying`in.fasta` as the query. I would expect to get all of the sequences back as hits which I do with blast.

Doing the same with diamond it seems you sometimes do not get all the sequences back.

Here is a small makefile that produces this issue

https://gist.github.com/necrolyte2/423a660a46c02130606c

In this example I get 10 unique hits back from blastx, but only get 9 back from diamond when I would expect to get 10.

**Comment by bbuchfink** [comment]
Sorry for the late reply. I will try to look into this asap but development
is currently delayed due to health issues.

2015-09-24 20:42 GMT+02:00 Tyghe Vallard <notifications@github.com>:

**Comment by necrolyte2** [comment]
No problem. Get better!

**Comment by bbuchfink** [comment]
Sorry for the extremely late reply. The reason is that diamond masks sequences between two stop codons below a certain length, as a simple gene calling heuristic. To disable this, use the option --run-len 1.
