### ISSUE TITLE
Sensitivity of the --more-sensitive option

### ISSUE THREAD

**Issue by xibalbanus** [bbuchfink/diamond#172]
Hello,

In the paper you mention that 92% of results obtained by DIAMOND-sensitive were the same as with BLASTX. Has this kind of verification of accuracy been completed since the publication's release using the more sensitive option? I would like to use this for the annotation of many transcriptomes and am curious to know the accuracy of this more sensitive version of DIAMOND compared to BLAST. 

Thank you for your time.

**Comment by bbuchfink** [comment]
Hi,

it's hard to give a percentage number for the sensitivity because this is
very dependent on your data. You should try yourself if the sensitivity is
sufficient for your application.
