### ISSUE TITLE
dbinfo command is not documented in --help and does not work with HUMAnN2 tutorial data

### ISSUE THREAD

**Issue by sritchie73** [bbuchfink/diamond#173]
Hi, 

I'm trying to run through the HUMAnN2 tutorial at (https://bitbucket.org/biobakery/biobakery/wiki/humann2)

I have installed diamond v0.9.10.111 , but upon running the first command I get an error from diamond: `Error: Database was built with a different version of diamond as is incompatible.`

The file diamond can apparently be downloaded from http://huttenhower.sph.harvard.edu/humann2_data/uniprot/uniref_annotated/uniref90_DEMO_diamond.tar.gz (according to the humann2_databases command used to download the file).

After digging through some Issues here, I was able to find that a `dbinfo` command has recently been added to diamond (note: this is not documented in `--help`), but it does not give me any information about the file:

```
> diamond dbinfo --db uniref90_demo_prots.dmnd 
diamond v0.9.10.111 | by Benjamin Buchfink <buchfink@gmail.com>
Licensed under the GNU AGPL <https://www.gnu.org/licenses/agpl.txt>
Check http://github.com/bbuchfink/diamond for updates.

Error: Database was built with a different version of diamond as is incompatible.
```

**Comment by bbuchfink** [comment]
Sorry, I will provide a fix for this shortly. The latest version to support
the old db format is 0.8.11.

**Comment by sritchie73** [comment]
Thanks,

I've just tried running humann2 with diamond v0.8.11 but I get an error; 
`"CRITICAL ERROR: Please update diamond from version 0.8.11 to version 0.8.22"` 
I'm not sure if this is returned from humann2 or diamond. 

I had also initially tried running the `diamond getseq` command with v0.9.11 to try to rebuild the humann2 example database, but got the same error as in the first post; `Error: Database was built with a different version of diamond as is incompatible.`

I tried the `diamond getseq` command using v0.8.11.73 (it seems to be present, but not documented in `--help` in that version) but get the error `Error: strict_fstream: open('',in|binary): open failed: No such file or directory`.

Is it likely to be possible to rebuild their example database using `diamond getseq` with some version of diamond > 0.8.11.73 but < 0.9.11 ?

I have opened an issue with the humann2 software noting the problems with their example data and their listed dependency requirements (their minimum dependency is diamond >= v0.7.3, but the humann2 software does not work with diamond v0.7.3 because humann2 tries to call the `version` command which is not in that version of diamond).

**Comment by bbuchfink** [comment]
The first error message is from humann2.

The getseq command is not supported in any version that is compatible with
the old db format. It would be possible to provide this if it's relevant to
you but it would also be a good idea if the humann2 people fixed their
example data.
