### ISSUE TITLE
bad_alloc

### ISSUE THREAD

**Issue by cmeesters** [bbuchfink/diamond#176]
Hi,

I am trying to get diamond working on our cluster and observe a rather strange behavior: diamond is started on nodes with 115 GB free memory (old AMD bulldozer nodes with 64 cores) and consumes lots of memory (up to 60 % of a 128 GB node, measured simply with top), before it crashes with 

<snip>
Building seed filter...  [0.0135s]
Searching alignments... Error: std::bad_alloc
terminate called after throwing an instance of 'std::bad_alloc'
  what():  std::bad_alloc

Both, the database and the query file contain roughly 2GB of data. I am using diamond version 0.9.12, yet observed this behavior also with version 0.9.6 (diamond is provided by a modulefile and I compiled both modules for our cluster; compilers were gcc v5.4.0 and v4.8.4).

The job script is (omitting cluster specific stuff):

#SBATCH -n 1
#SBATCH -c 64
#SBATCH -N1

module load bio/DIAMOND/0.9.12-foss-2016b

srun -c 64 diamond blastp -d db.dmnd -q query.fasta -p 64 

The number of threads does not make a difference (using 64 threads does not make sense anyway, as on our hardware diamond only scales to about 8 threads, which corresponds to a NUMA block - suggestions are welcome)

Any ideas?

Best regards,
Christian Meesters

**Comment by bbuchfink** [comment]
Hi Christian,

please try to use the option -o to set an output file. If possible this
should be on a fast local disk, but not a memdrive or a nfs drive. Could
you also use the option --log. This will generate a diamond.log file which
you should send to me.

Best regards,

Benjamin

**Comment by cmeesters** [comment]
Dear Benjamin,

will do. However, I forgot to mention, that I left as many options as possible out to keep this issue reproducible. I tried combinations of -o / --outfmt already. 

Best regards,
Christian

**Comment by cmeesters** [comment]
Good Morning Benjamin,

here you go:
[diamond.log](https://github.com/bbuchfink/diamond/files/1445444/diamond.log)

I also added the submit script. I copied the reference db onto a ramdisk to enable multiple diamond instances in a later version on multiple nodes:
[submit.txt](https://github.com/bbuchfink/diamond/files/1445446/submit.txt)

Cheers,
Christian

**Comment by bbuchfink** [comment]
Could you try again with option —algo 0 please?

Christian Meesters <notifications@github.com> schrieb am Mo. 6. Nov. 2017
um 09:23:

**Comment by cmeesters** [comment]
Hi,

That would be after line 54. (Nice that there is no overwrite!)
[diamond.log](https://github.com/bbuchfink/diamond/files/1446340/diamond.log)

Now, the run is a lot less memory hungry: less than 5 GB compared to more than 67 (same input). 
However: There is no aligned read in the output - as mentioned in the log file. 

Well, I am just trying to set up diamond for our users, maybe may example input is screwed. I am looking into this matter by comparing it with NCBI-BLAST-run, just now.

Best regards,
Christian

**Comment by cmeesters** [comment]
Need to re-do the reference run, there are several 100k hits, but alas the settings weren't comparable.

Can you draw any conclusions, yet?
Cheers
Christian

**Comment by bbuchfink** [comment]
It seems the --algo 1 (query-indexed) mode was auto-picked on your data,
which is normally only used for very small query datasets. Here it
shouldn't be used and I will have to adjust that. Until then you can
manually use the option --algo 0 if necessary. Please let me know if this
works on your data.

**Comment by cmeesters** [comment]
Well, there still is the minor issue of the zero content output. It might or might not be related to the reported issue: It might be that my testdata is not perfect, yet I get many hits with the canonical NCBI-BLAST+ but none with diamond. This is regardless of --rank-ratio(2) settings I used. I tinkered a bit with other settings to no avail. Any hint is welcome.

**Comment by bbuchfink** [comment]
Could it be very repetitive or low complexity data? You can try option
 —freq-sd 999999. you can also check the masking by running diamond mask -q
queryfile

Christian Meesters <notifications@github.com> schrieb am Mi. 8. Nov. 2017
um 10:31:
