### ISSUE TITLE
Error: Invalid output field

### ISSUE THREAD

**Issue by mycovirus** [bbuchfink/diamond#178]
this is my command：
 “diamond blastx -d /data/fasatq_nr/nr.dmnd -q 1.fasta --sensitive -p 40 -e 1e-4 -o 666.m8 --outfmt 6 qseqid qlen stitle pident slen length mismatch evalue & ”
then it reasulted in 
“Joining output blocks... Error: Invalid output field
Error: Invalid output field
terminate called recursively”

hoping your advices
Thanks

**Comment by bbuchfink** [comment]
qcovs is not a valid output field. If that does not fix your problem, can
you tell me what diamond version you are using? You can check by diamond
--version.

**Comment by mycovirus** [comment]
Thank your very much
