### ISSUE TITLE
On Linux, diamond is only for x86_64?

### ISSUE THREAD

**Issue by wwood** [bbuchfink/diamond#18]
Hi,

I just wanted to check, I presume that diamond is not meant for mips, arm or i686? They seem to not be building on these architectures:

arm http://hydra.gnu.org/build/701534/nixlog/1
mips http://hydra.gnu.org/build/700108/nixlog/1
i686 http://hydra.gnu.org/build/700494/nixlog/1

I understand if supporting these platforms is not a priority, I just wanted to double check before I disable the building of them in guix. x86_64 works great though!

Thanks,
ben

**Comment by bbuchfink** [comment]
Hi,

I never tested these platforms but hopefully I'll be able to support them
in a future version.

Benjamin

2015-10-06 12:39 GMT+02:00 Ben J Woodcroft <notifications@github.com>:

**Comment by wwood** [comment]
OK, no problem. Thanks.
