### ISSUE TITLE
idea: official diamond Docker container

### ISSUE THREAD

**Issue by antonkulaga** [bbuchfink/diamond#180]
Current biocontainers docker container is outdated, so I had to build my own https://quay.io/repository/comp-bio-aging/diamond (docker file is https://github.com/antonkulaga/rna-seq/tree/master/containers/diamond ).
It is quite a popular practice to have official docker container that automatically rebuilds (by quay or in other way) on each release I think it can be useful for diamond as well

**Comment by DrYak** [comment]
BTW, it seems that diamond [is in bioconda](https://bioconda.github.io/recipes/diamond/README.html)
and they automatically build containers on each recipe update.
That would also be a way to handle it.

**Comment by bbuchfink** [comment]
This is certainly a good idea and I plan on doing this along with an
official bioconda release after some other upcoming features.

**Comment by antonkulaga** [comment]
Diamond works like a charm, way faster than BlastP.
@bbuchfink just an offtopic question, do you plan to make a diamond-like alternative to BlastN?

**Comment by bbuchfink** [comment]
A BlastN mode is planned but there are other priorities right now so it's
probably not going to be available in the near future.

**Comment by bbuchfink** [comment]
An official docker container is now available:
https://hub.docker.com/r/buchfink/diamond/

**Comment by antonkulaga** [comment]
As it is avaliable, I am closing the issue
