### ISSUE TITLE
Failed to allocate sufficient memory

### ISSUE THREAD

**Issue by sfpravelo** [bbuchfink/diamond#182]
Hi, 

I'm running blastx via Diamond but met with this error. I tried to read some problems the same as mine here but nothing is working to the suggested solutions. I wonder what seems to be the problem in my run. 

![image](https://user-images.githubusercontent.com/32627080/34090393-9d72d75e-e3f1-11e7-9db6-0f4f0c3dd0a0.png)

**Comment by bbuchfink** [comment]
Hi,

please try to set a lower block size. For example: -b1 or -b0.4
