### ISSUE TITLE
convert dmnd to text file

### ISSUE THREAD

**Issue by nick-youngblut** [bbuchfink/diamond#183]
I want to assess all of the genes present in one diamond database used in the humann2 pipeline: uniref90.ec_filtered.1.1.dmnd. Only the dmnd file is provided, so I can't just look at the sequence file used to generate the dmnd file. Can I convert the dmnd file to a plain text file so that I can view the contents of the dmnd file?

**Comment by bbuchfink** [comment]
It depends on the version that was used to create the files. In the current
version you can use

diamond getseq -d dbfile

to get the sequences in fasta format. But for older versions there's no
such option.
