### ISSUE TITLE
error installation of diamond

### ISSUE THREAD

**Issue by cjieming** [bbuchfink/diamond#186]
I have been getting this error after I input "make install":
Install the project...
-- Install configuration: "Release"
CMake Error at cmake_install.cmake:47 (file):
  file INSTALL cannot find
  "/path/to/diamond".

I implemented before make install:
 cmake -DCMAKE_INSTALL_PREFIX=/path/to/ ..

Please help.

**Comment by bbuchfink** [comment]
For /path/to you need to use a path that actually exists and that you want
to install diamond to. Like to install it in your home directory you can
use:

cmake -DCMAKE_INSTALL_PREFIX=~
