### ISSUE TITLE
error installing latest version

### ISSUE THREAD

**Issue by evelienadri** [bbuchfink/diamond#187]
I tried to download the latest version of diamond (v0.9.15) from the link in the manual. 
wget http://github.com/bbuchfink/diamond/releases/download/v0.9.15/diamond-linux64.tar.gz
This gave a 404 Not Found error. 

When I tried the link from the readme page (v0.9.14) I got a very long coded credential error. 

Can you provide the correct wget link or best version to download? Thank you!
(I'm currently on v0.8.16, I hope that is not interfering)

**Comment by bbuchfink** [comment]
Sorry, the correct link is:
https://github.com/bbuchfink/diamond/releases/download/v0.9.14/diamond-linux64.tar.gz

**Comment by evelienadri** [comment]
Thank you! 

FYI, there is an issue with downloading the files with wget in Debian 5. The filename is too long and the download gets cancelled. It works in Debian 7.
