### ISSUE TITLE
FATAL: kernel too old

### ISSUE THREAD

**Issue by mkellom** [bbuchfink/diamond#188]
Trying to run the pre-compiled executable on my university's HPC cluster but I'm getting the error message: FATAL: kernel too old

Anyway to work around this?
Or do I need to contact our system admins?

Thanks

**Comment by bbuchfink** [comment]
You need to compile the software from source in this case. You can download
the source package here:
https://github.com/bbuchfink/diamond/archive/v0.9.14.tar.gz

Further instructions are in the manual.
