### ISSUE TITLE
Clarify license

### ISSUE THREAD

**Issue by colinbrislawn** [bbuchfink/diamond#19]
Hello @bbuchfink,

I've been working to get bioinformatics tools available as anaconda packages, including Diamond over at biocore/conda-recipes#16

I wanted to check in with you. Are you comfortable with this?

If you are cool with this, can you help me understand your license?
Your [COPYING file](https://github.com/bbuchfink/diamond/blob/master/src/COPYING) looks like BSD, while [a few of your files](https://github.com/bbuchfink/diamond/search?utf8=%E2%9C%93&q=license) use a Affero GPL.

Thanks for your time!
Colin

**Comment by bbuchfink** [comment]
All files are supposed to be under the BSD license. These few files need to be fixed.

Benjamin

**Comment by colinbrislawn** [comment]
Thank you for developing this software and helping me understand your license! I appreciate the flexibility the BSD provides.

**Comment by bgruening** [comment]
I guess this one can be closed.
