### ISSUE TITLE
Optimising diamond settings for metatranscriptomics

### ISSUE THREAD

**Issue by nabilquraishi** [bbuchfink/diamond#190]
Hi,
I am trying to optimise a pipeline for gut metatranscriptomics with Diamond using the latest Uniref90 db. I wondered if the default settings for diamond should be adjusted for RNA reads that are highly expressed. For example  '--freq-sd' would ignore repetitive seeds above a threshold. Would result in highly expressed gene transcripts from being discarded? Its just that I have found that randomly blasting unaligned reads was resulting in hits to gut bacteria at 1e-7 and identity threshold of >95% with >90% coverage. 

Thank you,
Nabil

**Comment by bbuchfink** [comment]
Hi,

I don't really have experience analyzing data like that. You should
probably experiment with these settings yourself and see what kind of
effect it has on your results.

Best regards,

Benjamin

**Comment by nabilquraishi** [comment]
Thanks Benjamin.
