### ISSUE TITLE
FreeBSD build error with v0.9.18 and latest commit (d80de34)

### ISSUE THREAD

**Issue by Jehops** [bbuchfink/diamond#192]
Hello,

Here is the error
`/wrkdirs/usr/ports/biology/diamond/work/diamond-d80de34c196cc181bd323c422b6b80eb3c043bb7/src/util/io/file_sink.cpp:43:102: error: use of undeclared identifier 'S_IRUSR'`

Here is the full build log:
http://pkg.awarnach.mathstat.dal.ca/data/11amd64-default/2018-02-17_19h57m54s/logs/errors/diamond-0.9.18.log

**Comment by bbuchfink** [comment]
Hi,

please try again with the latest commit.

**Comment by Jehops** [comment]
Fixed.  Thanks.
