### ISSUE TITLE
unaligned reads file writing 

### ISSUE THREAD

**Issue by jregalad-o** [bbuchfink/diamond#193]
On diamond 0.9.18

Aligning 4m reads to nr

Runs normally until unaligned reads file is written to disk. File keeps increasing indefinitely until no more space is left on disk. No error message is sent except when there is no more space in disk.  

system info:
Linux  4.4.109 #28 SMP Thu Jan 4 17:02:49 MET 2018 x86_64 x86_64 x86_64 GNU/Linux

Compilation logs:
[cmake.log](https://github.com/bbuchfink/diamond/files/1747685/cmake.log)
[make.log](https://github.com/bbuchfink/diamond/files/1747690/make.log)

cmd line:
diamond blastx -p 64 -d nr_082017.dmnd -o out -f 100 -v -q sampleR1R2.fq.gz -k 25 -b 10 -c 1 --log --un unaligned.fa -unal 1

I work in a network file system where executables are compiled in one server and executed in cluster nodes. I've had the problem of "illegal instruction" on a couple of nodes where I have to recompile diamond for that specific node. Although this doesn't correlate with the unaligned file problem. 

thanks for any help 

I get the same problems with different diamond version. Haven't tried exhaustively but diamond 0.9.1 works.  

In addition, in all versions of diamond I always get a slight discrepancy between total queries and queries aligned + queries unaligned where:

    # queries aligned + # queries unaligned >  # total queries

**Comment by bbuchfink** [comment]
Thanks for reporting this. I have just commited a patch that should fix
this issue.
