### ISSUE TITLE
Reduce the standard output of a command

### ISSUE THREAD

**Issue by minor7b5** [bbuchfink/diamond#194]
I would like to stop the visual progress that diamond blastx prints to the screen, e.g.:
```
diamond v0.9.18.119 | by Benjamin Buchfink <buchfink@gmail.com>
Licensed under the GNU AGPL <https://www.gnu.org/licenses/agpl.txt>
Check http://github.com/bbuchfink/diamond for updates.

#CPU threads: 4
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
#Target sequences to report alignments for: 1
Temporary directory: 
Opening the database...  [4.1e-05s]
Opening the input file...  [2.5e-05s]
Opening the output file...  [9.4e-05s]
```
I've tried funnelling the SO to``` >/dev/null```, which seems to work for ```diamond makedb```, but throws up errors for ```diamond blastx```, at least when the command is being called from within a python script.

Is there any way to make the programme run 'quietly'?

Many thanks

**Comment by bbuchfink** [comment]
Yes, you can use the option --quiet.
