### ISSUE TITLE
Not compiling

### ISSUE THREAD

**Issue by jregalad-o** [bbuchfink/diamond#196]
Latest commit is not compiling:

    cmake ..
-- The C compiler identification is GNU 5.4.0
-- The CXX compiler identification is GNU 5.4.0
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test COMPILER_SUPPORTS_MARCHNATIVE
-- Performing Test COMPILER_SUPPORTS_MARCHNATIVE - Success
-- Found ZLIB: .../libz.so (found version "1.2.11")
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
-- Configuring done
-- Generating done
-- Build files have been written to: 

    make
Bulding CXX object CMakeFiles/diamond.dir/src/output/output_format.cpp.o
In file included from .../diamond/src/output/../data/taxonomy.h:24:0,
from .../diamond/src/output/output_format.cpp:20:
.../diamond/src/output/../data/../util/util.h:471:26: error: variable or field ‘print_binary’ declared void
inline void print_binary(uint64_t x)
^
.../diamond/src/output/../data/../util/util.h:471:26: error: ‘uint64_t’ was not declared in this scope
In file included from .../diamond/src/output/../basic/match.h:27:0,
from .../diamond/src/output/output_format.h:23,
from .../diamond/src/output/output_format.cpp:21:
.../diamond/src/output/../basic/packed_loc.h:25:16: error: expected declaration before end of line
cc1plus: warning: unrecognized command line option ‘-Wno-ignored-attributes’
CMakeFiles/diamond.dir/build.make:758: recipe for target 'CMakeFiles/diamond.dir/src/output/output_format.cpp.o' failed
make[2]: *** [CMakeFiles/diamond.dir/src/output/output_format.cpp.o] Error 1
CMakeFiles/Makefile2:67: recipe for target 'CMakeFiles/diamond.dir/all' failed
make[1]: *** [CMakeFiles/diamond.dir/all] Error 2
Makefile:127: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by bbuchfink** [comment]
Sorry, please try again with the latest commit.

**Comment by MaryoHg** [comment]
Hi, both @jregalad-o @bbuchfink.

I'm having the same issue trying to compile diamond from github.
May you please help me to solve it?

I'm using:
` $ gcc --version`
gcc (GCC) 6.3.0
Copyright (C) 2016 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.

The error showed is:
> Scanning dependencies of target diamond
[  1%] Building CXX object CMakeFiles/diamond.dir/src/run/main.cpp.o
[  2%] Building CXX object CMakeFiles/diamond.dir/src/basic/config.cpp.o
/tmp/ccV9Ajq4.s: Assembler messages:
/tmp/ccV9Ajq4.s:11372: Error: no such instruction: `shlx %rax,%rdx,%rdx'
make[2]: *** [CMakeFiles/diamond.dir/src/basic/config.cpp.o] Error 1
make[1]: *** [CMakeFiles/diamond.dir/all] Error 2
make: *** [all] Error 2

Is is actually the same cause?



I appreciate your kind help,
Best,



MaryoHg.

**Comment by bbuchfink** [comment]
Hi,

an error like this could indicate some problem with the compiler setup on
your system. Do other tools compile without error using cmake? You could
also try another build method, the build_simple.sh script contained in the
package will also build diamond.

Best regards,

Benjamin

**Comment by MaryoHg** [comment]
Hi, again @bbuchfink.
Thanks for your soon reply.

I already checked which version of cmake is installed on server (among others):
`$module avail`
>cmake/3.6.1
cmake/3.9.3/gcc/5.2.0
cmake/3.9.3/gcc/6.3.0

I tried to compile using three vesion of it but failed. I'm don't know why.
Anyway,
it was successfully compiled using `build_simple.sh` script.



Thank you very much.
Best,


Maryo.
