### ISSUE TITLE
Seg fault and  Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by jregalad-o** [bbuchfink/diamond#197]
Hi, 

Still running into problems with diamond. 

In last commit I get a segmentation fault. No error messages before that. diamond.log ends in:

...
Gross cells = 0
Gross GCUPS = 0
Gross GCUPS/thread = 0
Net cells = 0
Net GCUPS = 0
Net GCUPS/thread = 0
Deallocating buffers...  [0.002206s]
Loading trace points...  [0.001146s]
 [85.5203s]
Deallocating reference...  [0.042435s]
Loading reference sequences...  [0.041787s]
Deallocating buffers...  [0.214531s]
Joining output blocks...  [26.6742s]
Writing unaligned queries...  [0.356759s]
Deallocating queries...  [0.129s]
Loading query sequences...  [0.002475s]
Closing the input file...  [0.002532s]
Closing the output file... 

System information:
OS - x86_64 GNU/Linux
CPU:
Architecture:          x86_64
CPU op-mode(s):        32-bit, 64-bit
Byte Order:            Little Endian
CPU(s):                16
On-line CPU(s) list:   0-15
Thread(s) per core:    2
Core(s) per socket:    4
Socket(s):             2
NUMA node(s):          2
Vendor ID:             GenuineIntel
CPU family:            6
Model:                 44
Stepping:              2
CPU MHz:               1600.000
BogoMIPS:              4787.95
Virtualization:        VT-x
L1d cache:             32K
L1i cache:             32K
L2 cache:              256K
L3 cache:              12288K
NUMA node0 CPU(s):     0-3,8-11
NUMA node1 CPU(s):     4-7,12-15

gcc - gcc version 4.9.4

Additionally, I've been running into "Illegal instruction (core dumped)" in some of the nodes in the cluster. If I have to recompile diamond in those specific nodes if I want it running.

**Comment by bbuchfink** [comment]
Hi,

could you give me the full command line that you used?

**Comment by jregalad-o** [comment]
diamond blastx -p 16 -d nr_082017.dmnd -o S1 -f 100 -v -q S1MetagenomicR1R2.fq.gz -k 25 -b 10 -c 1 --log --un S1unaligned.fa --unal 1

**Comment by bbuchfink** [comment]
I have just commited a patch that should fix this.

The illegal instruction problem is not that easy to handle. You could
compile a binary that is compatible with your oldest machine and use it for
all but you will lose performance on the newer ones like that.

I will have to look into generating alternative code paths but that will
take some time.

**Comment by jregalad-o** [comment]
Thanks, rerunning with latest commit. 

That's what I thought about  the illegal instruction. 

thanks a lot!!!
