### ISSUE TITLE
Broken link for precompiled binarys?

### ISSUE THREAD

**Issue by oleglovky** [bbuchfink/diamond#199]
I think the links are broken because I tried downloading versions 0.9.18 and 0.9.18 and the binary I got was version 0.7 (with the manual for 0.9.19 included in the .tar).

**Comment by oleglovky** [comment]
I downloaded the binaries to my server using 'wget' (e.g. 'wget http://github.com/bbuchfink/diamond/releases/download/v0.9.19/diamond-linux64.tar.gz'). After unpacking, 'diamond -v' game me version 0.7 and 'diamond -h' gave me an outdated help page which didn't correspond with manual that came with the download.

**Comment by bbuchfink** [comment]
Maybe you accidentally ran a diamond that was globally installed on your
system instead of the downloaded binary?

**Comment by oleglovky** [comment]
No, I didn't have diamond installed before that. I cloned diamond instead it now it's the correct version.
