### ISSUE TITLE
Different number of reads in input fasta and diamond results

### ISSUE THREAD

**Issue by senaj** [bbuchfink/diamond#20]
Hi bbuchfink,

I seem to be missing some reads from the diamond results. For example, my input fasta contains 44,518 sequences but Diamond only outputs 41352 reads in fast mode and 41426 reads in sensitive mode. I can recover some of the reads by by setting the --seg option to no. Are there other reasons that Diamond may exclude some to the reads from the output?

Thank you very much for your help!

**Comment by bbuchfink** [comment]
Hi senaj,
diamond does not include reads in the output which no alignment has been found for. This is probably the reason.

Benjamin

**Comment by senaj** [comment]
Hi Benjamin,

I believe you are correct. I tested this idea using a smaller custom
database and the diamond results produced many less hits.

Thank you very much for your help!

Diamond is a great tool! I am going to test out MALT as well!

Bests regards,

Johnny
