### ISSUE TITLE
could DIAMOND support multiple query files input？

### ISSUE THREAD

**Issue by Zjianglin** [bbuchfink/diamond#201]
Hi， I have two reads files: `50x_1.fq , 50x_2.fq`, which are sequenced from both end of a specific fragment. I'l like to input them at once when run ` diamond blastx ...`, is it possible? Thanks。

**Comment by bbuchfink** [comment]
Hi,
this is currently not possible. You have to align the two files separately.

**Comment by Zjianglin** [comment]
ok，get it. Thank you~

**Comment by arthurvinx** [comment]
Hello @Zjianglin,
I think you could use a read merger to generate a single file from the paired-end reads.
