### ISSUE TITLE
Build of 0.9.20 fails on OSX (10.13.4)

### ISSUE THREAD

**Issue by bromberglab** [bbuchfink/diamond#205]
build_simple.sh exits with an error when trying to include <malloc.h> (not found) - logs attached. No issues when building previous version (0.9.17).

[build.log](https://github.com/bbuchfink/diamond/files/1930020/build.log)

**Comment by ilovezfs** [comment]
Same thing on Homebrew CI https://jenkins.brew.sh/job/Homebrew%20Core%20Pull%20Requests/22588/version=el_capitan/testReport/junit/brew-test-bot/el_capitan/install_diamond/

**Comment by bbuchfink** [comment]
This should be fixed in the latest release.

**Comment by bromberglab** [comment]
resolved, thank you.
