### ISSUE TITLE
Build of 0.9.19 and 0.9.20 fails on CentOS 6.6 and 6.9

### ISSUE THREAD

**Issue by mecantao** [bbuchfink/diamond#206]
Hi, 

When I run build_simple.sh for both 0.9.19 and 0.9.20 versions, I receive the following error messages:

src/data/reference.cpp: In member function ‘void DatabaseFile::get_seq()’:
src/data/reference.cpp:331: error: using ‘typename’ outside of template
src/data/frequent_seeds.cpp: In static member function ‘static void Frequent_seeds::compute_sd2(Atomic<unsigned int>*, __gnu_cxx::__normal_iterator<JoinResult<SeedArray::Entry>*, std::vector<JoinResult<SeedArray::Entry>, std::allocator<JoinResult<SeedArray::Entry> > > >, std::vector<Sd, std::allocator<Sd> >*, std::vector<Sd, std::allocator<Sd> >*)’:
src/data/frequent_seeds.cpp:130: error: using ‘typename’ outside of template
src/data/frequent_seeds.cpp: In member function ‘void Frequent_seeds::Build_context2::operator()(unsigned int, unsigned int)’:
src/data/frequent_seeds.cpp:157: error: using ‘typename’ outside of template
src/search/stage0.cpp:29: error: using ‘typename’ outside of template
src/search/stage0.cpp: In function ‘void search_worker(Atomic<unsigned int>*, const SeedPartitionRange*, unsigned int, size_t, __gnu_cxx::__normal_iterator<JoinResult<SeedArray::Entry>*, std::vector<JoinResult<SeedArray::Entry>, std::allocator<JoinResult<SeedArray::Entry> > > >)’:
src/search/stage0.cpp:52: error: using ‘typename’ outside of template
src/util/memory/memory_pool.cpp: In member function ‘void MemoryPool::free(void*)’:
src/util/memory/memory_pool.cpp:142: error: using ‘typename’ outside of template

/****/
Same error message for CentOS 6.6 and 6.9 
No issues when building previous version (0.9.18).

**Comment by bbuchfink** [comment]
Hi,

this shold be fixed in the latest release.

**Comment by mecantao** [comment]
Hi,

One error when compile:
src/search/stage0.cpp:29: error: using ‘typename’ outside of template

**Comment by bbuchfink** [comment]
Ok, please try again with the latest commit.

**Comment by mecantao** [comment]
Now it's ok.
Thanks
