### ISSUE TITLE
Different results using --block-size and --index-chunks

### ISSUE THREAD

**Issue by kevlim83** [bbuchfink/diamond#207]
Hi,

I am trying to increase performance by tuning --block-size and --index-chunks and -t to /dev/shm. However, it seems that I get different results from the output log files (different number of aligned queries) compared to default --block-size and --index-chunks.

I was wondering how might this be possible since the rest of the parameters are kept the same? Any ideas would be appreciated.

Thanks.

**Comment by bbuchfink** [comment]
Hi,

this is quite normal and caused by certain heuristics that the aligner
uses. Specifically, the aligner ignores some very frequent seeds which can
be different depending on the block size. It's nothing to worry about.
