### ISSUE TITLE
Sequence in table output

### ISSUE THREAD

**Issue by jjkoehorst** [bbuchfink/diamond#208]
We are currently using the database fasta file and the diamond file for blasting such that we can store the homology relation and the sequence of the target. However as the databases gets bigger it becomes more time consuming to parse the fasta file as well. Is it possible to have the protein sequence in the table output file? or to only get the sequences of the targets as a separate file?

**Comment by bbuchfink** [comment]
The blast tabular format is configurable (see 3.6 in the manual) and
there's the field sseq which will print the aligned part of the subject
sequence into the output file. Is that sufficient for you?

**Comment by jjkoehorst** [comment]
Thanks for the tip already have been looking at the output format but unfortunately we need the whole sequence.

**Comment by bbuchfink** [comment]
Ok, I'll add an output field for the whole sequence. Should be done within
the day.

**Comment by bbuchfink** [comment]
Sorry but this will take a bit longer as it's not that easy. Since the
aligner processes the database in blocks, the subject sequences
themselves are not available any more when the output it generated. I
need to think about how to best solve this.

A quick solution for this may take up a lot of memory, so may I ask
how much RAM your system has?

**Comment by bbuchfink** [comment]
In this latest commit, I have now added the field full_sseq which will
print the full subject sequence into the tabular format. It will increase
memory usage depending on your data and settings though.

**Comment by jjkoehorst** [comment]
Thanks it works like a charm! It is however not in the help documentation?

**Comment by bbuchfink** [comment]
I still need to do that, thanks.
