### ISSUE TITLE
Too many open files

### ISSUE THREAD

**Issue by dixonmd** [bbuchfink/diamond#210]
Building seed filter...  [0.018018s]
Searching alignments...  [0.096161s]
Deallocating buffers...  [5e-06s]
Opening temporary output file...  [6.9e-05s]
Computing alignments...  [0.32837s]
Deallocating reference...  [0.020985s]
Loading reference sequences...  [6.55594s]
Building reference histograms...  [0.592933s]
Allocating buffers...  [0.00039s]
Initializing temporary storage...  [0.009389s]
Processing query chunk 0, reference chunk 16, shape 0, index chunk 0.
Building reference index...  [0.397403s]
Building query index...  [0.018443s]
Building seed filter...  [0.015104s]
Searching alignments...  [0.226411s]
Deallocating buffers...  [7e-06s]
Opening temporary output file... Too many open files
 [0.000682s]
Error: Error opening temporary file /dev/shm/diamond-tmp-hvAjo2

Same error if we are not use '-t' option.

**Comment by bbuchfink** [comment]
Try using the option --bin 4

**Comment by dixonmd** [comment]
I didn't find this --bin option in the documentation. What does it actually do?

**Comment by cjfields** [comment]
It appears the manual needs updating?  However, using the last release (v0.9.22) and `diamond help`, under aligner options:

```
--bin                  number of query bins for seed search
```
