### ISSUE TITLE
Support PAF output format?

### ISSUE THREAD

**Issue by tseemann** [bbuchfink/diamond#213]
Ben

Would it be possible to support the PAF output (especially for blastx with query being a genome).

https://github.com/lh3/miniasm/blob/master/PAF.md

It's used by all Heng Li's minimap and related tools.  Basically a nicer version of SAM.

The `X:` tags at the end could be used for score, bitscore and other things.

Torsten

**Comment by bbuchfink** [comment]
Sure, I'll include it in the next release.

**Comment by bbuchfink** [comment]
The format is now included in the latest commit. I used the same
custom fields like in the SAM format, which are AS(bitscore), ZR
(rawscore) and ZE (evalue). Let me know if you need anything else.

**Comment by bbuchfink** [comment]
Sorry, forgot to mention that the option to use the format is -f 103.

**Comment by tseemann** [comment]
Great, thanks Ben!
