### ISSUE TITLE
how to get the taxonomy assignment

### ISSUE THREAD

**Issue by chloelulu** [bbuchfink/diamond#214]
Hi,

I downloaded the latest version of diamond,
`diamond makedb --in nr.gz --db nr`
Then I ran `blastx -d /home/luyang/ncbi_nr/nr -q ../all_genes.fna --more-sensitive -f 102 -b 10 -c 1 -o output`
'`Error: Output format requires taxonomy mapping information built into the database (use --taxonmap parameter for the makedb command). Taxonomy features are not supported for the DAA format.`'
Then I went back to the manual, "Using this format requires setting the --taxonmap and --taxonnodes parameters for makedb."
May I know how to deal with this problem? 
Thanks in advance.

**Comment by bbuchfink** [comment]
As the message says, if you want to use the taxonomy output format, you
need to use the --taxonmap and --taxonnodes options for diamond makedb.
Please see the manual under 3.2 for a description.

**Comment by chloelulu** [comment]
Thanks so much. I have been running diamond for 3 days, still no result. It seems that it is running fine, but too too slow. May I know is there anything wrong with me? Enclosed is the running procedure file. Thanks so much.
[nohup.txt](https://github.com/bbuchfink/diamond/files/2054374/nohup.txt)

**Comment by bbuchfink** [comment]
Can you tell me about the size and sequence type of your query file, and
also your hardware (like how many cores etc.)?

**Comment by chloelulu** [comment]
I am using NCBI-nr database. And my contigs file is 1.2Gb. I am using 64 cores, 512Gb memory server.

**Comment by chloelulu** [comment]
It has been finished just now. All used 4.15 days.

**Comment by bbuchfink** [comment]
Dear Chloe,

The runtimes you are seeing are nothing unusual. You are running diamond in
its most sensitive mode against the huge nr database, that's going to take
some time. To put that into perspective, running BLAST on your data against
the nr would take more than a decade on that server, so 4 days is not that
bad actually.

If you want to speed things up, I'd recommend using a clustered database
like the Uniref50, that would be a lot faster.
