### ISSUE TITLE
taxonomy mapping in DB

### ISSUE THREAD

**Issue by bernt-matthias** [bbuchfink/diamond#217]
I'm struggling with adding taxonomic information to the diamond db. I have created a small test set: 

[db.fas.txt](https://github.com/bbuchfink/diamond/files/2090090/db.fas.txt)
[nodes.dmp.txt](https://github.com/bbuchfink/diamond/files/2090091/nodes.dmp.txt)
[prot.accession2taxid.txt](https://github.com/bbuchfink/diamond/files/2090092/prot.accession2taxid.txt)

fasta contains 2 sequences, nodes dmp 3 nodes (2 species + root), mapping contains 1 line per protein. 

But `diamond makedb --in db.fasta --db db-wtax.dmnd --taxonmap prot.accession2taxid --taxonnodes nodes.dmp` reports: 

```
1 sequences mapped to taxonomy, 1 total mappings.
4 taxonomy nodes processed.
Processed 2 sequences, 568 letters.
```

The 1st two numbers seem not to fit. 

Using v0.9.21 installed via bioconda.

**Comment by bernt-matthias** [comment]
Another small thing: 

--taxonmap             protein accession to taxid mapping file
--taxonnodes           taxonomy nodes.dmp from NCBI

are listed in the alignment options in `diamond help`

**Comment by bbuchfink** [comment]
In your database it says AAD414167 and in your mapping file AAD44167.1.

Thanks the help needs to be fixed.

**Comment by bernt-matthias** [comment]
Sorry, but I can't find it: in db.fas it is also AAD44167.1 ? Do I miss something? Which columns of the taxonmap and which parts of the fasta header are actually used for the mapping? 

How about the `4 taxonomy nodes processed.`? I would have expected 3.

**Comment by bbuchfink** [comment]
Sorry you're right that must have accidentally happened on my end. I'll
have to look into it and get back to you.

Diamond uses the second and third column of the mapping file. The accession
is parsed from the fasta header depending on the format but in your case it
should be AAD44167.1 etc.

**Comment by bbuchfink** [comment]
I'm really sorry this took so long, not sure what happened there. The
explanation is quite simple, Diamond skips the first line in the
prot.accession2taxid.txt file because in the original file from NCBI, it
contains the headings.
