### ISSUE TITLE
rebuilding reference index

### ISSUE THREAD

**Issue by bernt-matthias** [bbuchfink/diamond#219]
Just a question for understanding the diamond output (and potential issue). 

It seems that diamond rebuilds the reference index when processing different shape and index chunks even when still the same reference chunk is processed: 

```
Processing query chunk 0, reference chunk 0, shape 0, index chunk 0.
Building reference index...  [7.50803s]
Building query index...  [0.412061s]
Building seed filter...  [0.325481s]
Searching alignments...  [239.082s]
Processing query chunk 0, reference chunk 0, shape 0, index chunk 1.
Building reference index...  [8.54041s]
Building query index...  [0.468256s]
Building seed filter...  [0.325808s]
Searching alignments...  [224.683s]
Processing query chunk 0, reference chunk 0, shape 0, index chunk 2.
Building reference index...  [8.80243s]
Building query index...  [0.483447s]
Building seed filter...  [0.324863s]
Searching alignments...  [218.949s]
....
```

Given that with ~8s the time for rebuilding is well hidden behind the time for the alignment this is no big deal, but maybe a small optimization seems possible. 

Also: is it possible to output the total number of chunks, eg: 

`Processing query chunk 0/10, reference chunk 0/5, shape 0/3, index chunk 2/2`.

just for estimating how long I need to wait for the results.

**Comment by bbuchfink** [comment]
The reference index is different for each shape. An index always depends on
the seed shape so it's not possible to optimize anything there.

Displaying the totals is a good idea. It is not known for the query chunk
though because the query file is only being read once. It would be somewhat
less efficient if one needs to determine that number first and read the
query file twice.

**Comment by bernt-matthias** [comment]
OK. Cool got it. For the query the number of already processed sequences might be a good alternative, because the user nows the total number.
