### ISSUE TITLE
Options --matrix blosum45 and lower give "invalid scoring parameters"

### ISSUE THREAD

**Issue by tseemann** [bbuchfink/diamond#22]
Works with >= blosum62, but not < blosum62:

```
% diamond blastp -q NC_017032.faa -d sprot.dmnd -v -a out -k 1 -c 1 --matrix blosum45
diamond v0.7.9.58
Error: Invalid scoring parameters
```

**Comment by bbuchfink** [comment]
Ok, I will have to look into this.

**Comment by bbuchfink** [comment]
It's because these matrices do not support the default 11/1 gap penalties. You need to set different penalties, see the readme for supported values.
