### ISSUE TITLE
filter the subjects in the diamond database

### ISSUE THREAD

**Issue by thierryjanssens** [bbuchfink/diamond#223]
Hi,

in the blast+ suite of ncbi there is the possibility to use -negative_gilists in order to limit the search to subject that fall outside this list..
I was not able to find a comparable option in diamond or I might have overlooked this.

Kind regards,

Thierry

**Comment by bbuchfink** [comment]
Hi, there is no such option in diamond at the moment. It might be possible
to add this in a future version.
