### ISSUE TITLE
AGPL License?

### ISSUE THREAD

**Issue by bovee** [bbuchfink/diamond#226]
I'd like to play around with DIAMOND, but I'm somewhat confused by the licensing. I generally try to avoid AGPL software in pipelines because I'm not sure (and I don't think there's any legal precedent) how that license interacts with the other software in the pipeline or the pipeline orchestration itself. For example, it looks like HUMAnN2 is MIT licensed and has a dependency on DIAMOND (but I didn't think that was permitted via the AGPL license). How does that work?

If it's possible, could DIAMOND be GPL or BSD dual-licensed?

**Comment by bbuchfink** [comment]
Diamond being GPL licensed means you can't take the code and link it
into a MIT licensed binary, but if Diamond acts as a stand-alone
executable within a pipeline I don't think that's in violation of the
GPL. It probably happens on a regular basis and I have never heard of
anyone being sued. But if you need some more reassurance I can give
you written permission to use it for your pipeline.

I'll think about BSD licensing but it's probably not going to happen
tomorrow. GPL is not very different to AGPL and would not address the
issue you are concerned about I think.

**Comment by bovee** [comment]
Thanks for the fast response!

My understanding is that AGPL requires software that interacts "over a network" (which is vague enough to include use in a Docker container or similar) to have an AGPL license while GPL requires only software that's compiled/linked to have a GPL license (and the two are only compatible because they have [explicit legal clauses](https://en.wikipedia.org/wiki/GNU_Affero_General_Public_License#Compatibility_with_the_GPL) linking them). I think switching to a GPL license would address my concerns .

I'm just exploring a couple ideas for protein alignment and several people have recommended Diamond so I don't have a definite pipeline in mind, but thank you for the reassurance and I'll let you know if I need some kind of written permission. And thanks for considering an alternate license!
