### ISSUE TITLE
"update database" option

### ISSUE THREAD

**Issue by geronimp** [bbuchfink/diamond#227]
Hi there, 

This is sort of a feature request. It seems that with each update DIAMOND databases created with any previous version are not compatible with the current version.  

As a way around, I have been exporting sequences from the old database using `getseq` in the compatible (old) DIAMOND version and recreate a new database with those sequences with the new (current) version of DIAMOND. 

I'm not sure, but would it be easy to just include a "updatedb" option for each new release of DIAMOND? It would save a bit of time, and stop the need to keep previous versions of DIAMOND to update databases (if you dont have the sequences still available).

**Comment by wwood** [comment]
+1

**Comment by bbuchfink** [comment]
Hi Joel,

this is not supposed to happen, databases are supposed to be compatible
with later versions unless the format actually changes, which only happens
rarely. There must be a pretty serious bug if this happens on your system.
Please give me the exact pair of version numbers and I'll try to reproduce
this problem.

**Comment by Ferrisx4** [comment]
+1
Our case: a large number of databases generated with version 0.9.9 and testing new functionality in the latest version (0.9.24). Fails with error "Error: Database was built with a different version of Diamond and is incompatible." 

I'm guessing one of the rare format changes occurred between 0.9.9 and 0.9.24.

In our case, we still have the original sequences so we can regenerate new database files, but an update option might be useful, as @geronimp mentioned.

**Comment by bbuchfink** [comment]
There was a format change between these versions, I try to reduce those to a minimum but sometimes it is necessary. You can convert databases with a pipe like this:

`/old/diamond getseq -d dbfile | /new/diamond makedb -d new_db`

I should maybe mention it in the manual.

**Comment by Ferrisx4** [comment]
OK, and good to know.

Thank you
