### ISSUE TITLE
Using diamond to find protein locations in chromosomes

### ISSUE THREAD

**Issue by chklopp** [bbuchfink/diamond#229]
Hi,

I have aligned chromosomes (several tens of megabases) on a protein database with diamond (v0.9.9.110).
The alignment works but the reported hsps are limited compared to what I expect.
With standard parameters I get a few hundreds hsps for each chromosome this is probably due to the standard limit number of hsps produced for each query.
If I set -k to 100000 I get many more (tens of thousands) but still for each chromosome I get only one hsp per protein (the longuest matching exon?). I would like to retrieve all the exon positions.

What parameters should I use to get all (many) hsps of a chromosome on a protein?

**Comment by bbuchfink** [comment]
Hi,
you can try to increase the --max-hsps parameter. This controls the number
of HSPs to be reported within a single query/subject pair.

**Comment by chklopp** [comment]
Works fine.
Thank you.
