### ISSUE TITLE
compilation problem

### ISSUE THREAD

**Issue by RNAer** [bbuchfink/diamond#23]
We had [this problem](https://travis-ci.org/biocore/conda-recipes/jobs/90202664#L374) on Ubuntu 12.04.5 LTS when trying to compile it on Travis CI. Does anyone have any clue on the cause of failure? We also tried the `cmake` approach, which also [failed](https://travis-ci.org/biocore/conda-recipes/builds/90441490) on both Ubuntu and OSX...

**Comment by bbuchfink** [comment]
I haven't seen those compiler errors before. I will have to try using the same software versions.

**Comment by Jorge-C** [comment]
The problem is that diamond does not compile with gcc 4.6, which is the default available in travis-ci/ubuntu 12.04. From my testing, it does compile with gcc 4.7/4.8. Getting gcc 4.6 supported would be super nice :)

**Comment by bbuchfink** [comment]
Version 0.8.1 now compiles with GCC 4.6.
