### ISSUE TITLE
--max-target-seqs: Issue or not with DIAMOND?

### ISSUE THREAD

**Issue by MaryoHg** [bbuchfink/diamond#232]
Hi, Diamond developers,

I recently read this paper [10.1093/bioinformatics/bty833](https://academic.oup.com/bioinformatics/advance-article-abstract/doi/10.1093/bioinformatics/bty833/5106166?redirectedFrom=fulltext) and found that the BLAST option stated on the open issue was being misinterpreted.

>The invocation using the parameter `--max-target-seqs 1` simply returns the first good hit found in the database, not the best hit as one would assume. [...] Even ordering the database in a different way would cause BLAST to return a different "top hit" when setting [the same] parameter to 1. (Source: Shah et al. (2018).

Is this anything related to DIAMOND use?

Thanks.

MaryoHg

**Comment by bbuchfink** [comment]
Hi,

if you use --max-target-seqs 1 in Diamond, it is designed to return the
best hit, not just the first hit that meets the evalue treshold.

Like for every fast aligner, there are heuristics involved however and
there's no 100% guarantee that it will be the best hit.

Best regards,
Benjamin

**Comment by MaryoHg** [comment]
Hi @bbuchfink.

Thank you very much.
I appreciate your explanation.


Regards,

Maryo.

**Comment by ml3958** [comment]
Hi I know this issue is closed already. But I found my question fit into this question.

How does Diamond decide if two hits has same e-value (assuming e-value is the criteria to determine which hit is better)? Is it random, or there's second factor considered?

Thanks!

**Comment by bbuchfink** [comment]
The hits are first ranked by alignment score. For two hits with identical
score the one that comes first in the database will be reported first.

**Comment by slvrshot** [comment]
@bbuchfink I have the latest version of diamond and it tells me that --max_target_seqs is invalid. What could be the reason for this?

**Comment by bbuchfink** [comment]
The option is --max-target-seqs not --max_target_seqs.

**Comment by emilyhyde** [comment]
Hello! Really interesting thread here, I landed here because I had the exact same question as @MaryoHg. I do have a follow up question now though, where it is stated in the response "if you use --max-target-seqs 1 in Diamond, it is designed to return the best hit, not just the first hit that meets the evalue treshold." is this true for if we do not specify max target seqs and just run on default, will the top hit be reported still instead of just the first hit to meet the evalue threshold?

**Comment by bbuchfink** [comment]
>  is this true for if we do not specify max target seqs and just run on default, will the top hit be reported still instead of just the first hit to meet the evalue threshold?

The default setting is designed to return the best 25 hits (there is no guarantee to this effect of course due to heuristics).
