### ISSUE TITLE
getseq using accession rather than a number

### ISSUE THREAD

**Issue by IsmailM** [bbuchfink/diamond#234]
I would like to extract the FASTA sequence of all the BLAST HSPs in the Diamond BLAST XML output. Is there an easy way to do this?

It seems that I cannot search the Diamond database using an accession number but rather need to provide `diamond getseq` with a number (which is not provided in the Diamond BLAST XML output).

**Comment by bbuchfink** [comment]
You are right, getseq requires the number of the sequence.

Maybe seqtk is the right tool for you: https://github.com/lh3/seqtk
You can give it a list of accessions and it will extract these sequences
from a fasta file.

**Comment by IsmailM** [comment]
Thanks. Nonetheless, it will be quite useful to add this feature into `diamond getseq` - i.e. something similar to the functionality of `blastdbcmd -entry_batch ... -outfmt '%f' ...`
