### ISSUE TITLE
Concatenating DAA files

### ISSUE THREAD

**Issue by andrewjmc** [bbuchfink/diamond#235]
Hello,

Is it possible to concatenate DAA files? I have some fastq.gz files in batches, and rather than decompressing then concatenating them as input, I wondered about concatenating the DAA files afterwards.

Thanks for your help,

Andrew

**Comment by bbuchfink** [comment]
Hi,

it's not possible to concatenate DAA files. Some people have requested
this feature and I could implement it next week probably, right now is
very busy unfortunately.

Best regards,
Benjamin

**Comment by andrewjmc** [comment]
Hi Benjamin,

Thanks for your quick response!

Andrew
