### ISSUE TITLE
Invalid parameter count for optoin --top

### ISSUE THREAD

**Issue by laurafisch9** [bbuchfink/diamond#236]
I am trying to run a blast with Oxford Nanopore reads using the suggested settings for long error prone reads

The following command

`setsid diamond blastx -d ~/refseq84.dmnd -q nanofilt_q_8.fasta -o long_read_blast_settings.m8 -f 6 -b 70 -c 1 --threads 10 --no-self-hits --range-culling --top 10 –F 15 > q8diamond_m8.log`

 returns an error:

`Invalid parameter count for option '--top'`

**Comment by bbuchfink** [comment]
This command line should be fine. I just tested it and didn't get an error.
Please double check that this is your exact command line or if there are
maybe any missing spaces or anything.

**Comment by laurafisch9** [comment]
For some reason it is still not working. 
I tried running the command without --top 10,
the next error was:
`Invalid parameter count for option '--range-culling'`

After taking out the range-culling option the next error was 
`Invalid parameter count for option '--no-self-hits'`
...so on a so forth 
There is an issue with the option --top 10 and everything below that.

The following command will work for me:

`diamond blastx -d ~/programs/databases/refseq84.dmnd -q Synechococcus_sp.WH_8016_reads_q_8.fastq -o test2.m8 -f 6 -k 1 -b 70  -c 1 --threads 10 > test2.log`

When I try to put in the specific long read options is when the issue arises. 
Could the issue be specific to the server I'm using?

**Comment by bbuchfink** [comment]
When I copy and paste your command line the dash in front of F 15 is not a
normal dash, but some sort of special character. I think this is causing
this.

**Comment by laurafisch9** [comment]
I tried copying and pasting directly from the diamond manual for all of the long read options and got the following error. 
`Invalid parameter count for option '--frameshift'`

Then I tried typing out the command options with appropriate dashes and got the error:
`nvalid parameter count for option '--tmpdir'

But tmpdir isn't even in the command I was running:

`setsid diamond blastx -d ~/programs/databases/refseq84.dmnd -q reads.fastq -o long_read_blast_settings.m8 -f 6 -b 70 -c 1 --threads 10 --no-self-hits -F 15 --range-culling -top 10 > long_read_setting_test.log`

**Comment by bbuchfink** [comment]
Sorry, the message is a bit misleading. The problem is now that you need
two dashes for --top.

**Comment by laurafisch9** [comment]
Ok. I got it working. Thanks for your help
