### ISSUE TITLE
Add an outfmt 6 option for the query quality string

### ISSUE THREAD

**Issue by terrycojones** [bbuchfink/diamond#237]
Hi Benjamin

I'm not sure if this would be possible, but it would be nice to be able to specify `qquality` in `--outfmt 6` to have the FASTQ quality string (or, say, `-` if the input is FASTA and there is no quality info) printed. The reason is that if you run DIAMOND and get some query matches of interest and want to make a FASTQ file holding the matched reads you have to do a second round of processing where you read all the original FASTQ looking for the matching query ids. If the query quality was available in the output one could recreate the FASTQ on the fly (by also using `--qtitle`). Thanks!

**Comment by bbuchfink** [comment]
Hi Terry,

it would certainly be possible to do that. But for your purpose it would
probably be better to have an option to simply write the aligned queries to
a file, correct?

**Comment by terrycojones** [comment]
Yes, that would be good too. It might be more flexible to allow the quality strings to be in the output though as one could then pipe the output into a program that did something like examine the `btop` string and extract just a part of the query and quality.  Either would be workable, though I think it's more flexible to allow the subsequent processing to be done on the fly so it can begin before the run is fully complete and doesn't require the storage of both the full regular output and the fully matching reads.  Thanks!  BTW, we used DIAMOND in 2 papers and of course cited you. See https://www.nature.com/articles/s41586-018-0097-z and http://www.pnas.org/content/early/2018/06/26/1804921115

**Comment by bbuchfink** [comment]
Alright, I should be able to get this done within the week. Thanks for the
citations, you can never have too many of those.

**Comment by terrycojones** [comment]
Oops, we didn't use DIAMOND in the 2nd paper above - false alarm.

BTW, it's probably simpler for regular people if they don't need to write a program or awk script or whatever to produce FASTQ from the output, so I'd completely understand if that's the way you'd rather do it. Or you could do both :-)  Thanks again in any case.  Also, I had a look at the manual the other day - it's been a while - and the improvements look really good. Little things like being able to toggle whether output is produced for a read with no alignments are useful (simplify downstream processing) and the taxonomy stuff should be good. I did some work the other day to make it easier for people to build a local NCBI taxonomy db - see https://github.com/acorg/ncbi-taxonomy-database

**Comment by terrycojones** [comment]
Thanks!

**Comment by bbuchfink** [comment]
Hi Terry,

sorry it took a bit longer, but the feature is now contained in the latest
commit. You can use the qqual field to output the quality values.

**Comment by terrycojones** [comment]
Great!  Thanks a lot, this will really help simplify & speed up some processing.
