### ISSUE TITLE
blastp - incomplete alignment

### ISSUE THREAD

**Issue by zorino** [bbuchfink/diamond#238]
I'm trying to align a relatively short peptide (78 aa).

And the alignment cuts short at 39 aa.

Input query and subject present in the diamond database.

```
>pae975-scaffold_2005
MKKTVTLALLLAASLGLAACDKKEEDKAAAPAAPATETQPSAPATPPAEPSAPAPSSDTP
ATPQTPAPTPEQPQQNQQ*
```
```
>gnl|PHR|PAE981_2029
MKKTVTLALLLAASLGLAACDKKEEDKAAAPAAPATETQPSAPATPPAEPSAPAPSSDTP
ATPQTPAPTPEQPQQNQQ*
```

Alignment : 

```
Query= pae975-scaffold_2005

>gnl|PHR|PAE981_2029

Length=79
 Score = 55.5 bits (132),  Expect = 3.0e-09
 Identities = 29/29 (100%), Positives = 29/29 (100%), Gaps = 0/29 (0%)

Query   1  MKKTVTLALLLAASLGLAACDKKEEDKAA 29
           MKKTVTLALLLAASLGLAACDKKEEDKAA
Sbjct   1  MKKTVTLALLLAASLGLAACDKKEEDKAA 29
```

**Comment by bbuchfink** [comment]
This is due to low complexity masking. You can view the masking using
diamond getseq on your database:

>gnl|PHR|PAE981_2029
MKKTVTLALLLAASLGLAACDKKEEDKAAapaapatetqpsapatppaepsapapssdtpatpqtpaptpeqpqqnqq*

You can turn this off using --masking 0 although it is generally not
recommended to do that.

**Comment by zorino** [comment]
Thank you @bbuchfink
