### ISSUE TITLE
pthread missing from CMakelists.txt

### ISSUE THREAD

**Issue by patricksnape** [bbuchfink/diamond#24]
In `CMakeLists.txt`, [L21](https://github.com/bbuchfink/diamond/blob/master/CMakeLists.txt#L21)):

    - target_link_libraries(diamond blast_core ${Boost_LIBRARIES})
    + target_link_libraries(diamond blast_core ${Boost_LIBRARIES} -lpthread)

Linking to `pthread` seems to be missing. I'm not sure if this is exactly what you want to add because I imagine this may have ramifications on Windows. However, I also don't know if diamond works on Windows so just let me know if you want a quick patch for that fix?

**Comment by Jorge-C** [comment]
I ended up patching our conda build of diamond with [the following](https://github.com/Jorge-C/conda-recipes/blob/630e337233afca67ce6373e968c78ca370742828/recipes/Diamond/cmake_patch), which is supposed to be more portable:
```
--- CMakeLists_orig.txt	2015-11-12 17:48:32.078758260 -0700
+++ CMakeLists.txt	2015-11-12 17:48:14.434581321 -0700
@@ -1,6 +1,8 @@
 cmake_minimum_required (VERSION 2.6)
 project (DIAMOND)
 
+
+FIND_PACKAGE(Threads REQUIRED)
 find_package(Boost
   1.53.0 REQUIRED
   COMPONENTS program_options timer iostreams thread
@@ -18,6 +20,6 @@
   src/basic/options.cpp
   src/util/tinythread.cpp)
 
-target_link_libraries(diamond blast_core ${Boost_LIBRARIES})
+target_link_libraries(diamond blast_core ${Boost_LIBRARIES} ${CMAKE_THREAD_LIBS_INIT})
 
 install(TARGETS diamond DESTINATION bin)
```

**Comment by bbuchfink** [comment]
Thanks for the suggestions, I'm going to look into this.

**Comment by yesimon** [comment]
:+1: I made a mistake in my original `CMakeLists.txt` and this resolves it.
