### ISSUE TITLE
Filtering using diamond view?

### ISSUE THREAD

**Issue by cjfields** [bbuchfink/diamond#240]
I'm trying to filter a very large DAA file from metagenomic data using `diamond view` and am running into an odd issue when trying `-f 100`; this works with other formats.  Does `diamond view` allow you to recreate another filtered DAA file?

```
$ diamond view -k 5 --threads $SLURM_NPROCS -f 100 --daa G759_ATCCACTG-AGGTGCGT_L003.combined_kneaddata.fastq.gz.daa -o test.daa
diamond v0.9.22.123 | by Benjamin Buchfink <buchfink@gmail.com>
Licensed under the GNU AGPL <https://www.gnu.org/licenses/agpl.txt>
Check http://github.com/bbuchfink/diamond for updates.

#CPU threads: 4
Loading subject IDs...  [1.66917s]
Scoring parameters: (Matrix=custom Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 154979882
DB sequences used = 15356691
DB letters = 56767515206
Error: Invalid output format. Allowed values: 0,5,6,100,101,102
```

**Comment by bbuchfink** [comment]
Diamond view does not support creating another DAA file at this time,
although this would certainly be useful and should be implemented.

**Comment by cjfields** [comment]
> Diamond view does not support creating another DAA file at this time, although this would certainly be useful and should be implemented.

Definite +1.  The runs took about 24hrs per sample but generated huge files w/o compression, some are about 200GB (we used `--top 5`).  Hindsight and all 😄 

At the moment they collectively take up ~8TB; we'd like to filter it down and compress at some point.

**Comment by bbuchfink** [comment]
Ok, I'll try to get this implemented but I'm not sure how long exactly
it's going to take.

**Comment by cjfields** [comment]
Awesome, thanks @bbuchfink !  We'll give it a try; we have a pretty large range of files to test, including meganized ones.

**Comment by cjfields** [comment]
@bbuchfink I should have replied on this, but the filtering works wonderfully, thanks for adding this!
