### ISSUE TITLE
Diamond_blast_to_taxid.py

### ISSUE THREAD

**Issue by pm1z** [bbuchfink/diamond#241]
Hi,

I am trying to perform a Diamond_blast_to_taxid.py using a custom database. However, I keep getting the same error. Do you have any suggestion what I a might be doing wrong.

Thanks very much

$ python /Diamond_blast_to_taxid.py -i cytb_out.tab -t gi_taxid_prot.dmp -c categories.dmp -n names.dmp -d cytb_gi.dmnd -o outfile_cytb.tab

INFO: sys.version_info(major=2, minor=7, micro=6, releaselevel='final', serial=0)
INFO: Command-line: /Diamond_blast_to_taxid.py -i cytb_out.tab -t gi_taxid_prot.dmp -c categories.dmp -n names.dmp -d cytb_gi.dmnd -o outfile_cytb.tab
INFO: Starting testing: Fri Nov  2 09:57:16 2018
loading NCBI data files
Traceback (most recent call last):
  File "./Diamond_blast_to_taxid.py", line 1007, in <module>
    logger)
  File "./Diamond_blast_to_taxid.py", line 469, in parse_diamond_tab
    acc_to_tax_id = assign_taxon_to_dic(acc_taxid_prot)
  File "./Diamond_blast_to_taxid.py", line 284, in assign_taxon_to_dic
    acc, acc_version, tax_id, GI = line.rstrip("\n").split()
ValueError: need more than 2 values to unpack

**Comment by bbuchfink** [comment]
Hi,
sorry but I don't know this script and it was not developed by me. You
should ask the author for support. Alternatively you could use the
taxonomic classification provided by Diamond (see the manual for details).

**Comment by xushaoyi** [comment]
> 
> 
> Hi,
> 
> I am trying to perform a Diamond_blast_to_taxid.py using a custom database. However, I keep getting the same error. Do you have any suggestion what I a might be doing wrong.
> 
> Thanks very much
> 
> $ python /Diamond_blast_to_taxid.py -i cytb_out.tab -t gi_taxid_prot.dmp -c categories.dmp -n names.dmp -d cytb_gi.dmnd -o outfile_cytb.tab
> 
> INFO: sys.version_info(major=2, minor=7, micro=6, releaselevel='final', serial=0)
> INFO: Command-line: /Diamond_blast_to_taxid.py -i cytb_out.tab -t gi_taxid_prot.dmp -c categories.dmp -n names.dmp -d cytb_gi.dmnd -o outfile_cytb.tab
> INFO: Starting testing: Fri Nov 2 09:57:16 2018
> loading NCBI data files
> Traceback (most recent call last):
> File "./Diamond_blast_to_taxid.py", line 1007, in
> logger)
> File "./Diamond_blast_to_taxid.py", line 469, in parse_diamond_tab
> acc_to_tax_id = assign_taxon_to_dic(acc_taxid_prot)
> File "./Diamond_blast_to_taxid.py", line 284, in assign_taxon_to_dic
> acc, acc_version, tax_id, GI = line.rstrip("\n").split()
> ValueError: need more than 2 values to unpack

hi, have you solved the problem? I met the same error log.

**Comment by bbuchfink** [comment]
As I said before, the said `Diamond_blast_to_taxid.py` script was not developed by me and I can't provide support for it.
