### ISSUE TITLE
unexpected blastx alignment

### ISSUE THREAD

**Issue by bochaozhang** [bbuchfink/diamond#242]
Hi,

I was trying to blastx to align nucleotide sequences to some protein references. But I found some weird issue with the alignment length. Here are two sequences for example:

The query sequences are

>
>seq1
GGTAAGTCTGTGTGTTGGTCTTGAAGATCTGTGTGTTCCGGTCCCAATACTCCGGCCCCTCCTGCTCTATCCATGG
>seq2
CTCGGTAAGTCTGTGTGTTGGTCTTGAAGATCTGTGTGTTCCGGTCCCAATACTCCGGCCCCTCCTGCTCTATCC

The protein reference file is
>
>ref1
SHSMRYFYTAMSRPGRGEPRFIAVGYVDDTQFVRFDSDAASPRTEPRAPWIEQEGPEYWDRNTQIFKTNTQTYRESLRNLRGYYNQSEAG
>ref2
SHSMRYFYTAMSRPGRGEPRFIAVGYVDDTQFVRFDSDAASPRTEPRAPWIEQEGPEYWDRNTQIFKTNTQTYRENLRIALRYYNQSEAG

The two ref protein sequences are the same at positions 1 to 76, and the two query sequences are aligned to positions 49-74 and 51-75 so the alignments with both refs should be the same. But Diamond will always give a shorter alignment with ref2, as shown below
>seq1	0	ref1	49	255	25M	*	0	0	PWIEQEGPEYWDRNTQIFKTNTQTY	*	AS:i:60	NM:i:0	ZL:i:90
	ZR:i:146	ZE:f:2.2e-15	ZI:i:100	ZF:i:-1	ZS:i:76	MD:Z:25
seq1	0	ref2	49	255	19M	*	0	0	PWIEQEGPEYWDRNTQIFK	*	AS:i:48	NM:i:0	ZL:i:90	ZR:i:11
5	ZE:f:8.5e-12	ZI:i:100	ZF:i:-1	ZS:i:76	MD:Z:19
seq2	0	ref1	51	255	24M	*	0	0	IEQEGPEYWDRNTQIFKTNTQTYR	*	AS:i:55	NM:i:0	ZL:i:90
	ZR:i:133	ZE:f:6.7e-14	ZI:i:100	ZF:i:-3	ZS:i:73	MD:Z:24
seq2	0	ref2	51	255	17M	*	0	0	IEQEGPEYWDRNTQIFK	*	AS:i:41	NM:i:0	ZL:i:90	ZR:i:97
	ZE:f:1.0e-09	ZI:i:100	ZF:i:-3	ZS:i:73	MD:Z:17

It seems if I shorten the ref protein sequences by a couple of bases this issue goes away
>ref1-full
SHSMRYFYTAMSRPGRGEPRFIAVGYVDDTQFVRFDSDAASPRTEPRAPWIEQEGPEYWDRNTQIFKTNTQTYRESLRNLRGYYNQSEAG
>ref2-full
SHSMRYFYTAMSRPGRGEPRFIAVGYVDDTQFVRFDSDAASPRTEPRAPWIEQEGPEYWDRNTQIFKTNTQTYRENLRIALRYYNQSEAG
>ref1-short
SHSMRYFYTAMSRPGRGEPRFIAVGYVDDTQFVRFDSDAASPRTEPRAPWIEQEGPEYWDRNTQIFKTNTQTYRESLRNLRG
>ref2-short
SHSMRYFYTAMSRPGRGEPRFIAVGYVDDTQFVRFDSDAASPRTEPRAPWIEQEGPEYWDRNTQIFKTNTQTYRENLRIALR

>seq1	0	ref1-full	49	255	25M	*	0	0	PWIEQEGPEYWDRNTQIFKTNTQTY	*	AS:i:60	NM:i:0ZL:i:90	ZR:i:146	ZE:f:4.1e-15	ZI:i:100	ZF:i:-1	ZS:i:76	MD:Z:25
seq1	0	ref1-short	49	255	25M	*	0	0	PWIEQEGPEYWDRNTQIFKTNTQTY	*	AS:i:60	NM:i:0ZL:i:82	ZR:i:146	ZE:f:4.1e-15	ZI:i:100	ZF:i:-1	ZS:i:76	MD:Z:25
seq1	0	ref2-short	49	255	25M	*	0	0	PWIEQEGPEYWDRNTQIFKTNTQTY	*	AS:i:53	NM:i:3ZL:i:82	ZR:i:127	ZE:f:6.6e-13	ZI:i:88	ZF:i:-1	ZS:i:76	MD:Z:20XXX2
seq1	0	ref2-full	49	255	19M	*	0	0	PWIEQEGPEYWDRNTQIFK	*	AS:i:48	NM:i:0	ZL:i:90
	ZR:i:115	ZE:f:1.6e-11	ZI:i:100	ZF:i:-1	ZS:i:76	MD:Z:19
seq2	0	ref1-full	51	255	24M	*	0	0	IEQEGPEYWDRNTQIFKTNTQTYR	*	AS:i:55	NM:i:0ZL:i:90	ZR:i:133	ZE:f:1.3e-13	ZI:i:100	ZF:i:-3	ZS:i:73	MD:Z:24
seq2	0	ref1-short	51	255	24M	*	0	0	IEQEGPEYWDRNTQIFKTNTQTYR	*	AS:i:55	NM:i:0ZL:i:82	ZR:i:133	ZE:f:1.3e-13	ZI:i:100	ZF:i:-3	ZS:i:73	MD:Z:24
seq2	0	ref2-short	51	255	24M	*	0	0	IEQEGPEYWDRNTQIFKTNTQTYR	*	AS:i:48	NM:i:3ZL:i:82	ZR:i:114	ZE:f:2.0e-11	ZI:i:87	ZF:i:-3	ZS:i:73	MD:Z:18XXX3
seq2	0	ref2-full	51	255	17M	*	0	0	IEQEGPEYWDRNTQIFK	*	AS:i:41	NM:i:0	ZL:i:90
	ZR:i:97	ZE:f:1.9e-09	ZI:i:100	ZF:i:-3	ZS:i:73	MD:Z:17

Can you fix this please? Thank you very much.

**Comment by bbuchfink** [comment]
Hi,

this is not a bug but caused by the low complexity masking. You can view
the masking using diamond getseq on your database. It's not easy to see
here but subtle differences in sequence composition can cause segments to
be masked or not. You can turn off the masking using --masking 0, but it is
generally not recommended to do that.

**Comment by bochaozhang** [comment]
Thanks for the quick reply! This is very interesting! I thought the masking was only applied to the query sequences. I did try to switch the order of refs in my database but it produced the same result so that possibility just slipped my mind.
