### ISSUE TITLE
Taxonomy names

### ISSUE THREAD

**Issue by davidvilanova** [bbuchfink/diamond#244]
Hi,
I have build nr database with both `--taxonmap` and -`-taxonnodes` options. I went through the manual but it seems outdated (diamond v0.9.22 May 11, 2018) and i have version v0.9.22.123.

In the manual it says option `-f 102` will return taxonomy assignments but this option is not available in latest version. 

How could i get the taxa names in the blast output ??

Thanks

**Comment by bbuchfink** [comment]
Hi,

taxon names in the Blast output are not supported, only taxon ids. To use
it, set the staxids output field, for example:
diamond -f 6 qseqid sseqid bitscore staxids

The -f 102 format should also work. What kind of error message are you
getting?

**Comment by davidvilanova** [comment]
Thanks for the update. 
Also it  would be great as a suggestion to add the taxonomy name in the makedb process. Actually by adding the file `names.dmp` which contains the link between species id and its name. 

The `-f 102` seems  specific to diamond-sse2.
```
diamond-sse2 blastp --threads 6 -f 102 --query proteins.fa -o out --log --verbose --db newnr 
diamond v0.9.6.107 | by Benjamin Buchfink <buchfink@gmail.com>
Licensed under the GNU AGPL <https://www.gnu.org/licenses/agpl.txt>
Check http://github.com/bbuchfink/diamond for updates.

#CPU threads: 6
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
#Target sequences to report alignments for: 25
Error: Invalid output format. Allowed values: 5,6,100,101

```

**Comment by bbuchfink** [comment]
As you can see in the output, this is version 0.9.6, which does not yet
support this format. You can check the version by using diamond --version.

I'll look into implementing the taxon names.

**Comment by davidvilanova** [comment]
OK great !!!! thanks

**Comment by pvanheus** [comment]
@davidvilanova I've written a small Python tool that adds taxonomy names - [here](https://github.com/pvanheus/diamond_add_taxonomy) on github, coming to bioconda soon.

**Comment by davidvilanova** [comment]
Oh, great thanks !!!!
