### ISSUE TITLE
Insufficient arguments. Use diamond -h for help.

### ISSUE THREAD

**Issue by guanglifeng** [bbuchfink/diamond#245]
I am using diamond/0.7.12 through a server based on my University. After "diamond makedb --in nr.faa -d nr", the nr.dmnd was created. Then I did "diamond blastx -d nr -q reads.fna -o matches.m8". I got an error "Insufficient arguments. Use diamond -h for help". Could anyone advise me what the problems might be? Thanks.

**Comment by bbuchfink** [comment]
Try -a matches.m8. The version you are using is very old though, I
recommend upgrading to the latest version.
