### ISSUE TITLE
DIAMOND 0.8 vs 0.9 results

### ISSUE THREAD

**Issue by agolicz** [bbuchfink/diamond#247]
Hello,
I have been using DIAMOND for a while now.
I was re-running some of the result I got with DIAMOND 0.8.25 using DIAMOND 0.9.22.123 and the number of hits for ~100,000 sequences changed form 27,000 to 6,000. This is quite a dramatic change. I have noticed that the low e-value hits remained but a lot of relatively high e-values (1e-5 - 1e-15 range) were lost. This is quite a dramatic change. Any chance you could help shed light on this?

Commands:
/home/agolicz/apps/diamond.0.8.25/diamond blastx --threads 4 --query PDBU01.1.fsa_nt --db UP000005640_9606.dmnd --more-sensitive --out diamond.tab --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore stitle --evalue 0.00001 --max-target-seqs 10 --verbose

 /home/agolicz/apps/diamond.v0.9.22.123/diamond blastx --threads 4 --query PDBU01.1.fsa_nt --db UP000005640_9606.dmnd --more-sensitive --out diamond.tab --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore stitle --evalue 0.00001 --max-target-seqs 10 --verbose

Agnieszka

**Comment by bbuchfink** [comment]
Hi Agnieszka,

my first guess would be the low complexity masking. Could you try to run
v0.9.22 using the option --masking 0?

Best regards,

Benjamin
