### ISSUE TITLE
Query sequence and quality strings can differ in length in --outfmt 6 output

### ISSUE THREAD

**Issue by terrycojones** [bbuchfink/diamond#251]
Hi again Benjamin

I think there's sometimes a problem with sequence and quality strings differing in length. I have an input FASTQ sequence that looks like this:

```
@M04295:95:000000000-BPV62:1:1101:14577:1356 1:N:0:NTGAAGCT+ATAGAGGC
GTGGTGATAGGGGACATCCTTGTCTTGTACCAGATTTGAGAGAAAAAGACTTCAGTTTTTCCCCATTTAGAATTATGTTAGCTGTTGGATTGTCATAGATGGCTCTTATCAGGTTGAGGTAGAGGCCCTCTATTCCAATTTTCTGTAGGACTTTAACATGAATGAGTGTTGG
+
FGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
```

The sequence and quality are both 172 long. But running with `--outfmt 6 qseq qqual` I get an output with a sequence that has been hard-clipped (one base at the start, 15 at the end) to length 156, but the quality string is still length 172:

```
TGGTGATAGGGGACATCCTTGTCTTGTACCAGATTTGAGAGAAAAAGACTTCAGTTTTTCCCCATTTAGAATTATGTTAGCTGTTGGATTGTCATAGATGGCTCTTATCAGGTTGAGGTAGAGGCCCTCTATTCCAATTTTCTGTAGGACTTTAAC
FGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGGG
```

I guess the cause (and maybe the fix?) is fairly simple - that in the recent addition of `qqual` (#237) the quality string isn't also clipped when the sequence is.

I've still not made time to add some notes to the docs....   will try to get there soon.

Thanks!

**Comment by bbuchfink** [comment]
Hi Terry,

it can't hurt to have both options available, so I'll add another field
like qqual_clipped for the clipped version.

**Comment by bbuchfink** [comment]
I have changed the qqual field to be clipped in the latest commit. I also
added the field full_qqual for the unclipped version (as there is already a
field named full_sseq).

**Comment by terrycojones** [comment]
Hi. I just took a look at the new code - looks like it could also use a `full_qseq` :-)  Sorry if I'm being a pain. These changes are really good, because they mean people (i.e., ME) can stream and filter the format 6 output line-by-line without needing to write all output to disk or to do post facto processing where you have to go look the read sequence up (there may be tens or hundreds of millions of them, or more).

**Comment by terrycojones** [comment]
Great, thank you.  Can this issue be closed?

**Comment by bbuchfink** [comment]
Sure, looks like it's been addressed.

**Comment by terrycojones** [comment]
Closing....

**Comment by terrycojones** [comment]
Hi Benjamin

I'm re-opening this at I think it's still not right (running `v0.9.24.125`). The following was found by @TaliVeith.

Attached is a zip file with one subject FASTA file and a FASTQ file with one read query. If you make a DIAMOND database (`diamond makedb -d pegi --in subject.fasta`) and then run a blastx (`diamond blastx -d pegi -q read.fastq -f 6 full_qseq qseq qqual`) the lengths of the 3 things printed are 301, 294, and 299.

I think the user would expect that the lengths of `qseq` and `qqual` would be the same, and that the lengths of `full_qseq` and `full_qqual` (which doesn't exist, but could) would also match each other.

In the DIAMOND help output it says "qseq means Aligned part of query sequence" as compared to "qqual means Query quality values". If they're both supposed to be the aligned part, they should probably both say so.

BTW, part of the output from `diamond --help` goes to `stdout` and part to `stderr`. Maybe it could all go to `stdout`, unless you wanted it split that way? I don't think programs that print help messages should ever print to `stderr` because there's a non-significant overlap between people who need help and people who won't know how to control the output (i.e., in this case, if you run `diamond help | less` you won't see the "diamond v0.9.24.125 | by Benjamin Buchfink <buchfink@gmail.com>" output because it goes to `stderr`).

[files.zip](https://github.com/bbuchfink/diamond/files/2936915/files.zip)

**Comment by bbuchfink** [comment]
Hi Terry,

thanks for pointing out the issue, there was a bug that caused the `qqual` field to always run to the end of the query. I fixed it in the latest commit.

I fixed the command line help. `full_qqual` does exist actually, I added it to the help.

I changed the startup message to go to `stdout` for the help command.

**Comment by terrycojones** [comment]
Great, thanks!  I pulled down the latest, rebuilt, and checked the lengths are as expected, tried `full_qqual` & also `--help`. Sorry for the slowness - I was traveling. Closing.
