### ISSUE TITLE
compiling 0.9.23 under mac

### ISSUE THREAD

**Issue by gaboentropy** [bbuchfink/diamond#252]
The previous version compiles all right, no matter if I use clang or gcc. Now, the new version wants a linux-specific library:

/usr/local/diamond-0.9.23/src/util/system/system.cpp:13:10: fatal error: 
      'linux/limits.h' file not found
#include <linux/limits.h>
         ^~~~~~~~~~~~~~~~
1 error generated.
make[2]: *** [CMakeFiles/diamond.dir/src/util/system/system.cpp.o] Error 1
make[1]: *** [CMakeFiles/diamond.dir/all] Error 2
make: *** [all] Error 2

:(

**Comment by bbuchfink** [comment]
Sorry, I just pushed a commit that should fix this.

**Comment by gaboentropy** [comment]
Thanks you. It compiles all right now. It works with clang (default mac compiler), was well as with g++-8 (as part of gcc installed using homebrew).

**Comment by slvrshot** [comment]
Hey I'm new to this. How exactly were you able to get this work on mac? I'm trying to run ARGsOAP on a macOS and I'm having some difficulty.

**Comment by bbuchfink** [comment]
You should be able to compile it from source like this:

git clone https://github.com/bbuchfink/diamond.git
cd diamond
mkdir bin
cd bin
cmake ..
make

**Comment by gaboentropy** [comment]
Yep. That works all right in my macs.
