### ISSUE TITLE
Does DIAMOND keep a cache of read info (including read length)?

### ISSUE THREAD

**Issue by terrycojones** [bbuchfink/diamond#254]
Hi Benjamin

I spent most of the day debugging a difficult problem that took some time to find. Although it's not DIAMOND's fault I am guessing that DIAMOND could help avoid the issue. I was putting paired reads together with flash (https://ccb.jhu.edu/software/FLASH/) and then making a single file of the reads - the combined ones and the non-combined ones. To prevent read ids being identical in that single file, I was appending `/1` and `/2` (which seems to be fairly standard) to the first part of the read ids in the non-combined files.

Downstream, my code that processes DIAMOND format 6 output failed an assertion test. I've been using that code for a couple of years now, and it's well tested, so I was quite surprised.

Many hours later I found the problem. I was running `bwa` after doing the `flash` step above, and (presumably) because `/` is not legal in the query name in field 1 of a SAM file (see section 1.4 of https://samtools.github.io/hts-specs/SAMv1.pdf), `bwa` was silently stripping the `/1` and `/2` from the query names. As a result, the output SAM had lines with duplicate read ids. And the two reads had different lengths (one was 300, one was 301).

When I looked closely at the DIAMOND error I was seeing, the index of the end of the read match was 301, but the read was only length 300. I figured something must have gone wrong somewhere in my processing. Eventually I found the id stripping described above. Once I changed the `/1` to `-1` etc., the problem went away. I had thought that maybe I was caching read lengths, though I didn't think so.

Anyway, I'm now guessing that DIAMOND is keeping a cache of query info, keyed by sequence id. Is that right?  If so, a check could be added to cache inserts to first test if the id is present, and an error raised if so.  While it's not strictly an error to have a duplicate sequence id in the FASTQ input, it's probably a sign of a fatal condition (and if DIAMOND is in fact keeping a cache then it will result in incorrect output if the two (or more) sequences with the same id have different lengths, though that may be very hard to detect & diagnose, as in my case).

Sorry for such a long message... hope I'm on the right track.  I probably could have just gone and checked the code in the time it took to write it :-)

**Comment by bbuchfink** [comment]
Hi Terry,

duplicate sequence IDs will not cause any issues in Diamond, as internally
sequences are always addressed by a number (defined by the order in the
input file), not by their ID. Checking for duplicate IDs would require some
additional time and memory so I don't want to do it by default, but it
would be no problem to add this as an optional feature.

Best regards,

Benjamin

**Comment by terrycojones** [comment]
Hmmmm.... ok, I guess it must be something I am doing. I will probably write a tiny check just to make sure I believe you :-)  Then I'll have to think some more. Thanks!!

**Comment by terrycojones** [comment]
OK, I checked & you're right (as you knew). I was obviously confused and wishfully guessing the issue was somewhere else :-) Thanks again.
