### ISSUE TITLE
Range convention in hit versus query in XML output

### ISSUE THREAD

**Issue by daveuu** [bbuchfink/diamond#257]
I suspect this is just about conventions and not a problem with the software but . . . 

The HSP below is 11 amino acids long, the `Hsp_query-from` to `Hsp_query-to` is 8-19 which would return a string slice of length 11, but `Hsp_hit-from` to `Hsp_hit-to` is 40-50 which which would return a string slice of length 10.

So it looks like `Hsp_hit-from` to `Hsp_hit-to` is an inclusive range i.e., 40th and 50th amino acids should be included. Can I confirm the HSP positions in query and hit are reported in different ways: former a slice, latter an inclusive range? Thanks.

```
    <Hsp>
      <Hsp_num>1</Hsp_num>
      <Hsp_bit-score>34.4</Hsp_bit-score>
      <Hsp_score>71</Hsp_score>
      <Hsp_evalue>2.2e-03</Hsp_evalue>
      <Hsp_query-from>8</Hsp_query-from>
      <Hsp_query-to>19</Hsp_query-to>
      <Hsp_hit-from>40</Hsp_hit-from>
      <Hsp_hit-to>50</Hsp_hit-to>
      <Hsp_query-frame>0</Hsp_query-frame>
      <Hsp_hit-frame>0</Hsp_hit-frame>
      <Hsp_identity>11</Hsp_identity>
      <Hsp_positive>11</Hsp_positive>
      <Hsp_gaps>0</Hsp_gaps>
      <Hsp_align-len>11</Hsp_align-len>
         <Hsp_qseq>GFWGDRVDSQP</Hsp_qseq>
         <Hsp_hseq>GFWGDRVDSQP</Hsp_hseq>
      <Hsp_midline>GFWGDRVDSQP</Hsp_midline>
    </Hsp>
```

**Comment by bbuchfink** [comment]
I can confirm the different semantics but I'm not sure if I did that
deliberately or if it's a bug. Need to check how BLAST does that.

**Comment by daveuu** [comment]
It looks like this was fixed in v0.9.31?

Maybe here: 14eae9db24c7add7ce0d8a75ffcd9061dd10cc1c ?

**Comment by bbuchfink** [comment]
Yes, it was. Sorry for forgetting about this.

**Comment by daveuu** [comment]
No problem, thanks for the fix. I did an upgrade and a test failed at my end :-)
