### ISSUE TITLE
Suggestions for package building

### ISSUE THREAD

**Issue by Jehops** [bbuchfink/diamond#258]
Hello Benjamin,

If I am following the logic in `CMakeLists.txt` correctly, `-march=native` will be added by default to `CMAKE_CXX_FLAGS` if the compiler supports it. I guess this is not helpful when building a binary package that will be run on a different machine.  Do you have a suggestion for the value of `CMAKE_BUILD_MARCH` when building binary packages? I also plan to add a message to inform users that optimal performance will be obtained when building directly on the target machine.

Regards,

Joseph

**Comment by bbuchfink** [comment]
Hi Joseph,

I think -mtune=generic should build a binary that works on all systems
while still providing some optimization.

Best regards,

Benjamin

**Comment by Jehops** [comment]
Done.

https://svnweb.freebsd.org/ports?view=revision&revision=488819

Thank you.
