### ISSUE TITLE
Error: Invalid output format. Allowed values: tab,sam,xml,daa

### ISSUE THREAD

**Issue by slvrshot** [bbuchfink/diamond#259]
I attempt to execute this command:

`ls *.fa | parallel --gnu "diamond blastx -q {} -d BacMet2/Volumes/easystore/BacMet2/BacMet2.dmnd --max-target-seqs 1 --threads 4 --outfmt 6 --evalue 0.0001 -o {/.}.diamond.tab" `

And it returns:
```
#CPU threads: 4
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
#Target sequences to report alignments for: 1
Error: Invalid output format. Allowed values: tab,sam,xml,daa
```

I can't understand how I could be naming the output format incorrectly. Could you please help me?

**Comment by bbuchfink** [comment]
--outfmt 6 should not cause an error, but it is the default so you can also
just leave it out.
