### ISSUE TITLE
compiling under gcc(msys2)

### ISSUE THREAD

**Issue by smalltalkman** [bbuchfink/diamond#260]
Compiling under gcc(msys2) require following patchs:
-----

diff --git a/src/util/system.h b/src/util/system.h
index 7201cca..e2dcd74 100644
--- a/src/util/system.h
+++ b/src/util/system.h
@@ -21,7 +21,7 @@ along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
 #include <stdexcept>
 
-#ifdef _MSC_VER
+#ifdef _WIN32
 
 #define PACKED_ATTRIBUTE
 
@@ -31,7 +31,7 @@ along with this program.  If not, see <http://www.gnu.org/licenses/>.
 
 #endif
 
-#ifndef _MSC_VER
+#ifndef _WIN32
 
 #include <sys/resource.h>
 
diff --git a/src/util/system/system.cpp b/src/util/system/system.cpp
index b002cd1..95cc90a 100644
--- a/src/util/system/system.cpp
+++ b/src/util/system/system.cpp
@@ -5,7 +5,7 @@
 
 using namespace std;
 
-#ifdef _MSC_VER
+#ifdef _WIN32
 #include <windows.h>
 #else
 #include <unistd.h>
@@ -14,7 +14,7 @@ using namespace std;
 
 string executable_path() {
 	char buf[4096];
-#ifdef _MSC_VER
+#ifdef _WIN32
 	if (GetModuleFileNameA(NULL, buf, sizeof(buf)) == 0)
 		throw runtime_error("Error executing GetModuleFileNameA.");
 	return string(buf);
@@ -26,7 +26,7 @@ string executable_path() {
 }
 
 bool exists(const std::string &file_name) {
-#ifdef _MSC_VER
+#ifdef _WIN32
 	return GetFileAttributes(file_name.c_str()) != INVALID_FILE_ATTRIBUTES;
 #else
 	struct stat buffer;

-----

diff --git a/src/util/simd.cpp b/src/util/simd.cpp
index 7ce5b5e..02bc73d 100644
--- a/src/util/simd.cpp
+++ b/src/util/simd.cpp
@@ -20,6 +20,7 @@ along with this program.  If not, see <http://www.gnu.org/licenses/>.
 #include "log_stream.h"
 
 #ifdef _WIN32
+#include <intrin.h>
 #define cpuid(info,x)    __cpuidex(info,x,0)
 #else
 inline void cpuid(int CPUInfo[4], int InfoType) {

-----

diff --git a/src/dp/needleman_wunsch.cpp b/src/dp/needleman_wunsch.cpp
index af3da04..f66fd0e 100644
--- a/src/dp/needleman_wunsch.cpp
+++ b/src/dp/needleman_wunsch.cpp
@@ -171,6 +171,8 @@ const Fixed_score_buffer<_score>& needleman_wunsch(sequence query, sequence subj
 	return mtx.score_buffer();
 }
 
+template Fixed_score_buffer<int> const& needleman_wunsch<int, Local>(sequence, sequence, int&, Local const&, int const&);
+
 int needleman_wunsch(sequence query, sequence subject, int qbegin, int qend, int sbegin, int send, unsigned node, unsigned edge, Diag_graph &diags, bool log)
 {
 	const sequence q = query.subseq(qbegin, qend), s = subject.subseq(sbegin, send);

**Comment by bbuchfink** [comment]
Ok, I'll look into fixing this.

**Comment by smalltalkman** [comment]
Thanks! I found commit `Fixed template instantiation.` which correct template instantiation. 
But, I still need to change `_MSC_VER` to `_WIN32` in file `src/util/system.h` and file `src/util/system/system.cpp`, and add `#include <intrin.h>` in file `src/util/simd.cpp`. I think these changes will not cause vc++ to fail to compile.
