### ISSUE TITLE
Blastx version in diamond

### ISSUE THREAD

**Issue by juulluu21** [bbuchfink/diamond#261]
I am using diamond 0.9.24. I couldn't find the version of blastx installed with diamond. There was an issue with blast which got resolved in their Dec release (by NCBI). Does diamond 0.9.24 has that version of blast (BLAST+ 2.8.1: December 13, 2018)?

https://www.ncbi.nlm.nih.gov/books/NBK131777/

Thanks!

**Comment by bbuchfink** [comment]
Diamond is a separate software from BLAST, it does not come with any
version of BLAST. You need to install/update that tool separately.

**Comment by juulluu21** [comment]
Thanks!
