### ISSUE TITLE
Asterisks in sequence files

### ISSUE THREAD

**Issue by bakerkc** [bbuchfink/diamond#262]
Many peptide sequence files have optional terminal asterisks (*) on the sequence fields to indicate a stop codon. This is optional.
Diamond seems to consider these asterisks as actual residues for the purposes of statistical calculation. I'd argue that this is wrong, and they should be ignored (a parameter for this maybe?).

**Comment by bbuchfink** [comment]
This scoring of stop codons was taken from BLAST. In BLAST scoring
matrices, stop codons have a score of 1 against each other. But I will
include an option to set a negative score so they will be clipped from the
ends of alignments.

**Comment by bakerkc** [comment]
Brilliant, thank you.

**Comment by bbuchfink** [comment]
Sorry it took a bit longer. In the latest commit you can set the option `--stop-match-score 0` to have the stop codons clipped.

**Comment by bakerkc** [comment]
Brilliant! Thanks. 8-)
