### ISSUE TITLE
example data files 

### ISSUE THREAD

**Issue by tombradford** [bbuchfink/diamond#266]
I am a system administrator looking at installing diamond on our HPC cluster for a user who has requested the application. I do not have a bioinformatics background so I was wondering if you could provide an example data and query files (i.e. input and query) so we can test the makedb and blastx sub-commands?

**Comment by bbuchfink** [comment]
As input for makedb:
ftp://ftp.uniprot.org/pub/databases/uniprot/current_release/knowledgebase/complete/uniprot_sprot.fasta.gz

As input for blastx: ftp://ftp.ncbi.nlm.nih.gov/genomes/all/GCF/000/005/845/GCF_000005845.2_ASM584v2/GCF_000005845.2_ASM584v2_cds_from_genomic.fna.gz

**Comment by tombradford** [comment]
that's brilliant, thank you very much for the rapid response!
