### ISSUE TITLE
hello. syntaxerror.... help me

### ISSUE THREAD

**Issue by byeollee** [bbuchfink/diamond#269]
when i download diamond,

File "/usr/local/bin/diamond", line 113
    print "Diamond version %s" % (get_diamond_version())
                             ^
SyntaxError: invalid syntax

this error come...

thank you

**Comment by bbuchfink** [comment]
This looks like an error with the setup of Diamond on your system. Please try to download Diamond again and run it locally as described in the manual.

**Comment by byeollee** [comment]
other problem came out..

diamond v0.9.24.125 | by Benjamin Buchfink <buchfink@gmail.com>
Licensed under the GNU GPL <https://www.gnu.org/licenses/gpl.txt>
Check http://github.com/bbuchfink/diamond for updates.

#CPU threads: 1
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
Database file: nr.faa
Opening the database file... No such file or directory
 [0.000125s]
Error: Error opening file nr.faa

what is that mean??

thank you for your information.

**Comment by bbuchfink** [comment]
You need to download a database file to use with Diamond. There are various databases available like NCBI NR, UniProt, UniRef, SwissProt etc. You can find how to download them at the respective websites.

**Comment by terrycojones** [comment]
@byeollee Your original problem is because `/usr/local/bin/diamond` contains python 2 (you can tell because the `print` statement has no parentheses), but on the command line you are running it with python 3 (which gives a syntax error).
