### ISSUE TITLE
command line redirected input

### ISSUE THREAD

**Issue by g1o** [bbuchfink/diamond#27]
I tried to use diamond on some fastq files, but I was not wishing to use a temporary fasta file, so I redirected the input:
diamond blastx -db nr -a out.daa -q <(zcat READS.fastq.gz | fastq_to_fasta) 
Error: Invalid input file format

Is there no way for the user to avoid making a temporary fasta file?

**Comment by bbuchfink** [comment]
Diamond can directly read a gziped fastq file, no need to convert.
