### ISSUE TITLE
Build Database with many codon Stop

### ISSUE THREAD

**Issue by Nilad** [bbuchfink/diamond#270]
Hi,

First, thank for this amazing tool ;)

My Context: I want to search in many genome assembly (nucleic .fasta) a sequence.
So i translate theses genomes in protein format (with biopython Seq.translate) in one file (.faa) to make the database of diamond.

Problem: But the protein file contains many codon stop ("*"). Diamond can deal with this kind of file ? I make few blastx with a query sequence without results... (In Blastx online, i get results)

**Comment by bbuchfink** [comment]
One reason could be the ORF heuristic used by Diamond. Try the parameter `-l1` and see if that changes anything. Stop codons should not be a problem in itself unless there's too many of them, as Diamond does not consider seeds containing a stop codon. Can you show me an example of an alignment found by Blast?

**Comment by Nilad** [comment]
I try your tips with `-l1` without success...

### Query sequence

```
>seq1
TTGACTGATGATTATTTTTTTTATTATGGCCTAAAGCAGTTAACTGGACTACCTCTGTTTCATATTACATATGAAGGAGTAGTTAATAAATCAATAGCAATTAAGCACAAAAGAAACATAAGAGTATTGGTTGACAGCAGGATTTTTTATTCAGGGAAATGGGGAGGGTACAAAATGTTAAGGGGATCATTAAATATGATAAGCCAATGGATGTGGCTTGACGTTTCGGGGGGGGGGCGGTTTTATCCTAAAGGGTGTGATTATGACATCTATGTTAACATGCAAGGAAATGTAAAAAATAATATTGAAAAACTATATTTTGCATTCTTAAAGAAAAATGTTAGCCGAATTGTAAACCATTATCCACGGCTAACAAAAAAGGAACAAGCAGTGCTGCAATGCCTACTGAAAAATGGGGGCATTAATGAAATAAAAAGTCAACTAAAAATTGAAGAAAAAACGCTATCATGCTACCAAAGCAAAATAACAAGAAAATTTGGCTGCAAAAGGTACATAAGGTTTATGTATCTTTACAGCCTTAATAAAGAAATGGTTGATGAAAGATGGCTCATGCCAAGTATTTAG
```

### Blastx Result (ncbi - online)

```
 Score = 318 bits (815),  Expect = 1e-101, Method: Compositional matrix adjust.
 Identities = 194/194 (100%), Positives = 194/194 (100%), Gaps = 0/194 (0%)
 Frame = -2

Query  584    *ILGMshlsstisllrl*RYINLMYLLQPNFLVILLW*HDSVfssifs*lfisLMPPFFS  405
              *ILGMSHLSSTISLLRL*RYINLMYLLQPNFLVILLW*HDSVFSSIFS*LFISLMPPFFS
Sbjct  31588  *ILGMSHLSSTISLLRL*RYINLMYLLQPNFLVILLW*HDSVFSSIFS*LFISLMPPFFS  31647

Query  404    RHCSTACSFFVSRG*WFTIRLTFFFKNAKYSFSILFFTFPCMLT*MS*SHPLG*NRPPPE  225
              RHCSTACSFFVSRG*WFTIRLTFFFKNAKYSFSILFFTFPCMLT*MS*SHPLG*NRPPPE
Sbjct  31648  RHCSTACSFFVSRG*WFTIRLTFFFKNAKYSFSILFFTFPCMLT*MS*SHPLG*NRPPPE  31707

Query  224    TSSHIHWLIIFNDPLNILYPPHFPE*KILLSTNTLMFLLCLIAIDLLTTPSYVI*NRGSP  45
              TSSHIHWLIIFNDPLNILYPPHFPE*KILLSTNTLMFLLCLIAIDLLTTPSYVI*NRGSP
Sbjct  31708  TSSHIHWLIIFNDPLNILYPPHFPE*KILLSTNTLMFLLCLIAIDLLTTPSYVI*NRGSP  31767

Query  44     VNCFRP**KK*SSV  3
              VNCFRP**KK*SSV
Sbjct  31768  VNCFRP**KK*SSV  31781
```

# Area in the .faa of the subject sequence of the blastx result (31600 - 31800 aa)


```
31600 
 SLLRL*RYINLMYLLQPNFLVILLW*HDSVFSSIFS*LFISLMPPFFSRHCSTACSFFVSRG*WFTIRLTFFFKNAKYSFSILFFTFPCMLT*MS*SHPLG*NRPPPETSSHIHWLIIFNDPLNILYPPHFPE*KILLSTNTLMFLLCLIAIDLLTTPSYVI*NRGSPVNCFRP**KK*SSVNTMFTSLLHIK*IYFSI     31800

```

#### Diamond Version
 `diamond v0.9.24.125`


#### Command Diamond Blastx


`diamond blastx --more-sensitive -k 0 -p 12 -d my_assembly_diamond.dmnd -q test-diamond/query.fas --id 70 --subject-cover 70 -f 6 qseqid qframe sseqid slen qstart qend sstart send length pident nident ppos positive mismatch gapopen gaps qseq sseq full_sseq -o result_diamond --masking no -l1`

If you want more details, tell me.

**Comment by bbuchfink** [comment]
I tried it with your data and get the alignment when using `-l1`. Try to remove the `--subject-cover` option as it will filter this alignment if your subject sequence is that long.

**Comment by Nilad** [comment]
@bbuchfink Perfect, it's work without the option `--subject-cover` **and** with the `-l1` option.
