### ISSUE TITLE
DIAMOND seems to sometimes miss exact 201nt/67aa match

### ISSUE THREAD

**Issue by terrycojones** [bbuchfink/diamond#272]
Hi Benjamin

I'm still playing with reversing DIAMOND output to produce SAM (it's quite tricky if you want to map it back to forward/reversed and disjoint regions of an original nucleotide sequence). Anyway, I was playing on the command line and was surprised when DIAMOND did not find an exact 201nt/67aa sequence that I set up so I could test some options.  I investigated and the match is found when the DIAMOND database is very small but not with a bigger database. I guess I'm just not understanding something about the DIAMOND internals or options, but it doesn't seem intuitive/right that the default behavior is not to find such a match.

I wrote the digging up and put it online at http://antigenic-cartography.org/terry/diamond-non-matching-issue.html

Terry

**Comment by bbuchfink** [comment]
Hi Terry,

This is due to the repeat masking. If you look at the alignment, large parts are masked and the bitscore is only 40. That is enough for it to be reported if you use the small database, but for the large database it will be above the e-value cutoff.

I have worked on making the masking more conservative which will be released soon, but I'm not sure if it will affect this particular case. If it's a problem you can turn off the masking with `--masking 0` but that will also cause many false positive hits.

```
>acc|GENBANK|YP_009137150.1|GENBANK|NC_001798.2|neurovirulence protein ICP34.5 [Human herp
esvirus 2 strain HG52, complete genome]
Length=261

 Score = 40.0 bits (92),  Expect = 6.1e-08
 Identities = 66/66 (100%), Positives = 66/66 (100%), Gaps = 0/66 (0%)

Query   1  SRRRGPXXXXXXXXPRPXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXGTAVESAPAAS
           SRRRGPXXXXXXXXPRPXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXGTAVESAPAAS
Sbjct   2  SRRRGPXXXXXXXXPRPXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXGTAVESAPAAS

Query  61  SLLRRW
           SLLRRW
Sbjct  62  SLLRRW
```

**Comment by terrycojones** [comment]
Hi @bbuchfink - thanks. I am still digesting this news :-)  I'll close the issue.

**Comment by bbuchfink** [comment]
Sure. It's an issue that regularly leads to confusion among the users, and I'm asking myself how to better deal with it. You can read the tantan paper if you want to know the details: https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3045581/

**Comment by terrycojones** [comment]
I'll have a look at the paper, thanks. One thing that occurred to me was to weight the contribution of matching nucleotides in such a region by its complexity. E.g., if you could compress it down to almost nothing (using compression size as an example measure of complexity - there are many, you could also easily compute entropy per aa), you'd set the weight to almost nothing, and so on.

**Comment by terrycojones** [comment]
Also, I realized (belatedly, as usual) that I should read the manual more closely! :-)
