### ISSUE TITLE
diamond doesn't produce a non-zero return code in case of error 

### ISSUE THREAD

**Issue by davidemms** [bbuchfink/diamond#273]
Hi Benjamin

Thanks for all the great work on DIAMOND! I've just noticed an example where an error is detected by diamond but its return code is still 0 instead of non-zero. This might happen with other error cases too, I haven't looked. 

I provoked the error with:
`diamond blastp -d diamondDBSpecies0 -q Species1.fa -o out.txt`
where `diamondDBSpecies0` is any database and `Species1.fa` is a fasta file whose first line is empty.

The output was:
```
diamond v0.9.24.125 | by Benjamin Buchfink <buchfink@gmail.com>
Licensed under the GNU GPL <https://www.gnu.org/licenses/gpl.txt>
Check http://github.com/bbuchfink/diamond for updates.

#CPU threads: 8
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
Temporary directory: 
Opening the database...  [2.9e-05s]
#Target sequences to report alignments for: 25
Opening the input file...  [5.5e-05s]
Error: Error detecting input file format. First line seems to be blank.
```
 So the error was detected, but the error code was zero:
```
$ echo $#
0
```

Thanks
David

**Comment by bbuchfink** [comment]
Hi David,

use `echo $?` to get the exit code. `$#` is the number of command line arguments.

Best regards,

Benjamin

**Comment by davidemms** [comment]
Thanks, I'm an idiot :)

David
