### ISSUE TITLE
makedb memory problem 

### ISSUE THREAD

**Issue by davidvilanova** [bbuchfink/diamond#275]
Hi,
On linux cluster slurm env i´m trying to index a subset of NR containing only bacterial, archeal and fungi.

I get a memory problem. 

With slurm:
```
#SBATCH --mem=100G
#SBATCH --cpus-per-task=12
diamond  makedb --threads 12   --in nr.baf.fa.gz --db nrbactarchfung --taxonmap prot.accession2taxid.gz --taxonnodes nodes.dmp 


```
The size of the input protein file (nr.baf.fa.gz)  is 20Gb
I don´t really have a memory or cpu limitation on the cluster but just trying to understand what memory usage would be required to index such file.

 Can you suggest memory settings and/or cpus settings?

I´m using diamond v0.9.22.123

**Comment by davidvilanova** [comment]
Ok got it `"-b1"` with 12 cpus should use 96 GB...

**Comment by bbuchfink** [comment]
The memory usage with `-b1` should only be about 6 GB in total. This applies for the alignment run, makedb does not really have any substantial memory requirements so I'm quite puzzled that this runs out of memory for you. Could you try again with the latest version, omit the taxonomy parameters and use `/usr/bin/time -v diamond ...` to get stats on the memory usage?

**Comment by davidvilanova** [comment]
Ok i´ll try and let you know

**Comment by davidvilanova** [comment]
In a previous run where i used 90GB mem and 12 cpus with default B values of 2.

See attached log from slurm


![image](https://user-images.githubusercontent.com/11404840/56026657-e8531980-5d14-11e9-90e7-720f00242a3a.png)

**Comment by davidvilanova** [comment]
Hi,
Here is the log from the command line suggested. After 9min and 50seg it as killed by Diamond

SLURM mem and cpu requirements
```

#SBATCH --cpus-per-task=12
#SBATCH --mem=110G

```

Command line without taxonomy
`/usr/bin/time -v diamond  makedb  --threads 12   --in nr.baf.fa.gz --db nrbactarchfung 
`

Output:
```
diamond v0.9.24.125 | by Benjamin Buchfink <buchfink@gmail.com>
Licensed under the GNU GPL <https://www.gnu.org/licenses/gpl.txt>
Check http://github.com/bbuchfink/diamond for updates.


#CPU threads: 12
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
Database file: nr.baf.fa.gz
Opening the database file...  [0.023129s]
Loading sequences...  [587.474s]
Failed to allocate sufficient memory. Please refer to the manual for instructions on memory usage.
Command exited with non-zero status 1
        Command being timed: "diamond makedb --threads 12 --in nr.baf.fa.gz --db nrbactarchfung"
        User time (seconds): 471.05
        System time (seconds): 117.37
        Percent of CPU this job got: 99%
        Elapsed (wall clock) time (h:mm:ss or m:ss): 9:50.24
        Average shared text size (kbytes): 0
        Average unshared data size (kbytes): 0
        Average stack size (kbytes): 0
        Average total size (kbytes): 0
        Maximum resident set size (kbytes): 77632068
        Average resident set size (kbytes): 0
        Major (requiring I/O) page faults: 0
        Minor (reclaiming a frame) page faults: 6763786
        Voluntary context switches: 694
        Involuntary context switches: 1333
        Swaps: 0
        File system inputs: 0
        File system outputs: 0
        Socket messages sent: 0
        Socket messages received: 0
        Signals delivered: 0
        Page size (bytes): 4096
        Exit status: 1
```

**Comment by bbuchfink** [comment]
I have tried makedb for the nr database and it ran with 6.5 GB peak memory usage. If your database is a subset of nr or if there's nothing unusual in there that could be causing this problem, I have no idea about this error at this time. I will have to think about how this can be addressed. But you could maybe try to run this on another system. It should be possible to even run it on a desktop using `-b1`.

**Comment by davidvilanova** [comment]
Found the problem, the fasta file header was wrongly formatted. Had many ">" in one header. I guess i should have controlled for that. Thanks for looking into it.

**Comment by jolespin** [comment]
TIL that you can run `diamond makedb` with multiple threads...
