### ISSUE TITLE
LCA bitscore filter 

### ISSUE THREAD

**Issue by davidvilanova** [bbuchfink/diamond#276]
Hi,
I would like to suggest a bitscore filter for computing LCA used in diamond

Acutally LCA relies on top sequences (down to 10% compared to higher bitscore). WOuld it be possible to use instead a bitscore cutoff?

For e.g --bitscore 50 would compute LCA with all sequences above 50.

**Comment by bbuchfink** [comment]
I just pushed a new commit for this. You can now use `--min-score 50` and it should be used for the LCA computation instead of `--top`. (It is untested though)
