### ISSUE TITLE
Functional equivalence in blastp mode (blast2go)

### ISSUE THREAD

**Issue by abretaud** [bbuchfink/diamond#277]
Hi,
I'm trying to use some results from diamond to run blast2go (using b2gpipe).
In a way, it works well because blast2go returns some results. *But* it returns significantly less GO terms than using NCBI blastp output.
After some debugging I found out that the reason for these fewer go terms is that, contrary to NCBI blastp, diamond is not showing "functional equivalence" in its xml output.

An example of Hit produced by NCBI blastp (only kept the important chunks):

```
<Hit>
  <Hit_num>1</Hit_num>
  <Hit_len>284</Hit_len>
  <Hit_hsps>
    <Hsp>
      <Hsp_num>1</Hsp_num>
      <Hsp_bit-score>412.535</Hsp_bit-score>
      <Hsp_score>1059</Hsp_score>
      <Hsp_evalue>1.31999e-142</Hsp_evalue>
      <Hsp_query-from>25</Hsp_query-from>
      <Hsp_query-to>306</Hsp_query-to>
      <Hsp_hit-from>3</Hsp_hit-from>
      <Hsp_hit-to>284</Hsp_hit-to>
      <Hsp_query-frame>0</Hsp_query-frame>
      <Hsp_hit-frame>0</Hsp_hit-frame>
      <Hsp_identity>187</Hsp_identity>
      <Hsp_positive>232</Hsp_positive>
      <Hsp_gaps>0</Hsp_gaps>
      <Hsp_align-len>282</Hsp_align-len>
      <Hsp_midline>YS+  + + YETL I+VPK+F+Y V+LNRP KLNA +  MW EF  CF+EL   P+CR I+LSGAGK+F AG+D+QD +  GQ++ EH DIARK+K+ +  IKNYQ++FTA+EKC KPVIAA+H ACIG G+DMISAADIRYC+ DAWFQIKEVD+GMAADVG LQR  KIIGSDSL+REL YTARKF A EA++ GFV+R+F+N+E LL  S  +AE IA KSPVAIQG+KLS++YSRDH+VQEGLDHIA  N++ML SEDFLNA ++ ATKG+ P+FSKL</Hsp_midline>
    </Hsp>
  </Hit_hsps>
</Hit>
```

And the same returned by Diamond:

```
<Hit>
  <Hit_num>1</Hit_num>
  <Hit_len>284</Hit_len>
  <Hit_hsps>
    <Hsp>
      <Hsp_num>1</Hsp_num>
      <Hsp_bit-score>397.9</Hsp_bit-score>
      <Hsp_score>1021</Hsp_score>
      <Hsp_evalue>3.5e-107</Hsp_evalue>
      <Hsp_query-from>25</Hsp_query-from>
      <Hsp_query-to>307</Hsp_query-to>
      <Hsp_hit-from>3</Hsp_hit-from>
      <Hsp_hit-to>284</Hsp_hit-to>
      <Hsp_query-frame>0</Hsp_query-frame>
      <Hsp_hit-frame>0</Hsp_hit-frame>
      <Hsp_identity>187</Hsp_identity>
      <Hsp_positive>187</Hsp_positive>
      <Hsp_gaps>0</Hsp_gaps>
      <Hsp_align-len>282</Hsp_align-len>
      <Hsp_midline>YS       YETL I VPK F Y V LNRP KLNA    MW EF  CF EL   P CR I LSGAGK F AG D QD    GQ   EH DIARK K     IKNYQ  FTA EKC KPVIAA H ACIG G DMISAADIRYC  DAWFQIKEVD GMAADVG LQR  KIIGSDSL REL YTARKF A EA   GFV R F N E LL  S   AE IA KSPVAIQG KLS  YSRDH VQEGLDHIA  N  ML SEDFLNA    ATKG  P FSKL</Hsp_midline>
    </Hsp>
  </Hit_hsps>
</Hit>
```

The aligment is very very similar, but there are no "+" in the diamond output, and the `Hsp_positive` value is 45 lower = the number of "+".
The critical part is that blast2go must use a kind of threshold on the `Hsp_positive` and `Hsp_align-len` values/ratio to assign (or not) go terms to proteins.

I tred setting `Hsp_positive` to 232, or setting `Hsp_align-len` to 232 and it was enough to let blast2go return a go term association.

So, do you think it would be possible to modify diamond output to add this information? (if it's computed by Diamond of course...)

**Comment by bbuchfink** [comment]
Sorry but I could not reproduce this issue of missing positives in the Diamond output. Are you using the latest version? (check with `diamond --version`)

**Comment by abretaud** [comment]
I've just checked with the latest version 0.9.24 and I get the same result (ie no `+` sign in the xml or blast output)
Here are the commands I launch:

```
diamond blastp --query "input.fa" --salltitles --more-sensitive --db /db/nr/NR_2019-4-4/diamond/nr.dmnd --evalue 1e-8 --max-target-seqs 20 --threads 10 --outfmt 100 --out "output.daa"

diamond view --daa "output.daa" --outfmt 5 --out "output.xml"
```

**Comment by r1corre** [comment]
Hi anthony have you tried to produce directly the xml file in the first command line with --outfmt 5  instead of producing a DAA file format and convert it to xml ?

**Comment by abretaud** [comment]
Good catch @r1corre, writing directly in xml format gives the proper result. So I guess there is a bug in `diamond view`, what do you think @bbuchfink?

**Comment by bbuchfink** [comment]
Sorry for not replying earlier. It's a confirmed bug in `diamond view`. I will provide a fix shortly.
