### ISSUE TITLE
Error reading temporary file. 

### ISSUE THREAD

**Issue by MikaUhr** [bbuchfink/diamond#278]
I got this error with diamond version 0.9.24:
```
Joining output blocks... No such file or directory
Error: Error reading file /home/proj/usr/tmp/diamond-tmp-J1nIsx
terminate called after throwing an instance of 'File_read_exception'
  what():  Error reading file /home/proj/usr/tmp/diamond-tmp-J1nIsx
/var/spool/gridengine/execd/hpc47/job_scripts/16044: line 28:  1883 Aborted                 (core dumped) ${Diamond} blastp -t ${Tmp} --db ${DB} --query ${Q} --out ${Dir_out}/${Sample}.alignment.diamond --outfmt 6 --evalue 1e-3 --threads ${Thread} --matrix BLOSUM62
```

People who ask you about temporary file creation errors like #73 and #97 seem to be resolved by setting the "-t /dev/shm/" option.
However, since /dev/shm/ does not have enough disk space, I would like to set the temporary file directory to something other than /dev/shm/.

**Comment by bbuchfink** [comment]
Have you tried using some other directory as temp directory? Does the error always occur for any input data or just occasionally?

**Comment by Mika-jp** [comment]
I have tried using other directory but I got the same error.
The error always occur for any input data when the temp directory is set to a directory other than /dev/shm/.

**Comment by bbuchfink** [comment]
Please try to clone the repository and compile the latest commit from source. This version has an option `--no-unlink`, please try if that fixes your problem.

**Comment by MikaUhr** [comment]
the problem is solved thanks to you!
