### ISSUE TITLE
Advantage to taxonomy features

### ISSUE THREAD

**Issue by andrewjmc** [bbuchfink/diamond#280]
Can I chest:

```
--taxonmap <file>
Path to mapping file that maps NCBI protein accession numbers to taxon ids (gzip compressed). This parameter is optional and needs to be supplied in order to provide taxonomy features. The file can be downloaded from NCBI: ftp://ftp.ncbi.nlm.nih.gov/pub/
taxonomy/accession2taxid/prot.accession2taxid.gz.
--taxonnodes <file>
Path to the nodes.dmp file from the NCBI taxonomy. This parameter is optional and needs to
be supplied in order to provide taxonomy features. The file is contained within this archive
downloadable at NCBI: ftp://ftp.ncbi.nlm.nih.gov/pub/taxonomy/taxdmp.zip.
```

What are the advantages to using either of these? Do they avoid the need to meganize the files for MEGAN?

Thanks,

Andrew

**Comment by bbuchfink** [comment]
These options are for doing taxonomic classification directly with Diamond. They don't work with MEGAN and should not be used if you intend to import the output into MEGAN.

**Comment by andrewjmc** [comment]
OK, thanks for the clarification. I ran a number of samples with these options and am meganizing. Will this cause a problem?

**Comment by bbuchfink** [comment]
No that shouldn't be a problem.

**Comment by andrewjmc** [comment]
Great, thanks.

**Comment by slvrshot** [comment]
@bbuchfink What does the classification output look like? I am trying to classify some ARG types using the nr database. A paper I read said, "Taxonomic assignment of bacterial hosts of ARGs
Protein sequences of ORFs predicted in the contigs that carried ARG-like ORFs were annotated using BLASTP against NCBI NR database (downloaded on 2 February, 2015) at E value ≤ 10− 5. The BLASTP results were annotated using MEGAN (MEtaGenome ANalyzer, Version 5) [39] for assignment of taxonomic genus. The contig was assigned to the taxon if the voting score was more than 50% [11, 40]."
https://www.ncbi.nlm.nih.gov/pmc/articles/PMC5811963/#CR40

However if I can avoid using MEGAN I'd rather go the diamond route for taxonomic classification. Is the taxonomy feature new?

**Comment by bbuchfink** [comment]
The feature has been in there for some years now. To quote the manual:

> Taxonomic classification. This format will not print alignments but only a taxonomic
classification for each query using the LCA algorithm. The output lines consist of 3
tab-delimited fields:
> 1. Query ID
> 2. NCBI taxonomy ID (0 if unclassified)
> 3. E-value of the best alignment with a known taxonomic ID found for the query (0 if
> unclassified)
> The score range for the LCA algorithm is set by the --top parameter. The default value
> is 10 which means that all alignments whose score is at most 10% lower than the best
> score are considered for the LCA computation.
> Using this format requires setting the --taxonmap and --taxonnodes parameters for
> makedb.
