### ISSUE TITLE
Human sequences misidentified?

### ISSUE THREAD

**Issue by andrewjmc** [bbuchfink/diamond#281]
I am currently trialling diamond/MEGAN, kraken and other tools for a shotgun metagenomics project. I was pleased to see that diamond did a better job of identifying spiked E. coli in a human throat swab than kraken (25,430 reads in paired mode, vs. 1,030 in kraken).

I ran diamond on two separate concatenated fastq files containing paired reads:

```
diamond blastx --threads 32 --db nr.db.dmnd --outfmt 100 \
    --taxonnodes ~/medbio_databases/diamond/nodes.dmp --taxonmap ~/medbio_databases/diamond/prot.accession2taxid.gz \
    --query file_R1.fastq --unal 1 -o file_R1.daa -b 20
```
(NB - I now realise I did not need the taxonnodes and taxonmap features)

However, when I extracted the list of R2 reads that MEGAN matched to E. coli, I found that kraken had mapped the vast majority of these to Homo sapiens, and none of them to E. coli.

Here is one example which perplexes me.

Read NB551065:160:HNCCFBGX5:1:11101:10840:13919
Sequence: TTCATAATCTTGAGTTCTAATTTGATTGTGCTGAGAGACTGTTTATTATTATTTCAGTTCTTTTCATTTG
CTGAGGAGTGTATTACTTCCTATTATGAGATCAATTTTAGAGTAAGTGCCATGTGGCAACGAGAAGAATG
TATATTCTGTT

Kraken maps it and its mate pair unequivocally to Homo sapiens: 
Homo sapiens (taxid 9606)       151|151 9606:1 0:29 9606:17 0:3 9606:5 0:7 9606:1 0:16 9606:3 0:7 9606:1 0:11 9606:16 |:| 9606:63 0:9 9606:1 0:3 9606:5 0:4 9606:1 0:5 9606:26

NCBI blast against the NR database does similarly (top match to Homo sapiens protocadherin 11 X-linked (PCDH11X), RefSeqGene on chromosome X with 150/151 sequence identities)

Yet diamond/MEGAN gives the top match as:

```
Query= NB551065:160:HNCCFBGX5:1:11101:10840:13919

Length=151

>PBT82394.1
Length=80

 Score = 52.0 bits (123),  Expect = 7.0e-04
 Identities = 24/33 (72%), Positives = 24/33 (72%), Gaps = 0/33 (0%)
 Frame = -2

Query  150  TEYTFFSLPHGTYSKIDLIIGSNTLLSK*KELK
            TEYTFFS PH TYSK D IIGS TLLSK K
Sbjct   22  TEYTFFSVPHHTYSKTDHIIGSKTLLSKCKTME
```
(converted with diamond view command)

I have confirmed that this is in the reverse complement reading frame.

The NR database is managed by my bioinformatic facility and certainly contains metazoan reads (1.4 million reads map to metazoa, though this compares unfavourable to kraken which matches nearly 16 million to Homo sapiens).

The behaviour seems very strange. I fully expect I may have done something wrong in my running of diamond, and would appreciate any advice you have.

Best wishes,

Andrew

**Comment by bbuchfink** [comment]
I just used the online blastx for this read against the nr database and I'm getting the same top hit: `hypothetical protein BBJ18_07345, partial [Escherichia coli] Sequence ID: PBT82394.1`

Could it be that you used blastn instead of blastx? This read seems to map to a noncoding region so you can't identify it using protein alignment. For host read filtering I recommend using minimap2 or a similar tool against the human genome.

**Comment by andrewjmc** [comment]
Aha -- seems silly now you point it out :-)

Thanks for your help,

Andrew
