### ISSUE TITLE
Add 'strand' fields to --outfmt 6

### ISSUE THREAD

**Issue by tseemann** [bbuchfink/diamond#284]
I was wondering if a `strand` option could be added to custom output mode `--outfmt 6`

In `blastp` this would always be `+`
In `blastx` this would be `+`/`-` depending on the orientation of the protein to the DNA query

This comes about as I was hoping to produce a `--outfmt BED` line for piping into `bedtools`.

**Comment by bbuchfink** [comment]
Sure thing, it should be ready by tomorrow. You can also infer the strand from the query coordinates.

**Comment by bbuchfink** [comment]
`qstrand` has been added as output field in the latest commit. `qframe` is also available in case you need it.
