### ISSUE TITLE
Segmentation fault: 11  only when --range-culling used

### ISSUE THREAD

**Issue by tseemann** [bbuchfink/diamond#285]
This works
```
diamond blastx --query contigs.fna --db proteins.dmnd
```

This fails
```
diamond blastx --query contigs.fna --db proteins.dmnd --range-culling -F 15
```

Details:
```
diamond version 0.9.24

Database format version = 2
Diamond build = 120
Sequences = 107292
Letters = 22106161

Query is a bacterial chromosome DNA sequence ~ 5 Mbp

Darwin Kernel Version 18.6.0:  Mojave

```

**Comment by bbuchfink** [comment]
I'm aware of a Mac-specific segfault in the frameshift alignment code. Could you try using the Linux version instead? I'll try to fix this bug but it may take some time since I normally don't have access to a Mac.

**Comment by bbuchfink** [comment]
This should be fixed in the latest commit. I'll also be posting a new release soon. Let me know if you need anything else, I'd certainly be honored for Diamond to be included into one of your pipelines!

**Comment by tseemann** [comment]
Thanks @bbuchfink - the `--range-culling` is a key feature i need and I am planning on using Diamond in my next pipeline.
