### ISSUE TITLE
Error: std::bad_alloc

### ISSUE THREAD

**Issue by evolbeginner** [bbuchfink/diamond#286]
[diamond (4).log](https://github.com/bbuchfink/diamond/files/3280314/diamond.4.log)
Dear,

I was trying to run diamond blastp but encountered the following problem 

Error: Error: std::bad_alloc
Error: std::bad_allocstd::bad_alloc

terminate called after throwing an instance of 'std::bad_alloc'
terminate called recursively
  what():  std::bad_alloc
Aborted

I have tried with --algo 0 but it did not seem to work either. I attach the log file here. Would you please mind helping me with this issue? Thanks.

Sishuo

**Comment by bbuchfink** [comment]
Could you maybe try again using the latest version of diamond? How much memory does your computer have?

**Comment by evolbeginner** [comment]
Hi Ben,

There seemed to be the same problem with v0.9.24.125. The computer has 128 GB. Thank you.

**Comment by bbuchfink** [comment]
I can't tell the cause of this issue unfortunately, would it be possible to make your data available to me so I can try to reproduce it?

**Comment by evolbeginner** [comment]
I uploaded the database file to [onedrive](https://1drv.ms/u/s!AqfIFBa7fgHehExpEGRfN_azjR4x?e=arG4jf.). I am guessing there was something wrong with the fasta file? Thank you.

**Comment by bbuchfink** [comment]
Sorry for not replying earlier. In order to reproduce this, I would also need your input query file or a part of it that exhibits the problem.

**Comment by evolbeginner** [comment]
Thank you for your attention. The query file is attached.

**Comment by evolbeginner** [comment]
Thanks for your attention. The fasta file is attached.

[Saccharomyces_cerevisiae.fas.txt](https://github.com/bbuchfink/diamond/files/3357955/Saccharomyces_cerevisiae.fas.txt)

**Comment by bbuchfink** [comment]
Thanks, I'm able to reproduce the problem on my system. I will look into this and hopefully be able to provide a fix soon.

**Comment by bbuchfink** [comment]
The problem is sequence `YP_00168669` in your database, which is 53 million residues long (so probably not an actual protein). Diamond can't handle this sequence as the DP matrix will use too much memory. If you must align against this sequence, you should remove it from the database and try BLAST.

**Comment by evolbeginner** [comment]
Hi Ben,

Sorry for this trouble and thank you so much for your great efforts! I will remove this sequence and reperform the analysis. Again, many thanks for helping fix the problem!
