### ISSUE TITLE
Text file busy Error: Error calling unlink.

### ISSUE THREAD

**Issue by carlosparq** [bbuchfink/diamond#287]
Hi,

I've been trying to run diamond v0.24 and I get the following error:

> lubuntu@lubuntu:/media/sf_VMshared/eggnog/eggnog-mapper$ diamond blastp -q query.fa -d data/eggnog_proteins.dmnd
> Text file busy
> Error: Error calling unlink.

It also happens when I try to create a protein database. What can I do?
Thanks in advance,
Carlos.

**Comment by bbuchfink** [comment]
Could you try using the latest commit from the repository (clone the diamond github repo and compile from source)? This version has an option `--no-unlink` to disable the unlink call, so if that is what's causing this problem this should help.
