### ISSUE TITLE
Cann't run diamond on the HPC cluster

### ISSUE THREAD

**Issue by 473021677** [bbuchfink/diamond#288]
Hi
   I am trying to run diamond on the HPC cluster. I have cinnfigured the PBS script like below:
The PBS script "diamond_makedb.pbs" for making database is as follows:
#!/bin/bash
#PBS -N diamond_makedb.pbs
#PBS -l nodes=1:ppn=20
#PBS -q com_q
#PBS -j oe
cd /share/home/linanh/The_project_for_Marsarchaeota/Genome_expansion_through_HGT_for_Mars/gtdb_genomes
diamond makedb --in Combined.proteins.fasta -d Combined.proteins -b 4

The PBS script "diamond_blastp.pbs" for making database is as follows:
#!/bin/bash
#PBS -N diamond_makedb.pbs
#PBS -l nodes=2:ppn=40
#PBS -q com_q
#PBS -j oe
cd /share/home/linanh/The_project_for_Marsarchaeota/Genome_expansion_through_HGT_for_Mars/gtdb_genomes
diamond  blastp -d Combined.proteins -q Combined.proteins.fasta -a Combined.proteins_diamond -p 40 -e 1e-10 -c 1
I have use the PBS script "diamond_makedb.pbs" to make database successfully. But when I try to run diamond blastp using the PBS script "diamond_blastp.pbs", the process keeps in queue and can't run. I suspect that the diamond process cann't be distributed among multiple computing noodes when trying to run diamond on the HPC cluster. I am not sure about it. Would it be possible for you to help me?

Best regards,
Yuan

**Comment by bbuchfink** [comment]
You should try to set the number of nodes to just one, otherwise I don't see how this should work with diamond.

**Comment by 473021677** [comment]
Hi,
Thanks for your help very much. 

Best regards,
Yuan
