### ISSUE TITLE
Missing hit when there are too many query genes

### ISSUE THREAD

**Issue by michaelkyu** [bbuchfink/diamond#290]
I have a query gene that will only have a hit if it is in a separate fasta file. If I put this gene alongside many other genes in the same fasta file, then it will no longer have a hit. I am running the blastp tool in diamond v0.9.24, installed via anaconda. 

Data to reproduce error ([Google Drive link](https://drive.google.com/open?id=1pXtXSQNAGTP0UuleLEtEALyZ_KnhAtSr)):
`aa_sequences.fa`: sequences for 1,250,010 genes
`560270.fa`: sequence for only the gene '>560270' (also contained in `aa_sequences.fa`)
`COG.dmnd`: the target database
`test_diamond.sh`: script to reproduce error. This will take ~4 min with 16 threads to run on `aa_sequences.fa`
    
The strange thing is that a hit for gene '>560270' will be found if you run `diamond` on `560270.fa` but not if you run on `aa_sequences.fa`. When I try taking any random subset of genes, e.g. 1,250,000 of the 1,250,010 genes, this problem goes away!

Thanks for the help!

**Comment by bbuchfink** [comment]
This does seem to have to do with the frequent seed masking. Diamond ignores seeds that are too frequent in the queries or the database, which seems to affect this particular query when used together with the rest of the file. You can use the option `--freq-sd` with some big number like `1000000` to turn off the seed masking and recover the missing hits.

I'm aware that this behaviour is not optimal and I've been working on a better alternative for some time, which should be ready for release it the near future.

**Comment by michaelkyu** [comment]
That did the trick, thanks!

**Comment by michaelkyu** [comment]
Actually, I'm confused again. When I set `--freq-sd` to a big number like `1000000`, I indeed recover some of the missing hits, including the hits for gene `560270` in my example. However, I also lose many hits that were found when `--freq-sd` was not specified. I was expecting to ONLY recover hits, not lose any?

**Comment by bbuchfink** [comment]
This is due to the fact that Diamond will only report the best 25 hits for each query by default. So with the more sensitive settings, higher-scoring hits will be found that supersede the hits from the less sensitive run. To get all hits reported, you can use the option `-k0`.
