### ISSUE TITLE
How big should this nr.dmnd file be?

### ISSUE THREAD

**Issue by slvrshot** [bbuchfink/diamond#291]
Not really an issue per se but I was somewhat concerned. The nr.gz file is around 50 GB. The dmnd file is getting quite big. It is around 111 GB currently. Diamond is still loading, hashing, masking, writing sequences so everything looks good on that end. Still I wanted to know if you might be able to specify if I am getting close to finishing the database creation or if its going to be a while. Thanks!

**Comment by bbuchfink** [comment]
Thanks for the suggestion, I will add an (approximate) progress estimation.

**Comment by slvrshot** [comment]
> Thanks for the suggestion, I will add an (approximate) progress estimation.

No problem. What is the typical size after it is done creating the database (ballpark)?

**Comment by bbuchfink** [comment]
About the same size as the uncompressed fasta, so maybe 2-3 times the compressed file.

**Comment by slvrshot** [comment]
Thanks Benjamin
