### ISSUE TITLE
I successfully ran diamond blastp....but my files are not in .daa format

### ISSUE THREAD

**Issue by slvrshot** [bbuchfink/diamond#292]
I ran this command...

[diamond blastp -q sample.fa -d nr.dmnd -p 16 --max-target-seqs 1 --evalue 0.0001 -o sample_blastp.out](url)

But when I feed it to Megan6 it says the file is not in .daa format. Am I suppose to convert it? 

Thanks for your assistance.

**Comment by bbuchfink** [comment]
You need to use the parameter `-f daa` to get DAA format.

**Comment by slvrshot** [comment]
Thanks for answering this. I learned more about this over the weekend. In the future I'll make sure to always output .daa first, then convert to other formats as needed.
