### ISSUE TITLE
Input/output error

### ISSUE THREAD

**Issue by WJunHao** [bbuchfink/diamond#294]
Hi, when I used diamond, I got some errors :
"diamond v0.9.25.126 | by Benjamin Buchfink <buchfink@gmail.com>
Licensed under the GNU GPL <https://www.gnu.org/licenses/gpl.txt>
Check http://github.com/bbuchfink/diamond for updates.

#CPU threads: 48
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
Temporary directory: 
Opening the database...  [15.0454s]
#Target sequences to report alignments for: 25
Opening the input file...  [0.021789s]
Opening the output file...  [0.003107s]
Loading query sequences...  [34.3292s]
Masking queries...  [36.2324s]
Building query seed set...  [0.14502s]
Algorithm: Double-indexed
Building query histograms...  [3.24679s]
Allocating buffers...  [0.002059s]
Loading reference sequences...  [71.7147s]
Building reference histograms...  [1.48399s]
Allocating buffers...  [0.000195s]
Initializing temporary storage...  [0.070814s]
Processing query chunk 0, reference chunk 0, shape 0, index chunk 0.
Building reference index...  [2.06557s]
Building query index...  [3.47571s]
Building seed filter...  [0.237895s]
Searching alignments... No such file or directory
terminate called without an active exception
Input/output error
terminate called recursively
Aborted (core dumped)"
The order is " ./diamond blastx --db nr.dmnd --query ./NH1_RD_1.fq --out NH1_reads1.tab".
Thank you for your attention!

**Comment by bbuchfink** [comment]
Can you tell me more about your system (hardware, operating system)?

**Comment by WJunHao** [comment]
# Linux smp2 2.6.32-504.el6.x86_64 #1 SMP Tue Sep 16 01:56:35 EDT 2014 x86_64 x86_64 x86_64 GNU/Linux
Red Hat Enterprise Linux Server release 6.6 (Santiago) #

**Comment by WJunHao** [comment]
Linux smp2 2.6.32-504.el6.x86_64 #1 SMP Tue Sep 16 01:56:35 EDT 2014 x86_64 x86_64 x86_64 GNU/Linux
Red Hat Enterprise Linux Server release 6.6 (Santiago)

**Comment by bbuchfink** [comment]
Could you try using the option `--no-unlink`?

**Comment by WJunHao** [comment]
Like this " ./diamond blastx --db nr --query a.fna --out a.tab -e 0.00001 -f 6 --no-unlink" ?

**Comment by bbuchfink** [comment]
Yes, like this.

**Comment by WJunHao** [comment]
Thank you, it works. Do you mind tell me the meaning of the "--no-unlink"? Thank you again.

**Comment by bbuchfink** [comment]
The unlink system call is used to delete temporary files directly after creation. That is to have them automatically removed in case the program crashes etc. But apparently it does not seem to work on your system.

**Comment by WJunHao** [comment]
So, it means every time I use diamond , I must add "--no-unlink"?

**Comment by bbuchfink** [comment]
Yes, at least for now. I will implement something to detect this automatically.

**Comment by WJunHao** [comment]
Thank you for your kind reply. I am looking forward to your future works!

**Comment by bbuchfink** [comment]
The latest version no longer fails if unlink doesn't work.
