### ISSUE TITLE
Build issue building latest version 

### ISSUE THREAD

**Issue by tillea** [bbuchfink/diamond#295]
Hi,
I tried to update the Debian package of diamond to version 0.9.25 and got a build issue:

    [ 40%] Building CXX object CMakeFiles/diamond.dir/src/output/blast_pairwise_format.cpp.o
    /usr/bin/c++   -I/build/diamond-aligner-0.9.25+dfsg/src  -g -O2 -fdebug-prefix-map=/build/diamond-aligner-0.9.25+dfsg=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-                     time -                   D_FORTIFY_SOURCE=2 -std=gnu++11 -Wall -Wno-uninitialized -Wno-ignored-attributes -Wno-unused-variable   -std=gnu++11 -o CMakeFiles/diamond.dir/src/output/blast_pairwise_format.cpp.o -  c /build/diamond-aligner-0.9.25+dfsg/src/output/blast_pairwise_format.cpp
    /build/diamond-aligner-0.9.25+dfsg/src/dp/needleman_wunsch.cpp:330:120: error: duplicate explicit instantiation of ‘const Fixed_score_buffer<_score>& needleman_wunsch(sequence, sequence, int&, const        _mode&,    const _score&) [with _score = int; _mode = Local]’ [-fpermissive]
     template Fixed_score_buffer<int> const& needleman_wunsch<int, Local>(sequence, sequence, int&, Local const&, int const&);

Any hint how to fix this?
Kind regards, Andreas.

**Comment by bbuchfink** [comment]
Could you try again with the latest commit 82feea2aee5c82e283704b9317cb5e8abc625f90 ?

**Comment by tillea** [comment]
The package builds now.  I admit I'd be happy if there would be any at least basic test suite to test the functionality.  May be you could provide some simple data set and run the commands from README.md

    diamond makedb --in nr.faa -d nr
    diamond blastx -d nr -q reads.fna -o matches.m8

In Debian we are doing an effort to test all packages in the field of bioinformatics in a Continuous Integration environment.  It would be helpful if this could be provided with some test you crafted and used yourself as author of the software.
Thanks a lot for your quick response, Andreas.

**Comment by bbuchfink** [comment]
Sure thing, a test suite is planned and should be ready soon.

**Comment by tillea** [comment]
On Thu, Aug 01, 2019 at 06:10:27AM -0700, Benjamin Buchfink wrote:
> Sure thing, a test suite is planned and should be ready soon.
Thanks a lot!

**Comment by smoe** [comment]
I just updated to 0.9.26 and in its pristine version got this build error
```
/usr/local/bin/c++   -I/home/moeller/git/med-team/diamond-aligner/src  -g -O2 -fdebug-prefix-map=/home/moeller/git/med-team/diamond-aligner=. -fstack-protector-strong -Wformat -Werror=format-security -Wdate-time -D_FORTIFY_SOURCE=2 -std=gnu++11 -Wall -Wno-uninitialized -Wno-ignored-attributes -Wno-unused-variable   -std=gnu++11 -o CMakeFiles/diamond.dir/src/output/blast_pairwise_format.cpp.o -c /home/moeller/git/med-team/diamond-aligner/src/output/blast_pairwise_format.cpp
/home/moeller/git/med-team/diamond-aligner/src/dp/needleman_wunsch.cpp:330:120: error: duplicate explicit instantiation of ‘const Fixed_score_buffer<_score>& needleman_wunsch(sequence, sequence, int&, const _mode&, const _score&) [with _score = int; _mode = Local]’ [-fpermissive]
  330 | template Fixed_score_buffer<int> const& needleman_wunsch<int, Local>(sequence, sequence, int&, Local const&, int const&);
```
but all went find when commenting out that template again.

**Comment by bbuchfink** [comment]
Unfortunately, commenting it out leads to errors on other systems. Can you tell me your compiler version so I can try to reproduce this?

**Comment by smoe** [comment]
```
$ g++ --version
g++ (Debian 9.2.1-8) 9.2.1 20190909
```

**Comment by bbuchfink** [comment]
So I finally looked into this issue. Note that your compiler version is a snapshot as GCC 9.2.1 has not yet been officially released. I was not able to reproduce this error using GCC 9.2.0, neither using the latest snapshot which is GCC-9-20191005. I wasn't able to find your particular snapshot at the GCC website. But maybe you can try updating your compiler?

**Comment by tillea** [comment]
As far as I can see this is solved (either by diamond version 0.9.26 or the upgrade of gcc in Debian.

**Comment by bbuchfink** [comment]
> 
> 
> The package builds now. I admit I'd be happy if there would be any at least basic test suite to test the functionality. May be you could provide some simple data set and run the commands from README.md
> 
> ```
> diamond makedb --in nr.faa -d nr
> diamond blastx -d nr -q reads.fna -o matches.m8
> ```
> 
> In Debian we are doing an effort to test all packages in the field of bioinformatics in a Continuous Integration environment. It would be helpful if this could be provided with some test you crafted and used yourself as author of the software.
> Thanks a lot for your quick response, Andreas.

Sorry it took this long. A test suite is finally available in the latest release. Run `diamond test`.

**Comment by tillea** [comment]
On Wed, Mar 18, 2020 at 03:01:56PM -0700, Benjamin Buchfink wrote:
> > 
> > 
> > The package builds now. I admit I'd be happy if there would be any at least basic test suite to test the functionality. May be you could provide some simple data set and run the commands from README.md
> > 
> > ```
> > diamond makedb --in nr.faa -d nr
> > diamond blastx -d nr -q reads.fna -o matches.m8
> > ```
> > 
> > In Debian we are doing an effort to test all packages in the field of bioinformatics in a Continuous Integration environment. It would be helpful if this could be provided with some test you crafted and used yourself as author of the software.
> > Thanks a lot for your quick response, Andreas.
> 
> Sorry it took this long. A test suite is finally available in the latest release. Run `diamond test`.

We should definitly try this.  Unfortunately I get in cmake step:

   undefined reference to 'pthread_create'

Any takers in Debian Med team are welcome.  Salsa repository is updated.

Kind regards, Andreas.

**Comment by bbuchfink** [comment]
Hi Andreas, no idea about this error unfortunately, as `find_package(Threads REQUIRED)` is included in the CMake file. Can you tell me the exact specs of the system this is happening on and/or give me a full log?

**Comment by tillea** [comment]
Hi,

On Sat, Mar 21, 2020 at 03:56:27AM -0700, Benjamin Buchfink wrote:
> Hi Andreas, no idea about this error unfortunately, as `find_package(Threads REQUIRED)` is included in the CMake file. Can you tell me the exact specs of the system this is happening on and/or give me a full log?

Sorry, I'm flooded with work now currently.  Hope this zip attachment
from the complete Debian build log (also mentioning used build depends
and versions) is helpful.  No time to strip things down currently.

BTW, would you say diamond is relevant for fighting COVID-19.  We are
assembling a list of high priority packages.

Kind regards, Andreas.

**Comment by bbuchfink** [comment]
Hi Andreas, I have tried to reproduce this now in the latest Debian experimental Docker container. It has the same GCC and CMake versions, but the error does not occur.

I'm not personally aware of anybody using Diamond for Covid-19 research (except for our own group soon, probably) but I could see it being relevant.
