### ISSUE TITLE
reference chunk 32, has been running 44 hours. Is it normal?

### ISSUE THREAD

**Issue by elevendong** [bbuchfink/diamond#296]
Hi,
I am running blastx of a transcriptome against nr on a 64 core server.  
It is now doing query chunk 0, reference chunk 32 and has been running for 44 hours. Is this normal? Should I stop and run again? I did have the --sensitive option.
Thank you.
Below is my command:
docker run -v `pwd`:`pwd` buchfink/diamond diamond blastx -d `pwd`/nr.dmnd -q `pwd`/Collapsed_transcriptome.fasta -o `pwd`/diamond_nr_collasped_blast_result --sensitive -p 60 -f 6 -e 0.00001 --max-target-seqs 1

**Comment by bbuchfink** [comment]
Seems normal in sensitive mode. One thing you can do you speed it up is to use the options `-b12 -c1` if you server has enough memory. Depending on the size of your query file you should maybe restart this. Query chunk 0 means it is processing the first 2 GB of (translated) sequence from the query.

**Comment by elevendong** [comment]
Thank you for the suggestions.  My assembly has 220k contigs with N50 1400. 
I restarted the process with --sensitive -b 100 -c 1. 
It has been stuck as below for 10 hours. Is it expected?
-------------------------------------
Processing query chunk 0, reference chunk 0, shape 15, index chunk 0.
Building reference index...  [258.996s]
Building query index...  [1.68794s]
Building seed filter...  [22.5322s]
Searching alignments...  [1432.29s]
Deallocating buffers...  [3.68537s]
Computing alignments... 
-----------------------------------------
With the process running if I "memory -g"
$memory -g
                    total       used       free     shared    buffers     cached
Mem:          1514        771        742          0          3        579

Thank you.

**Comment by elevendong** [comment]
Just finished. Took 23 hours in total, not bad! --sensitive did make a huge difference in timing. I did a similar blastx 1.5 year ago on nr and got finished 30 mins. Nr was smaller at that time though.
