### ISSUE TITLE
Retrieve specific sequences from daa file?

### ISSUE THREAD

**Issue by hqtdave** [bbuchfink/diamond#298]
Hi,

Is there any way which I can retrieve all protein/nucleotide sequences assigned to a phylum (Bacteria, Eukaryota or Virus) or sequences which assign to a specific strain I interested in? 
I have finished a run for my metagenome and I found some species very strange in my data, I want to take them out of the whole dataset to make some analysis.

Thank you,
Dave

**Comment by bbuchfink** [comment]
It's not possible directly with Diamond, you have to make some script that parses the Diamond output, gets a list of all query sequences you need and extract them from the query file.

**Comment by hqtdave** [comment]
> It's not possible directly with Diamond, you have to make some script that parses the Diamond output, gets a list of all query sequences you need and extract them from the query file.

Oh,I got it. Thank you. I will try to write some script for that.
