### ISSUE TITLE
How to specify output format under outfmt6 parameter？

### ISSUE THREAD

**Issue by zhengyzh** [bbuchfink/diamond#300]
I want to make the output format as follows, but the error is reported.

diamond blastp --query pep.fa --db nr.fa --threads 8 --max-target-seqs 1 --outfmt "6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore" > blastp.outfmt6

Can you tell me the correct way to specify the output format I want? I will be grateful.

**Comment by bbuchfink** [comment]
Please try without the quotation marks.

**Comment by zhengyzh** [comment]
I've tried it before，but the error is still reported.I've tried various formats, but they all failed.
The software instructions are displayed in a format that can be specified.I think this may be a bug in the program.

**Comment by bbuchfink** [comment]
Can you show me the full program output (when trying without quotation marks)?

**Comment by zhengyzh** [comment]
It's incredible.I've tried it last week,the error is still reported.But it succeeded this time.I don't know why.Anyway, the problem has been solved. Thank you very much.
