### ISSUE TITLE
Execution on deprecated databases results in memory error.

### ISSUE THREAD

**Issue by rababerladuseladim** [bbuchfink/diamond#302]
Running diamond v0.9.25.126 on a database with schema version 0 (created using diamond v0.8.22) I get the following error:
`Error: Failed to allocate sufficient memory. Please refer to the manual for instructions on memory usage.`

Rebuilding the database fixes this, so this error is not actually related to memory.  
From digging around in other issues, I figured that this error should be thrown instead:
`Error: Database was built with a different version of diamond as is incompatible.`

The same problem is mentioned in another issuer [here](https://github.com/bbuchfink/diamond/issues/91#issuecomment-525744439_)

**Comment by bbuchfink** [comment]
I'm aware of this and it has been fixed in v0.9.26.
