### ISSUE TITLE
how much RAM and free disk space required to build full nr NCBI database?

### ISSUE THREAD

**Issue by Krasnopeev** [bbuchfink/diamond#304]
Hi, 
I have an issue with building nr database from NCBI. Archive has size about ~50Gb .
I use latest diamond release v0.9.26.
I tried to build it on my PC (2 core i5, 16 RAM) with default commands:

`diamond makedb --in nr.gz -d nr`

and it is built successfully. New diamond database has size about 140Gb.

But when I tried to use taxonomy information from downloaded files follow the links in manual:

`diamond makedb --in nr.gz -d nr --taxonmap prot.accession2taxid.gz --taxonnodes taxdmp/nodes.dmp`

it crushes on stage "loading Taxonomy..." with the next error:
`Failed to allocate sufficient memory.
`

Free space on local drive about 100Gb  and 300Gb on drive where is the database built.
So there is the question: how much RAM and free disk space required to build full nr NCBI database with taxonomy information?

Thanks a lot!

**Comment by Krasnopeev** [comment]
It was successfully built on server node with 128Gb RAM and 18 cores Xenon.

**Comment by fdecarpentier** [comment]
I was able to do it on a laptop with 16 gb of RAM in 2.6h with Diamond 2.1.10. The final database nr.dmnd is 357 Gb. Here is the command line :
```
diamond makedb \
--in nr.gz \
-d nr.db \
--taxonmap prot.accession2taxid.FULL.gz  \
--taxonnames names.dmp \
--taxonnodes nodes.dmp \
--threads 12 \
--tmpdir temp \
--no-unlink \
--log 
```
