### ISSUE TITLE
Excluding taxon(s) from database 

### ISSUE THREAD

**Issue by lesneski** [bbuchfink/diamond#305]
Hello,
 my lab is a huge fan of diamond so far.

We are wondering if there is a way to exclude taxon IDs with the --taxonlist option when executing   diamond blastx .  We are working with a coral transcriptome and would like to exclude 2 taxonomic codes to essentially parse our transcriptome, and have the output include everything except for those 2 taxonomic codes. 
Thanks!

**Comment by bbuchfink** [comment]
It is not possible at the moment, but this is easy to implement so I'll see to get it done within the next days.

**Comment by lesneski** [comment]
That would be amazing - thank you very much! (and for your quick reply!)

**Comment by bbuchfink** [comment]
This has been implemented in 24336ae85b2d1d4f82a08885569928797dd7bdb9. Use the parameter `--taxon-exclude` with a list of taxon ids. It has not been tested though, let me know if there are any issues.

**Comment by lesneski** [comment]
Thank you very much @bbuchfink ! We have included this update in our SCC and have done some test runs, but it appears as though there is  leakage from the excluded taxons that end up in the output files - including subject_name column items that actually only are associated with the requested excluded taxon (ex, I wanted to exclude cnidaria, yet on the order of thousands of transcripts that were pulled have been characterized in a cnidaria -
"XP_029189265.1 XK-related protein 6-like [Acropora millepora]" -  and Acropora is a cnidaria.

So, not sure if it is something on our end, but I am meeting with some consultants tomorrow.

**Comment by bbuchfink** [comment]
Alright, I'll run some tests and see if I can reproduce this problem.

**Comment by bbuchfink** [comment]
It should be fixed in fb416e7d42c5b243c0526a7cfe9b961585dd8bb9.
