### ISSUE TITLE
terminate called recursively

### ISSUE THREAD

**Issue by zillurbmb51** [bbuchfink/diamond#307]
Hello I am running blastp using the following command:
`diamond blastp -d /shire/databases/nr/new_db_with_taxa/nr -q specific_all.fasta -p 40 --outfmt 6 qseqid sseqid sgi qstart qend sstart send evalue bitscore pident length mismatch gapopen staxids sskingdoms sscinames salltitles stitle --evalue 1e-5 --max-target-seqs 1 -o blast6.out`
I am getting the following message:
```
Joining output blocks... terminate called recursively
terminate called recursively
terminate called after throwing an instance of 'terminate called recursively
terminate called recursively
Aborted (core dumped)
```
If I do not use taxonomic fields the same error appears. Any Help? Best, Zillur

**Comment by bbuchfink** [comment]
Does the error occur when not using the `--outfmt` option (default output format)?

**Comment by OH-AU** [comment]
FYI: Have the same or very similar problem with 0.9.28 using  "sscinames scomnames" in the output options - it didn't like scomnames. Using just sscinames it ran successfully. I grabbed a few of the options above to test and got the following results:
only sscinames =  works
only scomnames = crashes
sscinames scomnames =  crashes
sscinames salltitles stitle = works
sskingdoms sscinames salltitles stitle = crashes
So in my case it didn't like either scomnames, or sskingdoms.

**Comment by bbuchfink** [comment]
Neither scomnames nor sscinames are supported by Diamond at this time. There should be an error message that says like `Invalid output field`. If it is relevant I can include support in a future release.

**Comment by OH-AU** [comment]
Thanks for that; I think in some cases (when compiled with gcc + flto) it coredumped without the Invalid output field. For most of my output files, that error message was indeed there I believe. I assumed if it was in blast_tab_format.cpp, it was available. My apologies for that assumption.
I think it might be nice to include them in a future release.
