### ISSUE TITLE
0.9.27: Build failure (clang++ v6.0.1 /  FreeBSD 12.0 amd64)

### ISSUE THREAD

**Issue by Jehops** [bbuchfink/diamond#308]
Hello,

A [build issue](http://pkg.awarnach.mathstat.dal.ca/data/12amd64-default/2019-11-02_14h24m43s/logs/errors/diamond-0.9.27.log) was introduced with 0.9.27.   Please let me know if there is any other information I can provide or anything I can test.

Regards,
Joseph

**Comment by bbuchfink** [comment]
Please try again with the latest commit.

**Comment by Jehops** [comment]
[Looks good](http://pkg.awarnach.mathstat.dal.ca/data/12amd64-default/2019-11-02_18h25m10s/logs/diamond-0.9.27.1.log). Thanks.
