### ISSUE TITLE
No GI number from diamond blast output

### ISSUE THREAD

**Issue by dieunelderilus** [bbuchfink/diamond#309]
Dear Diamond  developper 

Why I don't have  GI number for my Hits from the diamond blast output ? How I can run the diamond blast to get GI number.
I'm processing large dataset and sequence ID i am getting have different format as : XP_002505182.1, EAS85021.1, YP_003212956.1. I was expecting  GI number for each hit for downstream analysis.

Thanks in advance.
DD

**Comment by bbuchfink** [comment]
GI numbers were phased out by NCBI some time ago. You can try to find an old database version that still contains the GI numbers. You could also try to map the accessions to GIs in postprocessing with info available from NCBI, like here: ftp://ftp.ncbi.nlm.nih.gov/genbank/livelists/

**Comment by dieunelderilus** [comment]
Dear

Thank you very much for your quick response and help. I didn't know if GI
was deprecated NCBI.

Cordially
------------------------------------------------------------------

*Dieunel Derilus, PhD Candidate*

*Department of Environmental Sciences *

*University of Puerto Rico, Rio Piedras (UPRP)*
*Bioinformatics Lab NCN 343B *
*dieunelderilus@gmail.com* <dieunelderilus@gmail.com>
*(787)-513-4667*
