### ISSUE TITLE
output format

### ISSUE THREAD

**Issue by ucassee** [bbuchfink/diamond#310]
Dear developer,
       My local database file is like :

>    >WP_003131952.1 MULTISPECIES: 30S ribosomal protein S18 [Lactococcus]
MAQQRRGGFKRRKKVDFIAANKIEVVDYKDTELLKRFISERGKILPRRVTGTSAKNQRKVVNAIKRARVMALLPFVAEDQN

If I want the result of  `-outfmt 5`  as:
 <Hit_id>WP_003131952.1</Hit_id>
  <Hit_def> MULTISPECIES: 30S ribosomal protein S18 [Lactococcus]</Hit_def>

What should I do to modify the database file?
Thanks in advance

**Comment by bbuchfink** [comment]
Diamond should do it like that already. Please check your version by using `diamond --version`.

**Comment by ucassee** [comment]
I use the version 0.8.36.  Is it too old ?

**Comment by bbuchfink** [comment]
Yes this is rather old, I recommend to try again with the latest version.

**Comment by ucassee** [comment]
It works after I update diamond. Thanks~
