### ISSUE TITLE
Missing C++ source files -  src/search/search.cpp, src/data/sorted_list.cpp, src/util/memory/memory_pool.cpp

### ISSUE THREAD

**Issue by prehensilecode** [bbuchfink/diamond#311]
Compiler: GCC 4.8.1
OS: RHEL 6.5

Ran the `build_simple.sh` script, and the following error messages were shown:

```
g++: error: src/search/search.cpp: No such file or directory
g++: error: src/data/sorted_list.cpp: No such file or directory
g++: error: src/util/memory/memory_pool.cpp: No such file or directory
```

The listed source files are also not in the master branch.

**Comment by bbuchfink** [comment]
I know that the `build-simple` script is dysfunctional as it has never been an official build method. Please try to use cmake if possible.
