### ISSUE TITLE
database version (in)compatibility?

### ISSUE THREAD

**Issue by nextgenusfs** [bbuchfink/diamond#313]
Since there seems to now be 3 different versions of the database, I'm curious as to which are compatible with one another. It seems that the newest version was released in v0.9.25 (version 3), however, it then seems that v0.9.28 can successfully query database version 2.  But the inverse is not true correct?, ie if database is version 3 then v0.9.24 is unable to query that database?

**Comment by bbuchfink** [comment]
Yes, it's true that the current version can read database versions 2 and 3, but the old releases that created version 2 databases can't read version 3 databases. I'll try to maintain better backward and forward compatibility in the future.
