### ISSUE TITLE
got incomplete result with blastp

### ISSUE THREAD

**Issue by jinhao94** [bbuchfink/diamond#314]
I encountered the following problems when using diamond: the results of diamond was incompleted with blastp, so I am quite puzzled... （diamond version is  linux v0.9.28.129）

A protein fasta file named query.faa I used:
_____________________________________

>\>M010_00196
MAGETIITVVGNLTADPEIRTVGNGSSVASFTIASTPRTWNRNTGQFEDGQALFMRCSAW
RDMAEHCAQSLSKGMRVIAQGRLQQRSYQANDGSQRTVVELQVDEIGPSLRYATAQVTRT
SSANGGNFAGNRGGNNFAGGNGGFNNGGFAGNAGGYQGGAGYSGGAGYQGGAAAPANAAP
AVQPAPASDPWGNSDNSGSSSFGSFGSSEFGGSSDEPEF
>\>BBCT_1533
MAGETIITVVGNLTADPEIRTVGNGSSVASFTIASTPRTWNRNTGQFEDGQALFMRCSAW
RDMAEHCAQSLSKGMRVIAQGRLQQRSYQANDGSQRTVIELQVDEIGPSLRYATAQVTRT
SNANGGNFAGNRGGNAFAGGNGGFNNGGFAGNAGGYQGGAGYSGGAGYQGGATAPANAAP
AVQPAPASDPWGNSDNSGSSSFGSFGSSEFGGSSDEPEF

________________________________________
And the commond I used:

diamond makedb --in query.faa  -d query.faa
diamond blastp --threads 64 --max-target-seqs 10 --db  query.faa.dmnd --query query.faa --outfmt 6 qseqid sseqid stitle pident qlen slen length mismatch gapopen qstart qend sstart send evalue bitscore --out query.dia

makeblastdb -in query.faa -input_type fasta -dbtype prot -out query.faa.bastdb
blastp -query query.faa -db query.faa.bastdb -outfmt 6 -out query.blastp

—————————————————
The diamond result：
M010_00196	M010_00196	100.0	132	0	0	1	132	1	132	4.0e-74	260.4
M010_00196	BBCT_1533	98.5	132	2	0	1	132	1	132	1.2e-73	258.8
BBCT_1533	BBCT_1533	100.0	132	0	0	1	132	1	132	1.8e-74	261.5
BBCT_1533	M010_00196	98.5	132	2	0	1	132	1	132	8.9e-74	259.2

The blastp result：
M010_00196	M010_00196	100.000	219	0	0	1	219	1	219	9.88e-163	436
M010_00196	BBCT_1533	98.174	219	4	0	1	219	1	219	2.75e-160	430
BBCT_1533	BBCT_1533	100.000	219	0	0	1	219	1	219	5.58e-163	437
BBCT_1533	M010_00196	98.174	219	4	0	1	219	1	219	2.75e-160	430
————————————————
Did I set the wrong parameter?
Thanks for the help!

**Comment by bbuchfink** [comment]
This is caused by the repeat masking using [tantan](https://www.ncbi.nlm.nih.gov/pmc/articles/PMC3045581/). You can see it by running `diamond mask -q QUERYFILE`. Also the masking can be turned off by using `--masking 0`.
