### ISSUE TITLE
What does "positive" mean in an AA match?

### ISSUE THREAD

**Issue by terrycojones** [bbuchfink/diamond#317]
Is there anything written down about what the `positive` option to output format 6 produces? I guess this means AA similarity, but (if so) how is similarity defined? Or does it mean something else that's contributing positively to the match score but which isn't just a matter of similar AA properties?  Thanks!

**Comment by bbuchfink** [comment]
It means a score >0 in the scoring matrix.

**Comment by terrycojones** [comment]
OK, thank you! :-)
