### ISSUE TITLE
COntradictory results between Diamond blastp and NCBI online blastp

### ISSUE THREAD

**Issue by JustineCharon** [bbuchfink/diamond#318]
Hello,

I can't retrieve the same results than NCBI online blastp when I use Diamond blastx. More precisely, one of my sequence has a match in NCBI Blastp while it give no output with Diamond Blastx, while using the same reference database and the same evalue cut-off.. I was wondering if this could come from a difference in the word length parameter used in NCBI online Blastp ? 

Thanks a lot in advance for your help,

Kind regards

Justine

**Comment by bbuchfink** [comment]
This could happen due to the repeat masking done by Diamond. You can test running Diamond with `--masking 0`. But Diamond also does not have equal sensitivity to Blast, so for <40% ID hits this could easily happen due to the sensitivity. You can also try the `--more-sensitive` mode of Diamond.
