### ISSUE TITLE
diamond makedb killed 

### ISSUE THREAD

**Issue by jzehnpfennig** [bbuchfink/diamond#319]
I downloaded diamond onto my HPCC account and I am trying to build a database. I used the command:

wget ftp://ftp.ncbi.nlm.nih.gov/blast//db/FASTA/nr.gz

To get the nr.gz file form ncbi, however when I use the command:

diamond makedb --in nr.gz -d nr

I get the following:

diamond v0.9.29.130 | by Benjamin Buchfink <buchfink@gmail.com>
Licensed under the GNU GPL <https://www.gnu.org/licenses/gpl.txt>
Check http://github.com/bbuchfink/diamond for updates.

#CPU threads: 20
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
Database file: nr.gz
Opening the database file...  [0.020418s]
Loading sequences...  [28.8023s]
Masking sequences...  [7.88837s]
Writing sequences...  [12.5897s]
Hashing sequences...  [0.833748s]
Loading sequences...  [23.0588s]
Masking sequences...  [7.88738s]
Writing sequences...  [9.5142s]
Hashing sequences...  [0.661319s]
Loading sequences...  [21.7611s]
Masking sequences...  [7.85409s]
Writing sequences...  [8.92032s]
Hashing sequences...  [0.33828s]
Loading sequences...  [13.4748s]
Masking sequences... Killed

I tried to unzip the nr.gz file as well before attempting to make the database andI got the same result. 

Any suggestions on how to fix this?

**Comment by bbuchfink** [comment]
This looks like the job ran out of memory. You can try it with `--masking 0` to reduce the memory usage. Also use `/usr/bin/time diamond ...` to track the memory usage. Do you know how much memory your instance has?

**Comment by jzehnpfennig** [comment]
Using the --masking 0 flag worked for building the database! Thank you!  The HPCC I use only allows for a max amount of memory in the developmental nodes. Tasks exceeding that memory usage have to be submitted as a job.
