### ISSUE TITLE
Querry errors (Diamond build = 84)

### ISSUE THREAD

**Issue by snaketron** [bbuchfink/diamond#322]
Some information about the diamond database (downloaded, not built myself) that I need to query:
Database format version = 0
Diamond build = 84
Sequences = 45670220
Letters = 27397603774

I have tried to query it with 'diamond v0.8.11.73' and with 'diamond v0.9.24.125' getting the following errors:

------------------------------------------------------------------------------------------------------------------------------------
./diamond_8_11/diamond blastp --query test.faa --db data/gene_landscape_full_db_v1.dmnd --daa out.tab
diamond v0.8.11.73 | by Benjamin Buchfink <buchfink@gmail.com>
Check http://github.com/bbuchfink/diamond for updates.

#CPU threads: 20
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
#Target sequences to report alignments for: 25
Temporary directory: 
Opening the database...  [0.005015s]
Error: Incompatible database version

------------------------------------------------------------------------------------------------------------------------------------

and 

------------------------------------------------------------------------------------------------------------------------------------
./diamond_9_24/diamond blastp --query test.faa --db data/gene_landscape_full_db_v1.dmnd --daa out.tab
diamond v0.9.24.125 | by Benjamin Buchfink <buchfink@gmail.com>
Licensed under the GNU GPL <https://www.gnu.org/licenses/gpl.txt>
Check http://github.com/bbuchfink/diamond for updates.

#CPU threads: 20
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
Temporary directory: 
Opening the database...  [0.000956s]
Error: Database was built with a different version of Diamond and is incompatible.

------------------------------------------------------------------------------------------------------------------------------------

Any hints of how to solve this?

Best

**Comment by bbuchfink** [comment]
Build 84 is version 0.8.22, you can try that one.

**Comment by snaketron** [comment]
Thanks, it worked!
