### ISSUE TITLE
Is there any reliable script to summarize taxa diversity to result of diamond to meta-transcriptome data

### ISSUE THREAD

**Issue by Shicheng-Guo** [bbuchfink/diamond#326]
Dear Benjamin, 

Is there any reliable script to summarize the output file of the diamond to receive taxa diversity to result of the diamond to meta-transcriptome data? 

Thanks. 

Shicheng

**Comment by bbuchfink** [comment]
There's some pipelines around, like HUMAnN2 or MEGAN. But I don't have a comprehensive overview.
