### ISSUE TITLE
Incremental database construction (update db)

### ISSUE THREAD

**Issue by kislyuk** [bbuchfink/diamond#328]
Hi, thank you for building and maintaining diamond.

Does `diamond makedb` support incremental updates to the database? For example, if I am building an index for a new version of nr (and have the diff against the previous version available), is it possible to reuse the existing database build from the previous version and update it, or to merge the two databases?

**Comment by bbuchfink** [comment]
You can't modify the diamond database file directly. What may help is to use `diamond getseq` to pipe the content of the existing database to a new `diamond makedb` run in fasta format, at which point you can also add new sequences.
