### ISSUE TITLE
Missing source file folder "blast"

### ISSUE THREAD

**Issue by aWormGuy** [bbuchfink/diamond#329]
Hi,
When I tried to compile `diamond` from source, using `build_simple.sh` , I get the following errors:

`gcc: src/blast/sm_blosum45.c: No such file or directory`
`gcc: src/blast/sm_blosum50.c: No such file or directory`
`gcc: src/blast/sm_blosum62.c: No such file or directory`
`gcc: src/blast/sm_blosum80.c: No such file or directory`
`gcc: src/blast/sm_blosum90.c: No such file or directory`
`gcc: src/blast/sm_pam30.c: No such file or directory`
`gcc: src/blast/sm_pam70.c: No such file or directory`
`gcc: src/blast/sm_pam250.c: No such file or directory`

Also, I do not see the `blast` subfolder under `src` in the current github version. How can this be fixed?
Thanks,
-Amit.

**Comment by bbuchfink** [comment]
The `build_simple.sh` script is deprecated, please compile using cmake as described here: http://www.diamondsearch.org/index.php?pages/installation/

**Comment by aWormGuy** [comment]
Hi Benjamin,
Thanks a lot for your answer. I could successfully compile and install `diamond` on my macOS 10.12.6 .
However when I run the following:
`diamond blastx --db $DIAMOND_DB -q $INPUT_FILE --outfmt 6 --out $OUT_FILE --threads 2  --max-target-seqs 1;`
I get the following error: `Illegal instruction: 4`. 

Any ideas to fix this?

The full log is pasted below:
`diamond v0.9.30.131 (C) Max Planck Society for the Advancement of Science`
`Documentation, support and updates available at http://www.diamondsearch.org`
``
`#CPU threads: 2`
`Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)`
`Temporary directory: `
`Opening the database...  [0s]`
`#Target sequences to report alignments for: 1`
`Reference = ref_proteins_db.dmnd`
`Sequences = 3260186`
`Letters = 1149334072`
`Block size = 2000000000`
`Opening the input file...  [0s]`
`Opening the output file...  [0s]`
`Loading query sequences...  [0.011s]`
`Masking queries...  [0.056s]`
`Building query seed set...  [0.01s]`
`Algorithm: Double-indexed`
`Building query histograms...  [0.013s]`
`Allocating buffers...  [0s]`
`Loading reference sequences...  [3.396s]`
`Masking reference...  [59.785s]`
`Initializing temporary storage...  [0.008s]`
`Building reference histograms...  [22.888s]`
`Allocating buffers...  [0s]`
`Processing query block 0, reference block 0, shape 0, index chunk 0.`
`Building reference seed array...  [19.229s]`
`Building query seed array...  [0.013s]`
`Computing hash join...  [5.373s]`
`Building seed filter...  [0.003s]`
`Searching alignments... Illegal instruction: 4`
 
Thanks,

**Comment by bbuchfink** [comment]
Could you please try to clone the repository and compile the latest commit from source? And see if the error persists.

**Comment by aWormGuy** [comment]
Hi Benjamin,
Thanks for your help. I did try compiling the latest commit (aab49d2) from the source but this time the `make install` failed. I have attached the terminal output.  If you need any other info just let me know.

I have managed to compile and install diamond version 0.9.30 working nicely on a separate Linux computer, so no rush for fixing the Mac installation from my end.

Thanks again,
-Amit.

[diamond-aab49d2-install.log](https://github.com/bbuchfink/diamond/files/4236481/diamond-aab49d2-install.log)

**Comment by bbuchfink** [comment]
Could you try again with the latest commit?

**Comment by aWormGuy** [comment]
Hi Benjamin,
Thanks for your help. I could compile and install the latest commit (b3c013c), but unfortunately, it is back to the same problem as last week, here are the last few lines of the console output: 
`Computing hash join...  [9.138s]`
`Building seed filter...  [0.002s]`
`Searching alignments... Illegal instruction: 4`

There were some warnings during the `make install`. I have pasted the complete log in the attached file.

Thanks,
-Amit.
[dimaond-cmake-install-log.txt](https://github.com/bbuchfink/diamond/files/4257566/dimaond-cmake-install-log.txt)

**Comment by bbuchfink** [comment]
Please try to run diamond with a debugger attached. First, compile using `cmake -DCMAKE_BUILD_TYPE=RelWithDebInfo ..`. Then use `lddb -- /path/to/diamond args`. When in the debugger, type `run`. Type `bt` once the program crashes and send the output to me.

**Comment by bbuchfink** [comment]
In the latest commit, there are some more changes that might address this problem. You can try this one.
