### ISSUE TITLE
X character in output sequences

### ISSUE THREAD

**Issue by MatDal** [bbuchfink/diamond#331]
Hello,

after the mapping between a set of reads and a protein sequence using diamond blastx, in the output SAM file there are some sequences with the character "X". For me this is a problem because there are tools that are not able to accept this character as input. There is any solution to exlude them? Also using the option masking=0 in the output I have 2 or 3 sequences with X.

Thanks
Best

**Comment by bbuchfink** [comment]
If after setting `--masking 0` there are still X, it means they were already in your input sequence. So you should filter your input accordingly.

**Comment by MatDal** [comment]
Thanks! but no in my input is not present a sequence with a "X".
After the mapping also with --masking 0 there is 1 output sequence match with the X.

**Comment by bbuchfink** [comment]
Can you send me a fasta of the affected sequences?

**Comment by MatDal** [comment]
The database is only one protein epitope:
>1
QAIVRGCSMPGPWRSGRLLVSRRWSVE
But the input file is 2.7 Gb of DNA reads.

**Comment by bbuchfink** [comment]
Then probably there are some N's in your DNA that are translated into X. You would have to filter those out.

**Comment by MatDal** [comment]
Ok thanks! I'll try.
