### ISSUE TITLE
Failed to append more columns of outfmt 6

### ISSUE THREAD

**Issue by jlli6t** [bbuchfink/diamond#335]
Hi developers,

I am using diamond 0.9.30, with subcommand blastp, I am struggling to append more columns of output besides default outfmt 6. 

I read from document that format 6 is the default one, and I sure want the tabular foramt result, so I have tried several combinations:

diamond blastp --outfmt "6 qlen qcovhsp slen scovhsp" -- FAILED
diamond blastp --outfmt 6 --outfm qlen qcovhsp slen scovhsp --FAILED
diamond blastp --outfmt 6 qlen qcovhsp slen scovhsp -- Which only output the last 4 columns I appended.

Could you please suggest me how to add those columns that I want?

Thank you,
Irene

**Comment by jlli6t** [comment]
I have also tested with diamond v0.9.31 just now, it also just returned 4 columns.

**Comment by bbuchfink** [comment]
You have to specify all columns that you want to get, like this: `--outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore qlen qcovhsp slen scovhsp`

**Comment by jlli6t** [comment]
Yes, it worked. Thank you for a such quick response.
