### ISSUE TITLE
makedb options in script docs: mismatch with online docs

### ISSUE THREAD

**Issue by nick-youngblut** [bbuchfink/diamond#338]
This is a small thing, but it's a bit confusing. For diamond 0.9.30, the `diamond help` docs state:

```
Makedb options:
--in                     input reference file in FASTA format

```

... but the [online docs](http://www.diamondsearch.org/index.php?pages/command_line_options/) include taxonomy options for `makedb` (eg., `--taxonmap`)

**Comment by bbuchfink** [comment]
You are right of course, I'll see to fix this.
