### ISSUE TITLE
how to set --band

### ISSUE THREAD

**Issue by wmnwmn** [bbuchfink/diamond#34]
Do you have any advice how (or whether) to increase sensitivity by raising the --band parameter? Also what are the possible values of the parameter (noting that the default is not a number, but "auto")?

**Comment by bbuchfink** [comment]
The band parameter corresponds to the maximum length of gaps that can be found in alignments. For short reads you can set it to small values like 3-4 to increase speed. For longer reads values around 30 are appropriate. You can increase that number if you care about finding alignments (as single linear alignments) with longer gaps than that.
