### ISSUE TITLE
Diamond blastx not aligning to ref

### ISSUE THREAD

**Issue by bochaozhang** [bbuchfink/diamond#341]
Hi,

I am trying to align a query NT sequence against a ref AA sequence using blastx.

query sequence:
AGGGCCTACCTGGAGGGCACGTGCGTGGAGAGGCTCGCAGACACCTGGAGAACGGGAAGGAGACGCTGCAGCTCACGGGT

ref sequence:
SHTIQMMYGCDVGSDGRFLRGYQQDAYDGKDYIALNEDLRSWTAADMAAQITQRKWEAARVAEQL**RAYLEGTCVER**LRRYLENGKETLQRTD

The query sequence can be translated to **RAYLEGTCVER**LADTWRTGRRRCSSR with 5'3' Frame 1, and the first 11 amino acid **RAYLEGTCVER** can be found in the reference sequence at 66 to 77.

However when I ran Diamond blastx using this command it reports 0 aligned. 
`diamond blastx --masking 0 --top 1 --algo 0 --max-hsps 1 --min-score 1 -k 0 --id 99 -c 1 -d ref.dmnd -q query.fasta -o alignment.m8`

>Reported 0 pairwise alignments, 0 HSPs.
>0 queries aligned.

Can you let me know why the query sequence is not aligned please? Thanks.

**Comment by bbuchfink** [comment]
Try using `--more-sensitive`. It worked for me like that.

**Comment by bochaozhang** [comment]
Thanks a lot! It worked. Do you mind elaborating on the differences between with and without --more-sensitive option? I'm curious how it changed the behavior. Thanks.

**Comment by bbuchfink** [comment]
Diamond uses shorter seeds with that option, in default mode the seeds are too long to detect an exact 11 letter match (this is due to the use of spaced seeds).

**Comment by bochaozhang** [comment]
That makes sense. Thanks!
