### ISSUE TITLE
OSX build fails with latest release

### ISSUE THREAD

**Issue by sjanssen2** [bbuchfink/diamond#343]
wrapping the latest release of diamond in bioconda fails to compile on OSX. https://circleci.com/gh/bioconda/bioconda-recipes/103298?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-checks-link I am pretty sure it is due to the missing include of string in `src/basic/value.h`
This has been fixed on the master branch and when compiling with the master version everything passes perfectly. Thus, may I ask you to make a new release from the current master branch?

**Comment by bbuchfink** [comment]
Sure, it will be done shortly.

**Comment by oschwengers** [comment]
Hi @bbuchfink thanks a lot for taking this on so quickly. Short question: Will the new release break db compatibility with v0.9.31?

Or in a more general sense: Does *every* new Diamond version break compatibility with db built with former versions (internal version checks) or does this occur only occasionally upon certain changes?

**Comment by bbuchfink** [comment]
No, this release will not break the compatibility. I try to minimize doing this and plan to keep all future versions downward compatible with the current format.

**Comment by bbuchfink** [comment]
Release has been posted.

**Comment by sjanssen2** [comment]
many thanks @bbuchfink
