### ISSUE TITLE
fails on architectures where char is unsigned

### ISSUE THREAD

**Issue by tillea** [bbuchfink/diamond#347]
There is a [bug report](https://bugs.debian.org/958090) against the Debian package of diamond.  I've added a build time test using the diamond call from proteinortho.  The call 

    diamond blastp --threads 1 --db 'test/C.faa.diamond' --query 'test/E.faa' --out TESTDIR/E.faa.vs.C.faa.diamond -e 1e-05 --outfmt 6 --quiet  --sensitive

with the data you can find [here](https://salsa.debian.org/med-team/diamond-aligner/-/tree/master/debian/tests/test) is crashing.  The fact that this is only the case on architectures which you can check on the [autobuilders](https://buildd.debian.org/status/package.php?p=diamond-aligner) could lead to the suspicion that somewhere char is used as pointer index - replacing it by int could solve the issue.
Kind regards, Andreas.

**Comment by bbuchfink** [comment]
It should be fixed in 63b3e686f41272851a87c632441ba8c6484a2fe2.

**Comment by tillea** [comment]
Hi again,
On Thu, Apr 30, 2020 at 07:49:22AM -0700, Benjamin Buchfink wrote:
> It should be fixed in 63b3e686f41272851a87c632441ba8c6484a2fe2.
I've tested the build on i386 and can confirm the binary builds.
However, the test suite issue exists here as well.  On amd64 the
full test suite is passing but on i386 I get:

    cd debian/tests && PATH=/build/diamond-aligner-0.9.32/obj-i686-linux-gnu:/usr/sbin:/usr/bin:/sbin:/bin sh diamond-calls
    + mktemp -d
    + TESTDIR=/tmp/tmp.Lr402xf8yU
    + diamond blastp --threads 1 --db test/C.faa.diamond --query test/E.faa --out /tmp/tmp.Lr402xf8yU/E.faa.vs.C.faa.diamond -e 1e-05 --outfmt 6 --quiet --sensitive
    + diamond blastp --threads 1 --db test/E.faa.diamond --query test/C.faa --out /tmp/tmp.Lr402xf8yU/C.faa.vs.E.faa.diamond -e 1e-05 --outfmt 6 --quiet --sensitive
    + diamond blastp --threads 1 --db test/C.faa.diamond --query test/L.faa --out /tmp/tmp.Lr402xf8yU/L.faa.vs.C.faa.diamond -e 1e-05 --outfmt 6 --quiet --sensitive
    + diamond blastp --threads 1 --db test/L.faa.diamond --query test/C.faa --out /tmp/tmp.Lr402xf8yU/C.faa.vs.L.faa.diamond -e 1e-05 --outfmt 6 --quiet --sensitive
    Error: vector::_M_default_append

Any idea what might be wrong here?
Kind regards, Andreas.

**Comment by bbuchfink** [comment]
I don't think Diamond runs on 32 bit platforms. Could you just remove the 32 bit build?

**Comment by tillea** [comment]
On Thu, Apr 30, 2020 at 12:17:00PM -0700, Benjamin Buchfink wrote:
> I don't think Diamond runs on 32 bit platforms. Could you just remove the 32 bit build?
The issue exists on **some** 64 Bit architectures for instance on ppc64 - see end of this log:

  https://buildd.debian.org/status/fetch.php?pkg=diamond-aligner&arch=ppc64&ver=0.9.32-2&stamp=1588280875&raw=0
