### ISSUE TITLE
Query produces low evalue hits by blastp - but fails by diamond

### ISSUE THREAD

**Issue by 000generic** [bbuchfink/diamond#349]
I'm testing diamond for a pipeline but it is failing relative to blastp for a sequence that blastp has no trouble finding hits for.  I understand Diamond can be less sensitive than Blastp - but I assumed these failures would be for obvious challenging sequences - so I'm not understanding why this is happening in this case, as it seems easy for blastp to find hits with very low evalues for the protein.

I built blast and diamond protein databases of the same sequences - gene models for ~1500 genomes across the tree of life.

I believe I'm using similar settings in blastp and diamond:

diamond blastp --query test-sequences --db all-sequences-AA.dmnd --threads 30 --out diamond-report_test-sequences --outfmt 6 --max-target-seqs 10 --max-hsps 1 --evalue 0.0000000001 --more-sensitive

blastp -query test-sequences -db all-sequences-AA -num_threads 30 -out blast-report_test-sequences -outfmt 6  -max_target_seqs 10 -max_hsps 1 -evalue 0.0000000001

Their output when blasted with the same two sequences (cuttlefish reflectin and octopus piezo) is:

**Blastp output:**
sepia-reflectin bobtailSquid-Esco-8465  84.342  281     36      3       1       277     1       277     8.32e-145       424
sepia-reflectin bobtailSquid-Esco-20932 80.836  287     42      4       6       289     1       277     6.82e-144       412
sepia-reflectin bobtailSquid-Esco-5867  78.231  294     47      5       1       291     150     429     2.29e-138       404

octopus-piezo   octopus-Obim-2482       100.000 2096    0       0       1       2096    1       2096    0.0     4343
octopus-piezo   octopus-Obim-2473       99.571  2096    1       1       1       2096    1       2088    0.0     4319
octopus-piezo   octopus-Obim-2480       99.475  2096    8       1       1       2096    1       2093    0.0     4316

**Diamond output:**
octopus-piezo   octopus-Obim-2482       100.0   2096    0       0       1       2096    1       2096    0.0e+00 3959.5
octopus-piezo   octopus-Obim-2473       99.6    2096    1       1       1       2096    1       2088    0.0e+00 3937.1
octopus-piezo   octopus-Obim-2480       99.5    2096    8       1       1       2096    1       2093    0.0e+00 3934.4

The piezo sequence is very long - while the reflectin sequence is shorter:

>sepia-reflectin
MNRFMNRYRPMFNNMHNNMYNNMYRGRYRGMMEPMSRMTMDFQGRYMDSQGRMVDPRYYD
YYGRWNDYDRYYGKSMFNYGWMMDGDRYNNYYRWMDFPERYMDMSGYQMDMYGRWMDMQG
RHCNPFNQWGHNRYGQSFNYNYGRNMFYPERWMDMSNYSMDMQGRYMDRWGRHCNPFSQN
MNWYGRYWNYPGYNNYYYNRHMYYPERYFDMSNWQMDMQGRWMDMQGRHNNPYWYNWYGR
QMYYPYQNNWYGRWDYPGMDYSNWQMDMQGRWMDMQGRYMDPWMSDYSYNN

The databases included octopus and bobtail squid genomes - so it makes sense that blastp successfully find hits for both of the query sequences, as they are from cephalopods. It's not clear to me why Diamond does not find hits for the reflectin sequence - given that the blastp hits for reflectin have such low evalues.  Diamond does find hits for the octopus piezo sequence - so it does seem like the cephalopod genomes are present in the Diamond database.

Any ideas why Diamond might be failing in this case - or is it hard to tell / likely a sensitivity issue due to the different methods under the hood of Diamond vs Blast?  Are there any features of the sequence that look like they might be problematic for Diamond - just so I have a sense of what to look for?

Thank you!

**Comment by bbuchfink** [comment]
This happens due to repeat masking. Using the tantan repeat masker, your sequence looks like this:
```
>sepia-reflectin
MNRFMnryrpmfnnmhnnmynnmyrgryrgMMEPMSRMTMDFQGRYMDSQ
GRMVDPRYYDYYGRWNDYDRYYGKSMFnygwmmdgdrynnyyrwmdFPER
YMDMSGYQmdmygrwmdmqgrHCNPFNQWGHNRYGQSFNYNYGRNMFYPE
RWMDMSNYSMdmqgrymdrwgrhcnpfsqnmnwygrywnypgynnyyynr
hmyyperyfdmsnwqmdmqgrwmdmqgrHNNPYWYNWYGRQMYYpyqnnw
ygrWDYPGMDYsnwqmdmqgrwmdmqgrymdpWMSDYSYNN
```

You can find more info here: http://cbrc3.cbrc.jp/~martin/tantan/

The masking can be disabled using `--masking 0`.
