### ISSUE TITLE
Error: Invalid taxonomic rank

### ISSUE THREAD

**Issue by 473021677** [bbuchfink/diamond#352]
Hello:

I intend to use the commond "diamond makedb --threads 16 --in db.faa --taxonmap prot.accession2taxid --taxonnodes taxdump/nodes.dmp --taxonnames taxdump/names.dmp --db diamond/db" to compile the GTDB database manually. The files nodes.dmp and names.dmp were generated using the python script "gtdb_to_taxdump".  But the program terminated abnormally and reported the error "Error: Invalid taxonomic rank". So I compared the file "nodes.dmp" with the correct file (nodes(ref107).dmp) within one pre-compiled test database "ref107", and I found that they had much difference. Therefore, the file "nodes.dmp" was probably the reason. 
Could you help me solve this problem? I have appended the files. Thanks.

[names.dmp.txt](https://github.com/bbuchfink/diamond/files/4677427/names.dmp.txt)
[nodes.dmp.txt](https://github.com/bbuchfink/diamond/files/4677437/nodes.dmp.txt)
[names(ref107).dmp.txt](https://github.com/bbuchfink/diamond/files/4677444/names.ref107.dmp.txt)
[nodes(ref107).dmp.txt](https://github.com/bbuchfink/diamond/files/4677446/nodes.ref107.dmp.txt)
[gtdb_to_taxdump.txt](https://github.com/bbuchfink/diamond/files/4677475/gtdb_to_taxdump.txt)
[nohup.log](https://github.com/bbuchfink/diamond/files/4677482/nohup.log)

Best regards

**Comment by bbuchfink** [comment]
The problem in your nodes.dmp file is that "domain" is not a valid taxonomic rank.

**Comment by 473021677** [comment]
Thanks for your help very much. My problem has been solved.

**Comment by 473021677** [comment]
Hello:
     I have used the commond "diamond makedb --threads 16 --in db.faa --taxonmap prot.accession2taxid --taxonnodes taxdump/nodes.dmp --taxonnames taxdump/names.dmp --db diamond/db" to compile the GTDB database manually. When I look into the log.txt file, I have one question. There are 64033 taxonomy nodes in the nodes.dmp file, but it shows "64034 taxonomy nodes processed" in the log.txt file. And there's only one node assigned to "no rank", but  it shows two nodes are assigned to "no rank" in the log.txt file. I don't know if there's something wrong with it. If you could help, I really appreciate. I have used diamond v0.9.32 and appended the files. Thanks.

Best regards
[log.txt](https://github.com/bbuchfink/diamond/files/6582992/log.txt)
[names.dmp.txt](https://github.com/bbuchfink/diamond/files/6582994/names.dmp.txt)
[nodes.dmp.txt](https://github.com/bbuchfink/diamond/files/6582995/nodes.dmp.txt)

**Comment by bbuchfink** [comment]
This is nothing to worry about, diamond creates a node with index 0 that does not appear in the files but is counted here.

**Comment by 473021677** [comment]
Thanks for your help.

**Comment by LR-2021** [comment]
Hi, 
I am having a similar problem creating a diamondb. 

$ diamond makedb -p 16 --in reference_proteomes.fasta.gz --taxonmap reference_proteomes.taxid_map --taxonnodes $TAXDUMP/nodes.dmp --taxonnames $TAXDUMP/names.dmp -d reference_proteomes.dmnd

nodes.dmp latest version

1) (diamond version 0.9.30) I first get this message 
....
Loading taxonomy...  [85.706s]
Accession mappings = 81466730
Loading taxonomy nodes...  [0.353s]
Error: Invalid taxonomic rank.

2) (diamond version 2.1.8) Then I tried to install the latest Diamond release and run locally and I get this message:

....
Accession parsing rules triggered for database seqids (use --no-parse-seqids to disable):
 UniRef prefix  0
gi|xxx| prefix  0
   xxx| prefix  226782039
   |xxx suffix  226782039
   .xxx suffix  0
  :PDB= suffix  0

Loading taxonomy mapping file... Error: Accession mapping file header has to be in one of these formats:
accession       accession.version       taxid   gi
accession.version       taxid

Could be is there an issue in the latest nodes.dmp?

Thank you for your support.

**Comment by chenhuag** [comment]
> Thanks for your help very much. My problem has been solved.
Hello, I have encountered the same problem as you, ,would like to ask you how to solve it?

**Comment by chenhuag** [comment]
> Hello:
> 
> I intend to use the commond "diamond makedb --threads 16 --in db.faa --taxonmap prot.accession2taxid --taxonnodes taxdump/nodes.dmp --taxonnames taxdump/names.dmp --db diamond/db" to compile the GTDB database manually. The files nodes.dmp and names.dmp were generated using the python script "gtdb_to_taxdump". But the program terminated abnormally and reported the error "Error: Invalid taxonomic rank". So I compared the file "nodes.dmp" with the correct file (nodes(ref107).dmp) within one pre-compiled test database "ref107", and I found that they had much difference. Therefore, the file "nodes.dmp" was probably the reason. Could you help me solve this problem? I have appended the files. Thanks.
> 
> [names.dmp.txt](https://github.com/bbuchfink/diamond/files/4677427/names.dmp.txt) [nodes.dmp.txt](https://github.com/bbuchfink/diamond/files/4677437/nodes.dmp.txt) [names(ref107).dmp.txt](https://github.com/bbuchfink/diamond/files/4677444/names.ref107.dmp.txt) [nodes(ref107).dmp.txt](https://github.com/bbuchfink/diamond/files/4677446/nodes.ref107.dmp.txt) [gtdb_to_taxdump.txt](https://github.com/bbuchfink/diamond/files/4677475/gtdb_to_taxdump.txt) [nohup.log](https://github.com/bbuchfink/diamond/files/4677482/nohup.log)
> 
> Best regards


Hello, I have encountered the same problem as you, ,would like to ask you how to solve it?

**Comment by davidbio** [comment]
So apparently, the NCBI renamed **superkingdom** to **domain** in one of their latest releases.
taxdmp_2024-11-01.zip still shows domain.

![Image](https://github.com/user-attachments/assets/1d7478cb-1f99-42c8-93ce-e837dd1c0020)

Do they change the naming from time to time? What is going on?

**Comment by DarrenObbard** [comment]
We have the same problem ..... Is this a permanent change, or an accidental one? Could diamond be made robust to it?

**Comment by davidbio** [comment]
Make domain superkingdom again!

<img src="https://github.com/user-attachments/assets/374498e7-5ee6-4e56-b001-d6990a14b33c" width="200">

In the meanwhile, you can use `sed -i 's/domain/superkingdom/g nodes.dmp'` as a workaround.

**Comment by DarrenObbard** [comment]
Ha! yes, - except that this is a diamond command that is being run int eh middle of someone else baroque SnakeMake pipeline, which I would rather not have  to edit!

**Comment by davidbio** [comment]
That was what I was thinking.
Happy to help!

**Comment by DarrenObbard** [comment]
FYI: "This is a permanent change reflecting necessary changes based on the relevant
codes of nomenclature." 
https://ncbiinsights.ncbi.nlm.nih.gov/2024/06/04/changes-ncbi-taxonomy-classifications/

**Comment by schmeltzy** [comment]
Came across this same issue today building a db- thanks for the workaround @davidbio ! Is this an easy fix @bbuchfink ?

**Comment by bbuchfink** [comment]
It should be possible to just add "domain" and "realm" as ranks in the next release, if that helps.

**Comment by CWYuan08** [comment]
> It should be possible to just add "domain" and "realm" as ranks in the next release, if that helps.

Dear @bbuchfink , I am having the same issue, how could this be resovled? 
Many thanks!

Best,
CW

**Comment by bbuchfink** [comment]
@CWYuan08 Like this probably until I provide a patch: https://github.com/bbuchfink/diamond/issues/866
