### ISSUE TITLE
Error writing file diamond-analysis2/diamond-5ed4bfc7-31.tmp. Disk full?

### ISSUE THREAD

**Issue by sunettevos** [bbuchfink/diamond#353]
Good day

I am using diamond blastp to search for proteins and then map them to pathways. I am using diamond version 0.9.14 on a windows 10, 64-bit operating system. I have already generated .daa files, but I also want to generate .xml files. I have most of the .xml files, however, I am struggling to generate the last 4 .xml files. The command I used: $ /usr/bin/diamond blastp -q filename.fa -d /home/database/nr.dmnd -o filename.xml -f 5 -p 12. 

This command worked fine for all the other .xml files. However, with the last 4 files, I get the following error from the same command: Error writing file diamond-analysis2/diamond-5ed4bfc7-31.tmp. Disk full? I understand this is a space issue somewhere. Once I got this issue, I did the following: $ df -h. I used this to get empty directories. I then created a directory on empty disk space and export this directory using $ export TMPDIR='/data'. I checked that the environment is correct using $ echo $TMPDIR. After I did this, I used the same diamond command as above, but I get the same error message. Any help on how to solve this will be highly appreciated. There is 160gb of free memory on my computer available. 

Regards
Sunette

**Comment by bbuchfink** [comment]
It means you don't have enough free disk space in your output directory. You say you run on Windows but you use Linux commands? What precisely is your execution environment?

**Comment by sunettevos** [comment]
Good day

All the Linux commands are executed in the PuTTY software on my computer.

Regards
Sunette

**Comment by bbuchfink** [comment]
So you are connecting remotely to a Linux machine? You need to put the output file into a directory with enough free space (Diamond does not use TMPDIR).

**Comment by sunettevos** [comment]
Yes, I am connecting remotely to a Linex machine. I will ask the other people working on the same partitions where my directories are located to remove any unwanted files to free up some space in the directories I am working on and then try again. Thank you for the help on this. 

Regards
Sunette
