### ISSUE TITLE
CMake Error from docker build

### ISSUE THREAD

**Issue by rcedgar** [bbuchfink/diamond#355]
Running this command with the Dockerfile in an otherwise empty directory:

`docker build -t diamond .`

I get this error:  

`CMake Error: The source directory "/opt/diamond" does not appear to contain CMakeLists.txt.
Specify --help for usage, or press the help button on the CMake GUI.`

**Comment by bbuchfink** [comment]
I can't reproduce the error, building the image worked for me. What is your execution environment?

I have also uploaded an image for the latest version to docker hub: `docker pull buchfink/diamond:latest`

**Comment by rcedgar** [comment]
Ubuntu 18.04. I'm a docker novice, I just copy the Dockerfile to an empty directory and run 

`docker build -t diamond .`

FYI I'm trying to implement diamond for this petabyte-scale metagenomics search for Coronaviruses: [Serratus](https://github.com/ababaian/serratus). I was able to get the binary so I'm able to test it, looks promising so far.

**Comment by bbuchfink** [comment]
You have to put the whole repo into the directory, not just the docker file.

Great to hear that my tool is being used for this project. Don't hesitate to contact me again if there's anything else I can do to help.

**Comment by rcedgar** [comment]
Great thanks., Sorry for the newbie blunder.
