### ISSUE TITLE
Enable "salltitles" option

### ISSUE THREAD

**Issue by tomck** [bbuchfink/diamond#36]
https://github.com/bbuchfink/diamond/blob/master/src/main.cpp#L98

It looks like the code is there but not implemented yet, I tested to see if it was a hidden feature but no luck. Having this feature would be amazing.

**Comment by bbuchfink** [comment]
Ok, I will look into this.

**Comment by bbuchfink** [comment]
This has been added in the latest version.

**Comment by tomck** [comment]
@bbuchfink does this require re-running the initial diamond or can it be used on existing .daa output files? I tried it for outputting the blast tab delimited output and while it did not complain about --salltitles it did not add the titles to the output. diamond v0.7.12.61

**Comment by bbuchfink** [comment]
You need to rerun diamond. The full titles are not written to the daa file by default.
