### ISSUE TITLE
technical issues on diamond view 

### ISSUE THREAD

**Issue by marco91sol** [bbuchfink/diamond#360]
Dear all, 

I launched diamond blastx and I obtained file.daa. 

Then, I tried to run the following command with no positive result: 
$diamond view --daa $diamond_output.daa -o $final_output -f tab
#####
#CPU threads: 128
Loading subject IDs...  [0.00122s]
Scoring parameters: (Matrix=custom Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 560292
DB sequences used = 2233
DB letters = 201357942
#Target sequences to report alignments for: 25
Generating output... Unexpected end of file.
terminate called after throwing an instance of 'std::runtime_error'
  what():  Unexpected end of file.
Aborted (core dumped)####

How can I solve that? 

Thanks for your support!

**Comment by bbuchfink** [comment]
There is currently a bug in view. It will be fixed in the next release, or you can compile using this commit: a0a9cd37b5b44e47e021fbcf7ab114db71eff677

**Comment by bbuchfink** [comment]
It should be fixed in the latest release.
