### ISSUE TITLE
HUMAnN3 diamond problem

### ISSUE THREAD

**Issue by nankaiwolf** [bbuchfink/diamond#361]
In HUMAnN3 I use diamond 0.9.24.125 to align uniref databases: uniref50_annotated_v201901, uniref50_ec_filtered_v201901, uniref90_annotated_v201901. However, uniref90_ec_filtered_v201901 does not work out. It is said, Database was built with a different version of Diamond and is incompatible. 
So which version of diamond do I choose to use?

**Comment by bbuchfink** [comment]
The database is format version 0 and Diamond v0.8.38 is the latest to support it. I recommend converting it to the current format. Download the old version here: https://github.com/bbuchfink/diamond/releases/tag/v0.8.38

Then use the latest version of Diamond like this: `/old/diamond getseq -d uniref90_201901.dmnd | /new/diamond makedb -d out_db` to convert it to the current format.

**Comment by nankaiwolf** [comment]
Thank you for reply, I forgot to use the getseq to reconstruct the dmnd file. I will try this at once. 
But due to my NUC computer, this will take a long time.

**Comment by nankaiwolf** [comment]
Everything goes fine, thank you very much for your help!
