### ISSUE TITLE
Issue in running diamond

### ISSUE THREAD

**Issue by Manimaran-nema** [bbuchfink/diamond#363]
diamond v0.9.14.115 | by Benjamin Buchfink <buchfink@gmail.com>
Licensed under the GNU AGPL <https://www.gnu.org/licenses/agpl.txt>
Check http://github.com/bbuchfink/diamond for updates.

#CPU threads: 4
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
#Target sequences to report alignments for: 25
Temporary directory: 
Opening the database...  [2.5e-05s]
Opening the input file...  [0.021681s]
Opening the output file...  [6.3e-05s]
Loading query sequences...  [2.98312s]
Masking queries...  [103.096s]
Building query seed set...  [0.104871s]
Algorithm: Double-indexed
Building query histograms...  [11.2808s]
Allocating buffers...  [9.4e-05s]
Loading reference sequences...  [30.4971s]
Building reference histograms...  [6.06886s]
Allocating buffers...  [5.9e-05s]
Initializing temporary storage...  [0.001919s]
Processing query chunk 0, reference chunk 0, shape 0, index chunk 0.
Building reference index... Killed

I am getting this ... can you help me in fixing it...

**Comment by bbuchfink** [comment]
This error message usually means that the program ran out of memory. How much memory does your system have? What is your command line? You can reduce the memory usage by setting a lower number for `-b`, for example `-b1`.
