### ISSUE TITLE
diamond view killed

### ISSUE THREAD

**Issue by 473021677** [bbuchfink/diamond#364]
Hello,
I have used diamond to compared the genes against egNOG database. But when I typed  "diamond view -a genes.daa -f tab -o genes.m8", it always terminated abnormally. The log file included "#CPU thresholds 5, killed". And when I used the test file which included only five genes, everything was OK. I don't know how t solve it and needed your help. The diamond version was 0.9.32. Thanks very much.

Best regards

**Comment by bbuchfink** [comment]
There was a bug in diamond view. Please try to use the latest version.

**Comment by 473021677** [comment]
Thanks for your help very much. The problem has been fixed.
&nbsp;
&nbsp;
------------------&nbsp;Original&nbsp;------------------
From: "Benjamin Buchfink"; 
Date: 2020年6月23日(星期二) 凌晨1:56
To: "bbuchfink/diamond"; 
Cc: "473021677"; "Author"; 
Subject: Re: [bbuchfink/diamond] diamond view killed (#364)

&nbsp;


 
There was a bug in diamond view. Please try to use the latest version.
