### ISSUE TITLE
diamond: error: no such option: --daa

### ISSUE THREAD

**Issue by Manimaran-nema** [bbuchfink/diamond#367]
diamond view --daa output.daa --out H_indica.cogs -f tab
Usage: diamond [options]
diamond: error: no such option: --daa

I want to use diamond for cog package...
I am getting this error...please help me to solve it

**Comment by bbuchfink** [comment]
It seems like you are using a very old version. Can you try with the current one?

**Comment by Manimaran-nema** [comment]
how to update it sir?

**Comment by bbuchfink** [comment]
See here: http://www.diamondsearch.org/index.php?pages/installation/

**Comment by Manimaran-nema** [comment]
Thank you so much...issues solved
