### ISSUE TITLE
Segmentation fault diamond 0.9.35 eggnogdb

### ISSUE THREAD

**Issue by MichWeb75** [bbuchfink/diamond#368]
The current DIAMOND version (0.9.35) appears to have problems with the eggnog database provided by (http://eggnog5.embl.de/download/emapperdb-5.0.0/eggnog_proteins.dmnd.gz  )

`diamond blastx -d eggnog_proteins.dmnd -q   test.fna --more-sensitive`

I have done several tests to narrow down the issue :

* appears only with --sensitive and --more-sensitive
* does not appear on earlier DIAMOND version 0.9.14
* does appear on any kind of input 
* also appears when I recompile `(diamond makedb)` on my local server

Here is an example input :
```
>A00517:211:H35ACESXE:3:1643:12689:12602 1:N:0:ACAGTG
GACGTGACGAACCACGAAAGGCTTCGGGGAGCAGTAAGTAAGCAATGATCCGGAGATATC
CGAATGGGGGAACCCAATACCGTGAGGTATTATCATTAACTGTTAAGGTTAATGAAGGAA
GACGCAGTGAACTGAAACATCTAAGTAGCTGCAGGAAGAGAAAGAAAAATCGATTTCCCA
AGTAG
```

**Comment by bbuchfink** [comment]
I have reproduced the crash, it seems to only occur when running in query-indexed mode that is triggered for small query files. Could you try again using `--algo 0`?

**Comment by MichWeb75** [comment]
Indeed this works and produces the output table. Thank you for the rapid reply!
