### ISSUE TITLE
Taxids missing for specific accessions

### ISSUE THREAD

**Issue by cmtom** [bbuchfink/diamond#370]
Hello,

I am having an issue where most of my diamond blastx output contains staxids but for certain accessions they are missing. I attached an example of my results. 

I used this command to make the database with all the latest NCBI files and the 6/30/20 Diamond release:
./diamond makedb --taxonmap prot.accession2taxid.gz --taxonnodes nodes.dmp --taxonnames names.dmp --in nr.fa -d nrtax3

I used this command to run Diamond:
diamond blastx -d "/projects/academic/cl243/Bear_NGS/modulefiles/diamond_aligner/nrtax3" --evalue 1e-1 --max-target-seqs 1 -q 6final.genome6byz.scf.fasta --outfmt 6 qseqid staxids bitscore stitle sseqid pident length mismatch gapopen qstart qend sstart send evalue -o 6byz.vs.nt.mts1.hsp1.1e1.diamond_blastx.txt 

Neither command returned an error and I noticed that the missing staxids are indeed present in the names.dmp file from NCBI, so I am a bit confused why I am getting this result. Do you have any suggestions/ideas? 

Thank you,
Crystal

[DiamondResults.txt](https://github.com/bbuchfink/diamond/files/4938401/DiamondResults.txt)

**Comment by bbuchfink** [comment]
I have checked the latest `prot.accession2taxid.gz` mapping file from NCBI and it does not contain a taxon mapping for `MCI16385` for instance, this is why Diamond is not able to provide a taxon id.

**Comment by LoreVE** [comment]
Hi, I'm experiencing a similar issue where a lot of Diamond hits do not have a taxon mapping (which leaves many of my sequences without taxonomical classifications...). Indeed the accessions are not in the protein.accessions2taxid file, but why? They are in the nr.gz file downloaded at the same moment? Anyone any idea what might be the issue (download was successful)? The accessions I checked all have a species name in their "name", so it is not that they don't know what organism they come from... Some examples include EBQ5447486 MUU05764 HCK95632 MTV74636 HBJ05119 EFC7838400 EEX7493492 EET2704668 EAR8049589 HCK95079 MUU05608 EFL9941439 HAH90916, but I have 100s of them...

**Comment by bbuchfink** [comment]
It looks like NCBI is now providing a more complete mapping file: ftp://ftp.ncbi.nlm.nih.gov/pub/taxonomy/accession2taxid/prot.accession2taxid.FULL.gz

Support for this file has been included in the latest commit: 4f624b019ea209e24be9836dad0c3ccd581c9bb3
