### ISSUE TITLE
Segmentation fault (core dumped) with Diamond 2.0.0

### ISSUE THREAD

**Issue by MatDal** [bbuchfink/diamond#371]
Hello,
I am having an issue with Diamond blastx version 2.0.0 (installed using conda).
When I run the command:

"lbzip2 -dc -n 30 test.fastq.bz2 | diamond blastx --quiet --query-gencode 11 -d nr -p 30 --ultra-sensitive --evalue 1000 --max-target-seqs 0 --id 5 -o test_mapping"

or 

"lbzip2 -dc -n 30 test.fastq.bz2 | diamond blastx  --quiet --query-gencode 11 -d nr -p 30 --more-sensitive --evalue 1000 --max-target-seqs 0 --id 5 -o test_mapping"

Diamond returns this error:
"Segmentation fault (core dumped)"

excluding the --ultra-sensitive or --more-sensitive parameters, Diamond ends correctly.

Thanks

**Comment by bbuchfink** [comment]
I have tried running some data with these parameters without an error occuring. Can you tell me what kind of input data that is, if you used any of the taxonomy parameters when building the database, your hardware and OS, and at what stage the error occured (console output)?

**Comment by MatDal** [comment]
-As input I am using sequencing data:
https://www.ebi.ac.uk/ena/data/view/SAMEA3134415

-For the database, no I'm not using taxonomy parameters.
diamond makedb --in xxx -d nr

-OS info:

DISTRIB_ID = Ubuntu
DISTRIB_RELEASE = 18:04
DISTRIB_CODENAME bionic =
DISTRIB_DESCRIPTION = "Ubuntu 18.04.3 LTS"

-Error:

Processing query block 0, reference block 0, shape 63, index chunk 0.
Building reference seed array ... [0.012s]
Building query seed array ... [0.051s]
Computing hash join ... [0.008s]
Building seed filter ... [0.094s]
Searching alignments ... [0.008s]
Deallocating buffers ... [0s]
Clearing query masking ... [0.252s]
Computing alignments ... munmap_chunk (): invalid pointer
Aborted (core dumped)

**Comment by bbuchfink** [comment]
I have tried reproducing this, using the latest NR database, the file ERR675367.fastq.gz as query, and the same parameters, but I'm still not getting the error. Can you tell me what query file exactly you are using or make your data available to me?

**Comment by bbuchfink** [comment]
I can reproduce the error now and will try to provide a fix in the next days.

**Comment by bbuchfink** [comment]
It should be fixed in the latest release.
