### ISSUE TITLE
diamond 2.0.0 in macosx, comp-based-stats 0

### ISSUE THREAD

**Issue by gaboentropy** [bbuchfink/diamond#373]
Hi,

Diamond 2.0.0 only works with comp-based-stats 0 with the fast mode. Modes with the word sensitive fail with a segmentation fault.

Command:
% zcat GenomeData/GCF_000005845.faa.gz |  diamond blastp --db DB/GCF_900747785 --sensitive --comp-based-stats 0  
Query file parameter (--query/-q) is missing. Input will be read from stdin.
zsh: done                zcat GenomeData/GCF_000005845.faa.gz | 
zsh: segmentation fault  diamond blastp --db DB/GCF_900747785 --sensitive --comp-based-stats 0

**Comment by gaboentropy** [comment]
(It works all right without specifying the comp-based-stats, but I want 0 there)

**Comment by bbuchfink** [comment]
Thanks for reporting this, I will try to provide a fix in the next days.

If you run diamond with `-v`, it will print a message like this: `CPU features detected: ssse3 popcnt sse4.1 avx2`. It will use AVX2 if detected on the host.

**Comment by bbuchfink** [comment]
It should be fixed in the latest release.

**Comment by gaboentropy** [comment]
It worked all right for all sensitivity options. Thanks!
