### ISSUE TITLE
Run half interrupted

### ISSUE THREAD

**Issue by fjptwenger** [bbuchfink/diamond#374]
I use diamond  to align fasta file to nr database，the command ：
**diamond blastx -d ~/software/diamond/nr.dmnd  --query t07.fa --out t07.tab** 
that run interrupted after hours later,and the command print error : 
```
Building seed filter...  [0.033s]
Searching alignments...  [1.406s]
Processing query block 0, reference block 54, shape 1, index chunk 3.
Building reference seed array...  [1.3s]
Building query seed array...  [0.6s]
Computing hash join...  [0.773s]
Building seed filter...  [0.033s]
Searching alignments...  [1.34s]
Deallocating buffers...  [0.122s]
Clearing query masking...  [0.064s]
Opening temporary output file...  [0.01s]
Computing alignments...  [84.936s]
Deallocating reference...  [0.08s]
Loading reference sequences...  [0s]
Deallocating buffers...  [0.045s]
Joining output blocks...  [93.539s]
Writing unaligned queries...  [0.398s]
Error: Invalid sequence file format
369s]
Error: Invalid sequence file format
```
"Invalid sequence file format " is nr database? right?  the nr was download from NCBI and check md5,also build by **diamond makedb **, so I don't know where to find the  Invalid format and what error format will it be. 

and  the error occurred in the middle of the run，the tail of t07.tab  file like,you can see the **k119%** ， stop after the error ：
```
k119_33485	WP_007212711.1	92.2	766	54	2	3814	1535	1	766	0.0e+00	1401.0
k119_33485	CDB72192.1	92.0	766	55	1	3814	1535	1	766	0.0e+00	1401.0
k119_%                                                                                                          
```
So this error confuses me and I need your help。

**Comment by bbuchfink** [comment]
From the output I would assume you are also using the `--un` option? Are you also using `--unfmt`? Also, what is your version of Diamond?

**Comment by fjptwenger** [comment]
you are right，--un t07.not  --unfmt  101   
version ：diamond v2.0.0.138 (C) Max Planck Society for the Advancement of Science

**Comment by bbuchfink** [comment]
`--unfmt` needs to be either `fasta` or `fastq`.

**Comment by fjptwenger** [comment]
my fault，thanks！
