### ISSUE TITLE
stuck at Loading reference sequences... for more than 12 hours

### ISSUE THREAD

**Issue by mijiandui** [bbuchfink/diamond#376]
(diamond2.0.1) ubuntu@ubuntu-server:/media/ubuntu/f0dddfea-0944-4c77-9973-120e8a99d7b5/MGEs$ diamond blastx -d /media/ubuntu/Elements/nr2.0.1 -p 35 -q YYW_MGE.fa  -f 6 qseqid qlen sseqid sallseqid slen qstart qend sstart send evalue bitscore score length pident nident mismatch positive gapopen gaps ppos staxids sscinames sskingdoms skingdoms sphylums stitle salltitles --evalue 1e-5 --taxonlist 2,2157,10239,4751 -o YYW_MGE_nr.m8 --masking 0 --max-target-seqs 10
diamond v2.0.1.139 (C) Max Planck Society for the Advancement of Science
Documentation, support and updates available at http://www.diamondsearch.org

#CPU threads: 35
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
Temporary directory: 
Opening the database...  [0.134s]
#Target sequences to report alignments for: 10
Reference = /media/ubuntu/Elements/nr2.0.1.dmnd
Sequences = 257100652
Letters = 92592102759
Block size = 2000000000
Loading taxonomy mapping...  [6.958s]
Loading taxonomy nodes...  [0.047s]
Building taxonomy filter...  [17.699s]
Loading taxonomy names...  [0.422s]
Opening the input file...  [0.001s]
Opening the output file...  [0s]
Loading query sequences...  [0.014s]
Building query seed set...  [0.047s]
The host system is detected to have 270 GB of RAM. It is recommended to increase the block size for better performance using these parameters: -b8 -c1
Algorithm: Query-indexed
Building query histograms...  [0.005s]
Allocating buffers...  [0s]
Loading reference sequences...

**Comment by mijiandui** [comment]
when i delete--taxonlist 2,2157,10239,4751, it works. I don't know why.

**Comment by bbuchfink** [comment]
There was an inefficiency in the code. Try using this commit: 00f75c477395efdf0861ffb5a3e2d5b93d57ac14

**Comment by bbuchfink** [comment]
The fix has now also been included in the latest release.

**Comment by mijiandui** [comment]
> The fix has now also been included in the latest release.

Thanks a lot!
