### ISSUE TITLE
Diamond threading behaves differently on similar systems...

### ISSUE THREAD

**Issue by intendo** [bbuchfink/diamond#38]
We have an MPI cluster with nodes with 16 cores and the following processors:
  model name	: Intel(R) Xeon(R) CPU E5-2670 0 @ 2.60GHz
and another MPI cluster with nodes with 24 cores and the following processors:
  model name	: Intel(R) Xeon(R) CPU E5-2670 v3 @ 2.30GHz

We run the same slurm job on both clusters but on the latter cluster, diamond runs 24 threads on 24 cores which performs as expected. On the former cluster, diamond runs 16 threads on 1 core.

Is there a command line option or environment variable that is causing the former cluster to multithread on a single core rather than spreading the threads across all the cores?

**Comment by bbuchfink** [comment]
Does it run 16 threads in total or 16 threads per core, so 256 threads in total? What happens if you manually set the number of threads (option -p)?

**Comment by intendo** [comment]
It behaves the same with the –p option or without the –p option.
NOTE: Both clusters are MPI-based and we are running the exact same sbatch job. The job starts 3 nodes and on each node, we have a c++ program that slices up the large input file into 3 smaller files and fires off diamond using a system() call.

We have isolated the job so that it only runs on a single node to eliminate as many variables as possible.

On the systems with 16 cores, we run the command:
  watch -n 5 -d “ps -C diamond -L -o pmem -o pcpu”

And we see 16 threads running. We also run top and display all the cpus (the "1" option in top) and see that only 1 core (cpu) is at 100% and the other cores are mostly idle and the load on the system is a little over 1. (This is bad, slow, and wastes most of the resources of the system.

Conversely, we run watch and top on the other system that has 24 cores and we see 24 thread running and 24 cores running at 90-100% with a load of 2400 on the system. (This is what we expect and want to happen).

We have talked with the cluster managers and they are scratching their heads too.

My guess is that there is a configuration file on the slurm nodes that has a directive or sets an environment variable that controls the thread policy of setting the thread affinity to one core or allows the threads to span cores.

Any help would be greatly appreciated.

FYI, we reverse engineered BLASTn to use alternative alphabets and scoring matrices to map cyber data into sequences that could be compared using the BLAST algorithms. So we have deep respect for the work you have done with Diamond.

Thanks in advance,

Darren Curtis

**Comment by bbuchfink** [comment]
Sorry but I have no idea how this happens. The program launches its threads with standard system calls and never sets thread affinities so I don't see how it could be causing this.

**Comment by intendo** [comment]
It turns out that there are OMP and/or MPI environment variables that can affect thread affinity strategies.
We were able to "purge" all the variables and only add in the ones we need and the diamond code now spreads the threads across all the cores.

Hopefully you can pass this on if someone if the future has the same problem.

**Comment by bbuchfink** [comment]
I will certainly remember. Glad that it's working now.
