### ISSUE TITLE
ungapped alignment and xdrop

### ISSUE THREAD

**Issue by YiJessePi** [bbuchfink/diamond#381]
Hi,
I'm trying to execute diamond blastp in a comparable way to ncbi blastp.
1) I wondering if there is a flag similar to blastp ungapped in order to perform ungapped alignment only.

2) x-drop, as I understand should be similar to ncbi blast x-dropoff which get value in bits. Can you explain what it expect to get? I didn't find it in the documentation.
My very best.
Jesse

**Comment by bbuchfink** [comment]
Answered here: http://www.diamondsearch.org/index.php?threads/diamond-blastp-produce-longer-alignments-with-lower-identity-than-ncbi-blast.98/
