### ISSUE TITLE
hit_id have problem in  diamond blastx outfmt 5 

### ISSUE THREAD

**Issue by feihongloveworld** [bbuchfink/diamond#382]
hi sir:
        @bbuchfink 

        when use **diamond blastp**,the hit_id as below:
```
        <Hit_id>gnl|BL_ORD_ID|2742</Hit_id>
        <Hit_def>3145_5003 | model_type_id: 40292 | pass_bitscore: 1000 | MCR-7.1</Hit_def>
```
 
        when use **diamond blastx** ,the hit_id as below:

```
        <Hit_id>145_5003</Hit_id>
        <Hit_def>| model_type_id: 40292 | pass_bitscore: 1000 | MCR-7.1</Hit_def>
```
        the result is ok Used blastx directly， so diamond blastx has bug ？？
please，

**Comment by bbuchfink** [comment]
I can't explain how there could be a difference between blastp and blastx like this. Please double check that you are using the same version of diamond for both calls with identical parameters.

**Comment by feihongloveworld** [comment]
> I can't explain how there could be a difference between blastp and blastx like this. Please double check that you are using the same version of diamond for both calls with identical parameters.

yes ,  reason is diff version diamond ........
