### ISSUE TITLE
Error: Tokenizer Exception/makedb/taxonmap

### ISSUE THREAD

**Issue by zeynepkurtw** [bbuchfink/diamond#384]
Hi,

I'm trying to do a blastp search by limiting the NR database with --taxonlist on diamond v2.0.2.140. However, I'm getting the error below, when I run makedb:
```
Loading sequences...  [9.312s]
Masking sequences...  [3.548s]
Writing sequences...  [1.357s]
Writing accessions...  [2.337s]
Hashing sequences...  [0.374s]
Loading sequences...  [0s]
Writing trailer...  [8.264s]
Loading taxonomy...  [529.105s]
Accession mappings = 865804414
Loading taxonomy nodes...  [0.058s]
Error: Tokenizer Exception
```
The command I've been using is the following:
` diamond makedb --in nr -d nr --taxonmap prot.accession2taxid --taxonnodes nodes.dmp`

and I'm getting the following error while I'm trying to run diamond blastp:

```
diamond blastp --query DMC1.faa  --db nr --out DMC1_NR.blastp --taxonlist tax_id.txt --outfmt 0  --threads 30 --evalue 0.00001 -b 20 --more-sensitive
diamond v2.0.2.140 (C) Max Planck Society for the Advancement of Science
Documentation, support and updates available at http://www.diamondsearch.org

#CPU threads: 30
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
Temporary directory: 
Opening the database...  [0.102s]
Error: Incomplete database file. Database building did not complete successfully.
```

any help would be appreciated!

Regards,
Zeynep

**Comment by zeynepkurtw** [comment]
You're right when I run the command with only the taxon id, not the list I don't get any error. I didn't make any difference in the tokenizer error, tough. I guess, now it's all right.
Thank you!

**Comment by grafau** [comment]
Hi, Had the same error.
For me the issue was that just like for the prot.accession2taxid.FULL.gz , I did not unzip the taxdmp.zip either.
taxdmp.zip contains multiple files and needs to be unzipped before use.
HTH

**Comment by Upe-ndra** [comment]
Hi, I am getting the same error (Error: Tokenizer Exception)
while running diamond makedb command. Have you got any solution for this please? 
I downloaded the latest nodes.dmp from NCBI. Below is the command I am using and the error.
Thank you

Command: 
diamond makedb -p 16 --in reference_proteomes.fasta.gz --taxonmap reference_proteomes.taxid_map --taxonnodes ../taxdump/nodes.dmp -d reference_proteomes.dmnd

Error:
Writing sequences...  [0.802s]
Writing accessions...  [3.045s]
Hashing sequences...  [0.319s]
Loading sequences...  [0s]
Writing trailer...  [0.777s]
Loading taxonomy...  [0.159s]
Error: Tokenizer Exception

**Comment by Upe-ndra** [comment]
I was following Blobtoolkit's instructions to create database [3. Fetch and format the UniProt database](https://blobtoolkit.genomehubs.org/install/)
changing 
```
echo "accession\taccession.version\ttaxid\tgi" > reference_proteomes.taxid_map
```
to 
```
echo -e accession'\t'accession.version'\t'taxid'\t'gi > reference_proteomes.taxid_map
```
solved the Tokenizer error above.
