### ISSUE TITLE
returning the first hits passing the evalue threshold?

### ISSUE THREAD

**Issue by rzhao-2** [bbuchfink/diamond#386]
Currently, setting --max-target-seqs to x returns the best x hits that passes the evalue threshold. However, is there a way to set DIAMOND to return the first hits instead even if they are not necessarily the best hits?

**Comment by bbuchfink** [comment]
No, there is no such option and the Diamond algorithm does not easily afford it, either. For best performance, the closest thing you can do is use the options `-k1 --ext-chunk-size 32`.
