### ISSUE TITLE
Improved performance and sensitivity

### ISSUE THREAD

**Issue by RamilNurtdinov** [bbuchfink/diamond#389]
Hi. 
Originally we used DIAMOND v0.9.32 version. For one particular sample we got 33,847 alignment. 
I have attached corresponding "diamond.log.09.32.txt" file. 
Target hits (stage 0) = 52345
Target hits (stage 5) = 33847

In DIAMOND v0.9.33 you improved performance and sensitivity, however we obtained less alignments with the same parameters and input. I have attached corresponding "diamond.log.09.33.txt" file. 
Target hits (stage 0) = 19708
Target hits (stage 5) = 11728

We next switched to DIAMOND v2.0.4. We used --ultra-sensitive. All the rest and input were the same, "diamond.log.20.04.txt"
We obtained lesser alignments than before
Target hits (stage 0) = 16880
Target hits (stage 4) = 8516

For instance we lost read with reported identity of 58.5% over 67.1% length.
I made reproducible example with two reads. Second read, at least in out hand, aligns only with version 32.

Can you investigate this issue of missed alignment?

Ramil
.

[diamond.log.09.32.txt](https://github.com/bbuchfink/diamond/files/5195573/diamond.log.09.32.txt)
[diamond.log.09.33.txt](https://github.com/bbuchfink/diamond/files/5195574/diamond.log.09.33.txt)
[diamond.log.20.04.txt](https://github.com/bbuchfink/diamond/files/5195575/diamond.log.20.04.txt)
[test.gz](https://github.com/bbuchfink/diamond/files/5195825/test.gz)

**Comment by bbuchfink** [comment]
For these very weak hits on short queries, you need to set a lower ungapped score cutoff, like so: `--short-query-ungapped-bitscore 15`

**Comment by RamilNurtdinov** [comment]
Thank you very much. Now I got 35,420 alignments that is perfectly fits with 33,848 obtained by v.09.32
This option --short-query-ungapped-bitscore is not documented so may be other users experience the same problem.

Can you clarify. You recommend the value of 15 for me, works fine. My read length is 75 nucleotides. What is your recommendation for 50 nucleotides reads.

**Comment by bbuchfink** [comment]
Sorry for the lack of documentation, I know I still need to work on that. I don't know the optimal value there, you have to try for yourself.

**Comment by RamilNurtdinov** [comment]
Thank you Benjamin for your help.
I am closing the issue, it is done.
