### ISSUE TITLE
Caching reference masking

### ISSUE THREAD

**Issue by fullama** [bbuchfink/diamond#390]
Hi!
Is it possible to cache the masking of the reference? or even better could the diamonddb be "pre-masked" on creation?
if its the same masking that happens every time it would save a bit of compute...

**Comment by bbuchfink** [comment]
It would be possible and used to work like that. I changed it so I can change the masking more flexibly without forcing users to rebuild the database. Overall it should not use that much time, but I know this solution is not ideal and I will try to provide something better in the future.

**Comment by fullama** [comment]
ah ok that makes sense... I guess it could be an option when building the database - that way it would be our own fault if we have to rebuild ;)

I only brought it up as it eats into the time when you have a large db and small query - which i know is not what diamond was made for but thats the situation i find myself in.. diamond works best for what we are doing..
Thanks for all your hard work on it btw... its a really nice tool.

**Comment by bbuchfink** [comment]
I neglected to mention that there is an easy workaround. You can use the tantan repeat masker to mask your database FASTA. Use these options for tantan: `-p -s 0.9 -x X`. Build your Diamond db with the masked FASTA then, and run Diamond using `--masking 0` to disable runtime masking. Your query will not be masked then, but it is fine to mask only the query or only the database.

**Comment by fullama** [comment]
..i had thought about doing that but i thought that if the query wasnt masked, the output might be wrong.. but if you are saying its enough to mask the fasta/db then thats great.. ill do that so.. thanks for your advice!
