### ISSUE TITLE
Questions of multiple alignments per each query sequence? 

### ISSUE THREAD

**Issue by liusoil** [bbuchfink/diamond#391]
Hi Everyone:

I'm aligning non-rRNA sequencing data (from SortMeRNA output) using DIAMOND. However, for the output, there are multiple aligned proteins for each non-rRNA sequence, although some of the non-rRNA sequence only has one aligned protein (see attached pix). Does this mean the default e-value of DIAMOND is too low (0.001)? But it seems impossible to change the default e-values too. Any suggestions would be greatly appreciated. 

 [
![WechatIMG77](https://user-images.githubusercontent.com/43674563/93162657-370f9a80-f6e3-11ea-8bbb-65f1fbe9736d.png)
](url)

**Comment by bbuchfink** [comment]
I don't think the evalue is too low (you can change it using the option `-e`). But if you want to get only the best hit for each query, use the option `-k1`.

**Comment by liusoil** [comment]
Thanks very much for the help. I will  give it a try. 

I have another question: for Makedb options, the -- taxonmap, --taxonnodes don't work. The --taxonlist also doesn't work as input options. Could you help with this? Thank you.

**Comment by bbuchfink** [comment]
Please show me your command line and the console output of Diamond when running makedb.

**Comment by liusoil** [comment]
> I don't think the evalue is too low (you can change it using the option `-e`). But if you want to get only the best hit for each query, use the option `-k1`.

I used the '-k 1', but there still many multiple alignments per query sequence, see below. Any further suggestions? 

C00124:579:CE42AANXX:7:2315:14994:71321	WP_131321754.1	95.1	41	2	0	128	6	344	384	4.2e-11	76.6
C00124:579:CE42AANXX:7:2315:8163:71542	WP_063196438.1	92.3	52	4	0	157	2	135	186	1.6e-20	108.2
C00124:579:CE42AANXX:7:2315:14437:65570	TNV75980.1	63.2	57	21	0	174	4	13	69	6.0e-10	73.2
C00124:579:CE42AANXX:7:2315:16388:65675	XP_006682303.1	82.9	35	6	0	105	1	399	433	1.5e-09	71.2
C00124:579:CE42AANXX:7:2315:6659:71919	WP_153589679.1	73.5	49	13	0	149	3	7	55	2.6e-12	80.9
C00124:579:CE42AANXX:7:2315:13352:71719	MBA3697537.1	63.0	46	17	0	139	2	43	88	9.9e-08	65.5
C00124:579:CE42AANXX:7:2315:5791:71811	ODU59322.1	70.0	50	15	0	150	1	100	149	1.1e-10	75.5
C00124:579:CE42AANXX:7:2315:10976:66089	MAS95786.1	88.9	36	4	0	114	7	2	37	3.2e-08	67.4
C00124:579:CE42AANXX:7:2315:11779:66427	BAL08091.1	90.7	43	4	0	3	131	50	92	5.9e-13	82.8
C00124:579:CE42AANXX:7:2315:12289:66329	AJK29683.2	97.8	45	1	0	138	4	253	297	1.3e-15	91.7
C00124:579:CE42AANXX:7:2315:1155:72212	WP_153291310.1	96.5	57	2	0	172	2	528	584	1.0e-22	115.5
C00124:579:CE42AANXX:7:2315:1544:72479	AOA64832.1	95.0	40	2	0	121	2	40	79	1.7e-11	77.8
C00124:579:CE42AANXX:7:2315:1544:72479	AOA64832.1	94.7	38	2	0	115	2	118	155	2.5e-10	73.9
C00124:579:CE42AANXX:7:2315:1544:72479	AOA64832.1	94.7	38	2	0	115	2	194	231	2.5e-10	73.9
C00124:579:CE42AANXX:7:2315:1544:72479	AOA64832.1	94.7	38	2	0	115	2	270	307	2.5e-10	73.9
C00124:579:CE42AANXX:7:2315:1544:72479	AOA64832.1	94.7	38	2	0	115	2	346	383	2.5e-10	73.9
C00124:579:CE42AANXX:7:2315:6817:71572	SOZ71339.1	76.5	34	8	0	18	119	36	69	2.0e-05	57.8
C00124:579:CE42AANXX:7:2315:5672:72268	HFM60777.1	59.6	47	19	0	143	3	512	558	1.8e-07	64.7
C00124:579:CE42AANXX:7:2315:17821:64882	OJW57500.1	51.8	56	27	0	2	169	560	615	4.6e-07	63.5
C00124:579:CE42AANXX:7:2315:20552:64857	ARF11598.1	65.3	49	17	0	155	9	1086	1134	2.5e-10	74.3
C00124:579:CE42AANXX:7:2315:20552:64857	ARF11598.1	65.3	49	17	0	155	9	1677	1725	9.7e-10	72.4
C00124:579:CE42AANXX:7:2315:20552:64857	ARF11598.1	63.3	49	18	0	155	9	1164	1212	9.7e-10	72.4
C00124:579:CE42AANXX:7:2315:20552:64857	ARF11598.1	62.7	51	19	0	161	9	1603	1653	1.3e-09	72.0
C00124:579:CE42AANXX:7:2315:20552:64857	ARF11598.1	63.3	49	18	0	155	9	1647	1695	1.3e-09	72.0
C00124:579:CE42AANXX:7:2315:20552:64857	ARF11598.1	63.3	49	18	0	155	9	2055	2103	1.3e-09	72.0
C00124:579:CE42AANXX:7:2315:20552:64857	ARF11598.1	63.3	49	18	0	155	9	2049	2097	1.3e-09	72.0
C00124:579:CE42AANXX:7:2315:20552:64857	ARF11598.1	63.3	49	18	0	155	9	1206	1254	1.7e-09	71.6
C00124:579:CE42AANXX:7:2315:20552:64857	ARF11598.1	60.8	51	20	0	161	9	1429	1479	2.2e-09	71.2

**Comment by bbuchfink** [comment]
What you see here are multiple HSPs contained in the same target. To change that, use `--max-hsps 1`.

**Comment by liusoil** [comment]
> What you see here are multiple HSPs contained in the same target. To change that, use `--max-hsps 1`.

I used the Diamond v0.8.9, which doesn't have the --max-hsps option. New just installed the v2.04 in the linux cluster. However, the output error message shows up: "Computing alignments... /home/xl17a/.lsbatch/1601087278.16357.shell: line 17:  8149 **Illegal instruction**". The output files have ZERO kb……could you help troubleshoot what's wrong? Thank you. 

diamond 2.0.4 is located under /share/pkg/diamond/2.0.4
diamond v2.0.4.142 (C) Max Planck Society for the Advancement of Science
Documentation, support and updates available at http://www.diamondsearch.org
 
#CPU threads: 64
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
Temporary directory: /nl/uma_kristen_deangelis/xiaojun/diamond/diamond_out/flash_diamond
Opening the database...  [0.967s]
#Target sequences to report alignments for: 1
Reference = /nl/uma_kristen_deangelis/xiaojun/diamond/raw_db/nr.dmnd
Sequences = 316065422
Letters = 113949932586
Block size = 2000000000
Opening the input file...  [1.302s]
Opening the output file...  [0.104s]
Loading query sequences...  [38.373s]
Masking queries...  [51.495s]
Building query seed set...  [0.16s]
ESC[1;33mThe host system is detected to have 542 GB of RAM. It is recommended to increase the block size for better performance using these parameters : -b12
 -c1
ESC[0;39mAlgorithm: Double-indexed
Building query histograms...  [15.34s]
Allocating buffers...  [0.001s]
Loading reference sequences...  [30.445s]
Masking reference...  [57.09s]
Initializing temporary storage...  [0.137s]
Building reference histograms...  [29.108s]
Allocating buffers...  [0s]
Processing query block 1, reference block 1/57, shape 1/2, index chunk 1/4.
Building reference seed array...  [17.899s]
Building query seed array...  [9.293s]
Computing hash join...  [5.916s]
Building seed filter...  [0.294s]
Searching alignments...  [16.948s]
Processing query block 1, reference block 1/57, shape 1/2, index chunk 2/4.
Building reference seed array...  [18.739s]
Building query seed array...  [9.823s]
Computing hash join...  [5.814s]
Building seed filter...  [0.293s]
Searching alignments...  [15.496s]
Processing query block 1, reference block 1/57, shape 1/2, index chunk 3/4.
Building reference seed array...  [19.157s]
Building query seed array...  [10.034s]
Computing hash join...  [5.855s]
Building seed filter...  [0.288s]
Searching alignments...  [14.681s]
Processing query block 1, reference block 1/57, shape 1/2, index chunk 4/4.
Building reference seed array...  [18.739s]
Building query seed array...  [9.823s]
Computing hash join...  [5.814s]
Building seed filter...  [0.293s]
Searching alignments...  [15.496s]
Processing query block 1, reference block 1/57, shape 1/2, index chunk 3/4.
Building reference seed array...  [19.157s]
Building query seed array...  [10.034s]
Computing hash join...  [5.855s]
Building seed filter...  [0.288s]
Searching alignments...  [14.681s]
Processing query block 1, reference block 1/57, shape 1/2, index chunk 4/4.
Building reference seed array...  [17.794s]
Building query seed array...  [9.207s]
Computing hash join...  [5.828s]
Building seed filter...  [0.295s]
Searching alignments...  [13.98s]
Processing query block 1, reference block 1/57, shape 2/2, index chunk 1/4.
Building reference seed array...  [17.221s]
Building query seed array...  [8.544s]
Computing hash join...  [5.586s]
Building seed filter...  [0.276s]
Searching alignments...  [13.751s]
Processing query block 1, reference block 1/57, shape 2/2, index chunk 2/4.
Building reference seed array...  [18.34s]
Building query seed array...  [8.985s]
Computing hash join...  [5.636s]
Building seed filter...  [0.273s]
Searching alignments...  [13.016s]
Processing query block 1, reference block 1/57, shape 2/2, index chunk 3/4.
Building reference seed array...  [18.914s]
Building query seed array...  [9.28s]
Computing hash join...  [5.602s]
Building seed filter...  [0.27s]
Searching alignments...  [13.135s]
Processing query block 1, reference block 1/57, shape 2/2, index chunk 4/4.
Building reference seed array...  [17.476s]
Building query seed array...  [8.593s]
Computing hash join...  [5.651s]
Building seed filter...  [0.27s]
Searching alignments...  [12.844s]
Deallocating buffers...  [0.015s]
Clearing query masking...  [0.644s]
Opening temporary output file...  [0.03s]
Computing alignments... /home/xl17a/.lsbatch/1601087278.16357.shell: line 17:  8149 Illegal instruction     diamond blastx -k 1 --max-hsps 1 -d /nl/uma_kristen_deangelis/xiaojun/diamond/raw_db/nr -q /nl/uma_kristen_deangelis/xiaojun/sortmerna/flash_out/sample1_non_rRNA.fastq -o /nl/uma_kristen_deangelis/xiaojun/diamond/diamond_out/flash_diamond/sample1_flash.m8

**Comment by bbuchfink** [comment]
Sorry for the late reply. The binary does not seem to be compatible with your system. Please try compiling Diamond from source.

**Comment by bbuchfink** [comment]
Illegal instruction errors have been fixed in the v2.0.6 release.
