### ISSUE TITLE
Issues with creating diamond nr database (Error: Invalid taxonomic rank.)

### ISSUE THREAD

**Issue by JustineCharon** [bbuchfink/diamond#392]
Hi,

I would like to create a diamond database using the NCBI protein nr database. When the makedb command is used : 
`diamond makedb --in nr.gz --db nr --taxonmap prot.accession2taxid.gz --taxonnodes nodes.dmp`
I get the following error =
`Error: Invalid taxonomic rank.
`
I suspect the error comes from the nodes.dmp file but I don;t know how to resolve this as I am using the one from the NCBI (ftp://ftp.ncbi.nlm.nih.gov/pub/taxonomy/taxdmp.zip)

Thanks for your help,

Best regards

Justine

**Comment by bbuchfink** [comment]
What diamond version are you using? NCBI has recently added new ranks, so you may need to update to a later version.

**Comment by JustineCharon** [comment]
Hi,

Thanks for your reply, I use v.0.9.32.

Kind regards

Justine

**Comment by bbuchfink** [comment]
Support for the new ranks has been added since v0.9.35.
