### ISSUE TITLE
makedb - Error writing file tmpdir/diamond-tmp-xz4Aj1

### ISSUE THREAD

**Issue by phrh** [bbuchfink/diamond#394]
Hello, 
I am running the following command

diamond makedb -p 16 --in reference_proteomes.fasta.gz --taxonmap reference_proteomes.taxid_map --taxonnodes /home/paula/Desktop/Datos/taxdump/nodes.dmp -d reference_proteomes.dmn --tmpdir tmpdir --parallel-tmpdir tmpdir

I get the following output and error

Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
Database input file: reference_proteomes.fasta.gz
Opening the database file...  [0s]
Loading sequences...  [9.051s]
Masking sequences...  [4.751s]
Writing sequences...  [0.979s]
Writing accessions...  [2.287s]
Hashing sequences...  [0.297s]
Loading sequences...  [9.069s]
Masking sequences...  [5.044s]
Writing sequences...  [1.005s]
Writing accessions... Input/output error
 [2.662s]
Error: Error writing file tmpdir/diamond-tmp-xz4Aj1

I added the --tmpdir tmpdir --parallel-tmpdir tmpdir trying to solve this issue but it didn't. Do you have any ideas what can it be?

Thank you

**Comment by bbuchfink** [comment]
Please make sure that the directory `tmpdir` exists and that there is enough free space left on the hard drive.

**Comment by phrh** [comment]
I did. the error came up before I assigned a tmpdir, for this reason I gave a directory with enough space

**Comment by bbuchfink** [comment]
Does the error occur without using the taxonomy parameters? Have you tried running the same call on another system?

**Comment by phrh** [comment]
I tried without the taxonomy parameters and It works.

How much space should I have left on the device? I have 1.3 T free, on a  FAT32 partition, do you think this might be a problem?

**Comment by bbuchfink** [comment]
No, it should not be a problem. It would help if you could try the same call on a different system, because I have no idea about this error right now unfortunately.

**Comment by phrh** [comment]
Ok thank you

**Comment by phrh** [comment]
Solved, there was a problem with the permissions on the partition.
