### ISSUE TITLE
Fasta output for blastp

### ISSUE THREAD

**Issue by johanneswerner** [bbuchfink/diamond#395]
Is it possible to obtain a protein fasta file as output for a `diamond blastp` run? Is this information maybe available in the daa format? Thank you very much.

**Comment by bbuchfink** [comment]
I would recommend using the tabular output format with the fields `full_qseq` or `full_sseq` depending on what you need, then pipe the output into a script to convert the tabular format into FASTA.

**Comment by johanneswerner** [comment]
Oh perfect, thank you for your help!
