### ISSUE TITLE
Error: Invalid character (@/64) in sequence

### ISSUE THREAD

**Issue by lfaller** [bbuchfink/diamond#4]
Hi Diamond team,

I am getting an "invalid character in sequence" error while running diamond blastx. As input, I gave it a fasta file with 76730390 records. I am also using these options: --evalue 1.0 --threads 1 --max-target-seqs 20 --sensitive

Does the error message mean there is an invalid character in the fasta sequence, or is it asking for a fastq sequence (where the sequence ID should start with an @ symbol)? I did try and grep for an "@" symbol in the input data and couldn't find one. Does the "64" refer to the ASCII value of "@"? Or is it a position in the input sequence? (my sequences are 100 bp long). I am running diamond v0.7.8.57 if that helps.

Thanks for any advice!
~Lina

**Comment by bbuchfink** [comment]
Hi,

yes it means that the @ was found in a sequence, and the 64 refers to the ascii value. If you say there is no @ in the file, I can't explain this error. Can you maybe try to reproduce it with a smaller file?

Benjamin

**Comment by lfaller** [comment]
Hi Benjamin,

My bad, I found the instance of the @ character, it was due to a malformed fastq sequence!
Sorry about the false alarm :)

~Lina
