### ISSUE TITLE
database naming issue .dmnd

### ISSUE THREAD

**Issue by jjkoehorst** [bbuchfink/diamond#40]
I was trying to make a simple wrapper either via the terminal and/or via galaxy.
Knowing that galaxy names its files as dataset_xxx.dat I was trying to perform a blast against such a name.dat

However diamond automatically adds the extension while the file does not have the dmnd extension which obviously results in a error opening file.

Error: function Input_stream::Input_stream(const string &, bool) line 75. Error opening file dataset_xxx.dat.dmnd

Is there a way to tell diamond what the file name is without diamond appending the dmnd extension? Otherwise I need to copy the database file every time a blast is performed...

**Comment by bbuchfink** [comment]
No there's no way to do that (other than edit the source code) but I can include it in the next version.

**Comment by bbuchfink** [comment]
Version 0.8.1 now has a switch --no-auto-append.
