### ISSUE TITLE
Failure of diamond blastx to find protein when protein is in NR db, but not in a db by itself.

### ISSUE THREAD

**Issue by swollen** [bbuchfink/diamond#403]
Below is a nucleotide sequence that ncbi-blastx matches to POS81882 with a score of ~90 and evalue of ~e-19, when the database is NR. When I use a diamond db of NR, the diamond blastx command does not find anything to match this sequence.   I have tried the ultra-sensitive setting, as well as others, to no avail.  Any ideas for what is going on?  I have about 2,000 other sequences that behave similarly, though this one has the best ncbi blastx score.

Thanks
Bill

>Cluster-81052.0        472
ATAAACTTCTACTGTACGCCCAAGTGGTACTGTTCCATGTGATATTTCTTGATTAGGACCTCTGAAAATTCAATAAGCAGCCCCTGCAGTCCCTTCTTTATTCAATGCACCGTCTGTACGAATTGTCAGGGCAAGTATCTTATCAGCTCGTGAAGCGGCTCATTTGCAATACTTGTTTAATGTATTTTCACGGCCAGTGGCACCAATCTCGGCTTTATTTGCTGTTCTATCGAAACTGAGCTACGGTGGATAATCCAACTATTGGGAGAGTTCTATGGTCTATAATTCTCTGATCCACTTAAAGTGTGATGAATTCCATCGGCCATGAAGTGGATGTTTGGGTCTGCCGCGGCTATACGAGCTGCGAAACGATCACGATATCGATTCAGCAAAAATTGAGGTACCCTATCCAGTTTCTCTAAGGAGTGCAGAAGTGGCAGTAGTCTTTTATACTGGTAGAACAGCGCGTGCG

**Comment by bbuchfink** [comment]
Have you tried disabling the repeat masking (`--masking 0`)?

**Comment by swollen** [comment]
Yes, but still no match.

**Comment by swollen** [comment]
I got confused yesterday, but after thorough review my original question stands as is (except the ncbi-blastx score and evalue were 213 and 1.16e-66).
I do not get a diamond result with or without repeat masking, when I use the entire NR.dmnd database.
I do get a diamond result if I make the target db with just the one target sequence (POS81882).  The score is then 38.9 with or without the –masking 0 flag.


From: Spollen, William
Sent: Sunday, November 8, 2020 7:18 AM
To: bbuchfink/diamond <reply@reply.github.com>; bbuchfink/diamond <diamond@noreply.github.com>
Cc: Author <author@noreply.github.com>
Subject: RE: [bbuchfink/diamond] Failure of diamond blastx to find protein when protein is in NR db, but not in a db by itself. (#403)

Yes, but still no match.

**Comment by bbuchfink** [comment]
The reason are the stop codons that cause diamond to mask short ORFs of length < 40. Use `--min-orf 1` to get the full hit.
