### ISSUE TITLE
I accidentally deleted the daa file but I have the job output file

### ISSUE THREAD

**Issue by raquelnb** [bbuchfink/diamond#404]
Hello, I don't know what happened, I guess I deleted it but I can't find the .daa file being generated by DIAMOND of one of my files, and it should be there cause the other jobs that I sent at the same time already have their .daa file. So I was wondering if there's any chance I could remake the daa file from the output file of the job? The thing is that this job has been running for more than a week already, so I wouldn't like to waste that time in running again the job.
Thank you

**Comment by bbuchfink** [comment]
Maybe the job hasn't finished yet, you should double check that. Also check the log if there were any errors. But if the job failed, there is no other way than to run it again, sorry.
