### ISSUE TITLE
Slow reference build/index steps on AWS Linux instance 

### ISSUE THREAD

**Issue by hillan141** [bbuchfink/diamond#405]
Hi,

Appreciate any troubleshooting suggestions.  Running on Amazon EC2 linux box, using precompiled diamond binary, diamond version indicated in log below.  Moving reference db to most performant available disk did not accelerate searches.  Any ideas on speeding this search?  Are these multi-hour searches expected for ~116 queries of typical bacterial proteins?

Thanks!

Query = protein fasta, 116 e.coli proteins
Reference DB: 21,841,973 proteins; 8.4 Gbase; 8.7GB in size

Command line: 

diamond blastp -d  $DB \
 -q $INFAA --more-sensitive -e 0.001 -o $OUTFILE --top 3 \
  --threads 2 -b4.0 -c4 2>&1 | tee $LOGFILE

I find that searches take multiple hours, with vast majority of time in the reference-related steps like:

Loading reference sequences...  [21.3338s]
Building reference histograms...  [259.657s]
...
Building reference index...  [59.3039s]
... etc.

== Full log output

diamond v0.9.24.125 | by Benjamin Buchfink <buchfink@gmail.com>
Licensed under the GNU GPL <https://www.gnu.org/licenses/gpl.txt>
Check http://github.com/bbuchfink/diamond for updates.
 
#CPU threads: 2
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
Temporary directory: 
Opening the database...  [0.032976s]
Percentage range of top alignment score to report hits: 3
Opening the input file...  [0.0008s]
Opening the output file...  [5.9e-05s]
Loading query sequences...  [0.001181s]
Masking queries...  [0.006181s]
Building query seed set...  [0.001011s]
Algorithm: Double-indexed
Building query histograms...  [0.004083s]
Allocating buffers...  [9.7e-05s]
Loading reference sequences...  [21.3338s]
Building reference histograms...  [259.657s]
Allocating buffers...  [7.4e-05s]
Initializing temporary storage...  [0.000416s]
Processing query chunk 0, reference chunk 0, shape 0, index chunk 0.
Building reference index...  [54.1804s]
Building query index...  [0.001762s]
Building seed filter...  [1.34921s]
Searching alignments...  [1.52066s]
Processing query chunk 0, reference chunk 0, shape 0, index chunk 1.
Building reference index...  [59.3039s]
Building query index...  [0.001992s]
Building seed filter...  [1.33278s]
Searching alignments...  [1.43462s]
Processing query chunk 0, reference chunk 0, shape 0, index chunk 2.
Building reference index...  [62.5873s]
Building query index...  [0.001963s]
Building seed filter...  [1.3384s]
Searching alignments...  [1.48379s]
Processing query chunk 0, reference chunk 0, shape 0, index chunk 3.
Building reference index...  [52.6666s]
Building query index...  [0.001405s]
Building seed filter...  [1.31334s]
Searching alignments...  [1.39403s]
Processing query chunk 0, reference chunk 0, shape 1, index chunk 0.
Building reference index...  [51.7188s]
Building query index...  [0.00283s]
Building seed filter...  [1.31179s]
Searching alignments...  [1.3451s]
Processing query chunk 0, reference chunk 0, shape 1, index chunk 1.
Building reference index...  [58.4144s]
Building query index...  [0.001149s]
Building seed filter...  [1.32431s]
Searching alignments...  [1.40854s]
Processing query chunk 0, reference chunk 0, shape 1, index chunk 2.
Building reference index...  [61.5494s]
Building query index...  [0.001711s]
Building seed filter...  [1.29603s]
Searching alignments...  [1.30253s]
Processing query chunk 0, reference chunk 0, shape 1, index chunk 3.
Building reference index...  [52.1053s]
Building query index...  [0.001279s]
Building seed filter...  [1.30479s]
Searching alignments...  [1.34051s]
Processing query chunk 0, reference chunk 0, shape 2, index chunk 0.
Building reference index...  [52.2624s]
Building query index...  [0.001177s]
Building seed filter...  [1.34008s]
Searching alignments...  [1.46163s]
Processing query chunk 0, reference chunk 0, shape 2, index chunk 1.
Building reference index...  [59.4296s]
Building query index...  [0.001106s]
Building seed filter...  [1.34172s]
Searching alignments...  [1.46618s]
Processing query chunk 0, reference chunk 0, shape 2, index chunk 2.
Building reference index...  [62.285s]
Building query index...  [0.001387s]
Building seed filter...  [1.30886s]
Searching alignments...  [1.36409s]
Processing query chunk 0, reference chunk 0, shape 2, index chunk 3.
Building reference index...  [52.8039s]
Building query index...  [0.001587s]
Building seed filter...  [1.33698s]
Searching alignments...  [1.46048s]
Processing query chunk 0, reference chunk 0, shape 3, index chunk 0.
Building reference index...  [51.9975s]
Building query index...  [0.001367s]
Building seed filter...  [1.32011s]
Searching alignments...  [1.38374s]
Processing query chunk 0, reference chunk 0, shape 3, index chunk 1.
Building reference index...  [58.9779s]
Building query index...  [0.001561s]
Building seed filter...  [1.33198s]
Searching alignments...  [1.3453s]
Processing query chunk 0, reference chunk 0, shape 3, index chunk 2.
Building reference index...  [62.1615s]
Building query index...  [0.002132s]
Building seed filter...  [1.33119s]
Searching alignments...  [1.36758s]
Processing query chunk 0, reference chunk 0, shape 3, index chunk 3.
Building reference index...  [52.4303s]
Building query index...  [0.000933s]
Building seed filter...  [1.38815s]
Searching alignments...  [1.37973s]
Processing query chunk 0, reference chunk 0, shape 4, index chunk 0.
Building reference index...  [51.7699s]
Building query index...  [0.00172s]
Building seed filter...  [1.29574s]
Searching alignments...  [1.49769s]
Processing query chunk 0, reference chunk 0, shape 4, index chunk 1.
Building reference index...  [58.7066s]
Building query index...  [0.001342s]
Building seed filter...  [1.30092s]
Searching alignments...  [1.40542s]
Processing query chunk 0, reference chunk 0, shape 4, index chunk 2.
Building reference index...  [61.6937s]
Building query index...  [0.001081s]
Building seed filter...  [1.3262s]
Searching alignments...  [1.41582s]
Processing query chunk 0, reference chunk 0, shape 4, index chunk 3.
Building reference index...  [52.2102s]
Building query index...  [0.001525s]
Building seed filter...  [1.35984s]
Searching alignments...  [1.38068s]
Processing query chunk 0, reference chunk 0, shape 5, index chunk 0.
Building reference index...  [52.0043s]
Building query index...  [0.001555s]
Building seed filter...  [1.3359s]
Searching alignments...  [1.3978s]
Processing query chunk 0, reference chunk 0, shape 5, index chunk 1.
Building reference index...  [58.9288s]
Building query index...  [0.00114s]
Building seed filter...  [1.36244s]
Searching alignments...  [1.38528s]
Processing query chunk 0, reference chunk 0, shape 5, index chunk 2.
Building reference index...  [61.7865s]
Building query index...  [0.001386s]
Building seed filter...  [1.28745s]
Searching alignments...  [1.4176s]
Processing query chunk 0, reference chunk 0, shape 5, index chunk 3.
Building reference index...  [52.2953s]
Building query index...  [0.001189s]
Building seed filter...  [1.31551s]
Searching alignments...  [1.32234s]
Processing query chunk 0, reference chunk 0, shape 6, index chunk 0.
Building reference index...  [51.738s]
Building query index...  [0.001559s]
Building seed filter...  [1.35609s]
Searching alignments...  [1.28754s]
Processing query chunk 0, reference chunk 0, shape 6, index chunk 1.
Building reference index...  [58.7257s]
Building query index...  [0.00173s]
Building seed filter...  [1.31244s]
Searching alignments...  [1.30251s]
Processing query chunk 0, reference chunk 0, shape 6, index chunk 2.
Building reference index...  [61.742s]
Building query index...  [0.002273s]
Building seed filter...  [1.3291s]
Searching alignments...  [1.32796s]
Processing query chunk 0, reference chunk 0, shape 6, index chunk 3.
Building reference index...  [52.1161s]
Building query index...  [0.00125s]
Building seed filter...  [1.31302s]
Searching alignments...  [1.25693s]
Processing query chunk 0, reference chunk 0, shape 7, index chunk 0.
Building reference index...  [51.9024s]
Building query index...  [0.001539s]
Building seed filter...  [1.31096s]
Searching alignments...  [1.34579s]
Processing query chunk 0, reference chunk 0, shape 7, index chunk 1.
Building reference index...  [59.2575s]
Building query index...  [0.001576s]
Building seed filter...  [1.3294s]
Searching alignments...  [1.33814s]
Processing query chunk 0, reference chunk 0, shape 7, index chunk 2.
Building reference index...  [61.8171s]
Building query index...  [0.001527s]
Building seed filter...  [1.32046s]
Searching alignments...  [1.35535s]
Processing query chunk 0, reference chunk 0, shape 7, index chunk 3.
Building reference index...  [52.2663s]
Building query index...  [0.001149s]
Building seed filter...  [1.30022s]
Searching alignments...  [1.34329s]
Processing query chunk 0, reference chunk 0, shape 8, index chunk 0.
Building reference index...  [52.1633s]
Building query index...  [0.001774s]
Building seed filter...  [1.30601s]
Searching alignments...  [1.34044s]
Processing query chunk 0, reference chunk 0, shape 8, index chunk 1.
Building reference index...  [59.262s]
Building query index...  [0.001542s]
Building seed filter...  [1.32112s]
Searching alignments...  [1.36484s]
Processing query chunk 0, reference chunk 0, shape 8, index chunk 2.
Building reference index...  [62.4348s]
Building query index...  [0.001698s]
Building seed filter...  [1.35655s]
Searching alignments...  [1.35442s]
Processing query chunk 0, reference chunk 0, shape 8, index chunk 3.
Building reference index...  [52.5214s]
Building query index...  [0.001355s]
Building seed filter...  [1.34455s]
Searching alignments...  [1.32726s]
Processing query chunk 0, reference chunk 0, shape 9, index chunk 0.
Building reference index...  [51.5838s]
Building query index...  [0.000941s]
Building seed filter...  [1.28263s]
Searching alignments...  [1.30054s]
Processing query chunk 0, reference chunk 0, shape 9, index chunk 1.
Building reference index...  [58.403s]
Building query index...  [0.001013s]
Building seed filter...  [1.30611s]
Searching alignments...  [1.25375s]
Processing query chunk 0, reference chunk 0, shape 9, index chunk 2.
Building reference index...  [61.6683s]
Building query index...  [0.001019s]
Building seed filter...  [1.29869s]
Searching alignments...  [1.28296s]
Processing query chunk 0, reference chunk 0, shape 9, index chunk 3.
Building reference index...  [51.8237s]
Building query index...  [0.001269s]
Building seed filter...  [1.28491s]
Searching alignments...  [1.31233s]
Processing query chunk 0, reference chunk 0, shape 10, index chunk 0.
Building reference index...  [52.4117s]
Building query index...  [0.00145s]
Building seed filter...  [1.32275s]
Searching alignments...  [1.35823s]
Processing query chunk 0, reference chunk 0, shape 10, index chunk 1.
Building reference index...  [58.624s]
Building query index...  [0.00112s]
Building seed filter...  [1.31939s]
Searching alignments...  [1.36432s]
Processing query chunk 0, reference chunk 0, shape 10, index chunk 2.
Building reference index...  [62.0695s]
Building query index...  [0.001483s]
Building seed filter...  [1.37423s]
Searching alignments...  [1.37492s]
Processing query chunk 0, reference chunk 0, shape 10, index chunk 3.
Building reference index...  [52.5315s]
Building query index...  [0.000855s]
Building seed filter...  [1.33309s]
Searching alignments...  [1.34431s]
Processing query chunk 0, reference chunk 0, shape 11, index chunk 0.
Building reference index...  [51.6723s]
Building query index...  [0.001179s]
Building seed filter...  [1.35566s]
Searching alignments...  [1.30189s]
Processing query chunk 0, reference chunk 0, shape 11, index chunk 1.
Building reference index...  [58.6377s]
Building query index...  [0.001134s]
Building seed filter...  [1.29614s]
Searching alignments...  [1.31292s]
Processing query chunk 0, reference chunk 0, shape 11, index chunk 2.
Building reference index...  [61.4249s]
Building query index...  [0.001617s]
Building seed filter...  [1.29786s]
Searching alignments...  [1.29254s]
Processing query chunk 0, reference chunk 0, shape 11, index chunk 3.
Building reference index...  [51.8501s]
Building query index...  [0.001522s]
Building seed filter...  [1.3159s]
Searching alignments...  [1.27302s]
Processing query chunk 0, reference chunk 0, shape 12, index chunk 0.
Building reference index...  [51.7632s]
Building query index...  [0.001105s]
Building seed filter...  [1.30323s]
Searching alignments...  [1.3497s]
Processing query chunk 0, reference chunk 0, shape 12, index chunk 1.
Building reference index...  [58.1771s]
Building query index...  [0.001138s]
Building seed filter...  [1.31175s]
Searching alignments...  [1.30541s]
Processing query chunk 0, reference chunk 0, shape 12, index chunk 2.
Building reference index...  [61.3982s]
Building query index...  [0.001242s]
Building seed filter...  [1.28825s]
Searching alignments...  [1.31229s]
Processing query chunk 0, reference chunk 0, shape 12, index chunk 3.
Building reference index...  [51.8252s]
Building query index...  [0.001268s]
Building seed filter...  [1.29887s]
Searching alignments...  [1.27471s]
Processing query chunk 0, reference chunk 0, shape 13, index chunk 0.
Building reference index...  [51.4871s]
Building query index...  [0.00148s]
Building seed filter...  [1.30731s]
Searching alignments...  [1.3498s]
Processing query chunk 0, reference chunk 0, shape 13, index chunk 1.
Building reference index...  [58.2006s]
Building query index...  [0.001088s]
Building seed filter...  [1.30439s]
Searching alignments...  [1.29602s]
Processing query chunk 0, reference chunk 0, shape 13, index chunk 2.
Building reference index...  [61.3123s]
Building query index...  [0.001721s]
Building seed filter...  [1.29625s]
Searching alignments...  [1.34257s]
Processing query chunk 0, reference chunk 0, shape 13, index chunk 3.
Building reference index...  [51.9605s]
Building query index...  [0.00157s]
Building seed filter...  [1.28495s]
Searching alignments...  [1.28797s]
Processing query chunk 0, reference chunk 0, shape 14, index chunk 0.
Building reference index...  [51.5465s]
Building query index...  [0.001525s]
Building seed filter...  [1.32364s]
Searching alignments...  [1.35609s]
Processing query chunk 0, reference chunk 0, shape 14, index chunk 1.
Building reference index...  [58.3436s]
Building query index...  [0.001037s]
Building seed filter...  [1.30979s]
Searching alignments...  [1.327s]
Processing query chunk 0, reference chunk 0, shape 14, index chunk 2.
Building reference index...  [61.4744s]
Building query index...  [0.001206s]
Building seed filter...  [1.31761s]
Searching alignments...  [1.38467s]
Processing query chunk 0, reference chunk 0, shape 14, index chunk 3.
Building reference index...  [52.6531s]
Building query index...  [0.001397s]
Building seed filter...  [1.30981s]
Searching alignments...  [1.3046s]
Processing query chunk 0, reference chunk 0, shape 15, index chunk 0.
Building reference index...  [51.537s]
Building query index...  [0.001501s]
Building seed filter...  [1.29029s]
Searching alignments...  [1.33493s]
Processing query chunk 0, reference chunk 0, shape 15, index chunk 1.
Building reference index...  [58.3115s]
Building query index...  [0.001724s]
Building seed filter...  [1.32018s]
Searching alignments...  [1.29482s]
Processing query chunk 0, reference chunk 0, shape 15, index chunk 2.
Building reference index...  [61.1248s]
Building query index...  [0.00107s]
Building seed filter...  [1.307s]
Searching alignments...  [1.37343s]
Processing query chunk 0, reference chunk 0, shape 15, index chunk 3.
Building reference index...  [51.5996s]
Building query index...  [0.001009s]
Building seed filter...  [1.30281s]
Searching alignments...  [1.31389s]
Deallocating buffers...  [0.842745s]
Opening temporary output file...  [6.4e-05s]
Computing alignments...  [1.84721s]
Deallocating reference...  [0.125047s]
Loading reference sequences...  [20.2281s]
Building reference histograms...  [276.065s]
Allocating buffers...  [9.2e-05s]
Initializing temporary storage...  [0.000362s]
Processing query chunk 0, reference chunk 1, shape 0, index chunk 0.
Building reference index...  [53.263s]
Building query index...  [0.001397s]
Building seed filter...  [1.29998s]
Searching alignments...  [1.37456s]
Processing query chunk 0, reference chunk 1, shape 0, index chunk 1.
Building reference index...  [58.3619s]
Building query index...  [0.000868s]
Building seed filter...  [1.28978s]
Searching alignments...  [1.31185s]
Processing query chunk 0, reference chunk 1, shape 0, index chunk 2.
Building reference index...  [61.2764s]
Building query index...  [0.001161s]
Building seed filter...  [1.34029s]
Searching alignments...  [1.28702s]
Processing query chunk 0, reference chunk 1, shape 0, index chunk 3.
Building reference index...  [51.9179s]
Building query index...  [0.001027s]
Building seed filter...  [1.29744s]
Searching alignments...  [1.2853s]
Processing query chunk 0, reference chunk 1, shape 1, index chunk 0.
Building reference index...  [50.5289s]
Building query index...  [0.001714s]
Building seed filter...  [1.27776s]
Searching alignments...  [1.19487s]
Processing query chunk 0, reference chunk 1, shape 1, index chunk 1.
Building reference index...  [57.2899s]
Building query index...  [0.001289s]
Building seed filter...  [1.26345s]
Searching alignments...  [1.23427s]
Processing query chunk 0, reference chunk 1, shape 1, index chunk 2.
Building reference index...  [60.5549s]
Building query index...  [0.001162s]
Building seed filter...  [1.2662s]
Searching alignments...  [1.1832s]
Processing query chunk 0, reference chunk 1, shape 1, index chunk 3.
Building reference index...  [51.0492s]
Building query index...  [0.001507s]
Building seed filter...  [1.24564s]
Searching alignments...  [1.20646s]
Processing query chunk 0, reference chunk 1, shape 2, index chunk 0.
Building reference index...  [51.4473s]
Building query index...  [0.001554s]
Building seed filter...  [1.31838s]
Searching alignments...  [1.38255s]
Processing query chunk 0, reference chunk 1, shape 2, index chunk 1.
Building reference index...  [58.1882s]
Building query index...  [0.00136s]
Building seed filter...  [1.29704s]
Searching alignments...  [1.27572s]
Processing query chunk 0, reference chunk 1, shape 2, index chunk 2.
Building reference index...  [61.1634s]
Building query index...  [0.002542s]
Building seed filter...  [1.29437s]
Searching alignments...  [1.238s]
Processing query chunk 0, reference chunk 1, shape 2, index chunk 3.
Building reference index...  [51.6041s]
Building query index...  [0.001388s]
Building seed filter...  [1.25743s]
Searching alignments...  [1.23989s]
Processing query chunk 0, reference chunk 1, shape 3, index chunk 0.
Building reference index...  [50.9613s]
Building query index...  [0.00097s]
Building seed filter...  [1.2923s]
Searching alignments...  [1.25638s]
Processing query chunk 0, reference chunk 1, shape 3, index chunk 1.
Building reference index...  [57.904s]
Building query index...  [0.001717s]
Building seed filter...  [1.2759s]
Searching alignments...  [1.20042s]
Processing query chunk 0, reference chunk 1, shape 3, index chunk 2.
Building reference index...  [60.874s]
Building query index...  [0.001512s]
Building seed filter...  [1.32504s]
Searching alignments...  [1.3535s]
Processing query chunk 0, reference chunk 1, shape 3, index chunk 3.
Building reference index...  [51.5101s]
Building query index...  [0.001003s]
Building seed filter...  [1.26026s]
Searching alignments...  [1.21499s]
Processing query chunk 0, reference chunk 1, shape 4, index chunk 0.
Building reference index...  [50.5845s]
Building query index...  [0.002685s]
Building seed filter...  [1.27012s]
Searching alignments...  [1.24933s]
Processing query chunk 0, reference chunk 1, shape 4, index chunk 1.
Building reference index...  [57.377s]
Building query index...  [0.002961s]
Building seed filter...  [1.26609s]
Searching alignments...  [1.21798s]
Processing query chunk 0, reference chunk 1, shape 4, index chunk 2.
Building reference index...  [60.6361s]
Building query index...  [0.001799s]
Building seed filter...  [1.26961s]
Searching alignments...  [1.26229s]
Processing query chunk 0, reference chunk 1, shape 4, index chunk 3.
Building reference index...  [51.2205s]
Building query index...  [0.001721s]
Building seed filter...  [1.26306s]
Searching alignments...  [1.22424s]
Processing query chunk 0, reference chunk 1, shape 5, index chunk 0.
Building reference index...  [50.9384s]
Building query index...  [0.001456s]
Building seed filter...  [1.29082s]
Searching alignments...  [1.24936s]
Processing query chunk 0, reference chunk 1, shape 5, index chunk 1.
Building reference index...  [57.8017s]
Building query index...  [0.001104s]
Building seed filter...  [1.29541s]
Searching alignments...  [1.21167s]
Processing query chunk 0, reference chunk 1, shape 5, index chunk 2.
Building reference index...  [60.856s]
Building query index...  [0.001096s]
Building seed filter...  [1.27656s]
Searching alignments...  [1.31069s]
Processing query chunk 0, reference chunk 1, shape 5, index chunk 3.
Building reference index...  [51.2453s]
Building query index...  [0.001427s]
Building seed filter...  [1.28275s]
Searching alignments...  [1.21551s]
Processing query chunk 0, reference chunk 1, shape 6, index chunk 0.
Building reference index...  [50.6276s]
Building query index...  [0.001171s]
Building seed filter...  [1.26252s]
Searching alignments...  [1.23575s]
Processing query chunk 0, reference chunk 1, shape 6, index chunk 1.
Building reference index...  [57.3319s]
Building query index...  [0.001541s]
Building seed filter...  [1.28566s]
Searching alignments...  [1.19181s]
Processing query chunk 0, reference chunk 1, shape 6, index chunk 2.
Building reference index...  [60.4277s]
Building query index...  [0.001462s]
Building seed filter...  [1.2915s]
Searching alignments...  [1.18906s]
Processing query chunk 0, reference chunk 1, shape 6, index chunk 3.
Building reference index...  [51.0733s]
Building query index...  [0.001157s]
Building seed filter...  [1.28301s]
Searching alignments...  [1.17584s]
Processing query chunk 0, reference chunk 1, shape 7, index chunk 0.
Building reference index...  [50.6038s]
Building query index...  [0.001341s]
Building seed filter...  [1.27682s]
Searching alignments...  [1.26212s]
Processing query chunk 0, reference chunk 1, shape 7, index chunk 1.
Building reference index...  [57.4573s]
Building query index...  [0.001105s]
Building seed filter...  [1.28878s]
Searching alignments...  [1.22062s]
Processing query chunk 0, reference chunk 1, shape 7, index chunk 2.
Building reference index...  [60.3671s]
Building query index...  [0.001776s]
Building seed filter...  [1.3158s]
Searching alignments...  [1.20381s]
Processing query chunk 0, reference chunk 1, shape 7, index chunk 3.
Building reference index...  [51.1743s]
Building query index...  [0.002895s]
Building seed filter...  [1.28308s]
Searching alignments...  [1.22055s]
Processing query chunk 0, reference chunk 1, shape 8, index chunk 0.
Building reference index...  [50.9743s]
Building query index...  [0.001028s]
Building seed filter...  [1.29287s]
Searching alignments...  [1.27486s]
Processing query chunk 0, reference chunk 1, shape 8, index chunk 1.
Building reference index...  [57.9896s]
Building query index...  [0.001737s]
Building seed filter...  [1.28602s]
Searching alignments...  [1.24736s]
Processing query chunk 0, reference chunk 1, shape 8, index chunk 2.
Building reference index...  [60.958s]
Building query index...  [0.001132s]
Building seed filter...  [1.28016s]
Searching alignments...  [1.23603s]
Processing query chunk 0, reference chunk 1, shape 8, index chunk 3.
Building reference index...  [51.5516s]
Building query index...  [0.001417s]
Building seed filter...  [1.26605s]
Searching alignments...  [1.21357s]
Processing query chunk 0, reference chunk 1, shape 9, index chunk 0.
Building reference index... 

<log truncated here, as search is still running>

**Comment by bbuchfink** [comment]
This does not seem untypical to me using only 2 threads. The problem is that the diamond algorithm is not very efficient using such small query files of 116 sequences. You should try to submit bigger batches of queries of say 100,000 sequences. But for your size of query file you will probably be better off using BLAST.

**Comment by hillan141** [comment]
OK, thank you for the feedback and recommendation -
