### ISSUE TITLE
"diamond version" still outputs 0.9.31

### ISSUE THREAD

**Issue by kim-fehl** [bbuchfink/diamond#406]
I've downloaded the latest release 2.0.4 and the program still outputs as its version is older.

**Comment by kim-fehl** [comment]
Seems that new option --mid-sensitive does not work too.

**Comment by bbuchfink** [comment]
Use `diamond version` to check the version. If it is not what you downloaded, maybe an older version of diamond is installed on your system that overrides your call. You can check using `which diamond` what executable you are running.

**Comment by kim-fehl** [comment]
Thanks, my bad. Some mess with the files occured. Sorry for bothering!
