### ISSUE TITLE
Incorrect pident in diamond view

### ISSUE THREAD

**Issue by u-xixi** [bbuchfink/diamond#407]
Hi Benjamin,

There seems a minor issue with diamond view. Blast tab format couldn't be loaded correctly with diamond > 2.0. 
It looks liek this, with the third field looking weird:
`SRR3656745.1.1099  WP_007841945.1 -922337203685477580.-8 0  0  0  52 0  1  0  1.6e-04 40.8`
It happens not only with daa files generated by the latest diamond, but also with rather old daa files.

But interestingly it works fine with older diamond:
`SRR3656745.1.1099  WP_007841945.1 51.5  33 16 0  52 150 1  33 1.6e-04 40.8`

The daa file itself is correct though. Could you please find out where the problem is?

Best,
Xixi

**Comment by bbuchfink** [comment]
Hi Xixi, thanks for reporting this. It should be fixed in this commit: 6149e78f787b5de65a4e4ab43c4f4bd73d2e8bff

**Comment by bbuchfink** [comment]
This is now fixed in the latest release.
