### ISSUE TITLE
qseq and sseq in outfmt 6 no gaps shown

### ISSUE THREAD

**Issue by gaboentropy** [bbuchfink/diamond#409]
Hi,
When I run diamond and ask for qseq and sseq it doesn't show any gaps in the sequences, it shows gaps if I change the format to 0 though.
This is with the latest release (diamond version 2.0.5), I don't know if this was already happening in previous versions.
Running in a mac, in case that might be relevant..

**Comment by gaboentropy** [comment]
I can confirm that this also happens with 2.0.4
:(

**Comment by bbuchfink** [comment]
You can use `qseq_gapped` and `sseq_gapped` for this. Sorry, I know this still needs to be documented.

**Comment by gaboentropy** [comment]
Thanks! That works all right.
