### ISSUE TITLE
Suggestions for Improving Diamond Output

### ISSUE THREAD

**Issue by gemmahoad** [bbuchfink/diamond#41]
Hi,

Today I've been comparing the data from blastall in regular versus tabular output.  I note that the diamond output is practically identical to that in the blastall tabular output.

An issue I'm having is that the tabular output of blastall and diamond does not contain such a rich set of data as blastall regular output.  In particular, the descriptions in the first column all refer to the query sequence and are therefore all identical.  We all have access to the fasta header of our input sequence so this isn't really providing any helpful information.  What would be helpful is to show the fasta header of the hit sequence in the first column of the tabular output instead.

This post I found highlights some issues with blast tabular output including the one I mention, in greater depth: http://blastedbio.blogspot.ca/2012/05/blast-tabular-missing-descriptions.html

It would be wonderful if this feature was provided as a command line option or even more wonderful if the width of the first column had the ability to be much wider so that useful information could be extracted from this field . :)

Here's hoping and many thanks for providing such a great bioinformatics tool for us to use in our lab!
Gemma

**Comment by bbuchfink** [comment]
There is an option to include the full length subject titles in the output (--salltitles). Is that what you need?

**Comment by gemmahoad** [comment]
Thanks for getting back to me so quickly.
That's exactly what I need! :) :)
