### ISSUE TITLE
Sequence identity column returns identical nonsensical number for all queries 

### ISSUE THREAD

**Issue by jessmewald** [bbuchfink/diamond#412]
I am at a loss. I've run DIAMOND on several different types of sequence files and I get the same nonsensical results returned every time. I installed DIAMOND with bio-conda, built the database and aligned both paired and khmer filtered paired reads. I also tried running diamond through SUPER-FOCUS, and got the exact same nonsensical results- which makes me even more curious about this error.

I am running diamond blastx and the sequence identity result no matter which samples I run, through either DIAMOND directly or SUPER-FOCUS, comes back as "-922337203685477580.-8" for every single query. 

The rest of the table output is as follows:
`A00876:74:HNHFGDRXX:1:2101:2175:1063	WP_048119838.1	-922337203685477580.-8	0	0	0	268	269	180	0	3.4e-31	144.4`

I'm using the nr database, and built it with the command:

`diamond makedb --in nr.gz -d nr --taxonmap prot.accession2taxid.gz --taxonnodes nodes.dmp --taxonnames names.dmp` 

No error is returned on the database build. 

Then I run a loop with this command for alignment
` diamond blastx -d nr -q ${filename} -a ${base}_aligned` 

The final lines of the output after running the blastx command are as follows

` Total time = 227717s
Reported 302876615 pairwise alignments, 302876615 HSPs.
15726353 queries aligned.
^[[1;33mThe host system is detected to have 270 GB of RAM. It is recommended to increase the block size for better performance using these parameters : -b8 -c1
^[[0;39m` 

Any suggestions?

**Comment by bbuchfink** [comment]
There was a bug in `diamond view`, see #407. It is fixed in the master branch, but no release yet.

**Comment by jessmewald** [comment]
I've spent the last couple hours trying to figure out how to fix the issue with my limited knowledge. I attempted to make the change within the conda environment, but was not able to find the file I would need to change. Is it correct that the best way to get the updated software is to compile from the source, since the release isn't updated yet? 

THANK YOU!

**Comment by bbuchfink** [comment]
Sorry for the inconvenience. Yes, you need to clone the repo and compile from source if you want to get the bugfix.

**Comment by bbuchfink** [comment]
This has been fixed in the latest release.
