### ISSUE TITLE
How to deliver the results to Blast2Go?

### ISSUE THREAD

**Issue by DustinChen1986** [bbuchfink/diamond#42]
0.8.1 version has great promotion compared to 0.7\* version with some new useful functions. 
It feels like 0.8.1 is a little slower than 0.7*, is this true?
Diamond has no output for xml format, so the question that how to deliver the result to Blast2Go remains to be solved.

**Comment by bbuchfink** [comment]
It hasn't been slower for me but I can check again.
I plan to implement support for the xml format, but I can't promise how long it's going to take. For now the only solution is probably to make a script that converts the diamond output into xml.

**Comment by bbuchfink** [comment]
The latest version now supports the xml format.

**Comment by DustinChen1986** [comment]
This update can be extremely helpful !!! Thank you.

**Comment by ErisonChen** [comment]
hi sir,
This is the code of b2g for blast results
`java -cp /b2g4pipe/*:/b2g4pipe/ext/*: es.blast2go.prog.B2GAnnotPipe -in shuimu_top.xml -out shuimu_top -prop /b2g4pipe/b2gPipe.properties -v -annot -annex`

This the code of b2g for diamond result
`java -cp /b2g4pipe/*:/b2g4pipe/ext/*: es.blast2go.prog.B2GAnnotPipe -in /diamond_k.xml -out diamond_k -prop /b2g4pipe/b2gPipe.properties -v -annot -annex`

The previous code for blast result is ok. However the code for diamond result is failed.
The warnning is "
**_Can not parse BLAST XML because can not find information about the used version!_**
**_Annotation of 0 seqs with 0 annots finished. Now searching for orfan IPRs..._**
**_B2G-Pipe finished_**
"

I can not find the reasons. Could you help me of this?

**Comment by bbuchfink** [comment]
Are you running these commands directly from the command line or are you using the blast2go gui? I tried to import diamond xml files in blast2go and it worked for me.

**Comment by ErisonChen** [comment]
These commands  run on the linux cluster system.
Here's the code to creat the seperated diamond.xml. 
`diamond makedb --in plant_nr.fa -d nr_k
diamond blastx -d nr_k -q med.unigene.fasta --sensitive -k 10 -e 1e-5 -o diamond_k.xml -f 5`

`diamond makedb --in plant_nr.fa -d nr_top
diamond blastx -d nr_top -q med.unigene.fasta --sensitive --top 5 -e 1e-5 -o diamond_top.xml -f 5 `

Then  i put the xml file to b2g, using the code `java -cp /b2g4pipe/*:/b2g4pipe/ext/*: es.blast2go.prog.B2GAnnotPipe -in /diamond_k.xml -out diamond_k -prop /b2g4pipe/b2gPipe.properties -v -annot -annex`, just like the pattern  on blast.xml.

**Comment by bbuchfink** [comment]
I have installed blast2go on my system, but I can't find those b2g4pipe java files. How do you get these?

**Comment by ErisonChen** [comment]
These all  files are in  http://www.blast2go.com/data/blast2go/b2g4pipe_v2.5.zip

but the  [b2gPipe.properties](https://github.com/JoseBlanca/franklin/blob/master/test/data/b2gPipe.properties) are changed to this one

**Comment by bbuchfink** [comment]
Ok, I got this to work now. I'm getting the same error message as you, but I'm also getting this error message using a XML file generated by BLAST, so I really don't know what's the problem there.

**Comment by aipolly** [comment]
change the blast software version in xml file header can solve this problem!!!

**Comment by ErisonChen** [comment]
I changed the version in xml file from `BLASTX 2.2.28+` or `diamond 0.8.22` to 'BLASTX 2.2.28'

here comes a new problem `Exception in thread "main" java.lang.OutOfMemoryError: Requested array size exceeds VM limit`

**Comment by bbuchfink** [comment]
You probably need to use the -Xmx option of java to allow it to use more memory.

**Comment by ErisonChen** [comment]
It's still not ok with `-Xmx5000m` 
That may becasue the xml file is so large. 1.4G. I could split it,But if so, how to get overall representation of my dataset ?
Another result whichi is 700MB is ok with the version `BLASTX 2.2.28`.

**Comment by bbuchfink** [comment]
I guess you need to find a computer with more memory. Other than that, you could ask the blast2go people to fix that problem.

**Comment by ErisonChen** [comment]
OK  thanks so much !

**Comment by ErisonChen** [comment]
@aipolly , could you tell me how you change the verison number.?
I changed the version in xml file from `BLASTX 2.2.28+` or  `diamond 0.8.22`  to `BLASTX 2.2.28` . 
The pipline worked ,but there is no result output.

**Comment by enjoypolly** [comment]
@ErisonChen  
in my situation ,blast2go run successfully after I changed the header，i think before use  diamond you'd better use a small xml file output by blstx to confirm the blast2go has no problems.
my Blast2GO Pipeline Version  is 2.5.0
<BlastOutput_version>BLASTX 2.2.28+</BlastOutput_version>
