### ISSUE TITLE
fail to install diammond program

### ISSUE THREAD

**Issue by Coderwzz-10** [bbuchfink/diamond#424]
Excuse me,How do I install the diamond program on my system? , I want to use the diamond command in tensorflow environment, but I use conda install -c bioconda diamond installation fails

**Comment by bbuchfink** [comment]
Please let me know what the error message is.

**Comment by Coderwzz-10** [comment]
Thank you, I solved it, the problem is that my system is windows, I successfully installed it in the linux environment

**Comment by shalm-een** [comment]
hello can you help me i also cant install it in windows
