### ISSUE TITLE
The time for loading nr database with --taxonlist

### ISSUE THREAD

**Issue by danghongyu** [bbuchfink/diamond#426]
Hi Benjamin,

I am aligning the shotgun sequencing results to several specific species with DIMOND v2.0.1.139.

For species with different number of subtree( identified strains belong to that species), the time to load the reference varies from several seconds to hours. I just listed time for loading the reference and the whole run.

For taxID: 5269, it has 1 subtree belonging to it,
Loading reference sequences...  [6.482s], Total time = 65.432s.

For taxID: 161493, it has 2 subtrees belonging to it,
Loading reference sequences...  [450.162s], Total time = 536.471s.

For taxID: 546, it has 18 subtrees belonging to it,
Loading reference sequences...  [10729.2s], Total time = 10824.6s.

For taxID: 550, it has 43 subtrees belonging to it,
Currently, it got stuck on Loading reference sequences...

It seems the time for loading the reference is not linear, and it might take very long time to load species with too many subtrees.

I am wondering if is this the problem of the old version of the DIAMOND that I am using or is it a problem for the tool itself?

Thanks,
Hongyu

**Comment by bbuchfink** [comment]
I think this issue has been addressed in the latest version, so please try again using that.

**Comment by danghongyu** [comment]
Yes. I installed the lasted version. it works well. Thanks for you help.

Hongyu
