### ISSUE TITLE
diamond makedb Error: Error reading input stream at line 11817785: Invalid character (3) in sequence

### ISSUE THREAD

**Issue by pinocytosis0513** [bbuchfink/diamond#428]
Hello, I knew lots of people have run into the same issue, but I have more questions addressing this issue. I use this guideline to download uniprot database and make [".fasta.gz" files](https://github.com/blobtoolkit/blobtools2/issues/6), I used ` diamond makedb -p 16 --in /scratch/mdegenna/slin023/uniprot/reference_proteomes.fasta.gz --taxonmap /scratch/mdegenna/slin023/uniprot/reference_proteomes.taxid_map --taxonnodes /scratch/mdegenna/slin023/blobtoolkit/taxdump/nodes.dmp -d reference_proteomes.dmnd` and I ran into this issue:
`Error: Error reading input stream at line 11817785: Invalid character (3) in sequence`
Apparently, I noticed some people were able to find that line, I am using SLURM, `less reference_proteomes.fasta.gz` does not indicate which line it is. Any command helps me find that specific line?
And my second question is once I remove it, what if it happens again at different line, how am I supposed to identify what results in **Invalid characters** ? Or if there is anyway to fix all invalid characters all at once that you don't have to manually hit `diamond makedb` to find invalid characters in your input files?

**Comment by bbuchfink** [comment]
You can use `zcat reference_proteomes.fasta.gz | sed '11817785!d'` to get that specific line out of your file. Diamond does not have an efficient way to give you all locations of invalid chars in your file at once. I would recommend writing a small python script for this if you need it more often.

**Comment by pinocytosis0513** [comment]
> You can use `zcat reference_proteomes.fasta.gz | sed '11817785!d'` to get that specific line out of your file. Diamond does not have an efficient way to give you all locations of invalid chars in your file at once. I would recommend writing a small python script for this if you need it more often.

Hi, thank you for your suggestion. Fortunately, I figured it, I actually used `zcat /scratch/mdegenna/slin023/uniprot/reference_proteomes.fasta.gz | head -n 11817785` to find conflicting lines, then use UltraEdit tool to edit manually. It's labor work, but at least everything is running now!
