### ISSUE TITLE
Diamond makedb issue: invalid characters 

### ISSUE THREAD

**Issue by pinocytosis0513** [bbuchfink/diamond#429]
Hello, I knew lots of people have run into the same issue, but I have more questions addressing this issue. I use this guideline to download uniprot database and make [".fasta.gz" files](https://github.com/blobtoolkit/blobtools2/issues/6), I used ` diamond makedb -p 16 --in /scratch/mdegenna/slin023/uniprot/reference_proteomes.fasta.gz --taxonmap /scratch/mdegenna/slin023/uniprot/reference_proteomes.taxid_map --taxonnodes /scratch/mdegenna/slin023/blobtoolkit/taxdump/nodes.dmp -d reference_proteomes.dmnd` and I ran into this issue:
`Error: Error reading input stream at line 11817785: Invalid character (3) in sequence`
Apparently, I noticed some people were able to find that line, I am using SLURM, `less reference_proteomes.fasta.gz` does not indicate which line it is. Any command helps me find that specific line?
And my second question is once I remove it, what if it happens again at different line, how am I supposed to identify what results in **Invalid characters** ? Or if there is anyway to fix all invalid characters all at once that you don't have to manually hit `diamond makedb` to find invalid characters in your input files?

**Comment by prathammanocha** [comment]
Atleast leave a solution before closing
