### ISSUE TITLE
FreeBSD package

### ISSUE THREAD

**Issue by Jehops** [bbuchfink/diamond#43]
Hello,

I've created a FreeBSD package, so FreeBSD users can install diamond with a simple `pkg install diamond`.  Packages are only available for 9amd64 and 10amd64 (I haven't had luck compiling on i386).

Maybe you could mention this in your README along with the other operating systems?

Regards.

**Comment by bbuchfink** [comment]
How often do such packages get updated? It is important to me that people use the latest version of the software.

**Comment by Jehops** [comment]
I just submitted a patch to upgrade to version 0.8.2.  It will hopefully be applied within hours or a day or two at the latest.  I'm the maintainer and I try to keep it up to date.  I have notifications set up, so when you roll a new release I get notified and usually submit an update within a day or two.  So, users of the FreeBSD diamond package will have access to the latest code with at most of few days delay.

**Comment by bbuchfink** [comment]
Ok, I added this to the readme.
