### ISSUE TITLE
Segmentation fault when aligning longer sequences (diamond blastx)

### ISSUE THREAD

**Issue by TypicalSEE** [bbuchfink/diamond#430]
Hi, I'm using diamond blastx (version 2.0.6) to align my genome sequences against nr database. When the input sequences are short (~ 100 Kb), diamond finishes successfully. But when aligning longer sequences (~ 4 Mb, for example), I meet "Segmentation fault" error almost every time. The command I used is "diamond blastx --threads $cpu --db /database/diamond.nr/nr --outfmt 6 --out m6.gz --query $fa --max-target-seqs 2000 --max-hsps 1000 --compress 1 --block-size 16". Did anybody meet this problem? 

I tried running it on a big-memory machine (1TB RAM), still segmentation fault, so memory shouldn't be the cause.

Appreciate it very much if you could help me. Thanks!

**Comment by bbuchfink** [comment]
I'm aware of this bug and it is on my todo list, however in the meantime I recommend running in frameshift alignment mode (`-F 15`). It is in general better suited to handle such long sequences, even if you don't need the frameshift alignment.

**Comment by bbuchfink** [comment]
Should be fixed in v2.0.7.
