### ISSUE TITLE
conda install failure due to conflicts

### ISSUE THREAD

**Issue by DhananjayMukhedkar** [bbuchfink/diamond#431]
Hello!
I am trying to `conda install` diamond with latest version. I am trying on a virtual env with Python 3.6. I get conflicts due to which the installation fails. However, the installation works for v0.9.14.115. I am trying to install on a cluster so a conda install is easier for me to manage and install instead of a native installation. Is this a known issue and is there a work around for it? Thank you!
```
Package _libgcc_mutex conflicts for:
diamond=2.0.6 -> libgcc-ng[version='>=7.5.0'] -> _libgcc_mutex=[build=main]
python=3.6 -> libgcc-ng[version='>=7.3.0'] -> _libgcc_mutex=[build=main]
```

**Comment by bbuchfink** [comment]
You need to create a new environment in such cases, see here: https://docs.conda.io/projects/conda/en/latest/user-guide/tasks/manage-environments.html
