### ISSUE TITLE
diamond 0.9.24

### ISSUE THREAD

**Issue by SPD20** [bbuchfink/diamond#433]
Hello,

No matter how I try I am unable to get this version of Diamond. This version is listed as dependency in DeepEC tool.

conda install -c compbiocore diamond

Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - diamond

Current channels:

  - https://conda.anaconda.org/compbiocore/win-64
  - https://conda.anaconda.org/compbiocore/noarch
  - https://repo.anaconda.com/pkgs/main/win-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/win-64
  - https://repo.anaconda.com/pkgs/r/noarch
  - https://repo.anaconda.com/pkgs/msys2/win-64
  - https://repo.anaconda.com/pkgs/msys2/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

Thanks,

**Comment by bbuchfink** [comment]
Have you tried this?
```
conda config --add channels defaults
conda config --add channels bioconda
conda config --add channels conda-forge
```

**Comment by SPD20** [comment]
Thanks a lot. I used tar file instead. Its working now. I will keep these commands handy.
