### ISSUE TITLE
Unexpectedly high memory usage

### ISSUE THREAD

**Issue by dparks1134** [bbuchfink/diamond#44]
Hello,

I am using the <code>blastp</code> mode of DIAMOND v0.8.3.65. The database was made with default parameters (namely, <code>--block-size</code> of 2). As such, I expected the maximum memory usage to be about 12GB as per the documentation. The <code>--tmpdir</code> was set to <code>/tmp</code> and  all other parameters left at default values.  The query file is very large and this appears to adds to the memory usage substantially with peak usage being over 80GB. Is it possible to limit memory usage for large query files or is this the expected behaviour?

Regards,
Donovan

**Comment by bbuchfink** [comment]
There's a known problem that can cause the blastp mode to use too much memory. I'll provide a fix soon.

**Comment by bbuchfink** [comment]
Please try again with the latest version.

**Comment by dparks1134** [comment]
Seems good. Thank you!
