### ISSUE TITLE
Sudden rise in memory usage during taxonomy assignments before makedb process is killed

### ISSUE THREAD

**Issue by naphtap** [bbuchfink/diamond#440]
Hello, 
I am currently using the latest version of DIAMOND, v2.0.8.146. I have had trouble creating a database that contains taxon IDs (with the --taxonmap, --taxonnodes, and --taxonnames flags) with the latest iteration of the nr.gz and unzipped nr file and the latest version of the prot.accession2taxid. Each time I try making the database, the process gets killed while assigning the taxonomies to the nr database. While running the program, I noticed two things: 
1. The program is only using one thread while writing the sequences. This is what the CPU monitor looks like during this process. At this stage, the program does not crash.
![image](https://user-images.githubusercontent.com/13200850/111020316-027b5380-8393-11eb-9a62-bd3c8b123cb6.png)
2. When the taxonomies are being assigned however, this is what the CPU monitor looks like. There's a huge rise in memory usage all the way to 100% before the command is killed. Is the sudden rise in CPU usage normal when assigning taxonomies when the whole time the program was using only one CPU?
![image](https://user-images.githubusercontent.com/13200850/111020779-4885e680-8396-11eb-802e-8bb9393effb3.png)

If there are any alternatives or work-arounds to this, I would appreciate it. I'm trying to perform DIAMOND alignments excluding specific taxa and I know that I need to set up my database with the taxonomies to do this.

**Comment by bbuchfink** [comment]
It's a known issue that db building with taxonomy takes a lot of memory. The only workaround at the moment is to use a system with more memory. That said, since it's a serious issue I will implement a fix next week.

**Comment by naphtap** [comment]
Hi, 
I was wondering if a fix has been implemented for the taxonomic functions when making the diamond database. 

Thanks!

**Comment by bbuchfink** [comment]
Sorry it took a bit longer, but I have implemented this and it should be ready later today.

**Comment by bbuchfink** [comment]
It's not been fully tested yet, but the latest master branch should now be able to build databases using < 16 GB of memory: 5ae7e67b608e0cd76697030f0a6a330561c88cca

Example output for the latest NR and FULL taxonomy mapping file:

```
Loading taxonomy mapping file...  [428.877s]
Joining accession mapping...  [677.578s]
Writing taxid list...  [33.831s]
Database sequences  362662548
Accessions in database  643697774
Entries in accession to taxid file  3316852368
Database accessions mapped to taxid  643548979
Database sequences mapped to taxid  362595370
Closing the input file...  [0s]
Closing the database file...  [0.571s]
Database hash = 629e7879b7dacfefa0367e4acd90d698
Processed 362662548 sequences, 131432498630 letters.
Total time = 2815.21s
```

**Comment by naphtap** [comment]
So far so good from my end! I'll update you if anything happens

**Comment by bbuchfink** [comment]
Release 2.0.9 can now build databases with very low memory use.
