### ISSUE TITLE
Error during diamond blastx

### ISSUE THREAD

**Issue by diecasfranco** [bbuchfink/diamond#449]
Hi all,
I'm trying to run diamond but is showing this error after a couple of hours

diamond blastx -d nr.dmnd -q Tru-1-1A_1.fq.gz -o W_Tru1.daa --threads 50

Computing alignments... terminate called after throwing an instance of 'std::length_error'
  what():  vector::_M_default_append
Aborted (core dumped)

Any ideas?

**Comment by bbuchfink** [comment]
I have not seen this error before. What version of Diamond are you using? Would it be possible to make the query file available to me?

**Comment by diecasfranco** [comment]
Problem solved.
1. I installed diamond using conda but somehow is installing 0.9 version, so I used github installation.
2. With the newest version I executed againg but with the same problem, but I realized it is a disk problem, using htop, the process was D "Uninterruptible sleep (usually IO)".

Now is working... Thanks

**Comment by saramonzon** [comment]
I'm having the same issue! Could you tell me @diecasfranco how did you fix the issue?

**Comment by diecasfranco** [comment]
Hi @saramonzon did you check diamond version?
My problem was related to diamond version and disk problem. 
Try this
diamond version 2.0.14
diamond blastx -d nr.dmnd -q file.fastq(a) -o file.daa -F 15 -f 100 --range-culling --top 10 --threads 70
