### ISSUE TITLE
Error while compiling from source diamond-0.8.5

### ISSUE THREAD

**Issue by VasilyTokarev** [bbuchfink/diamond#45]
Hello,

I have been trying to install **diamond v 0.8.5** on account without root permission.
This is what I have done:

```
$ wget http://github.com/bbuchfink/diamond/archive/v0.8.5.tar.gz
$ tar xzf v0.8.5.tar.gz
$ cd diamond-0.8.5
$ mkdir bin
$ cd bin
$ cmake .. -DCMAKE_INSTALL_PREFIX=/home/tokarev/programs/diamond
$ make install

```

This is what I get

```
[tokarev@hhmi bin]$ make install
[  3%] Building CXX object CMakeFiles/diamond.dir/src/run/main.cpp.o
In file included from /home/tokarev/tmp/install_files/diamond/src/run/../data/seed_histogram.h:26,
                 from /home/tokarev/tmp/install_files/diamond/src/run/../data/sorted_list.h:25,
                 from /home/tokarev/tmp/install_files/diamond/src/run/../data/reference.h:29,
                 from /home/tokarev/tmp/install_files/diamond/src/run/main.cpp:25:
/home/tokarev/tmp/install_files/diamond/src/run/../data/sequence_set.h: In constructor 'Sequence_set::Sequence_set(Input_stream&)':
/home/tokarev/tmp/install_files/diamond/src/run/../data/sequence_set.h:41: error: class 'Sequence_set' does not have any field named 'String_set'
make[2]: *** [CMakeFiles/diamond.dir/src/run/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/diamond.dir/all] Error 2
make: *** [all] Error 2
```

I am trying to install **humann2** using **anaconda** running on **python 2.7**, **Humann2** requires **diamond** and I get this message while installing it.

Thank you!
Vasily

**Comment by bbuchfink** [comment]
Hi,
can you tell me what gcc version you use? (run `g++ --version`)

**Comment by VasilyTokarev** [comment]
I just updated gcc and successfully installed diamond! Thank you for your help!

**Comment by bbuchfink** [comment]
Hi,
I just uploaded a new release that should fix this problem.

**Comment by nana-marinbio** [comment]
Many thanks
AP

Em terça-feira, 12 de julho de 2016, bbuchfink <notifications@github.com>
escreveu:

> Hi,
> I just uploaded a new release that should fix this problem.
>
> —
> You are receiving this because you commented.
> Reply to this email directly, view it on GitHub
> <https://github.com/bbuchfink/diamond/issues/45#issuecomment-232045269>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/ATL8fBXr9-4Xfag9lob9-HlYZ01tpRUzks5qU5UbgaJpZM4IwBOK>
> .
>


-- 
Dra. Ana Paula B. Moreira
Bióloga
˜˜˜˜˜˜˜˜˜˜˜˜˜˜˜˜˜˜˜˜˜˜˜˜˜˜˜
Bolsista CAPES/PNPD - Projeto Ilhas Oceânicas
Colaboradora Rede Abrolhos e Rede Biotecmar

Endereço:
UFRJ - CCS - Instituto de Biologia
Av. Carlos Chagas Fo. 373
Bloco A, Anexo A3, Sl. 302
Cidade Universitária, RJ - RJ
Cep 21941-599
Tel/Whatsapp: 3938-6567/+55 21 *98822-0753*
Fax: +55 21 2259-0753
E-mails: apbmoreira@gmail.com / anapaulabm@biologia.ufrj.br
Skype: anapaulabmoreira
