### ISSUE TITLE
Support for tblastn

### ISSUE THREAD

**Issue by DanielRivasMD** [bbuchfink/diamond#458]
Hi, really interesting tool. I would like to use it to compare a compilation of protein sequences against genome assemblies. I would regularly use tblastn for this and was wondering whether there is support for this version, or alternatively can use diamond blastx. Appreciate your attention.

**Comment by bbuchfink** [comment]
There is no direct support for tblastn in Diamond. You can try to use the assemblies as query and the proteins as database in blastx mode. I'd probably also use the frameshift alignment mode (`-F 15`) in that case to better handle long queries.

**Comment by DanielRivasMD** [comment]
Thanks for you help. I tried as you suggested and seemed to work fine I believe. I'll procced to close this issue
