### ISSUE TITLE
Diamond view reading gzipped files?

### ISSUE THREAD

**Issue by dcdanko** [bbuchfink/diamond#46]
Would it be possible to modify `diamond view` so that it can read gzipped diamond archive files or so that it can read from stdin?

**Comment by bbuchfink** [comment]
Yes it would, I can include it in the next version.

**Comment by bbuchfink** [comment]
Actually, it's not that simple, because the program needs random access on the daa file. What do you need this for?

**Comment by dcdanko** [comment]
When aligning big query sets to NR my DAA files can get up to several 100gb. 

There are lots of ways to work around this of course but it would definitely be easier if I didn't have to think about it at all.

Maybe it's possible to have diamond output SAM/BlastTab files directly? Or blocked gzip?

**Comment by bbuchfink** [comment]
The daa files don't compress too well so I'm not sure if that would help. But you could get these files a lot smaller by not storing the database sequences into the edit transcripts, but have view load the original database file instead.

**Comment by dcdanko** [comment]
That would work well for my purposes. Is that easy to implement?

**Comment by bbuchfink** [comment]
Quite easy but it's probably still going to take some time.

**Comment by bbuchfink** [comment]
A new daa format is planned, but for now I've added back the option to directly generate the other formats. Compressed blasttab format should work better.
