### ISSUE TITLE
Evalue calculation

### ISSUE THREAD

**Issue by PedroMTQ** [bbuchfink/diamond#460]
I'm developing a tool that currently uses HMMER for homology search, however I'm also interested in adding Diamond for certain databases that don't provide HMMs.
At a certain point my tool will sort homologs by their e-value across different reference databases. This works fine when only using HMMER since the e-value calculation can be standardized (scaled to sample size). However, I'm not sure how e-value is calculated with Diamond and which adjustments would need to be done.
I think blast's evalue scales with the reference size but I'm not 100% sure, is that also the case for Diamond?
Would it be possible to have an e-value scaled to sample size instead?

Regards,
Pedro

**Comment by bbuchfink** [comment]
The e-value scales with the size of the database. You can use `--dbsize` to compute it with respect to a custom size.

**Comment by PedroMTQ** [comment]
Thanks @bbuchfink

**Comment by bbuchfink** [comment]
Try multiplying with the number of letters in the database, not sequences.

**Comment by PedroMTQ** [comment]
Ah I see, so does that mean that when scalling to sample size, one would scale to number of letters (do you mean residues/aminoacids?) instead of the number of sequences?

Thanks

**Comment by bbuchfink** [comment]
Yes, I mean the number of residues.

**Comment by PedroMTQ** [comment]
Sorry, but is that a yes also for the use of residues for sample scaling?

**Comment by bbuchfink** [comment]
Yes it is.

**Comment by PedroMTQ** [comment]
Thanks!
