### ISSUE TITLE
Issues with makedb using taxonomy files

### ISSUE THREAD

**Issue by RKFrench** [bbuchfink/diamond#467]
Hi,

I'm having problems building the nr database including taxonomy mapping, with diamond/2.0.9. 
I'm using the following code:
**diamond makedb --in $wd/nr_$today/nr_$today.gz --db $wd/nr_$today/ --taxonmap $wd/nr_$today/prot.accession2taxid.FULL.gz --taxonnodes $wd/nr_$today/nodes.dmp --taxonnames $wd/nr_$today/names.dmp**

When I run it with prot.accession2taxid.FULL.gz I get this error:
**Loading taxonomy mapping file...  [0.168s]
Error: Inflate error.** 

If I unzip it myself first I get this error:
**Loading taxonomy mapping file... File too large. 
Error: Error writing file diamond-tmp-SDIgC5.**

I don’t appear to be running out of space or memory. The taxonomy files were all downloaded from ftp://ftp.ncbi.nlm.nih.gov/pub/taxonomy

I've attached the two error files.

Many thanks

[error_DBupdate_gzip.txt](https://github.com/bbuchfink/diamond/files/6543167/error_DBupdate_gzip.txt)
[error_DBupdate.txt](https://github.com/bbuchfink/diamond/files/6543172/error_DBupdate.txt)

**Comment by RKFrench** [comment]
I’m using a high performance computing cluster, with a lustre file system. I had 12 cores and 120GB allocated. The jobs only used just over 1 core and about 23GB before crashing (although the error file says 32 CPU threads?). There was about 50TB of free disk space when I ran the job.

From: Benjamin Buchfink ***@***.***>
Date: Wednesday, 26 May 2021 at 11:20 pm
To: bbuchfink/diamond ***@***.***>
Cc: Rebecca French ***@***.***>, Author ***@***.***>
Subject: Re: [bbuchfink/diamond] Issues with makedb using taxonomy files (#467)

How much free disk space do you have in your working directory? What are your system specs and the file system of the drive you are using?

**Comment by bbuchfink** [comment]
Resources should not be a problem then. "File too large" is a strange error that I can't make sense of. Do you have the option to run the same call on a different system to see if the error persists?

**Comment by kks-vir** [comment]
Hi! I'm dealing with a similar issue during makedb:

#### command line:
_diamond makedb --in viral.nonredundant_protein.1.protein.faa.gz -d ./viral_refseq_nonredundant_protein --taxonmap prot.accession2taxid.FULL.gz --taxonnodes nodes.dmp --taxonnames names.dmp_

#### output
  _diamond v2.0.10.148 (C) Max Planck Society for the Advancement of Science
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 8
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
Database input file: viral.nonredundant_protein.1.protein.faa.gz
Opening the database file...  [0s]
Loading sequences...  [0s]
Masking sequences...  [0.001s]
Writing sequences...  [0s]
Writing accessions...  [0s]
Hashing sequences...  [0s]
Loading sequences...  [0s]
Writing trailer...  [0s]
Loading taxonomy nodes...  [0.551s]
Loading taxonomy names...  [0.763s]
Loaded taxonomy names for 2342453 taxon ids.
Loading taxonomy mapping file...  [6.498s]
Error: Inflate error._


I using a MAC 16 GB 2133 MHz LPDDR3 and the working directory has 100 GB.



What am I doing wrong?

Thanks in advance.

**Comment by bbuchfink** [comment]
Maybe the mapping file is corrupted. Have you tried unpacking it with `gunzip`?

**Comment by kks-vir** [comment]
> Maybe the mapping file is corrupted. Have you tried unpacking it with `gunzip`?

I've tried unsuccessfully gunzip 'prot.accession2taxid.FULL.gz' many times, even downloading it again, but the **gunzip** have never worked with this file. 

I could run **diamond makedb** using the mapping file **prot.accession2taxid.gz**. 

Do you have any ideia if there is a problem in the file **prot.accession2taxid.FULL.gz** (ftp://ftp.ncbi.nlm.nih.gov/pub/taxonomy/accession2taxid/prot.accession2taxid.FULL.gz) or this is only happening to me? 


Thanks!

**Comment by bbuchfink** [comment]
> Do you have any ideia if there is a problem in the file **prot.accession2taxid.FULL.gz** (ftp://ftp.ncbi.nlm.nih.gov/pub/taxonomy/accession2taxid/prot.accession2taxid.FULL.gz) or this is only happening to me?

I just tried to download and gunzip this file and it worked for me. I guess you have to try again until it works.
