### ISSUE TITLE
DIAMOND v0.8.5 ftell error

### ISSUE THREAD

**Issue by blaize1st** [bbuchfink/diamond#47]
Hi,
I've got the "Error executing ftell on stream filename.daa" message on Windows Server 2012 Standard. Diamond only has generated incomplete output file (~4Gb). 

Command: diamond blastx -d nr -q filename.fa -a filenamedmnd -c 1 --sensitive

Fortunately Linux version completed without any issues.

Thank you: Blaize

**Comment by bbuchfink** [comment]
Hi,
does the problem also occur for smaller files?

**Comment by blaize1st** [comment]
Hi,
Doing a test run with an very small dataset (~1400 Ion reads) versus full NR succeeded without any problems

Thanks: B

**Comment by bbuchfink** [comment]
Ok, I'll fix this in the next version.

**Comment by bbuchfink** [comment]
This should be fixed in the latest version
