### ISSUE TITLE
Detect nucleotide sequences in building a database

### ISSUE THREAD

**Issue by terrycojones** [bbuchfink/diamond#472]
Hi @bbuchfink

I just did something really dumb..... gave a nucleotide FASTA file to `diamond makedb`. It took me a while to work out why I wasn't seeing the expected results when running a query. Diamond could easily (probabilistically) detect this, e.g., just by checking the first sequence it's told to index. It could warn about it (but that would be easy to overlook, or not even shown if `--quiet` were used) so it might be better to refuse to build, unless `--ignore-warnings` or some such flag were given.  Anyway, after all these years I still manage to screw up in new ways :-(

**Comment by bbuchfink** [comment]
Yes, such a check would certainly be reasonable. Shouldn't be a problem to include that.

**Comment by bbuchfink** [comment]
This has been implemented in v2.0.10.
