### ISSUE TITLE
Performance regression in 2.0.9

### ISSUE THREAD

**Issue by sjaenick** [bbuchfink/diamond#473]
With 2.0.9, diamond performance seems to have suffered for both blastx and blastp modes, taking almost
twice as long in comparison to the previous release (2.0.8). The issue does NOT occur for small databases
(e.g. uniprot_swissprot.dmnd, ~240MB), but becomes pretty obvious for large databases.

In the example given below, `psc.dmnd` is a 27GB database:

2.0.8:
```
[sjaenick@hp-dl560:~ ]$ time /vol/mgx-sw/src/tools/diamond blastx --query 1k.fas --db /vol/software/share/bakta/db/psc.dmnd --threads 8 --id 90 --query-cover 80 --subject-cover 80 --max-target-seqs 1 --block-size 3 --tmpdir /tmp/ >/dev/null

real    6m7.760s
user    27m12.652s
sys     2m40.695s
```

2.0.9:
```
[sjaenick@hp-dl560:~ ]$ time /vol/mgx-sw/bin/diamond blastx --query 1k.fas --db /vol/software/share/bakta/db/psc.dmnd --threads 8 --id 90 --query-cover 80 --subject-cover 80 --max-target-seqs 1 --block-size 3 --tmpdir /tmp/ >/dev/null

real    10m4.234s
user    53m46.150s
sys     4m1.917s
```

**Comment by bbuchfink** [comment]
I assume this also only happens for small query files? Since diamond uses a different algorithm for small query files, some changes were made to harmonize the results with the regular mode, at the expense of some efficiency. You should be able to approximate the old behaviour using the option `--shape-mask 11110110111` for example.

Some more optimizations to improve performance for small query files are upcoming, so I hope this situation will look better soon.

**Comment by oschwengers** [comment]
I can confirm this for small query sizes. I'm glad to hear that you'll addressing this. I'm looking forward to these optimizations. Until then, I stick with `v1.0.8`.

**Comment by sjaenick** [comment]
Yes, 1000 short metagenomic reads for testing. Even though 2.0.8 is still way faster, things are looking less bad with the `--shape-mask 11110110111` option:

2.0.8:
```
[sjaenick@hp-dl560:~ ]$ time /vol/mgx-sw/src/tools/diamond blastx --query 1k.fas --db /vol/software/share/bakta/db/psc.dmnd --threads 8 --id 90 --query-cover 80 --subject-cover 80 --max-target-seqs 1 --block-size 3 --tmpdir /tmp/ --shape-mask 11110110111 >/dev/null

real    5m7.412s
user    27m14.902s
sys     2m42.877s
```

2.0.9:
```
[sjaenick@hp-dl560:~ ]$ time /vol/mgx-sw/bin/diamond blastx --query 1k.fas --db /vol/software/share/bakta/db/psc.dmnd --threads 8 --id 90 --query-cover 80 --subject-cover 80 --max-target-seqs 1 --block-size 3 --tmpdir /tmp/ --shape-mask 11110110111 >/dev/null

real    6m44.238s
user    39m3.374s
sys     3m2.734s
```

**Comment by bbuchfink** [comment]
Note that diamond is not very efficient for small query files, so if that is not your main application, you should test again with a larger dataset.

**Comment by bbuchfink** [comment]
v2.0.11 now contains some optimizations for small query files. You can also get the old behaviour back using the option `--algo ctg`, which may or may not improve performance depending on the file size. Note that this option should *only* be used for small query files.
