### ISSUE TITLE
taxon filter error

### ISSUE THREAD

**Issue by Lix1993** [bbuchfink/diamond#475]
when i use `--taxonlist 9606` to filter nr result， it raise

`Error: No taxonomy node found for taxon id 2820085`

how can i fix this？

**Comment by Lix1993** [comment]
without `--taxonlist 9606` it works.

command:
`diamond blastx --query human.cds.fa --db /share/Databases/NCBI/NR/current/blast_db/nr --outfmt 6 qseqid qstart qend qlen sseqid stitle staxids sstart send slen length pident nident mismatch gapopen evalue bitscore --out dna.all.xls --max-target-seqs 1 --evalue 1e-05 -c1 -b12`

result:
[nr.txt](https://github.com/bbuchfink/diamond/files/6691710/nr.txt)

**Comment by Lix1993** [comment]
fails with taxonlist argument

```
diamond blastx --query human.cds.fa --db /share/Databases/NCBI/NR/current/blast_db/nr --outfmt 6 qseqid qstart qend qlen sseqid stitle staxids sstart send slenlength pident nident mismatch gapopen evalue bitscore --out dna.all.xls --max-target-seqs 1 -evalue 1e-05 -c1 -b12 --taxonlist 9606
diamond v2.0.8.146 (C) Max Planck Society for the Advancement of Science
Documentation, support and updates available at http://www.diamondsearch.org

#CPU threads: 88
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
Temporary directory: 
#Target sequences to report alignments for: 1
Opening the database...  [0.063s]
Database: /share/Databases/NCBI/NR/current/blast_db/nr.dmnd (type: Diamond database, sequencs: 345670150, letters: 124962271495)
Block size = 12000000000
Loading taxonomy mapping...  [12.796s]
Loading taxonomy nodes...  [0.019s]
Building taxonomy filter...  [0.035s]
Error: No taxonomy node found for taxon id 2820085
```

**Comment by Lix1993** [comment]
same error using diamond v2.0.9

**Comment by Lix1993** [comment]
The `prot.accession2taxid.gz` I used has some line with taxid:2820085
```
WP_181868587	WP_181868587.1	2820085	1885925367
WP_181868588	WP_181868588.1	2820085	1885925368
WP_181868589	WP_181868589.1	2820085	1885925369
WP_181868590	WP_181868590.1	2820085	1885925370
```

but `nodes.dmp`  has no info about it.

**Comment by bbuchfink** [comment]
Please try to redownload the `taxdmp.zip` and rebuild the database. The current `nodes.dmp` file does have an entry for that taxid.

**Comment by Lix1993** [comment]
Thanks.

After rebuild diamond db with updated taxonomy dmp， it works now.

**Comment by Lix1993** [comment]
A suggestion:
in blast+ 
- `--taxonlist` require a  taxon id file
- `-taxids`  require  taxon ids like `--taxonlist` in diamond

could you please add an argument to get a taxon id file input
