### ISSUE TITLE
Problems downloading the prot.accession2taxid.FULL.gz file 

### ISSUE THREAD

**Issue by SergeyBaikal** [bbuchfink/diamond#476]
I can't download the file. I tried it using Linux (Debian 10, wget, wget --continue, LANG=C wget -c) and Windows (download master). The speed is very low and after 3% the connection is broken. `(118 KB/s) - Control connection closed.` 
I also tried to download from home without a proxy and from a work computer with a proxy. Can you please tell me what could be the problem?

**Comment by Lix1993** [comment]
I download it 20 hours ago, using
`wget https://ftp.ncbi.nlm.nih.gov/pub/taxonomy/accession2taxid/prot.accession2taxid.FULL.gz`

**Comment by Lix1993** [comment]
I download it 20 hours ago, using
`wget https://ftp.ncbi.nlm.nih.gov/pub/taxonomy/accession2taxid/prot.accession2taxid.FULL.gz`

**Comment by SergeyBaikal** [comment]
Li Xing, Thank you very much! Through Http downloaded in 4 hours. I tried to download from the link that is given in the manual for the diamond. ftp://ftp.ncbi.nlm.nih.gov/pub/taxonomy/accession2taxid/prot.accession2taxid.FULL.gz

**Comment by Lix1993** [comment]
I cannot download it by ftp too.

It may because network between ncbi ftp server and China....

**Comment by SergeyBaikal** [comment]
And between ncbi ftp server and Russia... =)
