### ISSUE TITLE
DIAMOND versions >0.9.25 are 15x slower, as compared to <=0.9.25

### ISSUE THREAD

**Issue by damianszk** [bbuchfink/diamond#477]
Dear Benjamin,

We use diamond in production (STRING database among others) to query small to medium inputs against large databases (up to 50mln sequences). It works like magic. Recently I've updated it from 0.9.22 to 2.0.9 and I've noticed a 15x slowdown.

Basically default settings:
time ./diamond_0.9.22/diamond blastp -p 1 -q trpa.fa -d 0.9.22/db.dmnd
...
real	0m1.764s

time ./diamond_2.0.9/diamond blastp -p 1 -q trpa.fa -d 2.0.9/db.dmnd
...
real	0m31.319s

I run diamond from binaries. I've tested the old releases and this issue first appeared in the 0.9.26 release, while 0.9.25 is still fast. The results are consistent between different linux machines and linux OSs (3 tested) and different inputs, so unless this is expected my guess is there is some issue with a specific library. I can provide more info if needed.

Thanks!
Damian.

**Comment by bbuchfink** [comment]
The problem is most likely the runtime repeat masking introduced in that version. Could you try again using `--masking 0`?

**Comment by damianszk** [comment]
Thanks for the quick reply!
It helps(!), but it's not the full story:

0.9.26 returns to the 0.9.25 performance:
time ./diamond_9.0.26/diamond blastp --masking 0 -p 1 -q trpa.fa -d 0.9.26/db.dmnd
real	0m1.799s

However the newest version is "only" 2x as fast as before (7x slower than 0.9.25):
time ./diamond_2.0.9/diamond blastp --masking 0 -p 1 -q trpa.fa -d 2.0.9/db.dmnd
...
real	0m16.688s (previously 0m31.309s)

**Comment by damianszk** [comment]
ok. So it's actually only 2.0.9 version that this issue appears again. 
2.0.8 computes the same alignment in 2.3s (2.0.0 and 0.9.36 in 2.0s, while 0.9.25 in 1.8s)

**Comment by bbuchfink** [comment]
How about if you run v2.0.9 also using `--algo 1`?

**Comment by damianszk** [comment]
Halved again :) to 7s, still 3x slower.
./diamond_2.0.9/diamond blastp --masking 0 --algo 1 -p 1 -q trpa.fa -d 2.0.9/db.dmnd 
...
real	0m7.019s

./diamond_2.0.8/diamond blastp --masking 0 -p 1 -q trpa.fa -d 2.0.8/db.dmnd 
...
real	0m2.290s

**Comment by bbuchfink** [comment]
Interesting, how big are your query and database files?

**Comment by damianszk** [comment]
Query is just 1 protein, the db is 1.2mln

**Comment by bbuchfink** [comment]
The remaining slowdown is due to some functionality I had removed for the release, but given that it is significant I will resurrect this part of the code for the next release that will be available within the week.

**Comment by damianszk** [comment]
Great, thanks!
Looking forward!

**Comment by bbuchfink** [comment]
v2.0.11 now has the option `--algo ctg` to restore the old behaviour.
