### ISSUE TITLE
Unaccounted Query Seqeunces

### ISSUE THREAD

**Issue by adityabandla** [bbuchfink/diamond#48]
Hi Benjamin

I am trying to use DIAMOND (v0.7.12.61) on a FASTQ file containing approx. 20 million 250bp reads. The verbose output once DIAMOND starts shows NR as containing 89 mil. seqs and query seqs. (which I suppose are my input seqs.) as 117 mil. (approx. 5x times more than the actual sequences in my input file). Is this normal?

I have also been trying to replicate the performance testing stats that you report in your paper. I am currently running my dataset on a server with 24 cores (exclusive use) and 256G RAM. I  So I set my block size to 10 and index chunks to 4, to max out. But, still it seems to be taking quite long (more than a day) for a single file.

**Comment by bbuchfink** [comment]
Hi,
since you're running in blastx mode, it reports the number of translated queries, so this is normal.

Well the NR has gotten 4 times bigger since we published the paper and 250bp reads also take longer to align than 100bp reads, also the speed depends on your data. Still, the speeds seems slow. I'll have to look into it when possible.

The 0.7.12 version contains a serious bug in blastx mode, so please upgrade to the latest version.

**Comment by adityabandla** [comment]
Hi,

Thank you for the head up. I have updated to v0.8.5. 

DIAMOND seems to be running OK so far with index-chunks 1 and block-size 2. This has generated approx. 17 reference chunks (makedb output) and 3 query chunks (my guess based on previous makedb output). Its currently taking about 40 mins per reference chunk. So, I expect my file to be completed within 34h (40min x 17 ref chunks x 3 query chunks = 2040h)

Requesting advise if I can further optimize the block-size to speed it up, given my hardware settings (24 cores, 256G RAM, 127G on /dev/shm)

**Comment by bbuchfink** [comment]
The reason is that it reports the number of sequences in the current query chunk, not the whole file.

You can speed it up with a larger block size, like 6-10. You can also consider using uniref90 or uniref50 as database instead of nr.

**Comment by adityabandla** [comment]
Hi Benjamin

Thank you for being so helpful. I have been testing different values for the block size and its impact on the performance on a 24 core, 256G server, using the latest NR

A file containing approx. 19 million sequences takes 36h using block size 4 and took slightly longer (48h) using block size 2 as expected

However, contrary to expectations, block size 5,6 and 10 seem to take forever (running for 3 days continuously and I killed it after that), without any data dumps, for the same file. Index chunks were held at 1 across all runs

I am not sure what is causing this behaviour as one would expect a speed up using larger block sizes

**Comment by bbuchfink** [comment]
Hi,

that is very strange behaviour. Does your data happen to be publicly available, so I can try to run it myself?

**Comment by adityabandla** [comment]
Hi Benjamin

No, its not publicly available yet. However, I can share the file offline on Dropbox if that works?

**Comment by bbuchfink** [comment]
Yes, that would work.
