### ISSUE TITLE
error . 

### ISSUE THREAD

**Issue by senukobla** [bbuchfink/diamond#481]
Could you kindly help me with the error below . Why is it showing up and how can I resolve? 

#CPU threads: 28
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
Temporary directory: 
Opening the database... No such file or directory

**Comment by bbuchfink** [comment]
Looks like the database you specified does not exist, so make sure you have the correct path here.
