### ISSUE TITLE
Comptibility of qseq and sseq options for -outfmt 6 format

### ISSUE THREAD

**Issue by EduardoCorel** [bbuchfink/diamond#483]
Hi,
I appreciate (among other things, of course) the Blast-compatible output of Diamond; however I'm having difficulties with the "qseq" and "sseq" options of -outfmt 6. In principle, the segments returned are the same-length gapped segments of the query and search sequences that are identified as HSPs; however, in the diamond version, the segments are gapless and have not the same length. I don't seem to find the option to retrieve the useful relevant information (i.e. the position of the gaps...). Is it possible to get this data with diamond?
Best regards,
E. Corel
Team AIRE, Sorbonne University, Paris

**Comment by bbuchfink** [comment]
You can use the `qseq_gapped` and `sseq_gapped` fields for this.

**Comment by xdgene** [comment]
> You can use the `qseq_gapped` and `sseq_gapped` fields for this.

But if it is  qseq_translated？ how to set gapped？qseq_translated_gapped? qseq_translated_gapped were wrong. Can you tell me  thanks a lot !
