### ISSUE TITLE
Diamond is running very slow

### ISSUE THREAD

**Issue by donthuanalyst** [bbuchfink/diamond#488]
Hello,

I am trying to run diamond v2.0.10.148 using the following options. 

The size of the input contigs fasta file is 229 Mb (229,607,708 bytes) and the uniprot diamond database is 29 Gb (29,629,429,732 bytes).

It has been running for more than 5 days on one node (AMD Opteron(TM) Processor 6272) and more than 1 day 21 hours on another node  (AMD Opteron(TM) Processor 6274). Both the jobs are still running and did not print any information to the log file.

I felt that it is unusually very slow for diamond to run this long. I saw another thread where someone mentioned that the newer versions of diamond are 15X slower than the older versions. 

Could you please let me know how I can improve the speed of this diamond run. 

<pre>
diamond blastx \
        --query assembly.v2.FINAL.fasta \
        --db uniprot_reference_proteomes_version_2021_03.dmnd \
        --outfmt 6 qseqid staxids bitscore qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore \
        --sensitive \
        --max-target-seqs 1 \
        --evalue 1e-25 \
        --threads 16 \
        --tmpdir /dev/shm \
        > diamond_asmCtgs_vs_upRefproteomes.out
</pre>

**Comment by bbuchfink** [comment]
How long is your longest query sequence? The blastx mode can be slow for very long queries. The standard solution for this would be to run gene calling/extract ORFs from your contigs first, then run Diamond in blastp mode. If you want to search the raw contigs, it may help to use the frameshift mode (`-F 15`). It is better at handling this type of query.

**Comment by donthuanalyst** [comment]
My longest query sequence is 27 Mb in length. I need to run diamond on raw contigs so that I can use the output to run with blobtools.

 I will try the -F 15 option.

Thank you for your quick response.

**Comment by donthuanalyst** [comment]
I used the -F 15 option and the job completed in 5 hours. 

Thank you very much for your help.
