### ISSUE TITLE
Tutorial Output Does Not Match

### ISSUE THREAD

**Issue by pcsearle** [bbuchfink/diamond#490]
Hello,

I installed diamond using anaconda and then made sure to update bioconda to make sure I was using the most recent version of diamond.  However, when I run through the tutorial, I get slightly different results for the output statistics listed in the tutorial.  

The tutorial output is the following:

Total time = 5.494s
Reported 69284 pairwise alignments, 69284 HSPs.
14323 queries aligned.

while my output is the following:

Total time = 1.323s
Reported 74440 pairwise alignments, 74440 HSPs.
14323 queries aligned

I also had the same result when I used the binary download. Is this something that I should be worried about and if so, do you have any suggestions on how to fix it?

Peter

**Comment by bbuchfink** [comment]
You don't need to worry about that, scoring and evalue computations have been improved since then, leading to different results.

**Comment by pcsearle** [comment]
Awesome thanks!
