### ISSUE TITLE
makedb (Error: Tokenizer Exception)

### ISSUE THREAD

**Issue by kabilov** [bbuchfink/diamond#495]
Hi Benjamin,

When I tried to make database with command:
diamond makedb --in nr.gz --db nr --taxonmap prot.accession2taxid --taxonnames names.dmp --taxonnodes nodes.dmp

in the end I see error:

Writing accessions...  [1.22s]
Hashing sequences...  [0.217s]
Loading sequences...  [0s]
Writing trailer...  [14.375s]
Loading taxonomy nodes...  [0.894s]
Loading taxonomy names...  [1.497s]
Loaded taxonomy names for 2349941 taxon ids.
Loading taxonomy mapping file...  [228.738s]
Error: Tokenizer Exception

It was used diamond v2.0.11.149 in ubuntu.
Could you please tell how fix the error?

Best wishes,
Marsel

**Comment by bbuchfink** [comment]
It could be that your `prot.accession2taxid` file is corrupted. Try to redownload it from NCBI and verify its MD5 hash.

**Comment by bbuchfink** [comment]
See above:

> It could be that your prot.accession2taxid file is corrupted. Try to redownload it from NCBI and verify its MD5 hash.

**Comment by Mayfm** [comment]
Deallocating buffers...  [0.006s]
Loading trace points...  [0s]
 [4.05s]
Deallocating reference...  [0.157s]
Loading reference sequences...  [0.026s]
Deallocating buffers...  [0s]
Joining output blocks... Joining output blocks... Error: Format error: Invalid varint encoding.
Error: Format error: Invalid varint encoding.
Error: Format error: Invalid varint encoding.
Error: /cm/local/apps/sge/var/spool/compute-00-11/job_scripts/431708: line 42: 252148 Segmentation fault

**Comment by bbuchfink** [comment]
@Mayfm Sorry for the late reply. Let me know if the problem persists with the current version.
