### ISSUE TITLE
Unexpected behaviour when using BLAST-generated target DBs

### ISSUE THREAD

**Issue by salvoc81** [bbuchfink/diamond#497]
Hello @bbuchfink and thanks a lot for creating Diamond.  

I have recently tested the searches using the `diamond blastp` command on databases generated using `makeblastdb`  
But the IDs for the target sequences in the output files correspond to sequencial numbers in the original FASTA file rather than the original protein IDs.  

Following is the command I used to prepare the target database for use with Diamond  

```
> diamond prepdb -d target_db              15:58:53
diamond v2.0.11.149 (C) Max Planck Society for the Advancement of Science
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

Processing volume: target_db
Number of sequences: 18528
Number of accessions: 18528
```

NOTE: The target_db.acc is properly created.
Then I perform the search using the following command:

```
diamond blastp --query query.fasta --db target_db --out query-target_db.tsv -p 1 --sensitive --quiet -f 6 qseqid sseqid qstart qend sstart send bitscore
```

The output looks as follows:

```
G1KA10	BL_ORD_ID:2081	27	530	13	525	78.6
G1KA10	BL_ORD_ID:621	39	529	22	528	60.8
G1KA61	BL_ORD_ID:1852	34	463	456	840	99.8
...
```
As you can see, in the second column an index (based on the BLAST DB ordering?) is shown, rather than the protein IDs.  
Another thing I have noticed is that the execution times, as well as the output results, are exactly the same to those obtained when using `.dmnd` database files, as shown below:
```
G1KA10	Q8NSS0	27	530	13	525	78.6
G1KA10	Q8NM64	39	529	22	528	60.8
G1KA61	Q8NQ17	34	463	456	840	99.8
...
```

Is the above behaviour expected?  
Please let me know if I am doing something wrong.

Thanks a lot,

Salvatore

**Comment by bbuchfink** [comment]
Hey, you need to use `-parse_seqids` when you run `makeblastdb` to fix this.

**Comment by salvoc81** [comment]
Oh, thanks a lot
