### ISSUE TITLE
error with compiling v8.0.7 on Mac OSX

### ISSUE THREAD

**Issue by Ewout1988** [bbuchfink/diamond#50]
I get the following error when I try to compile the newest version of diamond:
git/diamond/src/run/../output/output_format.h:222:26: error: default initialization of an object of const type 'const XML_format' without a
      user-provided default constructor
        static const XML_format xml;
                                ^
1 error generated.

When I do a git checkout to 89ec7d532382970ecef2869e2d17d6b0eb7db20d it does compile

**Comment by bbuchfink** [comment]
I just commited a patch that should fix this.

**Comment by Ewout1988** [comment]
I've pulled the latest version and that indeed fixed it.
Thank you
