### ISSUE TITLE
Spelling error: "diamond prepdp -d DATABASE_PATH"

### ISSUE THREAD

**Issue by hmontenegro** [bbuchfink/diamond#502]
If one fails to prepare blast databases for use with diamond 2.0.11, the error message has a spelling error:

Accession file not found. BLAST databases require preprocessing using this command line: diamond **prepdp** -d DATABASE_PATH

It should read `diamond prepdb` instead.

**Comment by bbuchfink** [comment]
Thanks, will be fixed.
