### ISSUE TITLE
custom database build with tax information got Duplicate keys  Error

### ISSUE THREAD

**Issue by aipolly** [bbuchfink/diamond#504]
I'm using --taxonmap option to build a database,  sequnce ids contain dot like seq.1 seq.2, I've tried taxonmap format 'accession	accession.version	taxid	gi'
and 
'accession.version	taxid'
both got Duplicate keys  Error.  
Is it possible  not changing  sequence id  ? thanks in advance!

**Comment by bbuchfink** [comment]
Diamond deletes everything after the final dot in the accession, so I assume this is why you get duplicate entries. One way would be to replace the dot with another character like `_`.

**Comment by aipolly** [comment]
> Diamond deletes everything after the final dot in the accession, so I assume this is why you get duplicate entries. One way would be to replace the dot with another character like `_`.

I append a fake version to every sequence in taxonmap, currently there is no error found, thanks for your answer!
