### ISSUE TITLE
--no-self-hits option produces an error when using Blast indexes

### ISSUE THREAD

**Issue by FredericBGA** [bbuchfink/diamond#507]
Hi,

I'm facing an error with diamond 2.0.11.

When I use indexes from Blast (and `diamond prepdb` step which creates the .acc file) I have an error when I add the `-no-self-hits` option:

> diamond blastp --quiet --threads 6 --db ./database --query 'toto.fasta' --no-self-hits --out OUT
> Error: Block::ids()

It works well when I launch the same command line but I use instead, as a database, the same fasta file indexed with `diamond makedb`

Can you reproduce this?
Thank you.

**Comment by bbuchfink** [comment]
It's a known issue and will be fixed in the next release. For now you should work around using the regular db format.

**Comment by bbuchfink** [comment]
It should be fixed in v2.0.12.
