### ISSUE TITLE
outfmt, adding new columns to outfmt 6 causes error 

### ISSUE THREAD

**Issue by liupfskygre** [bbuchfink/diamond#510]
Hi all,
         I am using diamond blastp and add two addition columns to the output with -f 6 qlen slen,
however, the output only has qlen and slen, two columns, without the outfmt 6 12 columns

diamond v2.0.11 is used 
and this the command line used

diamond makedb --in viral.123.protein.faa -d Ref207_all_proteins_db

diamond blastp --query glacier_total_virus_final123_95-85_PC_rep_seq.fasta --db Ref207_all_proteins_db --evalue 1e−5 --id 30 --max-target-seqs 577642 --threads 2 -o glacier_total_PC_blastp_ref207-DIAMOND.tsv -f 6 qlen slen

#in the tsv, i got only two column
443 566 
xx xx

thanks

**Comment by bbuchfink** [comment]
You need to specify all columns i.e. `-f 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore qlen slen`
