### ISSUE TITLE
custom scoring matrices

### ISSUE THREAD

**Issue by hbckleikamp** [bbuchfink/diamond#513]
Dear Benjamin,
Currently I am not able to successfully apply the custom scoring matrix feature.
I do not get an error but the output file is empty.

I tested this by writing the example matrix file to .txt with Python and used 10/1 for -gapopen -gapextend
code:
url="http://diamondsearch.org/blosum62.mat"
with open("blosumtest.txt","w") as f:
    f.write(requests.get(url).text)

Thanks and kind regards,
Hugo Kleikamp

**Comment by bbuchfink** [comment]
I can confirm that there is a bug, I should be able to fix this shortly.

**Comment by bbuchfink** [comment]
This should be fixed in the latest master branch. I will also post a new release shortly.

**Comment by hbckleikamp** [comment]
Thanks a lot!

**Comment by bbuchfink** [comment]
It should be fixed in v2.0.12.
