### ISSUE TITLE
prepdb is an invalid command

### ISSUE THREAD

**Issue by greenmna** [bbuchfink/diamond#514]
Hello there!

I have been trying to run prepdb in order to use the blast database that is stored on my cluster. However, when I run `diamond prepdb -d /path/to/database/` I end up with the following error: 
![image](https://user-images.githubusercontent.com/35266190/134258323-8992c57f-c108-4c4d-b900-4d7a4f69b55f.png)

I have installed diamond v. 2.0.11 on a linux system via biconda and can execute every other command easily enough, but this one command does not seem available when I look at `diamond help` as shown here: 
![image](https://user-images.githubusercontent.com/35266190/134258457-246d26ce-28ce-493e-88f3-bd2e8ce61df9.png)

I was reading that I probably have to link my libraries with blast+/2.11.0 (or anything later than 2.9.0), but I want to make sure something else hasn't messed up before I go to my admin. 

Thanks for the help!

**Comment by bbuchfink** [comment]
BLAST database support is not included in the conda version, you have to download the github release version or compile from source.

**Comment by greenmna** [comment]
Oh okay great! Thank you for the prompt reply!
