### ISSUE TITLE
Error version binary in windows

### ISSUE THREAD

**Issue by vagnerfonseca** [bbuchfink/diamond#52]
When you run the command "diamond.exe blastx -d nr -q reads.fna -a matches"... the program is aborted unexpectedly. I using the binary version available  to windows. [ https://github.com/bbuchfink/diamond/releases/ ]... my is Windows 10...

below is the log of the use. 

diamond v0.8.8.70 | by Benjamin Buchfink <buchfink@gmail.com>
Check http://github.com/bbuchfink/diamond for updates.

#CPU threads: 4
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
#Target sequences to report alignments for: 25
Temporary directory: 
Opening the database...  [0.000133605s]
Opening the input file...

**Comment by bbuchfink** [comment]
There's a problem with the Windows version for checking file existance. Are you sure that your files exist and you give the correct path on the command line?

**Comment by vagnerfonseca** [comment]
sorry my file is corrupt!
