### ISSUE TITLE
ZSTD_LIBRARY error

### ISSUE THREAD

**Issue by jhnath21** [bbuchfink/diamond#525]
While trying to perform the installation on CentOS 7 using the blast support I was following the instructions in the wiki but using the latest version of BLAST.  Here are the commands:

wget https://ftp.ncbi.nlm.nih.gov/blast/executables/blast+/2.12.0/ncbi-blast-2.12.0+-src.tar.gz
tar xzf ncbi-blast-2.12.0+-src.tar.gz
cd ncbi-blast-2.12.0+-src/c++
./configure --prefix=/apps/BLAST2.12 --with-static --without-debug --without-exe --without-boost --without-gui
make -j8 
make install
cd
wget https://github.com/bbuchfink/diamond/archive/v2.0.13.tar.gz
tar xzf v2.0.13.tar.gz
mkdir diamond-2.0.13/bin
cd diamond-2.0.13/bin
cmake -DBLAST_INCLUDE_DIR=/apps/BLAST2.12/include/ncbi-tools++ -DBLAST_LIBRARY_DIR=/apps/BLAST2.12/lib -DEXTRA=ON ..

When I run the cmake command I get the following output:
-- The C compiler identification is GNU 4.8.5
-- The CXX compiler identification is GNU 4.8.5
-- Check for working C compiler: /usr/bin/cc
-- Check for working C compiler: /usr/bin/cc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/bin/c++
-- Check for working CXX compiler: /usr/bin/c++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test HAS_GNUPP14
-- Performing Test HAS_GNUPP14 - Failed
-- Found ZLIB: /usr/lib64/libz.so (found version "1.2.7")
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE
Setting -fabi-version for GCC 4.x
BLAST_INCLUDE_DIR: /apps/BLAST2.12/include/ncbi-tools++
BLAST_LIBRARY_DIR: /apps/BLAST2.12/lib
Found BLAST library: /apps/BLAST2.12/lib/libseqdb.a
Found BLAST library: /apps/BLAST2.12/lib/libbiblio.a
Found BLAST library: /apps/BLAST2.12/lib/libblastdb.a
Found BLAST library: /apps/BLAST2.12/lib/libblastdb_format.a
Found BLAST library: /apps/BLAST2.12/lib/libgeneral.a
Found BLAST library: /apps/BLAST2.12/lib/libgenome_collection.a
Found BLAST library: /apps/BLAST2.12/lib/libmedline.a
Found BLAST library: /apps/BLAST2.12/lib/libpub.a
Found BLAST library: /apps/BLAST2.12/lib/libseq.a
Found BLAST library: /apps/BLAST2.12/lib/libseqcode.a
Found BLAST library: /apps/BLAST2.12/lib/libseqset.a
Found BLAST library: /apps/BLAST2.12/lib/libsequtil.a
Found BLAST library: /apps/BLAST2.12/lib/libsubmit.a
Found BLAST library: /apps/BLAST2.12/lib/libxobjmgr.a
Found BLAST library: /apps/BLAST2.12/lib/libxobjutil.a
Found BLAST library: /apps/BLAST2.12/lib/libxser.a
Found BLAST library: /apps/BLAST2.12/lib/libxncbi.a
Found BLAST library: /apps/BLAST2.12/lib/libxutil.a
Found BLAST library: /apps/BLAST2.12/lib/liblmdb.a
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
ZSTD_LIBRARY
    linked by target "diamond" in directory /apps/diamond-2.0.13

-- Configuring incomplete, errors occurred!
See also "/apps/diamond-2.0.13/bin/CMakeFiles/CMakeOutput.log".
See also "/apps/diamond-2.0.13/bin/CMakeFiles/CMakeError.log".

However if I remove the two DBLAST options from the command it will go through cmake fine.

**Comment by bbuchfink** [comment]
You need to install the zstd library on your system and make sure its in the search path. Also, this will probably not compile since BLAST needs C++14 since v2.10.0 I believe. When compiling on CentOS I normally use a later GCC version as described here: https://github.com/bbuchfink/diamond/wiki/5.-Advanced-topics#compiling-with-custom-gcc

**Comment by jhnath21** [comment]
Thank you for the link for the GCC compiling.  I followed the link and also installed the zstd library via yum.  When I run cmake -DBLAST_INCLUDE_DIR=/apps/BLAST2.12/include/ncbi-tools++ -DBLAST_LIBRARY_DIR=/apps/BLAST2.12/lib -DEXTRA=ON .. command again it still states:
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
ZSTD_LIBRARY
linked by target "diamond" in directory /apps/diamond-2.0.13

If I set the ZSTD_LIBRARY=/usr/bin/zstd and rerun the cmake command, the cmake error goes away.  However when I run the make -j8 command I get the following:

Scanning dependencies of target arch_avx2
Scanning dependencies of target arch_sse4_1
Scanning dependencies of target arch_generic
[  0%] [  1%] [  1%] [  2%] [  3%] [  4%] [  5%] [  5%] Building CXX object CMakeFiles/arch_avx2.dir/src/search/stage2.cpp.o
Building CXX object CMakeFiles/arch_avx2.dir/src/tools/benchmark.cpp.o
Building CXX object CMakeFiles/arch_avx2.dir/src/dp/swipe/banded_3frame_swipe.cpp.o
Building CXX object CMakeFiles/arch_avx2.dir/src/tools/benchmark_swipe.cpp.o
Building CXX object CMakeFiles/arch_avx2.dir/src/dp/swipe/swipe_wrapper.cpp.o
Building CXX object CMakeFiles/arch_generic.dir/src/dp/swipe/banded_3frame_swipe.cpp.o
Building CXX object CMakeFiles/arch_sse4_1.dir/src/dp/swipe/banded_3frame_swipe.cpp.o
Building CXX object CMakeFiles/arch_sse4_1.dir/src/search/stage2.cpp.o
[  5%] Building CXX object CMakeFiles/arch_avx2.dir/src/util/tantan.cpp.o
[  6%] Building CXX object CMakeFiles/arch_generic.dir/src/search/stage2.cpp.o
[  7%] Building CXX object CMakeFiles/arch_sse4_1.dir/src/tools/benchmark.cpp.o
[  8%] Building CXX object CMakeFiles/arch_sse4_1.dir/src/tools/benchmark_swipe.cpp.o
[  8%] Building CXX object CMakeFiles/arch_sse4_1.dir/src/dp/swipe/swipe_wrapper.cpp.o
[  9%] Building CXX object CMakeFiles/arch_sse4_1.dir/src/util/tantan.cpp.o
[  9%] Building CXX object CMakeFiles/arch_sse4_1.dir/src/dp/scan_diags.cpp.o
[ 10%] Building CXX object CMakeFiles/arch_avx2.dir/src/dp/scan_diags.cpp.o
[ 10%] Building CXX object CMakeFiles/arch_generic.dir/src/tools/benchmark.cpp.o
[ 11%] Building CXX object CMakeFiles/arch_generic.dir/src/tools/benchmark_swipe.cpp.o
[ 11%] Building CXX object CMakeFiles/arch_generic.dir/src/dp/swipe/swipe_wrapper.cpp.o
[ 12%] Building CXX object CMakeFiles/arch_generic.dir/src/util/tantan.cpp.o
[ 13%] Building CXX object CMakeFiles/arch_sse4_1.dir/src/dp/ungapped_simd.cpp.o
[ 14%] Building CXX object CMakeFiles/arch_generic.dir/src/dp/scan_diags.cpp.o
[ 14%] Building CXX object CMakeFiles/arch_avx2.dir/src/dp/ungapped_simd.cpp.o
[ 14%] Building CXX object CMakeFiles/arch_generic.dir/src/dp/ungapped_simd.cpp.o
[ 14%] Built target arch_generic
[ 14%] Built target arch_avx2
[ 14%] Built target arch_sse4_1
Scanning dependencies of target diamond
[ 15%] [ 16%] [ 16%] [ 16%] [ 17%] [ 18%] [ 18%] [ 19%] Building CXX object CMakeFiles/diamond.dir/src/run/main.cpp.o
Building CXX object CMakeFiles/diamond.dir/src/basic/config.cpp.o
Building CXX object CMakeFiles/diamond.dir/src/stats/score_matrix.cpp.o
Building CXX object CMakeFiles/diamond.dir/src/data/queries.cpp.o
Building CXX object CMakeFiles/diamond.dir/src/data/reference.cpp.o
Building CXX object CMakeFiles/diamond.dir/src/data/seed_histogram.cpp.o
Building CXX object CMakeFiles/diamond.dir/src/output/daa/daa_record.cpp.o
Building CXX object CMakeFiles/diamond.dir/src/util/command_line_parser.cpp.o
[ 19%] Building CXX object CMakeFiles/diamond.dir/src/util/seq_file_format.cpp.o
[ 20%] Building CXX object CMakeFiles/diamond.dir/src/util/util.cpp.o
[ 21%] Building CXX object CMakeFiles/diamond.dir/src/basic/basic.cpp.o
[ 21%] Building CXX object CMakeFiles/diamond.dir/src/basic/hssp.cpp.o
[ 22%] Building CXX object CMakeFiles/diamond.dir/src/dp/ungapped_align.cpp.o
[ 22%] Building CXX object CMakeFiles/diamond.dir/src/run/tools.cpp.o
[ 23%] Building CXX object CMakeFiles/diamond.dir/src/chaining/greedy_align.cpp.o
[ 24%] Building CXX object CMakeFiles/diamond.dir/src/output/output_format.cpp.o
[ 24%] Building CXX object CMakeFiles/diamond.dir/src/output/clustering_variables.cpp.o
[ 25%] Building CXX object CMakeFiles/diamond.dir/src/output/clustering_format.cpp.o
[ 25%] Building CXX object CMakeFiles/diamond.dir/src/output/join_blocks.cpp.o
[ 26%] Building CXX object CMakeFiles/diamond.dir/src/data/frequent_seeds.cpp.o
[ 27%] Building CXX object CMakeFiles/diamond.dir/src/align/legacy/query_mapper.cpp.o
[ 27%] Building CXX object CMakeFiles/diamond.dir/src/output/blast_tab_format.cpp.o
[ 28%] Building CXX object CMakeFiles/diamond.dir/src/output/blast_pairwise_format.cpp.o
[ 28%] Building CXX object CMakeFiles/diamond.dir/src/run/double_indexed.cpp.o
[ 29%] Building CXX object CMakeFiles/diamond.dir/src/output/sam_format.cpp.o
[ 30%] Building CXX object CMakeFiles/diamond.dir/src/align/align.cpp.o
[ 30%] Building CXX object CMakeFiles/diamond.dir/src/search/setup.cpp.o
[ 31%] Building CXX object CMakeFiles/diamond.dir/src/data/taxonomy.cpp.o
[ 31%] Building CXX object CMakeFiles/diamond.dir/src/masking/masking.cpp.o
[ 32%] Building CXX object CMakeFiles/diamond.dir/src/data/seed_set.cpp.o
[ 33%] Building CXX object CMakeFiles/diamond.dir/src/util/simd.cpp.o
[ 33%] Building CXX object CMakeFiles/diamond.dir/src/output/taxon_format.cpp.o
[ 34%] Building CXX object CMakeFiles/diamond.dir/src/output/daa/view.cpp.o
[ 34%] Building CXX object CMakeFiles/diamond.dir/src/output/output_sink.cpp.o
[ 35%] Building CXX object CMakeFiles/diamond.dir/src/output/target_culling.cpp.o
[ 36%] Building CXX object CMakeFiles/diamond.dir/src/align/legacy/banded_swipe_pipeline.cpp.o
[ 36%] Building CXX object CMakeFiles/diamond.dir/src/util/io/compressed_stream.cpp.o
[ 37%] Building CXX object CMakeFiles/diamond.dir/src/util/io/deserializer.cpp.o
[ 37%] Building CXX object CMakeFiles/diamond.dir/src/util/io/file_sink.cpp.o
[ 38%] Building CXX object CMakeFiles/diamond.dir/src/util/io/file_source.cpp.o
[ 39%] Building CXX object CMakeFiles/diamond.dir/src/util/io/input_file.cpp.o
[ 39%] Building CXX object CMakeFiles/diamond.dir/src/util/io/input_stream_buffer.cpp.o
In file included from /apps/diamond-2.0.13/src/util/io/input_file.cpp:36:
/apps/diamond-2.0.13/src/util/io/zstd_stream.h:2:10: fatal error: zstd.h: No such file or directory
    2 | #include <zstd.h>
      |          ^~~~~~~~
compilation terminated.
make[2]: *** [CMakeFiles/diamond.dir/src/util/io/input_file.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
make[1]: *** [CMakeFiles/diamond.dir/all] Error 2
make: *** [all] Error 2

**Comment by bbuchfink** [comment]
You need the zstd library and header files installed, not just the executables. If there is no centos package you can try compiling zstd from source. After that, if the files are not in your search path you can set `-DZSTD_LIBRARY` *and* `-DZSTD_INCLUDE_DIR` for cmake.

**Comment by jhnath21** [comment]
Thanks.  I had to pull zstd from github and run the make and make install commands.  Once I did that the only other thing I needed to do after compiling diamond successfully was I had to set the following for diamond to run: export LD_LIBRARY_PATH=$HOME/GCC-10.2.0/lib64
