### ISSUE TITLE
makedb process issue. Error: Inflate error.

### ISSUE THREAD

**Issue by Edward-Tristan** [bbuchfink/diamond#526]
Hi,
The required zip package has been downloaded, but there has some issues in makedb process, command line: nohup diamond makedb --in nr.gz -d diamond_nr --taxonmap prot.accession2taxid.FULL.gz --taxonnodes nodes.dmp --taxonnames names.dmp
The issues are below:
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
Database input file: nr.gz
Opening the database file...  [0s]
Loading sequences...  [0.009s]
Error: Inflate error.

**Comment by bbuchfink** [comment]
This means the file is corrupted, try to redownload it and verify its MD5 hash.

**Comment by tanpham15** [comment]
Hi,

I got the same error, even I tried the newest version (by conda)

```
Variable OMP_NUM_THREADS has been set to 2
diamond v2.1.9.163 (C) Max Planck Society for the Advancement of Science, Benjamin Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 36
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
Database input file: /data/scratch/mpx586/Batesia_hypochlora/test/prot0s6qxgsr
Opening the database file... Error: Inflate error.
```

Here is my command:
```
#!/bin/bash
#$ -cwd
#$ -j y
#$ -pe smp 2
#$ -l h_rt=2:0:0
#$ -l h_vmem=24G

# Load package
module load anaconda3
conda activate diamond2

prot0s6qxgsr="/data/scratch/mpx586/Batesia_hypochlora/test/prot0s6qxgsr"

diamond makedb --in $prot0s6qxgsr -d diamond_db
```
