### ISSUE TITLE
Computing alignments... Error: std::bad_alloc

### ISSUE THREAD

**Issue by mictadlo** [bbuchfink/diamond#527]
Hi, I ran diamond on a 128GB ram computer with a 2.8Gb genome. However, it appears it ran out of memory. 

```
    $ diamond makedb --in GenbankAA.fasta --db diamond -p 8
    $ diamond blastx --threads 1 -q genome.softmasked.fasta --db diamond -o diamond.matches.tab -e 1e-10 -k 0 --more-sensitive -f 6 sseqid slen sstart send qseqid qlen qstart qend pident length evalue score qcovhsp qframe
    ...
    Searching alignments...  [0.602s]
    Deallocating buffers...  [0s]
    Clearing query masking...  [0.247s]
    Computing alignments... Error: std::bad_alloc
```
I created for each of the 19 chromosomes a FASTA file. Each of the 19 FASTA files is around 150Mb and I still got the same error.

However, I successfully use the frameshift mode (option `-F 15`) on the whole genome and the error disappears. 

1. How to determine the optimal frameshift value and what does it mean? 
2. Is there another way to reduce memory consumption?

Thank you in advance

**Comment by bbuchfink** [comment]
1. It is the penalty for a frameshift in the alignment. This value is recommended in literature, I'm not sure how to determine the optimal one.
2. For such long queries, what would work best is to chop them into smaller windows or to extract ORFs.
