### ISSUE TITLE
Align multiple files

### ISSUE THREAD

**Issue by jregalad** [bbuchfink/diamond#53]
Is there a way to specify multiple query files and multiple .daa output files in a fashion similar to malt?
So far I get "Error: Invalid parameter count for option <-q or -a>"

**Comment by jregalad** [comment]
Solved the issue with the -a option by separating with commas. If I try the same with -q option, I get a "Error: strict_fstream:" complaining about the input files not existing.

**Comment by bbuchfink** [comment]
It's not possible at the moment but I will probably add it in a future version.

**Comment by jregalad** [comment]
bummer, looking forward to it :) 
thanks a lot
