### ISSUE TITLE
Blast virtual databases

### ISSUE THREAD

**Issue by FredericBGA** [bbuchfink/diamond#534]
Hi,

I'm trying to work with TREMBL data.
For some of these Blast databases, there's more than one single index:

- TREMBL_PLANTS.00.acc
- TREMBL_PLANTS.00.phd
- TREMBL_PLANTS.00.phi
- TREMBL_PLANTS.00.phr
- TREMBL_PLANTS.00.pin
- TREMBL_PLANTS.00.pog
- TREMBL_PLANTS.00.psq
- TREMBL_PLANTS.01.acc
- TREMBL_PLANTS.01.phd
- TREMBL_PLANTS.01.phi
- TREMBL_PLANTS.01.phr
- TREMBL_PLANTS.01.pin
- TREMBL_PLANTS.01.pog
- TREMBL_PLANTS.01.psq
- TREMBL_PLANTS.pal
- TREMBL_PLANTS.pdb
- TREMBL_PLANTS.perf
- TREMBL_PLANTS.pos
- TREMBL_PLANTS.pot
- TREMBL_PLANTS.ptf
- TREMBL_PLANTS.pto

When I launch `>diamond prepdb -d TREMBL_PLANTS` it creates two` .acc` files
- TREMBL_PLANTS.00.acc
- TREMBL_PLANTS.01.acc

Is it possible to get a single file? In order to be able to launch a single Diamond analysis?

Can I concatenate those files?

thank you.

**Comment by bbuchfink** [comment]
There is one file per database volume, but you can still use the database as a whole.

**Comment by FredericBGA** [comment]
nice! it's perfect. thank you for your answer.
