### ISSUE TITLE
Building on alpine

### ISSUE THREAD

**Issue by bschiffthaler** [bbuchfink/diamond#535]
Hi!

I often build single tool containers, diamond is one of them. To keep the images small, they are based on alpine Linux, which doesn't define `_SC_LEVEL3_CACHE_SIZE` in `gcc` as it's based on MUSL libc, so there are often small differences. I usually patch the source myself, but was wondering if you'd want to upstream the following patch. It's a single change in `src/util/system/system.cpp`

```diff
--- diamond-2.0.13_old/src/util/system/system.cpp
+++ diamond-2.0.13/src/util/system/system.cpp
@@ -195,7 +195,7 @@
 }
 
 size_t l3_cache_size() {
-#if defined(_MSC_VER) || defined(__APPLE__) || defined(__FreeBSD__)
+#if defined(_MSC_VER) || defined(__APPLE__) || defined(__FreeBSD__) || (! defined(_SC_LEVEL3_CACHE_SIZE))
 	return 0;
 #else
 	const auto s = sysconf(_SC_LEVEL3_CACHE_SIZE);

```

**Comment by bbuchfink** [comment]
Added it to the latest master.
