### ISSUE TITLE
diamond makedb error

### ISSUE THREAD

**Issue by Xia991018** [bbuchfink/diamond#537]
Hi Benjamin,

When I tried to make database with command:
diamond makedb --in nr_Euk.fa.gz --db nr_Euk --taxonmap prot.accession2taxid .gz --taxonnodes nodes.dmp
I set the taxonmap parameter.However, the "loading taxonomy mapping file" is not displayed, and there is no error.

Writing accessions... [1.22s]
Hashing sequences... [0.217s]
Loading sequences... [0s]
Writing trailer... [14.375s]

It was used diamond v0.39.34.
Could you please tell how fix the error?

Best wishes,
Xialinfeng

**Comment by bbuchfink** [comment]
I'm not sure about this error, have you tried using the latest diamond version?

**Comment by Xia991018** [comment]
> I'm not sure about this error, have you tried using the latest diamond version?

Thank you, after downloading the latest version, it has been successful

**Comment by Xia991018** [comment]
> I'm not sure about this error, have you tried using the latest diamond version?

Thank you, after downloading the latest version, it has been successful.
