### ISSUE TITLE
Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by ap1438** [bbuchfink/diamond#542]
$ ./diamond --help
Illegal instruction (core dumped)

I tried to install the updated version 2.0.13 and this error came.
The error came for version 2.0.12 also.
But 2.0.11 worked fine.

The same issue was faced while installing diamond in conda environment.
Also when i updated diamond from 2.0.9 to 2.0.13 illigal instruction (core dump) error came.

Can you please help me understand whats the issue with the v12 and v13.

**Comment by bbuchfink** [comment]
It will be fixed in the next release. Also see here: https://github.com/bbuchfink/diamond/issues/540

**Comment by bbuchfink** [comment]
This should be fixed in v2.0.14.

**Comment by ap1438** [comment]
Thanks for the clarification and quick response.
