### ISSUE TITLE
Failed to allocate sufficient memory. Please refer to the manual for instructions on memory usage.

### ISSUE THREAD

**Issue by ap1438** [bbuchfink/diamond#547]
Architecture: x86_64
CPU op-mode(s): 32-bit, 64-bit
Byte Order: Little Endian
CPU(s): 32
On-line CPU(s) list: 0-31
Thread(s) per core: 2
Core(s) per socket: 4
Socket(s): 4
NUMA node(s): 4
Vendor ID: GenuineIntel
CPU family: 6
Model: 45
Model name: Intel(R) Xeon(R) CPU E5-4603 0 @ 2.00GHz
Stepping: 7
CPU MHz: 1971.637
CPU max MHz: 2000.0000
CPU min MHz: 1200.0000
BogoMIPS: 3999.58
Virtualization: VT-x
L1d cache: 32K
L1i cache: 32K
L2 cache: 256K
L3 cache: 10240K
NUMA node0 CPU(s): 0-3,16-19
NUMA node1 CPU(s): 4-7,20-23
NUMA node2 CPU(s): 8-11,24-27
NUMA node3 CPU(s): 12-15,28-31
Flags: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good nopl xtopology nonstop_tsc cpuid aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic popcnt tsc_deadline_timer aes xsave avx lahf_lm epb pti ssbd ibrs ibpb stibp tpr_shadow vnmi flexpriority ept vpid xsaveopt dtherm arat pln pts md_clear flush_l1d

MemTotal: 528354364 kB

This is my CPU information with RAM
I am using diamond version 2.0.11

And my file size is arround 14GB unzipped.
I am using nr.dmd database which is arround 230 GB

So, i got this error
Failed to allocate sufficient memory. Please refer to the manual for instructions on memory usage.

Can anyone help me out on this error.

**Comment by bbuchfink** [comment]
Please let me know your full command line and type of input data.

**Comment by ap1438** [comment]
diamond blastx -d /mnt/USB2/group_gs/Akash/Database/Diamond/nr -q $path/"$filename"-merged.fastq -o $filename-merged_D.daa -f 100.
Input data is a soil metagenomic data with 150 PE reads. To be used by MEGAN for analysis.

**Comment by ap1438** [comment]
I don't know what went wrong that time but later it worked fine.
Thank you for your valuable time and support.
