### ISSUE TITLE
Diamond v2.0.14 make -j4 error and warning 

### ISSUE THREAD

**Issue by ap1438** [bbuchfink/diamond#548]
/mnt/USB2/Tools/diamond/diamond-2.0.14/src/data/seed_array.cpp: In instantiation of ‘SeedArray::SeedArray(Block&, const ShapeHistogram&, const SeedPartitionRange&, char*, const _filter*, const EnumCfg&) [with _filter = NoFilter; ShapeHistogram = std::vector<std::array<unsigned int, 1024> >]’:
/mnt/USB2/Tools/diamond/diamond-2.0.14/src/data/seed_array.cpp:140:136:   required from here
/mnt/USB2/Tools/diamond/diamond-2.0.14/src/data/seed_array.cpp:130:35: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
  for (size_t i = range.begin(); i < range.end(); ++i)
                                 ~~^~~~~~~~~~~~~
/mnt/USB2/Tools/diamond/diamond-2.0.14/src/data/seed_array.cpp: In instantiation of ‘SeedArray::SeedArray(Block&, const ShapeHistogram&, const SeedPartitionRange&, char*, const _filter*, const EnumCfg&) [with _filter = SeedSet; ShapeHistogram = std::vector<std::array<unsigned int, 1024> >]’:
/mnt/USB2/Tools/diamond/diamond-2.0.14/src/data/seed_array.cpp:141:135:   required from here
/mnt/USB2/Tools/diamond/diamond-2.0.14/src/data/seed_array.cpp:130:35: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
/mnt/USB2/ools/diamond/diamond-2.0.14/src/data/seed_array.cpp: In instantiation of ‘SeedArray::SeedArray(Block&, const ShapeHistogram&, const SeedPartitionRange&, char*, const _filter*, const EnumCfg&) [with _filter = HashedSeedSet; ShapeHistogram = std::vector<std::array<unsigned int, 1024> >]’:
/mnt/USB2/Tools/diamond/diamond-2.0.14/src/data/seed_array.cpp:142:141:   required from here
/mnt/USB2/ools/diamond/diamond-2.0.14/src/data/seed_array.cpp:130:35: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]

This was the error while installing the new version 2.0.14 using the tar.gz file .
This error was generated from the make -j4 command mentioned in the manual.
Along with that it showed 2 warnings also 

cc1plus: warning: unrecognized command line option ‘-Wno-unknown-warning-option’
cc1plus: warning: unrecognized command line option ‘-Wno-deprecated-copy’

Should i worry about these error and warnings?

**Comment by bbuchfink** [comment]
I don't see an error in the output that you copied, only warnings. These are nothing to worry about.

**Comment by ap1438** [comment]
Thank You for clarifying.
