### ISSUE TITLE
compliation issue introduced in 0.8.10

### ISSUE THREAD

**Issue by Jehops** [bbuchfink/diamond#55]
Here is a build log showing the problem:
http://pkg.awarnach.mathstat.dal.ca/data/10amd64-default/2016-07-06_02h47m52s/logs/errors/diamond-0.8.10.log.

The problem occurs on both FreeBSD 9.3 and 10.3 amd64.

There were no such problems in 0.8.9.

**Comment by bbuchfink** [comment]
Thanks, this should be fixed in the latest version.

**Comment by Jehops** [comment]
Confirmed.  Thank you.
