### ISSUE TITLE
ERROR: --taxonlist/--taxon-exclude used with invalid argument (0 or 1).

### ISSUE THREAD

**Issue by freixas84** [bbuchfink/diamond#557]
I am getting the above error with a taxonlist file generated from NCBI. Please help!!!!!

**Comment by bbuchfink** [comment]
These parameters do not support using a file, you need to specify the list of taxon ids on the command line.

**Comment by freixas84** [comment]
> These parameters do not support using a file, you need to specify the list of taxon ids on the command line.

Thank you! I figured it out based on a previous comment. So if I limit --taxonlist 4751 my diamond blastx will be limited to fungi?? if I want to add other kingdoms, I just enter their taxid separaed by a comma, without spaces?

**Comment by bbuchfink** [comment]
> Thank you! I figured it out based on a previous comment. So if I limit --taxonlist 4751 my diamond blastx will be limited to fungi?? if I want to add other kingdoms, I just enter their taxid separaed by a comma, without spaces?

Yes correct.
