### ISSUE TITLE
Error while compiling from source diamond-0.8.14

### ISSUE THREAD

**Issue by vagnerfonseca** [bbuchfink/diamond#56]
[ 85%] Building CXX object CMakeFiles/diamond.dir/src/output/output_format.cpp.o
/Users/vagner/Downloads/diamond-0.8.14/src/output/output_format.cpp:124:34: error: 
      use of overloaded operator '<<' is ambiguous (with operand types
      'Text_buffer' and 'uint64_t' (aka 'unsigned long long'))
                << "      <Statistics_db-num>" << ref_header.sequences <...
                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~ ^  ~~~~~~~~~~~~~~~~~~~~
/Users/vagner/Downloads/diamond-0.8.14/src/output/../basic/../util/text_buffer.h:131:15: note: 
      candidate function
        Text_buffer& operator<<(char c)
                     ^
/Users/vagner/Downloads/diamond-0.8.14/src/output/../basic/../util/text_buffer.h:138:15: note: 
      candidate function
        Text_buffer& operator<<(uint32_t x)
                     ^
/Users/vagner/Downloads/diamond-0.8.14/src/output/../basic/../util/text_buffer.h:146:15: note: 
      candidate function
        Text_buffer& operator<<(int x)
                     ^
/Users/vagner/Downloads/diamond-0.8.14/src/output/../basic/../util/text_buffer.h:154:15: note: 
      candidate function
        Text_buffer& operator<<(size_t x)
                     ^
/Users/vagner/Downloads/diamond-0.8.14/src/output/../basic/../util/text_buffer.h:161:15: note: 
      candidate function
        Text_buffer& operator<<(double x)
                     ^
1 error generated.
make[2]: *** [CMakeFiles/diamond.dir/src/output/output_format.cpp.o] Error 1
make[1]: *** [CMakeFiles/diamond.dir/all] Error 2
make: *** [all] Error 2

**Comment by vagnerfonseca** [comment]
g++ --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 6.0 (clang-600.0.57) (based on LLVM 3.5svn)
Target: x86_64-apple-darwin13.4.0
Thread model: posix

**Comment by bbuchfink** [comment]
I've just commited a patch that should fix this. Please clone the latest version of the repo and let me know if this works.

**Comment by vagnerfonseca** [comment]
yes working thanks

but there is warning 

[ 97%] Building CXX object CMakeFiles/diamond.dir/src/data/frequent_seeds.cpp.o
/Users/vagner/Downloads/diamond-master/src/data/frequent_seeds.cpp:54:3: warning: 
      '/*' within block comment [-Wcomment]
                /*size_t n = 0;
                ^
1 warning generated.
