### ISSUE TITLE
Can diamond install on arrch64?

### ISSUE THREAD

**Issue by catslu** [bbuchfink/diamond#570]
Hi Buchfink:

  I am trying to install DIAMOND on my aarch64-linux device. Conda could not install it and I tried to download from github and it also reported an error. 

  Can DIAMOND support to work on arrch64-linux platform? Because I using HUMAnN to analysis metagenome data.

  Thanks for you help!

Sincerely,

Louie

**Comment by bbuchfink** [comment]
I don't provide binaries for that platform but you can compile Diamond from source on it.
