### ISSUE TITLE
Score values are all zero for outfmt6

### ISSUE THREAD

**Issue by hmontenegro** [bbuchfink/diamond#573]
Using DIAMOND 2.0.14, the score column contains only zeros, e.g.:

    TRINITY_DN186147_c0_g1_i1.p1    MRN1_YEAST      60.3    68      27      0       1       68      445     512     8.90e-27        0.0

Just to confirm:

    $ cat diamondp.uniprot.outfmt6 | datamash sum 12
    0

Version 2.0.11 output reasonable score values:

    TRINITY_DN137179_c0_g1_i1.p1    PWP2A_HUMAN     42.1    107     59      1       288     394     616     719     2.60e-18        90.5

Commands:

```
diamond blastp -p 16 -d unitpot.dmnd -q peptides.fas -a diamondp.uniprot -e 1e-5 -k 10 \
    --matrix blosum62 --ultra-sensitive \
    --index-chunks 1 --salltitles
diamond view -a diamondp.uniprot.daa -f 6 -o diamondp.uniprot.outfmt6

```
Both blasp and blastx modes are affected.

**Comment by bbuchfink** [comment]
The bug is confirmed, I will try to provide a fix shortly.

**Comment by bbuchfink** [comment]
Should be fixed in the latest release.
