### ISSUE TITLE
DIAMOND does not report two matches to the same subject region

### ISSUE THREAD

**Issue by shelkmike** [bbuchfink/diamond#575]
I have the following problem:

As a subject for an alignment I use a 50 aa sequence:
MDKFQGYLEFDGARQQSFLYPLFFREYIYVLAYDHGLNRLNRNRYIFLEN

As a query I use the same sequence but repeated two times:
MDKFQGYLEFDGARQQSFLYPLFFREYIYVLAYDHGLNRLNRNRYIFLENMDKFQGYLEFDGARQQSFLYPLFFREYIYVLAYDHGLNRLNRNRYIFLEN

When Blastp from BLAST 2.11.0 aligns this query to this subject, it correctly reports two matches. However, when I use DIAMOND 2.0.13 it reports only one match, even though I use --max-hsps 100. How can I make DIAMOND to report both matches?

**Comment by bbuchfink** [comment]
Have you tried using `--masking 0`?

**Comment by shelkmike** [comment]
Yes, I have. Still reports one match instead of two.

**Comment by bbuchfink** [comment]
This is also affected by hit culling, as the subject range of the two alignments in the same. Try using `--culling-overlap 200`.

**Comment by shelkmike** [comment]
This doesn't help either. The command I use is
`diamond blastp --query protein_sequence_repeated_two_times.fasta --threads 1 --db protein_sequence.fasta --out results --masking 0 --culling-overlap 200 --outfmt 0 --max-target-seqs 100 --max-hsps 100`

**Comment by bbuchfink** [comment]
You can find that HSP if sequence 1 is the query, but not if it's the target. That's because the range of the primary HSP is masked in the target before recomputing the alignment. That is a limitation at the moment I'm afraid for which there is no workaround.

**Comment by shelkmike** [comment]
Thank you

**Comment by sanyalab** [comment]
Hello,

Related to the above question, I wanted to know whether diamond can combine HSP's and summarize it into a single hit between query and subject. For example See below

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/sanyalab/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/sanyalab/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



query | subject | %idn | aln_l | mis | gap | qs | qe | ss | se | ev | sc | qcov | scov
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
QueryA | SubjectB | 88.372 | 258 | 29 | 1 | 1 | 257 | 94 | 351 | 1.10E-161 | 469 | 93.455 | 33.55
QueryA | SubjectB | 60 | 280 | 101 | 5 | 5 | 275 | 489 | 766 | 4.07E-110 | 336 | 98.545 | 36.151



</body>

</html>


If I were to summarize the HSP's above into one hit that captures the homology between query and subject, is there a method in diamond to implement that? 

Thank you
Abhijit
