### ISSUE TITLE
tmpdir cannot be seen

### ISSUE THREAD

**Issue by Biofarmer** [bbuchfink/diamond#577]
Hi, may I ask whether the --tmpdir can be seen in the specified directory during running diamond? Thanks

**Comment by bbuchfink** [comment]
I'm not sure what you mean, if the temp files can be seen in that directory? Normally not, since `unlink` is called on them upon creation.

**Comment by Biofarmer** [comment]
Hi, thanks, I mean when running diamond, I cannot see any temporary folder or files produced in the output directory (where I set the --tmpdir), is that normal?

**Comment by bbuchfink** [comment]
Yes that's normal, to make the files visible you can set `--no-unlink`.

**Comment by Biofarmer** [comment]
Okay, but the temporary folder or files are for sure in the specified pathway, right?

**Comment by bbuchfink** [comment]
Yes.

**Comment by Biofarmer** [comment]
Many thanks!

**Comment by Biofarmer** [comment]
Hi, may I further ask a question? If the --tmpdir pathway is set as "current working directory", and the output directory is another pathway (not current working directory). If I run several jobs from the same current working directory in parallel, with different output directories, may I ask whether diamond will select the right temporary files from the same current working directory? Is the temporary file of each job with different names? Thanks

**Comment by bbuchfink** [comment]
Yes you can use the same working/temporary directory for multiple diamond runs, that is not a problem.

**Comment by Biofarmer** [comment]
Hi, thanks for confirmation. May I ask a bit how diamond select the right temporary file from the same current working directory? Is the name of temporary file of each run different? Thanks

**Comment by bbuchfink** [comment]
It is done using the `mkstemp` system call.

**Comment by Biofarmer** [comment]
Thanks, and it's good to learn.
