### ISSUE TITLE
XML output

### ISSUE THREAD

**Issue by raphenya** [bbuchfink/diamond#58]
```
<Hit>
  <Hit_num>1</Hit_num>
  <Hit_id></Hit_id>
  <Hit_def>199_1718 | model_type_id: 40292 | pass_evalue: 1e-150</Hit_def> 
  <Hit_accession></Hit_accession>
  <Hit_len>378</Hit_len>
  <Hit_hsps>
```

To  set `Hit_def` you use `--salltitles`

But which option do we use to populate the `<Hit_id></Hit_id>` and `<Hit_accession></Hit_accession>` ?

@bbuchfink

**Comment by bbuchfink** [comment]
It's currently not supported, because blast fills these with some internal values only, as far as I know. But I could add this in a future version.

**Comment by raphenya** [comment]
@bbuchfink Thank you. It will be a nice addition.
