### ISSUE TITLE
makedb run time

### ISSUE THREAD

**Issue by hnote123** [bbuchfink/diamond#581]
Hi,

Is this supposed to happen? It's been going on continuously since I entered the makedb line a while ago

c:\Users\hnoteboom\Diamond>diamond makedb --in nr.gz.gz --db nr
diamond v2.0.14.152 (C) Max Planck Society for the Advancement of Science
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 16
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
Database input file: nr.gz.gz
Opening the database file...  [0.002s]
Loading sequences...  [11.242s]
Masking sequences...  [5.259s]
Writing sequences...  [0.424s]
Hashing sequences...  [0.296s]
Loading sequences...  [11.165s]
Masking sequences...  [5.268s]
Writing sequences...  [0.409s]
Hashing sequences...  [0.303s]
Loading sequences...  [11.134s]
Masking sequences...  [5.295s]
Writing sequences...  [0.404s]
Hashing sequences...  [0.309s]
Loading sequences...  [11.202s]
Masking sequences...  [5.254s]
Writing sequences...  [0.431s]
Hashing sequences...  [0.298s]
Loading sequences...  [11.181s]
Masking sequences...  [5.267s]
Writing sequences...  [0.422s]
Hashing sequences...  [0.29s]
Loading sequences...  [11.208s]
Masking sequences...  [5.313s]
Writing sequences...  [0.39s]
Hashing sequences...  [0.294s]
Loading sequences...  [11.179s]
Masking sequences...  [5.245s]

Thanks

**Comment by bbuchfink** [comment]
yes!

**Comment by hnote123** [comment]
Thanks! Should it take a couple hours?
