### ISSUE TITLE
Cannot update to the latest version

### ISSUE THREAD

**Issue by haochh** [bbuchfink/diamond#590]
Hi there,

 I would like to install DIAMOND on the server via Bioconda. After running 'conda install -c bioconda diamond', the diamond is version 0.9.14. Then I tried to update the version by running 'conda update diamond'. No error occurred, but it was still the same old version! The conda I am using is version 4.9.2. 

I also tried to download it locally on my mac. The two lines of code all ran well. But when I tried to check the version by executing 'diamond version', the error said 'cannot execute binary file'. I supposed this might be due to a permission issue, so I opened all the permissions, but still the same error. 

Could you please help me with these two problems? Sorry if I am so stupid, I am quite new to Linux and python.

Many thanks,
Chunhui

**Comment by bbuchfink** [comment]
Please see if this solution works for you: https://github.com/bbuchfink/diamond/issues/474

How did you download it on your mac, using conda as well?

**Comment by haochh** [comment]
Thank you for your reply. Yes! I used conda to download it on my mac. I will try this solution first!

**Comment by haochh** [comment]
Hi, I've tried conda config --add channels conda-forge but this does not work for me. 

(base) kakuharus-MacBook-Pro:~ haochunhui$ conda install diamond=2.0.13
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - diamond=2.0.13

Current channels:

  - https://conda.anaconda.org/conda-forge/osx-64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/osx-64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.

**Comment by bbuchfink** [comment]
I'd recommend downloading the release binary from github instead, or compiling from source. For mac you can also try homebrew.

**Comment by haochh** [comment]
Okay, thanks!
