### ISSUE TITLE
Thread Usage During Computing Alignments Stage

### ISSUE THREAD

**Issue by raufs** [bbuchfink/diamond#592]
Hi, 

I am using Diamond v2.0.8 for a self-alignment of a large FASTA file. While the program uses the requested threads (set using `-p`) for the majority of its course, during one of the final steps `Computing alignments...` (when writing to file) it appears to exceed the requested number of threads and can briefly use 60-70 threads in short bursts. Is there a solution to avoid ? Would writing to a daa file first and subsequently using `view` avoid this issue from happening? 

Thank you!
Rauf

**Comment by bbuchfink** [comment]
What number of threads did you request? There is one thing that could be causing this. Try setting `--query-parallel-limit 2000000000`.

**Comment by raufs** [comment]
Awesome, thank you!! That seems to have worked! I requested 40 threads both times.
