### ISSUE TITLE
Out of memory for all-vs-all search

### ISSUE THREAD

**Issue by CuriousTim** [bbuchfink/diamond#597]
Hello,
I am trying to do an all-vs-all search with about 800K sequences for the purposes of clustering and diamond is unable to complete the alignment computation step because there is not enough memory. I am using a computer with 32G of RAM which I thought would be reasonable for a fairly small protein set. I tried using `--block-size 0.4` and even that doesn't work. I guess the block size doesn't really matter for the alignment computation step.

I also tried with an even smaller query set of ~150K sequences and set a the memory limit with `--memory-limit` and memory usage just explodes at the alignment computation step until the program is killed.

Are there some parameters that I can use to get the memory usage under control or is it unreasonable to try this search with 32G RAM?

**Comment by bbuchfink** [comment]
Try to increase the `--bin` parameter (e.g `--bin 64`). What are your command line options and your diamond version?

**Comment by CuriousTim** [comment]
I am using version `2.0.15`
I initially tried
```
diamond blastp --outfmt 6 --sensitive --no-self-hits --evalue 0.00001 --id 40 --query-cover 80 --subject-cover 80 --threads 8 --max-target-seqs 500
```
I omit query/db/out options for brevity.

I then experimented with different `--block-size` parameters: `1` and `0.4`.
I experimented with different `--index-chunks` parameters: `1` and `2`.
I experimented with different sensitivities: `--fast` and the default
I did try `--bin 64` at some point after reading through the other issues.
I tried lower `--max-target-seqs`:  `500`, `25`,  `5`.
I tried setting lower `--global-ranking`

I was eventually able to complete a search using a reduced protein set of `~80K` sequences with the following command
```
diamond blastp --outfmt 6 --max-target-seqs 500 --threads 8 --evalue 0.00001 --bin 64
```
but the memory usage gets past 20GB so I doubt it will scale. I noticed that there are more than 101M alignments reported for 80K sequences so I am guessing that the sequences are very similar (this is expected; they are all the same kind of protein) and too many sequences are passing through to the alignment stage. I thought `--global-ranking` would address this issue, but am I misunderstanding this option?

**Comment by bbuchfink** [comment]
Global ranking does not really fix this since it still means that all seeds hits have to be written to disk and read back in. If this call works for 200k sequences you should be able to set a block size accordingly such that 200k sequences correspond to one block and process the whole dataset like this.

**Comment by CuriousTim** [comment]
It seems I will need an HPC environment to scale anyways so I will try that. Thank you for your help.
