### ISSUE TITLE
Default for query genetic code

### ISSUE THREAD

**Issue by ilnamkang** [bbuchfink/diamond#6]
Hello,

I'd like to know the default value for query genetic code in Diamond.

Further, can I change the default genetic code in command line?

Thanks.

**Comment by bbuchfink** [comment]
The default is the same as for blast, the standard code. It's not possible to change it on the command line at the moment, although that would be fairly easy to add.

**Comment by nekrut** [comment]
The inability to set the genetic code would be a major objection for using diamond in cases where organellar genomes are involved such as surveys of plant biodiversity.

**Comment by bgruening** [comment]
:+1:  for this feature

**Comment by RNAer** [comment]
👍 for this feature too. It would be great to be able to set genetic code.

**Comment by bbuchfink** [comment]
Ok, I will implement this. It should be ready in the next days.

**Comment by bbuchfink** [comment]
Latest version now has the option to change the genetic code.

**Comment by RNAer** [comment]
Thanks!
