### ISSUE TITLE
case of matrix parameter

### ISSUE THREAD

**Issue by jvolkening** [bbuchfink/diamond#60]
Somewhere between v0.7.10 and v0.8.16, the accepted values for `--matrix` changed from uppercase to lowercase - I had to look through the source to figure out why I was now getting an "Invalid scoring matrix" error. It would be helpful to either update the documentation to reflect the case change (e.g. in the "Scoring matrices" table and the default parameter section) or to accept either case in the parameter parsing.

**Comment by bbuchfink** [comment]
Sorry, didn't realize that. I'll have it accept uppercase again in the next version.

**Comment by bbuchfink** [comment]
This should be fixed in the latest version.
