### ISSUE TITLE
Package diamond using conda

### ISSUE THREAD

**Issue by raphenya** [bbuchfink/diamond#61]
Hi,

Currenlty most of the [galaxyproject](https://galaxyproject.org/) community is packaging their software using bioconda-conda (https://github.com/bioconda/bioconda-recipes). The motivation being resolving dependencies with ease.

@bbuchfink Is there a plan to package diamond using conda? 

Cheers.

**Comment by bbuchfink** [comment]
No plan yet but I'll look into it and see if this would work well for diamond.

**Comment by raphenya** [comment]
@bbuchfink Thank you!
