### ISSUE TITLE
`prepdb` not available in conda install

### ISSUE THREAD

**Issue by EvanKomp** [bbuchfink/diamond#621]
Hello.

I would like to include Diamond as a dependency in my project (thanks for making it conda available!). My workflow already creates a blast style database, so the `prepdb` command is ideal for my use case, however both on mac and linux, the command is not available, only `makedb`

I would rather not have a dependency that requires building from source in order to get the command. For reference, the Diamond versions installed through conda on linux and mac that I have tried:

linux - `diamond                   2.0.15               hb97b32f_1    bioconda`
mac - `diamond                   2.0.15               h9d1909e_1    bioconda`

Thanks for any help.

**Comment by bbuchfink** [comment]
Adding blast database support to conda is not trivial unfortunately. It's on my todo list but it may still take some time.
