### ISSUE TITLE
Calculate self scores without alignment

### ISSUE THREAD

**Issue by snayfach** [bbuchfink/diamond#631]
I'd like to calculate the DIAMOND bit score of a protein sequence aligned to itself without actually doing the alignment. Any thoughts on how to do this? 

I've used the BLOSUM62 matrix to calculate the sum of self-scores for all amino acids in a protein, but that result differs from the bit score reported by DIAMOND.

**Comment by bbuchfink** [comment]
It is pretty involved if you want to exactly reproduce diamond's computation. First, tantan masking needs to be applied to the sequences. Then, to compute the raw scores diamond uses composition based score adjustment as described here: https://academic.oup.com/bioinformatics/article/32/9/1323/1744460
This gives you the raw score, to compute the bitscore use (lambda * raw_score - ln(K)) / ln(2). Lambda and K are constants depending on the score matrix.

**Comment by snayfach** [comment]
Thanks for the detailed reply - I'll give that a shot!
