### ISSUE TITLE
Unable to process some files - segmentation fault

### ISSUE THREAD

**Issue by brymerr921** [bbuchfink/diamond#64]
Hi,

I'm trying to run BLASTX on a batch of files that are similar in size (~8GB) and have similar numbers of reads and all but two samples worked great. I used this command on a supercomputer with 48 cores and a total of 192GB of RAM.

`diamond blastx -d ORFs_160722 -q reads.fastq.trimmed.fna -o results.txt -e 0.001 -c 1 -p 48 -f tab --sensitive --log`

It ran up until this point:
```
diamond v0.8.17.79 | by Benjamin Buchfink <buchfink@gmail.com>
Check http://github.com/bbuchfink/diamond for updates.

#CPU threads: 48
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
SEG masking = 1
SSSE3 enabled.
Reduction: [RNDQEK][C][G][H][M][F][Y][ILV][W][P][AST]
Seed frequency SD: 10
Shape configuration: 1111011111,111001101111,11101100101011,11010010111011,111010100001111,1110100011001011,11100010100101011,11011000001100111,1101010010000010111,11100001000100100111,110110000100010001101,1110000100001000101011,1101010000010001001011,1101001001000010000111,1101000100100000100000111,1110001000100000001010011
#Target sequences to report alignments for: 25
Temporary directory: /output
Opening the database...  [0.005895s]
Reference = ORFs_160722.dmnd
Sequences = 3029237
Letters = 253191948
Block size = 2000000000
Opening the input file...  [0.04896s]
Opening the output file...  [0.002258s]
Loading query sequences...  [43.1384s]
Sequences = 44007924, letters = 2000000298, average length = 45
Running complexity filter...  [40.9201s]
Building query histograms...
```

And then stopped and gave this error:
`/var/spool/slurmd/job9198232/slurm_script: line 34: 35623 Segmentation fault`

Since it worked great on all but two reads files I'm thinking it may be a file-specific issue, but don't know where to look to figure out what is causing it to have a segmentation fault at this particular step with both of these files. Thanks.

**Comment by bbuchfink** [comment]
Hi,
I realize that 8 GB files are pretty big, but do you have a way of making the file available to me?

**Comment by brymerr921** [comment]
Yes, I can share a OneDrive link after it uploads.

**Comment by brymerr921** [comment]
Here's a link to the file.
https://office365stanford-my.sharepoint.com/personal/bmerrill_stanford_edu/_layouts/15/guestaccess.aspx?guestaccesstoken=9RGWjj%2behnVTgiHPr5lHCIR96dutOIX70adypBi0hpg%3d&docid=0b3cc57862e5b46b98769f1464ccfa529&rev=1&expiration=2016-08-03T23%3a15%3a37.000Z

**Comment by bbuchfink** [comment]
I think I found the problem, could you please clone the latest version of the repo and see if this works.

**Comment by brymerr921** [comment]
Thanks for the quick fix. I think it's working because it got much farther past "Building query histograms." Unfortunately the process wasn't able to run to completion because of other unrelated issues with the supercomputer that suddenly popped up that I'm working to get ironed out. It's looking very good, and I'll update you when I can get it to run to completion.

**Comment by brymerr921** [comment]
Everything worked great. Thanks for the fix.
