### ISSUE TITLE
DIAMOND-windows needs C++ 2015 

### ISSUE THREAD

**Issue by DustinChen1986** [bbuchfink/diamond#65]
I can not run the DIAMOND-windows in my Win7 system computer. And I find the DIAMOND is implemented in C++. So I try to install the recent C++ 2015.  Then it is OK. 

Therefor, I just let someone, who want to try DIAMOND in Winows system, know this to save time here.

**Comment by bbuchfink** [comment]
You're right, I've added this to the readme.
