### ISSUE TITLE
The result .m8 file!

### ISSUE THREAD

**Issue by ErisonChen** [bbuchfink/diamond#66]
I'm new here of the blast software.

Please help me with the meaning of each columns in the result .m8 file.

Thanks so much!

**Comment by bbuchfink** [comment]
The meaning is the same as for blast generated files, see here for example:
http://www.drive5.com/usearch/manual/blast6out.html

**Comment by ErisonChen** [comment]
Hi again!
I found that the fifth coloum names "_Number of mismatches_" and the sixth coloum is "Number of gap opens."

I am striving to know What does the mismatches really mean. Cause i noticed that the "Number of gap opens. / Alignment length." is close to 50%.

**Comment by ErisonChen** [comment]
This really confused me a lot, Please help me!

**Comment by bbuchfink** [comment]
Mismatches is the number of letters in the alignment that do not match between the query and the subject sequence.

**Comment by ErisonChen** [comment]
![image](https://cloud.githubusercontent.com/assets/11779421/17764280/e9dc0514-6550-11e6-8b51-4944a304c3c6.png)

I made a mistake before. Sorry .
I really want to ask is the  correlation between "_Number of mismatches_" and "_Alignment length_."

Just like the picture i submitted. The percents of  "_Number of mismatches_" to "_Alignment length_."

are all near 50%. Does that mean something?  Why is it so high？
 May be i go to the wrong way to think .Could you help me to figure it .

**Comment by bbuchfink** [comment]
It means your alignments have around 50% identity. That is normal for protein alignments, nothing to worry about.
