### ISSUE TITLE
diamond.exe not running successfully on windows virtual machine

### ISSUE THREAD

**Issue by emmamglass** [bbuchfink/diamond#660]
I am trying to run diamond on a windows virtual machine (windows 11, via parallels desktop). I am running a command I am able to successfully run on a Mac, but when I run it on the windows VM it just prints out a blank line and doesn't save to the specified output file (see screenshot below). I have tried to use several different releases of the diamond program but all of them result in the same failed output. I have tried the command using both "diamond.exe" and just "diamond". Any tips? 

![Screen Shot 2023-02-09 at 11 56 20 AM](https://user-images.githubusercontent.com/93220912/217883838-c8ae0d8a-425b-4d55-b20d-f288e72d4ddb.png)

**Comment by bbuchfink** [comment]
Can you tell me the specs of the host system, the CPU in particular?

**Comment by emmamglass** [comment]
The host system is a MacBook Pro running Monterey (version 12.6), with an apple M1 max processor

**Comment by emmamglass** [comment]
Sorry, forgot to mention the CPU. It has 10 Core CPU

**Comment by bbuchfink** [comment]
Could you try if it works with this executable?

[diamond.zip](https://github.com/bbuchfink/diamond/files/10707269/diamond.zip)

**Comment by emmamglass** [comment]
This works perfectly! Thank you! Would this work on a regular windows machine as well? Or is is specifically for virtual machines

**Comment by bbuchfink** [comment]
> This works perfectly! Thank you! Would this work on a regular windows machine as well?

yes

**Comment by bbuchfink** [comment]
Hi @emmamglass, would it be possible that you test this new binary on your Windows VM: https://github.com/bbuchfink/diamond/releases/download/v2.1.6/diamond-windows.zip

I have recently done some work to improve compatibility but don't have an older Windows system to test this myself.
