### ISSUE TITLE
cluster-steps Error options

### ISSUE THREAD

**Issue by kullrich** [bbuchfink/diamond#663]
Dear Benjamin,

If one chooses a wrong parameter for the `diamond cluster --cluster-steps` parameter, the following Error is printed:

`Permitted values: default, fast, faster, mid-sensitive, more-sensitive, sensitive, ultra-sensitive, very-sensitive`

As a suggestion, I would order them not alpha-numeric but according to the sensitivity, so that the user gets not confused by the applied sensitivity level:
e.g.:
`Permitted values: faster, fast, mid-sensitive, sensitive (default), more-sensitive, very-sensitive, ultra-sensitive`

Best regards

Kristian

**Comment by bbuchfink** [comment]
Thanks that's probably a good idea.
