### ISSUE TITLE
compiling 0.8.18 from scratch

### ISSUE THREAD

**Issue by Wildish-LBL** [bbuchfink/diamond#68]
Hi,

I'm trying to compile 0.8.18 from scratch, and get an error which suggests there's a problem with the architecture chosen by cmake (version 3.4.3 or 2.8.12.2, both give the same result):

> cmake  ..
-- The C compiler identification is GNU 4.9.2
-- The CXX compiler identification is GNU 4.9.2
-- Check for working C compiler: /usr/common/usg/languages/gcc/4.9.2/bin/gcc
-- Check for working C compiler: /usr/common/usg/languages/gcc/4.9.2/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Detecting C compile features
-- Detecting C compile features - done
-- Check for working CXX compiler: /usr/common/usg/languages/gcc/4.9.2/bin/g++
-- Check for working CXX compiler: /usr/common/usg/languages/gcc/4.9.2/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
-- Detecting CXX compile features
-- Detecting CXX compile features - done
-- Performing Test COMPILER_SUPPORTS_MARCHNATIVE
-- Performing Test COMPILER_SUPPORTS_MARCHNATIVE - Success
-- Found ZLIB: /usr/lib/libz.so (found version "1.2.3.4") 
-- Looking for pthread.h
-- Looking for pthread.h - found
-- Looking for pthread_create
-- Looking for pthread_create - not found
-- Looking for pthread_create in pthreads
-- Looking for pthread_create in pthreads - not found
-- Looking for pthread_create in pthread
-- Looking for pthread_create in pthread - found
-- Found Threads: TRUE  
-- Configuring done
-- Generating done
-- Build files have been written to: /usr/common/jgi/aligners/diamond/build/diamond-0.8.18/bin

> make
Scanning dependencies of target diamond
[  2%] Building CXX object CMakeFiles/diamond.dir/src/run/main.cpp.o
/scratch/ccbm7hDX.s: Assembler messages:
/scratch/ccbm7hDX.s:8712: Error: no such instruction: `shlx %ebx,%eax,%eax'
/scratch/ccbm7hDX.s:9035: Error: no such instruction: `shlx %ebp,%edx,%edx'
/scratch/ccbm7hDX.s:11887: Error: no such instruction: `andn %eax,%ecx,%eax'
/scratch/ccbm7hDX.s:11907: Error: no such instruction: `andn %eax,%ecx,%eax'
/scratch/ccbm7hDX.s:19043: Error: no such instruction: `shlx %r11d,%r12d,%r8d'
/scratch/ccbm7hDX.s:22685: Error: no such instruction: `vinserti128 $0x1,statistics+16(%rip),%ymm0,%ymm0'
/scratch/ccbm7hDX.s:22686: Error: suffix or operands invalid for `vpaddq'
/scratch/ccbm7hDX.s:22688: Error: no such instruction: `vextracti128 $0x1,%ymm0,statistics+16(%rip)'
/scratch/ccbm7hDX.s:22690: Error: no such instruction: `vinserti128 $0x1,statistics+48(%rip),%ymm0,%ymm0'
/scratch/ccbm7hDX.s:22691: Error: suffix or operands invalid for `vpaddq'
/scratch/ccbm7hDX.s:22693: Error: no such instruction: `vextracti128 $0x1,%ymm0,statistics+48(%rip)'
/scratch/ccbm7hDX.s:22695: Error: no such instruction: `vinserti128 $0x1,statistics+80(%rip),%ymm0,%ymm0'
/scratch/ccbm7hDX.s:22696: Error: suffix or operands invalid for `vpaddq'
/scratch/ccbm7hDX.s:22698: Error: no such instruction: `vextracti128 $0x1,%ymm0,statistics+80(%rip)'
/scratch/ccbm7hDX.s:22700: Error: no such instruction: `vinserti128 $0x1,statistics+112(%rip),%ymm0,%ymm0'
/scratch/ccbm7hDX.s:22701: Error: suffix or operands invalid for `vpaddq'
/scratch/ccbm7hDX.s:22703: Error: no such instruction: `vextracti128 $0x1,%ymm0,statistics+112(%rip)'
/scratch/ccbm7hDX.s:22705: Error: no such instruction: `vinserti128 $0x1,statistics+144(%rip),%ymm0,%ymm0'
/scratch/ccbm7hDX.s:22706: Error: suffix or operands invalid for `vpaddq'
/scratch/ccbm7hDX.s:22708: Error: no such instruction: `vextracti128 $0x1,%ymm0,statistics+144(%rip)'
/scratch/ccbm7hDX.s:22710: Error: no such instruction: `vinserti128 $0x1,statistics+176(%rip),%ymm0,%ymm0'
/scratch/ccbm7hDX.s:22711: Error: suffix or operands invalid for `vpaddq'
/scratch/ccbm7hDX.s:22713: Error: no such instruction: `vextracti128 $0x1,%ymm0,statistics+176(%rip)'
/scratch/ccbm7hDX.s:22715: Error: no such instruction: `vinserti128 $0x1,statistics+208(%rip),%ymm0,%ymm0'
/scratch/ccbm7hDX.s:22716: Error: suffix or operands invalid for `vpaddq'
/scratch/ccbm7hDX.s:22718: Error: no such instruction: `vextracti128 $0x1,%ymm0,statistics+208(%rip)'
/scratch/ccbm7hDX.s:23404: Error: no such instruction: `shlx %r9d,%r12d,%r10d'
/scratch/ccbm7hDX.s:25246: Error: no such instruction: `shlx %rax,8(%rdi),%rbp'
/scratch/ccbm7hDX.s:36522: Error: no such instruction: `vinserti128 $0x1,statistics+16(%rip),%ymm0,%ymm0'
/scratch/ccbm7hDX.s:36523: Error: suffix or operands invalid for `vpaddq'
/scratch/ccbm7hDX.s:36525: Error: no such instruction: `vextracti128 $0x1,%ymm0,statistics+16(%rip)'
/scratch/ccbm7hDX.s:36527: Error: no such instruction: `vinserti128 $0x1,statistics+48(%rip),%ymm0,%ymm0'
/scratch/ccbm7hDX.s:36528: Error: suffix or operands invalid for `vpaddq'
/scratch/ccbm7hDX.s:36530: Error: no such instruction: `vextracti128 $0x1,%ymm0,statistics+48(%rip)'
/scratch/ccbm7hDX.s:36532: Error: no such instruction: `vinserti128 $0x1,statistics+80(%rip),%ymm0,%ymm0'
/scratch/ccbm7hDX.s:36533: Error: suffix or operands invalid for `vpaddq'
/scratch/ccbm7hDX.s:36535: Error: no such instruction: `vextracti128 $0x1,%ymm0,statistics+80(%rip)'
/scratch/ccbm7hDX.s:36537: Error: no such instruction: `vinserti128 $0x1,statistics+112(%rip),%ymm0,%ymm0'
/scratch/ccbm7hDX.s:36538: Error: suffix or operands invalid for `vpaddq'
/scratch/ccbm7hDX.s:36540: Error: no such instruction: `vextracti128 $0x1,%ymm0,statistics+112(%rip)'
/scratch/ccbm7hDX.s:36542: Error: no such instruction: `vinserti128 $0x1,statistics+144(%rip),%ymm0,%ymm0'
/scratch/ccbm7hDX.s:36543: Error: suffix or operands invalid for `vpaddq'
/scratch/ccbm7hDX.s:36545: Error: no such instruction: `vextracti128 $0x1,%ymm0,statistics+144(%rip)'
/scratch/ccbm7hDX.s:36547: Error: no such instruction: `vinserti128 $0x1,statistics+176(%rip),%ymm0,%ymm0'
/scratch/ccbm7hDX.s:36548: Error: suffix or operands invalid for `vpaddq'
/scratch/ccbm7hDX.s:36550: Error: no such instruction: `vextracti128 $0x1,%ymm0,statistics+176(%rip)'
/scratch/ccbm7hDX.s:36552: Error: no such instruction: `vinserti128 $0x1,statistics+208(%rip),%ymm0,%ymm0'
/scratch/ccbm7hDX.s:36553: Error: suffix or operands invalid for `vpaddq'
/scratch/ccbm7hDX.s:36555: Error: no such instruction: `vextracti128 $0x1,%ymm0,statistics+208(%rip)'
/scratch/ccbm7hDX.s:37041: Error: no such instruction: `shlx %ecx,%eax,%eax'
/scratch/ccbm7hDX.s:37271: Error: no such instruction: `shlx %r12d,%edx,%edx'
/scratch/ccbm7hDX.s:43383: Error: no such instruction: `shlx %edi,%eax,%eax'
/scratch/ccbm7hDX.s:43842: Error: no such instruction: `shlx %r14d,%eax,%eax'
/scratch/ccbm7hDX.s:43921: Error: no such instruction: `shlx %edi,%eax,%eax'
/scratch/ccbm7hDX.s:44091: Error: no such instruction: `vinserti128 $0x1,statistics+16(%rip),%ymm0,%ymm0'
/scratch/ccbm7hDX.s:44092: Error: suffix or operands invalid for `vpaddq'
/scratch/ccbm7hDX.s:44094: Error: no such instruction: `vextracti128 $0x1,%ymm0,statistics+16(%rip)'
/scratch/ccbm7hDX.s:44096: Error: no such instruction: `vinserti128 $0x1,statistics+48(%rip),%ymm0,%ymm0'
/scratch/ccbm7hDX.s:44097: Error: suffix or operands invalid for `vpaddq'
/scratch/ccbm7hDX.s:44099: Error: no such instruction: `vextracti128 $0x1,%ymm0,statistics+48(%rip)'
/scratch/ccbm7hDX.s:44101: Error: no such instruction: `vinserti128 $0x1,statistics+80(%rip),%ymm0,%ymm0'
/scratch/ccbm7hDX.s:44102: Error: suffix or operands invalid for `vpaddq'
/scratch/ccbm7hDX.s:44104: Error: no such instruction: `vextracti128 $0x1,%ymm0,statistics+80(%rip)'
/scratch/ccbm7hDX.s:44106: Error: no such instruction: `vinserti128 $0x1,statistics+112(%rip),%ymm0,%ymm0'
/scratch/ccbm7hDX.s:44107: Error: suffix or operands invalid for `vpaddq'
/scratch/ccbm7hDX.s:44109: Error: no such instruction: `vextracti128 $0x1,%ymm0,statistics+112(%rip)'
/scratch/ccbm7hDX.s:44111: Error: no such instruction: `vinserti128 $0x1,statistics+144(%rip),%ymm0,%ymm0'
/scratch/ccbm7hDX.s:44112: Error: suffix or operands invalid for `vpaddq'
/scratch/ccbm7hDX.s:44114: Error: no such instruction: `vextracti128 $0x1,%ymm0,statistics+144(%rip)'
/scratch/ccbm7hDX.s:44116: Error: no such instruction: `vinserti128 $0x1,statistics+176(%rip),%ymm0,%ymm0'
/scratch/ccbm7hDX.s:44117: Error: suffix or operands invalid for `vpaddq'
/scratch/ccbm7hDX.s:44119: Error: no such instruction: `vextracti128 $0x1,%ymm0,statistics+176(%rip)'
/scratch/ccbm7hDX.s:44121: Error: no such instruction: `vinserti128 $0x1,statistics+208(%rip),%ymm0,%ymm0'
/scratch/ccbm7hDX.s:44122: Error: suffix or operands invalid for `vpaddq'
/scratch/ccbm7hDX.s:44124: Error: no such instruction: `vextracti128 $0x1,%ymm0,statistics+208(%rip)'
/scratch/ccbm7hDX.s:44399: Error: no such instruction: `shrx %eax,-13(%r12),%ecx'
/scratch/ccbm7hDX.s:44405: Error: no such instruction: `shrx %edi,(%rax),%edx'
/scratch/ccbm7hDX.s:44431: Error: no such instruction: `shrx %edi,(%rax),%edx'
/scratch/ccbm7hDX.s:47894: Error: no such instruction: `shlx %rax,-72(%rbp),%rax'
/scratch/ccbm7hDX.s:50220: Error: no such instruction: `shlx %ecx,%edx,%edx'
make[2]: *** [CMakeFiles/diamond.dir/src/run/main.cpp.o] Error 1
make[1]: *** [CMakeFiles/diamond.dir/all] Error 2
make: *** [all] Error 2

Any suggestions?

Thanks in advance,
Tony.

**Comment by bbuchfink** [comment]
Hi,
what are your system and hardware specs?

**Comment by Wildish-LBL** [comment]
Hi,

wow, that's what I call a fast response!

it's a Debian derivative, running kernel 2.6.32.

> cat /proc/cpuinfo | egrep 'flags|model name' | tail -2
model name	: Intel(R) Xeon(R) CPU E5-2698 v3 @ 2.30GHz
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx pdpe1gb rdtscp lm constant_tsc arch_perfmon pebs bts rep_good xtopology nonstop_tsc aperfmperf pni pclmulqdq dtes64 monitor ds_cpl vmx smx est tm2 ssse3 fma cx16 xtpr pdcm pcid dca sse4_1 sse4_2 x2apic movbe popcnt tsc_deadline_timer aes xsave avx f16c rdrand lahf_lm abm ida arat epb xsaveopt pln pts dts tpr_shadow vnmi flexpriority ept vpid fsgsbase bmi1 avx2 smep bmi2 erms invpcid

**Comment by bbuchfink** [comment]
No idea how this happens. If you give me your precise distro version I can try to reproduce the problem.

**Comment by Wildish-LBL** [comment]
Hi,

that's not so easy, it's a lab-maintained machine which doesn't have a precisely defined version that could be easily reproduced. The basis is Debian 6, but it's probably been patched a few times so I don't know how to characterize it today.

Maybe we can try another approach: can you tell me what version of gcc/cmake/anything-else you use, I can try compiling with them?

**Comment by bbuchfink** [comment]
First you can try to compile using the build_simple.sh script included in the package, and using the precompiled binary version.

**Comment by Wildish-LBL** [comment]
build_simple.sh works, so does the pre-compiled binary.

I'm reluctant to use the pre-compiled binary though, since I'm installing this for a number of users on a cluster, and prefer to have native compilations.

**Comment by bbuchfink** [comment]
If the build_simple script works then ok, no reason not to use that.

**Comment by Wildish-LBL** [comment]
OK, thanks. I was concerned I might not get the full level of optimization with that, but if that's not the case then it's perfect.

Thanks for the really fast support, I appreciate it!
