### ISSUE TITLE
`prepdb` not working in v2.1.4

### ISSUE THREAD

**Issue by xinehc** [bbuchfink/diamond#680]
Hi,

`prepdb` seems not working in v2.1.4. It returns an error saying that the database is not a blast database, after loading all files. Here is one example (also tested for nr):

```
update_blastdb.pl --source gcp --decompress swissprot
diamond prepdb --db swissprot

Connected to GCP
diamond v2.1.4.158 (C) Max Planck Society for the Advancement of Science
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

Processing volume: /db/swissprot
Number of sequences: 480805
Number of accessions: 568898
Error: Database file is not a BLAST database
```

Files in the folder after running:
```
total 513M
2.5M swissprot.acc  117M swissprot.phr  1.9M swissprot.pog  5.9M swissprot.pot   16K swissprot.ppi  492K swissprot.ptf  154M taxdb.btd
 24M swissprot.pdb  3.7M swissprot.pin  8.6M swissprot.pos  3.7M swissprot.ppd  175M swissprot.psq  2.3M swissprot.pto   17M taxdb.bti
```

`blastdbcheck` returns no error:
```
blastdbcheck -db swissprot -full
Writing messages to <stdout> at verbosity (Summary)
ISAM testing is ENABLED.
Legacy testing is DISABLED.
TaxID testing is DISABLED.
Using `full' mode: every OID will be tested.

Testing 1 volume(s).
 Result=SUCCESS. No errors reported for 1 volume(s).
Testing 0 alias(es).
 Result=SUCCESS. No errors reported for 0 alias(es).
```

**Comment by bbuchfink** [comment]
It will be fixed. You can ignore this error though, `prepdb` should still finish correctly.

**Comment by xinehc** [comment]
thanks! will try the new version later

**Comment by bbuchfink** [comment]
Should be fixed in v2.1.5.

**Comment by mjfi2sb3** [comment]
I am using diamond/2.1.9, I have tried to use prepdb but this error Error: Database file is not a BLAST database

**>> update_blastdb.pl --decompress --blastdb_version 5 mito**
Connected to NCBI; downloading BLASTDBv5
The contents of mito.tar.gz are up to date in your system.

**>> diamond prepdb --db mito**
diamond v2.1.9.163 (C) Max Planck Society for the Advancement of Science, Benjamin Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

Error: Database file is not a BLAST database

**Comment by bbuchfink** [comment]
@mjfi2sb3 mito is a nucleotide database so it will not work with diamond.
