### ISSUE TITLE
Issue compiling 2.1.4

### ISSUE THREAD

**Issue by OH-AU** [bbuchfink/diamond#684]
v2.1.4 is failing to compile: have tried various gcc compiler versions from 10.3 to 12.1 all fail at:
align.cpp:332:125: error: ‘struct Config’ has no member named ‘heartbeat’

v2.1.3 compile as expected with the same compiled options

> /dmd-2.1.4/src/align/align.cpp: In function ‘void align_queries(Consumer*, Search::Config&)’: 
/dmd-2.1.4/src/align/align.cpp:332:125: error: ‘struct Config’ has no member named ‘heartbeat’ 
  332 |                 if (config.verbosity >= 3 && config.load_balancing == Config::query_parallel && !config.swipe_all && config.heartbeat)

**Comment by bbuchfink** [comment]
You can try again with the latest release.

**Comment by OH-AU** [comment]
Thank you - I can confirm 2.1.5 compiles and works as expected.
