### ISSUE TITLE
Lambda and K for custom matrix

### ISSUE THREAD

**Issue by cmerenstein** [bbuchfink/diamond#69]
I noticed that Diamond now has the ability to use custom substitution matrices for alignment. I have a custom matrix, but to use it Diamond requires me to input a Lambda and a K parameter, which I don't have.

Is there a recommended way to generate these parameters?

Thank you!

**Comment by bbuchfink** [comment]
The FASTA package (http://faculty.virginia.edu/wrpearson/fasta/) can compute these values if you use it with your matrix. They are being displayed when you search.

**Comment by cmerenstein** [comment]
Thanks for the reply!

FASTA seems to give the Lambda parameter but not the K, unless I'm mistaken? I haven't spent more than an hour or so with it, but I can't find anywhere that gives the K parameter. Is there somewhere else I can find it?

**Comment by bbuchfink** [comment]
Yes I've had that problem, I managed to get the K by just using one sequence as query and reference.

**Comment by cmerenstein** [comment]
Ah, thank you!! That worked.
