### ISSUE TITLE
Error: Missing size specifier in number: 125. Permitted values: 'G'

### ISSUE THREAD

**Issue by rzhan186** [bbuchfink/diamond#693]
Dear diamond developers,

I came across this error while running nucleotide sequences against the NCBI nr database using blastx. I am not too sure what might have caused this error, could you help me troubleshoot? 

Here is the error message:

`Computing alignments... Error: Missing size specifier in number: 125. Permitted values: 'G'`

```
Here is the code I used:
diamond blastx \
-q $input/unaligned.${site}.fixed.fa \
-d ncbi-nr.dmnd \
-o $output/mRNA.${site}.tsv \
--very-sensitive \
--outfmt 100 \
--threads 32 \
--memory-limit 125
```

I’ve attached the log file below.

[diamond.log.txt](https://github.com/bbuchfink/diamond/files/11074241/diamond.log.txt)

Thanks for your help!

**Comment by bbuchfink** [comment]
You have to specify the number like `--memory-limit 125G`.

**Comment by rzhan186** [comment]
Thank you so much! This is a sloppy mistake ...
