### ISSUE TITLE
Help with DIAMOND Error: Invalid character in sequence

### ISSUE THREAD

**Issue by lizardman472** [bbuchfink/diamond#697]
Hi DIAMOND Community,

I've been encountering an issue while running DIAMOND on shotgun metagenomic samples, and I'm hoping someone here can help me figure it out. I keep getting an error message about invalid characters in the sequence, even though the reported invalid characters are actually valid amino acids.

Error message:
Loading query sequences... Error: Error reading input stream at line 2: Invalid character (P) in sequence

I've tried several troubleshooting steps, including:

- Double-checking the input file formatting. It looks correctly formatted in FASTA format, with sequences starting with '>' and the sequence itself in the next line(s).
- Making sure the line endings in the input file are correct, to avoid any issues from differences in line endings between operating systems.
- Cleaning the input file by removing any hidden non-printable characters using an awk command, while keeping the headers intact:
- awk '{ if (substr($0, 1, 1) == ">") { print $0 } else { gsub(/[^A-Za-z]/, "", $0); print $0 } }' input_file > cleaned_input_file
- Running DIAMOND with a different dataset, but still encountering the same error, which makes me think it might be related to the database.
- Downloading the latest version of the nr database from NCBI and recreating the DIAMOND database using the makedb script. However, the error still persisted after that.

I'm using DIAMOND version 2.1.1-GCC-11.3.0 on the NeSI HPC platform.

Since the error is still happening even after trying all these things, I was wondering if anyone in the community has experienced similar issues or has any suggestions on how to resolve the problem.

Any help or guidance you can provide would be greatly appreciated. If you need more information about my data or computing environment, just let me know, and I'll be happy to provide it.

Thanks in advance for your help!

**Comment by beaPhD** [comment]
Hello, I also encountered the same problem, but I found that I used the wrong parameter, write blastp instead of blastx, when I corrected, my script can run normally, hope my answer will be helpful to you.
