### ISSUE TITLE
"Joining output blocks... Killed" error on last reference block

### ISSUE THREAD

**Issue by glarue** [bbuchfink/diamond#699]
I'm trying to perform a protein-based search (`blastp`) of the human proteome (longest isoform only, ~23k records) versus `nr` using `DIAMOND` (v2.1.6) on a small server (32 GB RAM, 10 cores). Here is the error that is produced:
```
Processing query block 1, reference block 106/106, shape 16/16.
Building reference seed array...  [9.749s]
Building query seed array...  [0.023s]
Computing hash join...  [3.388s]
Searching alignments...  [17.247s]
Deallocating memory...  [0s]
Deallocating buffers...  [0.729s]
Clearing query masking...  [0.001s]
Opening temporary output file...  [0s]
Computing alignments... Loading trace points...  [1.782s]
Sorting trace points...  [0.857s]
Computing alignments...  [151.812s]
Deallocating buffers...  [0.068s]
Loading trace points...  [0s]
 [154.967s]
Deallocating reference...  [0.1s]
Loading reference sequences...  [0s]
Deallocating buffers...  [0.008s]
Joining output blocks... Loading dictionary...  [221.132s]
Joining output blocks... Killed
```
It's unclear to me from this output whether this is an out-of-memory issue or a disk space issue (both are possible!). One thing that might help is knowing the default temp. directory used by `DIAMOND` (assuming this isn't obviously a memory issue).

Relevant args: `--evalue 1e-5 --max-target-seqs 0 --threads 9 --sensitive`

**Comment by bbuchfink** [comment]
The default temp dir is the output directory. `Killed` usually means it ran out of memory. You can try reducing the block size.

**Comment by glarue** [comment]
Understood—thanks for the input.
