### ISSUE TITLE
A few questions about the comparison between Diamond and BLASTX

### ISSUE THREAD

**Issue by ilnamkang** [bbuchfink/diamond#7]
Hello,

Is it possible that a match is found only by Diamond but not by BLASTX when same parameters are used?

And, are e-values and bitscores from Diamond same as those from BLASTX when same database is used?

Thanks.

**Comment by bbuchfink** [comment]
Hi,
bit scores and e-values computed by Diamond are not identical to blast, because blast uses some more advanced algorithms to compute these, such as composition based statistics. Therefore it can also happen that a match is reported by Diamond but not by blast due to the score treshold.

Benjamin
