### ISSUE TITLE
Diamond fails to load taxon names

### ISSUE THREAD

**Issue by sarahfrail** [bbuchfink/diamond#701]
I have been trying to remake my diamond database with taxon information. I have done this successfully in the past, however, my new databases are giving IDs, rather than names, for all taxon information. Here is the command I am using to produce the database (identical to what has worked in the past)

`diamond makedb --in nr.gz -d nr_taxdmp_dmnd --taxonmap prot.accession2taxid.FULL.gz --taxonnodes nodes.dmp --taxonnames names.dmp`

downloaded from `ftp://ftp.ncbi.nlm.nih.gov/pub/taxonomy/taxdmp.zip` and `https://ftp.ncbi.nlm.nih.gov/pub/taxonomy/accession2taxid/prot.accession2taxid.FULL.gz`

This database is made successfully however during the process of running it prints  "loaded taxonomy names for 0 taxon IDs" in the following output. This results in all result files containing only IDs, rather than names. How can I fix this?

```diamond v2.1.6.160 (C) Max Planck Society for the Advancement of Science
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 32
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
Database input file: ../nr.gz
Opening the database file...  [0.042s]
Loading sequences...  [12.432s]
....
etc...
Hashing sequences...  [0.047s]
Loading sequences...  [0s]
Writing trailer...  [10.526s]
Loading taxonomy names...  [0.733s]
Loaded taxonomy names for 0 taxon ids.```

**Comment by bbuchfink** [comment]
See here: https://github.com/bbuchfink/diamond/issues/692

**Comment by sarahfrail** [comment]
Ah thanks so much, apologies for missing the previous post

**Comment by bbuchfink** [comment]
This should be fixed in the latest release.

**Comment by lucyintheskyzzz** [comment]
Hi, How long does this process usually take on HPC (CPU 40 threads) to create the makedb with all the taxonomic names downloaded from NCBI? I just submitted my job and it is stalling here, but I just wanted to double check how long it usually takes?

(/lustre/project/taw/share/conda-envs/diamond-env) [kvigil@cypress2 Reference]$ diamond makedb --in /lustre/project/taw/kvigil/Reference/refseq_viral_proteins/viral.1.protein.faa.gz -d viralprotein --taxonmap /lustre/project/taw/kvigil/Reference/prot.accession2taxid.FULL.gz --taxonnames  /lustre/project/taw/kvigil/Reference/names.dmp --taxonnodes /lustre/project/taw/kvigil/Reference/nodes.dmp
diamond v2.1.8.162 (C) Max Planck Society for the Advancement of Science, Benjamin Buchfink, University of TuebingenDocumentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 40
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
Database input file: /lustre/project/taw/kvigil/Reference/refseq_viral_proteins/viral.1.protein.faa.gz
Opening the database file...  [0.356s]
Loading sequences...  [13.78s]
Masking sequences...  [0.838s]
Writing sequences...  [1.351s]
Writing accessions...  [5.399s]
Hashing sequences...  [0.059s]
Loading sequences...  [0s]
Writing trailer...  [0.015s]

Accession parsing rules triggered for database seqids (use --no-parse-seqids to disable):
 UniRef prefix  0
gi|xxx| prefix  0
   xxx| prefix  0
   |xxx suffix  0
   .xxx suffix  592770
  :PDB= suffix  0

Loading taxonomy names...  [13.939s]
Loaded taxonomy names for 2534199 taxon ids.
Loading taxonomy mapping file...  [2889.8s]
Joining accession mapping...

**Comment by lucyintheskyzzz** [comment]
Hi, It looks like it took 4888s to download just finished! Thanks!
