### ISSUE TITLE
Diamond can't run on Ensembl Homo Sapiens proteome  

### ISSUE THREAD

**Issue by davidemms** [bbuchfink/diamond#707]
Hi Benjamin

I'm currently unable to run `diamond makedb` on the Ensembl version of the Human proteome: https://ftp.ensembl.org/pub/release-109/fasta/homo_sapiens/pep/Homo_sapiens.GRCh38.pep.all.fa.gz as the check for only DNA errors  makes it impossible.

Option 1, try and run:
`diamond makedb --in Homo_sapiens.GRCh38.pep.all.fa -d db_out`

Output:

> diamond v2.1.6.160 (C) Max Planck Society for the Advancement of Science
> Documentation, support and updates available at http://www.diamondsearch.org
> Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)
> 
> #CPU threads: 4
> Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
> Database input file: Homo_sapiens.GRCh38.pep.all.fa
> Opening the database file...  [0.004s]
> Loading sequences... Error: The sequences are expected to be proteins but only contain DNA letters. Use the option --ignore-warnings to proceed.

Option 2, use `--ignore-warnings` as suggested:
`diamond makedb --in Homo_sapiens.GRCh38.pep.all.fa -d db_out --ignore-warnings`

Output:

> Error: Option is not permitted for this workflow: ignore-warnings

Would it be possible to reinstate the `--ignore-warnings` option for `makedb`? 

Many thanks
David

**Comment by bbuchfink** [comment]
Hi David. Sorry for this, I will post a new release shortly.

**Comment by davidemms** [comment]
Thanks, appreciated!

**Comment by bbuchfink** [comment]
It should be fixed in the latest release.

**Comment by davidemms** [comment]
Thanks, I can also confirm that it works when I try.
