### ISSUE TITLE
Output format 7

### ISSUE THREAD

**Issue by wakamoto5959** [bbuchfink/diamond#713]
Hello, 

Would it be possible to save as output format 7, as BLAST+ dose? 
I tried the option myself using DIAMOND but it did not accept the option. 
My informatics procedure requires that format. 

Best,

**Comment by bbuchfink** [comment]
It's possible to implement but not a priority probably. You can get header lines using `--header simple` and use `-f 6 qtitle` for the full query title.

**Comment by wakamoto5959** [comment]
Thank you for your update and sorry for my slow reply. I will try with what you suggested.
