### ISSUE TITLE
Running out of disk space 

### ISSUE THREAD

**Issue by jacekzkominek** [bbuchfink/diamond#714]
Hi there, I am trying to run an all-vs-all diamond blastp search on a dataset of ~5.5M sequences (~10.5B letters). I built a diamond database from the original FASTA file, and then use that same FASTA file as query in the run proper, which uses the following params: `--id 40.0`, `-e 1e-05`, `--query-cover 40.0`, `--subject-cover 40.0`, `--outfmt 6 qseqid sseqid`, `--tmpdir ./tmpdir/` and finally `--max-target-seqs 0`. 

The execution always run out of disk space, which is filled up with the diamond temp files, and always during the "Searching alignments..." step. The highest storage amount I currently tested is 4TB, and that gets eaten up like cupcakes. I could try more, but I don't think that is the right solution. Here's an example crash:

```
Processing query block 1, reference block 1/1, shape 1/2, index chunk 1/4.
Building reference seed array...  [3.565s]
Building query seed array...  [3.683s]
Computing hash join...  [2.634s]
Masking low complexity seeds...  [0.376s]
Searching alignments... No space left on device
terminate called after throwing an instance of 'File_write_exception'
  what():  Error writing file ./tmpdir//diamond-tmp-0BhwX7
Aborted
```

The crash happens regardless of how I conduct the run: I tried different diamond versions (2.0.9, 2.0.15, 2.1.7, 2.1.8), chunk sizes (4 and 1), block sizes (from 12 down to 0.2), bins (16 and 64), threads (16, 32, 64, 128), disabling unlink, and even using only 10% of the original sequences as query. The only difference is whether the crash happens sooner or later in the process, and it is always due to lack of disk space. The execution never runs out of memory, of which there is plenty on the VM (128CPus and ~500GBs of RAM) and even at high `-b` and low `-c` it never becomes a problem. 

I realize that with `--max-target-seqs 0` it might be a tall order, but I was hoping there is at least some solution to get through it, even if it involves longer runtime. Any advice on that would be appreciated!

**Comment by bbuchfink** [comment]
It looks like you want to compute all-vs-all for a set of highly similar sequences. Disk space can run out in such cases due to the huge number of seed hits (it should not depend on `--max-target-seqs 0`). The easiest solution would be to cluster your sequences first, if that is an option. You can also try `--freq-masking`. Other than this I'm afraid Diamond is not well suited for this type of problem.

**Comment by jacekzkominek** [comment]
> It looks like you want to compute all-vs-all for a set of highly similar sequences. Disk space can run out in such cases due to the huge number of seed hits (it should not depend on `--max-target-seqs 0`). The easiest solution would be to cluster your sequences first, if that is an option. You can also try `--freq-masking`. Other than this I'm afraid Diamond is not well suited for this type of problem.

Yes, that is true in my case - the database contains a lot of redundant or highly-similar sequences. I ended up clustering them at 100% identity and just rolling with the smaller database, coincidentally, just like you suggested.
