### ISSUE TITLE
Error code -9

### ISSUE THREAD

**Issue by avw-adifranco** [bbuchfink/diamond#717]
Hello,

I am using Bakta 1.8.1 to get annotation of microbial genomes.
However, when I run it inside my docker container, I get an error from Diamond returning the error code -9 during the CDS annotation on some genome.

I guess I've an issue on some dependencies but I cannot figure it out.

Could you tell me to which issue this error code is referring ? I did not manage to find the information.

Thank you

**Comment by avw-adifranco** [comment]
I've managed to figure out that the error occurs during the "Building reference seed array" step of diamond blastp.
However, still no clue on what makes it fail only for some genome and specifically in a docker container.

It works perfectly on other genome in the container and also works on the problematic genome with a conda environment only...

**Comment by bbuchfink** [comment]
It may fail due to running out of memory, have you checked that?

**Comment by avw-adifranco** [comment]
Hello Benjamin,

Yes, as I had the ouf of memory error on some other jobs, I've tried to increase it globally and it manage to fix all other issue.

So, -9 is a "out of memory" error code, and nextflow weirdly does not always catch it as such.
