### ISSUE TITLE
Unable to run blastx on block size > 2

### ISSUE THREAD

**Issue by brymerr921** [bbuchfink/diamond#72]
Hi,

I am trying to run a very large Diamond search and would like to increase the block size parameter above 2. I am running Diamond blastx on a supercomputer while requesting 2 nodes with 16 cores each (32 threads) and 125 GB RAM. Here is my command:

`diamond blastx -d nr -q reads.fa -e 0.001 -p 32 -f 100 -o nrfull_panassembly_diamond_output.daa -c 1 -b 12 --more-sensitive`

The same command works with a block size of 2, and fails when the block size is 4, or above. This job failed after 8 minutes, and this is the output of the error file:

```
Failed to allocate sufficient memory. Please refer to the readme for instructions on memory usage.
Error: Invalid DAA file. DIAMOND run probably has not completed successfully.
```

However, the report from the supercomputer indicates that only 34.10 GB of RAM was used.

Here is the output from the command prompt window:

```
diamond v0.8.22.84 | by Benjamin Buchfink <buchfink@gmail.com>
Check http://github.com/bbuchfink/diamond for updates.

#CPU threads: 32
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
#Target sequences to report alignments for: 25
Temporary directory: 
Opening the database...  [0.095137s]
Opening the input file...  [0.049789s]
Opening the output file...  [0.012661s]
Loading query sequences...  [104.963s]
Running complexity filter...  [158.981s]
Building query histograms...  [52.1617s]
Allocating buffers...  [0.005358s]
Loading reference sequences...  [53.051s]
Building reference histograms...  [122.314s]
Allocating buffers...  [0.15474s]
diamond v0.8.22.84 | by Benjamin Buchfink <buchfink@gmail.com>
Check http://github.com/bbuchfink/diamond for updates.

#CPU threads: 16
```

And that's where it dies. Thanks so much for your help.

**Comment by bbuchfink** [comment]
The memory used should be roughly 2(b+9b/c), for b=12 and c=1 that's 240 GB, so that's not going to work. When the memory allocation fails then the program will not be reported to have used that much memory. A value of b=4 should work, however. Do you get the same output in that case?

**Comment by brymerr921** [comment]
I changed to b=4 and it still failed at the same spot, whether I had 128 GB of RAM and 2 nodes (32 cores) or 3 nodes (48 cores). It no longer says that memory is an issue, but it still stops running.
```
diamond v0.8.22.84 | by Benjamin Buchfink <buchfink@gmail.com>
Check http://github.com/bbuchfink/diamond for updates.

#CPU threads: 32
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
#Target sequences to report alignments for: 25
Temporary directory: 
Opening the database...  [0.106129s]
Opening the input file...  [0.059919s]
Opening the output file...  [0.002117s]
Loading query sequences...  [65.6794s]
Running complexity filter...  [100.01s]
Building query histograms...  [32.9879s]
Allocating buffers...  [0.00634s]
Loading reference sequences...  [16.8438s]
Building reference histograms...  [40.6424s]
Allocating buffers...  [0.006154s]
Initializing temporary storage...  [0.369244s]
Processing query chunk 0, reference chunk 0, shape 0, index chunk 0.
Building reference index...  [28.2422s]
Building query index... diamond v0.8.22.84 | by Benjamin Buchfink <buchfink@gmail.com>
Check http://github.com/bbuchfink/diamond for updates.

#CPU threads: 16
```
This time however, the error message was just:
```
Killed
Error: Invalid DAA file. DIAMOND run probably has not completed successfully.
```

**Comment by bbuchfink** [comment]
So it does not seem to be a memory issue in this case. Do you think you could make your query file available to me? I could give you a ssh login to my server so you could transfer by scp.

**Comment by brymerr921** [comment]
Yes, that would be fine.

**Comment by bbuchfink** [comment]
Please send me an email (buchfink@gmail.com) so I can give you the login info.
