### ISSUE TITLE
Using DIAMOND to get counts data?

### ISSUE THREAD

**Issue by lilyyycao** [bbuchfink/diamond#720]
Hello,

I am looking to annotate my de novo assembled reads with DIAMOND but I am also particularly interested in getting a counts table where I can see how many counts per function there are for each of my different samples. Is there a way to output this sort of data from DIAMOND, or is that information lost once the annotation is ran?
Thank you.

**Comment by bbuchfink** [comment]
Diamond can't produce this information directly, you have to process the output with some other tool or script to accomplish this.
