### ISSUE TITLE
 Error: Multiprocessing mode is not compatible with database filtering

### ISSUE THREAD

**Issue by Alexander-Rivero** [bbuchfink/diamond#721]
Hello,

Im triying to run this in a cluster server:

diamond blastx -d DB_nr_plants/nr_plants.dmnd -q Valeriana_clarionifolia.fasta -o blastx_plants.outfmt6 -k 5 --taxonlist 33090 -f 6 qseqid stitle pident length mismatch gapopen qstart qend sstart send evalue bitscore sscinames staxids -e 1e-5 -b 4.5 -p 24 
--mp-init --multiprocessing --tmpdir /tmp --parallel-tmpdir /yaguarete/arivero/tmp-diamond

An I get this error:

Error: Multiprocessing mode is not compatible with database filtering.

Is diamond expected to work this way? Or i I made a mistake?

Thank, you!

**Comment by bbuchfink** [comment]
As it says, these options together are not supported.
