### ISSUE TITLE
Error: Error reading file diamond-57e3e9a9-1.tmp

### ISSUE THREAD

**Issue by Lafond-LapalmeJ** [bbuchfink/diamond#73]
Hi,
I have run diamond lot of time on a cluster computer, it was always working. Now I use a different cluster computer and I got this error on a temporary file that I don't understand. here is my command and the log :

$./diamond blastx -q ~/assembly/trinity_pallida_1rep/trinity.fasta -d ~/database/uniref90 -o test.daa

#CPU threads: 48
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
#Target sequences to report alignments for: 25
Temporary directory: 
Opening the database...  [0.342677s]
Opening the input file...  [0.037232s]
Opening the output file...  [0.002564s]
Loading query sequences...  [0.622562s]
Running complexity filter...  [0.492979s]
Building query histograms...  [0.070694s]
Allocating buffers...  [0.00202s]
Loading reference sequences...  [23.1978s]
Building reference histograms...  [4.16883s]
Allocating buffers...  [0.002126s]
Initializing temporary storage...  [5.27573s]
Processing query chunk 0, reference chunk 0, shape 0, index chunk 0.
Building reference index...  [3.36765s]
Building query index...  [0.042285s]
Building seed filter...  [0.200809s]
Searching alignments...   [47.1427s]
Processing query chunk 0, reference chunk 0, shape 0, index chunk 1.
Building reference index...  [3.50891s]
Building query index...  [0.044014s]
Building seed filter...  [0.200403s]
Searching alignments...  [0.314517s]
Processing query chunk 0, reference chunk 0, shape 0, index chunk 2.
Building reference index...  [3.6378s]
Building query index...  [0.044381s]
Building seed filter...  [0.201254s]
Searching alignments...  [0.315585s]
Processing query chunk 0, reference chunk 0, shape 0, index chunk 3.
Building reference index...  [3.26817s]
Building query index...  [0.040596s]
Building seed filter...  [0.199604s]
Searching alignments...  [0.30722s]
Processing query chunk 0, reference chunk 0, shape 1, index chunk 0.
Building reference index...  [3.23177s]
Building query index...  [0.039744s]
Building seed filter...  [0.200247s]
Searching alignments...  [0.29826s]
Processing query chunk 0, reference chunk 0, shape 1, index chunk 1.
Building reference index...  [3.57171s]
Building query index...  [0.042054s]
Building seed filter...  [0.200247s]
Searching alignments...  [0.273951s]
Processing query chunk 0, reference chunk 0, shape 1, index chunk 2.
Building reference index...  [3.60143s]
Building query index...  [0.043703s]
Building seed filter...  [0.200456s]
Searching alignments...  [0.280618s]
Processing query chunk 0, reference chunk 0, shape 1, index chunk 3.
Building reference index...  [3.34531s]
Building query index...  [0.039184s]
Building seed filter...  [0.200353s]
Searching alignments...  [0.284397s]
Processing query chunk 0, reference chunk 0, shape 2, index chunk 0.
Building reference index...  [3.1885s]
Building query index...  [0.037673s]
Building seed filter...  [0.200388s]
Searching alignments...  [0.269528s]
Processing query chunk 0, reference chunk 0, shape 2, index chunk 1.
Building reference index...  [3.42631s]
Building query index...  [0.040364s]
Building seed filter...  [0.200099s]
Searching alignments...  [0.242703s]
Processing query chunk 0, reference chunk 0, shape 2, index chunk 2.
Building reference index...  [3.50891s]
Building query index...  [0.041268s]
Building seed filter...  [0.203426s]
Searching alignments...  [0.251584s]
Processing query chunk 0, reference chunk 0, shape 2, index chunk 3.
Building reference index...  [3.24307s]
Building query index...  [0.037344s]
Building seed filter...  [0.202136s]
Searching alignments...  [0.262891s]
Processing query chunk 0, reference chunk 0, shape 3, index chunk 0.
Building reference index...  [3.20422s]
Building query index...  [0.036811s]
Building seed filter...  [0.200843s]
Searching alignments...  [0.252825s]
Processing query chunk 0, reference chunk 0, shape 3, index chunk 1.
Building reference index...  [3.34854s]
Building query index...  [0.039122s]
Building seed filter...  [0.200787s]
Searching alignments...  [0.244975s]
Processing query chunk 0, reference chunk 0, shape 3, index chunk 2.
Building reference index...  [3.46202s]
Building query index...  [0.040032s]
Building seed filter...  [0.201473s]
Searching alignments...  [0.252987s]
Processing query chunk 0, reference chunk 0, shape 3, index chunk 3.
Building reference index...  [3.12916s]
Building query index...  [0.036598s]
Building seed filter...  [0.20182s]
Searching alignments...  [0.254801s]
Deallocating buffers...  [0.009803s]
Opening temporary output file...  [0.022988s]
Computing alignments...  [0.012002s]
Error: Error reading file diamond-57e3e9a9-1.tmp

**Comment by bbuchfink** [comment]
Hi,

that is a very strange error. Could you try to use the -t option to relocate the temp directory to somewhere else, maybe something that is not a network drive?

**Comment by Lafond-LapalmeJ** [comment]
I have already try this and actually I am not able to see that file in the temdir ... I have tried with a smaller database and a smaller input file and it is still the same problem. I think the .tmp file is just not created.

**Comment by bbuchfink** [comment]
It is normal that you can't see the temp file, they are created in a special hidden mode. That could possibly cause some kind of incompatibility on your system. I'll provide an option to turn that off and we'll see if that helps.

In the meantime, have you tried /dev/shm as temp directory?

**Comment by Lafond-LapalmeJ** [comment]
I have tried and succed  to run the command with the version 0.7.12. So there is something broken between those 2 versions.

**Comment by Lafond-LapalmeJ** [comment]
What is the best way to send you my database and input test files to see if you can reproduce the problem on your side ?

**Comment by bbuchfink** [comment]
If you contact me by email I can give you a ssh login to my server so you can use scp to transfer the files.

**Comment by Lafond-LapalmeJ** [comment]
it works with the --tmpdir /dev/shm parameter
