### ISSUE TITLE
Illegal Instruction message on makedb v2.1.5

### ISSUE THREAD

**Issue by saskiadmp** [bbuchfink/diamond#730]
Hi,
I am new to diamond and I'm encountering some issues when making the database. I'm using v2.1.5 installed on the institutional server (Ubuntu 16.04.7 LTS (GNU/Linux 4.15.0-142-generic x86_64)) and so far I've just tried making the database using the following commands:

`wget https://ftp.ncbi.nlm.nih.gov/blast/db/FASTA/nr.gz`
`diamond makedb --in nr.gz --db nr`

Upon running `diamond makedb` I get the message: `Illegal instruction`

I've looked at the open issues but the other instances where people get this message are when downloading diamond or running blastx.
Is this an issue of v2.1.5? Any advice on how I can fix it?

Many thanks in advance

**Comment by bbuchfink** [comment]
Please try again with the latest version.

**Comment by saskiadmp** [comment]
Thank you!
