### ISSUE TITLE
Temporary directory: No such file or directory Error: Error opening temporary file Diamond/diamond-tmp-BqExkD

### ISSUE THREAD

**Issue by Racataure** [bbuchfink/diamond#731]
Running Diamond on Mac (Apple silicon) I made the mistake of starting more than one job in parallel. That made Diamond unhappy. The error message in the subject line was the result. It persisted after a restart. I then let Homebrew clean up and upgrade my Diamond 2.16 to version 2.18. But the error persisted even after that.
Is this a bug? And is there a workaround?

Thanks

**Comment by bbuchfink** [comment]
This should not happen normally, I will have to try whether I can reproduce the issue.

**Comment by bbuchfink** [comment]
I tried to reproduce this on an Apple M1 but couldn't, please reopen in case the issue persists.
