### ISSUE TITLE
-static and OSX 

### ISSUE THREAD

**Issue by wasade** [bbuchfink/diamond#74]
I attempted to build v0.8.22 from source on OSX (10.10.5) and received the following error:

``` bash
$ ./build_simple.sh
ld: library not found for -lcrt0.o
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

Removing [`-static`](https://github.com/bbuchfink/diamond/blob/master/build_simple.sh#L2) from `build_simple.sh` allowed the build to complete (and basic sanity checking of `--version` works). It seems as though the core OSX libraries are not compiled for static linking (SO post [here](http://stackoverflow.com/questions/3801011/ld-library-not-found-for-lcrt0-o-on-osx-10-6-with-gcc-clang-static-flag)).

GCC version details:

``` bash
$ gcc --version
Configured with: --prefix=/Library/Developer/CommandLineTools/usr --with-gxx-include-dir=/usr/include/c++/4.2.1
Apple LLVM version 7.0.2 (clang-700.1.81)
Target: x86_64-apple-darwin14.5.0
Thread model: posix
```

I'd be happy to submit a PR to resolve this but wasn't sure if there was a bigger picture reason for the use of `-static`

**Comment by bbuchfink** [comment]
The build_simple.sh script was actually made for my personal use, it's not really the "official" way to compile diamond. That would be using cmake.

**Comment by wasade** [comment]
Unfortunately, `cmake` is not part of the standard xcode stack. Would it make sense to revise `build_simple.sh` to make it an "official" method?

**Comment by bbuchfink** [comment]
I suppose that would work as a temporary solution. In the long run it would probably be better to go back to using autoconf instead of cmake, it is more compatible but also more cumbersome.
