### ISSUE TITLE
Threads usage 

### ISSUE THREAD

**Issue by zhangwenda0518** [bbuchfink/diamond#740]
Hello, author, I used **--threads** to set the number of threads used. Why didn't it actually run as fast as I wanted through command detection?

![image](https://github.com/bbuchfink/diamond/assets/77140740/ea611ee8-9531-4dd7-b333-3548ac426769)

**Comment by bbuchfink** [comment]
You may be looking at individual threads instead of processes in htop, but in any case the tool also has stages that run single-threaded.
