### ISSUE TITLE
Alternative translation tables

### ISSUE THREAD

**Issue by wwood** [bbuchfink/diamond#742]
Hi,

Is there an option for DIAMOND blastx to use alternative translation tables? I couldn't see one documented or in a quick look through the code.

I'm particularly interested in table 4, fwiw.

Thanks in advance, ben

**Comment by bbuchfink** [comment]
The option should be `--query-gencode`, same codes as blast.

**Comment by wwood** [comment]
Ah, somehow missed that in both searches - unlucky. Anyway, that solves it, thanks.
