### ISSUE TITLE
install diamond

### ISSUE THREAD

**Issue by vahidodin** [bbuchfink/diamond#744]
Hi
whenever I try to install diamond using Conda, I get the below error : 
![Screenshot (248)](https://github.com/bbuchfink/diamond/assets/61935562/01243220-5a6d-4aba-8e4c-c8df93642730)

I've tested the following commands didn't work: 

conda install -c bioconda diamond
conda install -c "bioconda/label/cf201901" diamond
conda install -c bioconda -c conda-forge diamond

what should I do to install diamond on anaconda?

**Comment by kashutk** [comment]
Went through that last night, make a new environment in Conda.  It worked for me.

**Comment by vahidodin** [comment]
> Went through that last night, make a new environment in Conda. It worked for me.

Thanks ... it takes a lot of energy to reinstall necessary requirements :)

**Comment by parsanayyara** [comment]
Having the same issue! Tried creating a new environment and it's still giving the same issue (package not available). Tried installing via the windows .exe file (from https://github.com/bbuchfink/diamond/releases) too. Any suggestions on how to install it in windows?

**Comment by shambhabchaki** [comment]
I have downloaded vsredist 2015, still diamond.exe is not opening in windows 11. What to do? Please help!

**Comment by bbuchfink** [comment]
> I have downloaded vsredist 2015, still diamond.exe is not opening in windows 11. What to do? Please help!

Open the command prompt (`cmd.exe`) and start diamond from there.

**Comment by bbuchfink** [comment]
See here: https://www.youtube.com/watch?v=9umV9jD6n80

**Comment by shambhabchaki** [comment]
Thank you very much! Much appreciated...!

**Comment by bbuchfink** [comment]
@vahidodin Diamond is not available through bioconda on Windows, you have to download the github release version.
