### ISSUE TITLE
Blast running in a loop for nanopore data

### ISSUE THREAD

**Issue by bioinfo23** [bbuchfink/diamond#746]
Hi ! I am using diamond blast (blastx) to align nanopore reads against NR database. The process runs fine until the last bin but suddenly gets in a loop and restarts the complete process again. It works fine on 1000 reads but dowmsampling to 1 million also shows same issue without throwing any error.

**Comment by bbuchfink** [comment]
I'm not sure I fully understand, can you run diamond with the `--log` option and send me the resulting `diamond.log` file?
