### ISSUE TITLE
Taxonomic families

### ISSUE THREAD

**Issue by lucyintheskyzzz** [bbuchfink/diamond#749]
Hi!
I got diamond to work perfectly to export all the taxonomy from blastx, but I do not see any taxonomic families, it seems to end at phylum. Is there something I can add to my code while running Diamond to export the taxonomic families? Also, I meganized my .daa files and tried to export my data into a .tsv file, but it doesnt seem like the megan output is as good as Diamond (it does not tab separate), but it does include the taxonomic families.

Thanks! Katie

**Comment by lucyintheskyzzz** [comment]
It would be great to add the full taxonomic lineage to the diamond .tsv output if possible? @bbuchfink

**Comment by lucyintheskyzzz** [comment]
Here is my output. I would like to add order, families and subfamilies if possible:

Here is how I executed Diamond:

diamond blastx -d /lustre/project/taw/kvigil/Reference/viralprotein.dmnd -q barcode04.fastq.gz -o ONR030223barcode04.tsv --ultra-sensitive -f 6 qseqid sseqid pident length mismatch evalue bitscore staxids sscinames sskingdoms skingdoms sphylums stitle

Also, do I have to specify anywhere that I am using nanopore long read sequences? Thanks!

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/katie/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/katie/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">
<style>

</style>
</head>

<body link="#0563C1" vlink="#954F72">



qseqid | sseqid | pident | length | mismatch | evalue | bitscore | staxids | sscinames | sskingdoms | skingdoms | sphylums | stitle
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
25c2714c-e084-4f02-beb9-80ba579608d5 | YP_002333628.1 | 55.4 | 65 | 28 | 4.15E-17 | 76.6 | 491893 | Abalone shriveling syndrome-associated virus | Viruses | Heunggongvirae | Uroviricota | YP_002333628.1 single-stranded DNA binding protein [Abalone   shriveling syndrome-associated virus]



</body>

</html>

**Comment by bbuchfink** [comment]
> Also, do I have to specify anywhere that I am using nanopore long read sequences? Thanks!

For blastx of long reads it is recommended to use e.g. `-F 15 --range-culling --top 10`.

Output of full lineage is a planned feature but I can't tell you when this may be ready.

**Comment by lucyintheskyzzz** [comment]
Hi @bbuchfink thank you for your response. I will add that to my code. It will be great to get the family and subfamily output. Thank you for working on this!

**Comment by lucyintheskyzzz** [comment]
@bbuchfink Supposedly Megan can produce the same .tsv output as Diamond with the output of the full lineage but I have yet to figure this out and nobody seems to respond on the community page with how to do this.

**Comment by lucyintheskyzzz** [comment]
Hi I got it working, 

I read that you can't add the taxonomy features with the .daa format.

(/lustre/project/taw/share/conda-envs/diamond-env) [kvigil@cypress2 ~]$ diamond blastx -d /lustre/project/taw/kvigil/Reference/viralprotein.dmnd -q /lustre/project/taw/kvigil/ONR/baratariabay/ONR_baratariabay100623/20231006_1648_MN18851_FAW76720_acec0fdf/fastq_pass/concatenate/barcode04.fastq.gz -o /lustre/project/taw/kvigil/ONR/baratariabay/ONR_baratariabay100623/20231006_1648_MN18851_FAW76720_acec0fdf/fastq_pass/concatenate/ONR030223barcode04.daa --frameshift 15 --ultra-sensitive --range-culling --top 10

**Comment by lucyintheskyzzz** [comment]
I will close this now and monitor https://github.com/bbuchfink/diamond/issues/256#issuecomment-1798198257

Issue #256 , to see whenever Diamond gets updated to add the Taxonomic Families @bbuchfink
