### ISSUE TITLE
Quick question about data availability

### ISSUE THREAD

**Issue by onsi** [bbuchfink/diamond#754]
Hey there, this looks like an amazing tool and I’ve been reading your upcoming publication at: https://doi.org/10.1101/2023.01.24.525373

I’m wondering if there are any plans to release the generated cluster data for further analysis by other groups?  It seems like an excellent starting point for exploring a host of follow-on questions.

Thanks!

**Comment by bbuchfink** [comment]
Yes, we're planning to release the data in the next weeks.

**Comment by onsi** [comment]
Wonderful, that's fantastic news!  All the best as you work towards the release.
