### ISSUE TITLE
Error: Input file is not a DAA file 

### ISSUE THREAD

**Issue by lucyintheskyzzz** [bbuchfink/diamond#755]
Hi, I am getting a similar issue as https://github.com/bbuchfink/diamond/issues/356

I cannot meganize my .daa file in Megan because it is saying that the input file is not a DAA file.  Thanks for your help!

(/lustre/project/taw/share/conda-envs/diamond-env) [kvigil@cypress1 diamond]$ diamond view -a ONR100623barcode04.daa
 -o output.view
diamond v2.1.8.162 (C) Max Planck Society for the Advancement of Science, Benjamin Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 40
Loading subject IDs... Error: Input file is not a DAA file.

**Comment by lucyintheskyzzz** [comment]
Here is my code for generating the .daa file:
(/lustre/project/taw/share/conda-envs/diamond-env) [kvigil@cypress1 diamond]$ diamond blastx -d /lustre/project/taw/kvigil/Reference/refseq_viral_prot_102723/viralprotein.dmnd -q /lustre/project/taw/kvigil/ONR/baratariabay/ONR100623baratariabay/20231006_1648_MN18851_FAW76720_acec0fdf/fastq_pass/concatenate/barcode03.fastq.gz -o ONR100623barcode03.daa --ultra-sensitive --long-reads

**Comment by lucyintheskyzzz** [comment]
[ONR100623barcode03.zip](https://github.com/bbuchfink/diamond/files/13260732/ONR100623barcode03.zip)
[ONR100623barcode04.zip](https://github.com/bbuchfink/diamond/files/13260733/ONR100623barcode04.zip)

**Comment by lucyintheskyzzz** [comment]
Hi, I re-ran my samples again and I am still getting "input file is not a DAA file" when I go to Meganize my samples on the Megan6 Ultimate edition GUI. 

 diamond blastx -d /lustre/project/taw/kvigil/Reference/refseq_viral_prot_102723/viralprotein.dmnd -q barcode04.fastq.gz -o ONR100623barcode04.daa --ultra-sensitive --frameshift 15 --range-culling --top 10

Here is "diamond-view"

(/lustre/project/taw/share/conda-envs/diamond-env) [kvigil@cypress1 concatenate]$ diamond view -a ONR100623barcode04.daa -o output.view
diamond v2.1.8.162 (C) Max Planck Society for the Advancement of Science, Benjamin Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 40
Loading subject IDs... Error: Input file is not a DAA file.

**Comment by lucyintheskyzzz** [comment]
I typed in dmesg and got:

[Hardware Error]: Machine check events logged
CPU16: Core temperature above threshold, cpu clock throttled (total events = 3713710)
CPU6: Package temperature above threshold, cpu clock throttled (total events = 3821562)
CPU18: Package temperature above threshold, cpu clock throttled (total events = 3821571)
CPU0: Package temperature above threshold, cpu clock throttled (total events = 3821563)
CPU10: Package temperature above threshold, cpu clock throttled (total events = 3821568)
CPU2: Package temperature above threshold, cpu clock throttled (total events = 3821568)
CPU12: Package temperature above threshold, cpu clock throttled (total events = 3821569)
CPU4: Package temperature above threshold, cpu clock throttled (total events = 3821573)
CPU28: Package temperature above threshold, cpu clock throttled (total events = 3821571)
CPU14: Package temperature above threshold, cpu clock throttled (total events = 3821571)
CPU20: Package temperature above threshold, cpu clock throttled (total events = 3821568)
CPU26: Package temperature above threshold, cpu clock throttled (total events = 3821566)
CPU22: Package temperature above threshold, cpu clock throttled (total events = 3821572)
CPU32: Package temperature above threshold, cpu clock throttled (total events = 3821564)
CPU8: Package temperature above threshold, cpu clock throttled (total events = 3821571)
CPU34: Package temperature above threshold, cpu clock throttled (total events = 3821568)
CPU30: Package temperature above threshold, cpu clock throttled (total events = 3821573)
CPU24: Package temperature above threshold, cpu clock throttled (total events = 3821560)
CPU38: Package temperature above threshold, cpu clock throttled (total events = 3821572)
CPU4: Package temperature/speed normal
CPU20: Package temperature/speed normal
CPU2: Package temperature/speed normal
CPU14: Package temperature/speed normal
CPU10: Package temperature/speed normal
CPU32: Package temperature/speed normal
CPU34: Package temperature/speed normal
CPU24: Package temperature/speed normal
CPU26: Package temperature/speed normal
CPU22: Package temperature/speed normal
CPU6: Package temperature/speed normal
CPU18: Package temperature/speed normal
CPU28: Package temperature/speed normal
CPU38: Package temperature/speed normal
CPU0: Package temperature/speed normal
CPU12: Package temperature/speed normal
CPU30: Package temperature/speed normal
CPU8: Package temperature/speed normal
CPU16: Core temperature/speed normal
CPU36: Core temperature above threshold, cpu clock throttled (total events = 3713710)
CPU36: Core temperature/speed normal
[Hardware Error]: Machine check events logged

**Comment by bbuchfink** [comment]
Your command line in incorrect, to get DAA format you need to set `-f daa`.

**Comment by lucyintheskyzzz** [comment]
@bbuchfink Hi thank you for correcting this. I was able to get the daa file, but when I meganized it, nothing showed up whereas the .tsv file has alot of blastx hits.

Here is my updated code (I am not sure if this is the correct way for long-reads)

.tsv code:
diamond blastx -d /lustre/project/taw/kvigil/Reference/viralprotein.dmnd -q barcode04.fastq.gz -o ONR030223barcode04.tsv --ultra-sensitive --frameshift 15 --range-culling --top 10 qseqid sseqid pident length mismatch evalue bitscore staxids sscinames sskingdoms skingdoms sphylums stitle

.daa code:
diamond blastx -d /lustre/project/taw/kvigil/Reference/refseq_viral_prot_102723/viralprotein.dmnd -q barcode04.fastq.gz -o ONR10623barcode04.daa --ultra-sensitive --long-reads -f 100

**Comment by lucyintheskyzzz** [comment]
Hi I ended up just meganizing my .daa file using megan command line and it seems to work now:

daa-meganizer -i ONR10623barcode04.daa -mdb /lustre/project/taw/share/conda-envs/megan/megan-map-Feb2022.db

Thanks!

**Comment by husonlab** [comment]
> [ONR100623barcode03.zip](https://github.com/bbuchfink/diamond/files/13260732/ONR100623barcode03.zip) [ONR100623barcode04.zip](https://github.com/bbuchfink/diamond/files/13260733/ONR100623barcode04.zip)

Just looked inside these files: they are in tab format, not DAA format, you need to use option -f 100 to generate DAA format

**Comment by lucyintheskyzzz** [comment]
Hi I ended up just using R taxonomizr to get all the taxonomy.
