### ISSUE TITLE
Segmentation fault running blastx

### ISSUE THREAD

**Issue by kennethban** [bbuchfink/diamond#76]
I attempted running diamond blastx (v0.8.22) on a ~48MB fasta dataset with the NR database. The NR database base was built from the NR fasta file downloaded from NCBI.

I ran the following command:

```
diamond blastx -q sequence.fasta -d diamond_nr.dmnd -o sequence.m8 -e 0 -k 1
```

Everything goes ok until the last step when I get a segmentation fault while diamond is joining the output blocks

```
#CPU threads: 24
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
#Target sequences to report alignments for: 1
Temporary directory: /tmp/
Opening the database...  [0.282103s]
Opening the input file...  [0.001087s]
Opening the output file...  [0.005431s]
Loading query sequences...  [1.14314s]
Running complexity filter...  [0.886299s]
Building query histograms...  [0.05598s]
Allocating buffers...  [0.001358s]
Loading reference sequences...  [4.77077s]
Building reference histograms...  [3.50113s]
Allocating buffers...  [0.001615s]
Initializing temporary storage...  [0.023484s]
Processing query chunk 0, reference chunk 0, shape 0, index chunk 0.
Building reference index...  [3.15116s]
Building query index...  [0.046051s]
Building seed filter...  [0.18127s]
Searching alignments...  [1.28574s]

…

Processing query chunk 0, reference chunk 16, shape 3, index chunk 3.
Building reference index...  [3.07833s]
Building query index...  [0.024544s]
Building seed filter...  [0.175473s]
Searching alignments...  [0.368155s]
Deallocating buffers...  [0.0103s]
Opening temporary output file...  [0.000895s]
Computing alignments...  [16.2232s]
Deallocating reference...  [0.009539s]
Loading reference sequences...  [0.000756s]
Deallocating buffers...  [0.000365s]
Joining output blocks...  Segmentation fault     
```

Diamond is running on a compute cluster node (24 cores, 128 GB ram).

```
======================================================================================

                        Resource Usage on 2016-09-24 11:52:59.166818:

        JobId: 1934395.wlm01
        Project: _pbs_project_default
        Exit Status: 139
        NCPUs Requested: 24                             NCPUs Used: 24
                                                        CPU Time Used: 09:11:29
        Memory Requested: None                          Memory Used: 11356040kb
                                                        Vmem Used: 17961084kb
        Walltime requested: 1018:59:00                  Walltime Used: 00:25:30

        Execution Nodes Used: (std0232:ncpus=24)

 ======================================================================================
```

**Comment by bbuchfink** [comment]
Please try a different value for the -e parameter, or leave it at the default (0.001). Evalue treshold of 0 makes no sense, it will report only extremely high-scoring alignments whose e-value is rounded down to 0.

**Comment by kennethban** [comment]
Thanks! I transferred the -e parameter from Rapsearch2 without checking if they mean the same thing in Diamond. It works now.

**Comment by kennethban** [comment]
A quick unrelated question: how do I get diamond to report only the first gi identifier in the header? Equivalent to -v 1 in rapsearch?

gi|766544065| instead of gi|766544065|gb|AJS14317.1| 

I have tried --single-domain but it doesn't seem to work. Thanks in advance!

**Comment by bbuchfink** [comment]
Sorry but there's no option for that in diamond.

**Comment by moskalenko** [comment]
Not sure if this is a similar issue or not, so posting here before opening a separate request. Running diamond-0.8.25 against the md5nr database diamond segfaults a few hours into the run

...
Building query index...  [2.40572s]
Building seed filter...  [0.407992s]
Searching alignments...  [13.1247s]
Processing query chunk 0, reference chunk 9, shape 3, index chunk 2.
Building reference index...  [10.7676s]
Building query index...  [2.45905s]
Building seed filter...  [0.410746s]
Searching alignments...  [14.235s]
Processing query chunk 0, reference chunk 9, shape 3, index chunk 3.
Building reference index...  [9.75613s]
Building query index...  [2.0913s]
Building seed filter...  [0.40788s]
Searching alignments...  [14.3722s]
Deallocating buffers...  [0.643082s]
Opening temporary output file...  [0.243099s]
Computing alignments...  [1142.43s]
Deallocating reference...  [0.238702s]
Loading reference sequences...  [0.001472s]
Deallocating buffers...  [0.243562s]
Joining output blocks... 26532 Segmentation fault diamond blastx -p 16 -q unmapped_1.fastq -d md5nr.dmnd -k 1 --min-score 0.0005 -a diamond.daa --tmpdir ${TMPDIR}

**Comment by bbuchfink** [comment]
The --min-score parameter takes a bit score so you're setting this too low, you need to use -e 0.0005. Please try if that fixes the problem.

**Comment by yyminmax** [comment]
diamond blastx -q demo.fa -d nr_meta.dmnd -o result -b 20 -c 1

it also occured Segmentation fault when Joining output ..

**Comment by bbuchfink** [comment]
What version of diamond are you using?

I will look into this, in the meantime you can try to set a lower value for
-b and see if that helps.

2017-01-14 15:06 GMT+01:00 yyminmax <notifications@github.com>:

> diamond blastx -q demo.fa -d nr_meta.dmnd -o result -b 20 -c 1
>
> it also occured Segmentation fault when Joining output ..
>

**Comment by yyminmax** [comment]
v0.8.31

**Comment by bbuchfink** [comment]
No, your database should not be too large. I will try to look into this.

**Comment by bbuchfink** [comment]
I have looked over my code and didn't find a bug. I have added some checks
however that should help me narrow down the problem. Could you try to run
this again with the latest version? Also, please use the option --log. This
will create a diamond.log file which you should send to me.

**Comment by yyminmax** [comment]
[diamond.log.txt](https://github.com/bbuchfink/diamond/files/707150/diamond.log.txt)


Joining output blocks... Error: Sequence set index out of bounds.

**Comment by bbuchfink** [comment]
This crash only happens when there were no alignments found. I have
commited a fix for this now and will upload a new release later today.

**Comment by yyminmax** [comment]
thanks..
