### ISSUE TITLE
Diamond not able to detect repeats?

### ISSUE THREAD

**Issue by gandarath** [bbuchfink/diamond#763]
Dear colleagues,

We decided to initiate the change, from blast to diamond, given the amazing performance of your program, congratulations BTW!
However, we obtained unexpected results in case of domain repeats, which was not solved by using the max-hsps option.

**Issue**
Our issue arose while trying to identify domain presence in multidomain proteins while comparing the full-length query to an isolated domain sequence (a characterized member in the family): only one hit is reported!

But to illustrate this issue, let's use a simplier example : a monodomain protein and a second, artifical, protein consisting in a tandem duplicate of the first

**Sequences**
>\>7378 
MAFPAGFGWAAATAAYQVEGGWDADGKGPCVWDTFTHQGGERVFKNQTGDVACGSYTLWEEDLKCIKQLGLTHYRFSLSWSRLLPDGTTGFINQKGIDYYNKIIDDLLKNGVTPIVTLYHFDLPQTLEDQGGWLSEAIIESFDKYAQFCFSTFGDRVKQWITINEANVLSVMSYDLGMFPPGIPHFGTGGYQAAHNLIKAHARSWHSYDSLFRKKQKGMVSLSLFAVWLEPADPNSVSDQEAAKRAITFHLDLFAKPIFIDGDYPEVVKSQIASMSQKQGYPSSRLPEFTEEEKKMIKGTADFFAVQYYTTRLIKYQENKKGELGTLQDAEIEFFPDPSWKNVDWIYVVPWGVCKLLKYIKDTYNNPVIYITENGFPQSDPAPLDDTQRWEYFRQTFQELFKAIQLDKVNLQVYCAWSLLDNFEWNQGYSSRFGLFHVDFEDPARPRVPYTSAKEYAKIIRNNGLEAHL

>\>tandemDupli7378 
MAFPAGFGWAAATAAYQVEGGWDADGKGPCVWDTFTHQGGERVFKNQTGDVACGSYTLWEEDLKCIKQLGLTHYRFSLSWSRLLPDGTTGFINQKGIDYYNKIIDDLLKNGVTPIVTLYHFDLPQTLEDQGGWLSEAIIESFDKYAQFCFSTFGDRVKQWITINEANVLSVMSYDLGMFPPGIPHFGTGGYQAAHNLIKAHARSWHSYDSLFRKKQKGMVSLSLFAVWLEPADPNSVSDQEAAKRAITFHLDLFAKPIFIDGDYPEVVKSQIASMSQKQGYPSSRLPEFTEEEKKMIKGTADFFAVQYYTTRLIKYQENKKGELGTLQDAEIEFFPDPSWKNVDWIYVVPWGVCKLLKYIKDTYNNPVIYITENGFPQSDPAPLDDTQRWEYFRQTFQELFKAIQLDKVNLQVYCAWSLLDNFEWNQGYSSRFGLFHVDFEDPARPRVPYTSAKEYAKIIRNNGLEAHLMAFPAGFGWAAATAAYQVEGGWDADGKGPCVWDTFTHQGGERVFKNQTGDVACGSYTLWEEDLKCIKQLGLTHYRFSLSWSRLLPDGTTGFINQKGIDYYNKIIDDLLKNGVTPIVTLYHFDLPQTLEDQGGWLSEAIIESFDKYAQFCFSTFGDRVKQWITINEANVLSVMSYDLGMFPPGIPHFGTGGYQAAHNLIKAHARSWHSYDSLFRKKQKGMVSLSLFAVWLEPADPNSVSDQEAAKRAITFHLDLFAKPIFIDGDYPEVVKSQIASMSQKQGYPSSRLPEFTEEEKKMIKGTADFFAVQYYTTRLIKYQENKKGELGTLQDAEIEFFPDPSWKNVDWIYVVPWGVCKLLKYIKDTYNNPVIYITENGFPQSDPAPLDDTQRWEYFRQTFQELFKAIQLDKVNLQVYCAWSLLDNFEWNQGYSSRFGLFHVDFEDPARPRVPYTSAKEYAKIIRNNGLEAHL

**Output results**
While blast is able to report the two HSP
tandemDupli7378 7378    100.000 469     0       0       1       469     1       469     0.0     978
tandemDupli7378 7378    100.000 469     0       0       470     938     1       469     0.0     978

Diamond does not seem able to see more than the first, depite the use of the --max-hsps option
7378_duplicated    7378    100    469    0    0    470    938    1    469    0.0    990

**Commands**
We used the following command lines (files attached for convenience)
makeblastdb -dbtype prot -in 7378.fa
blastp -evalue 1e-10 -outfmt 6 -query tandemDupli7378.fa -db 7378.fa > blast_results.txt

diamond makedb --in tandemDupli7378.fa -d db_test.fa
diamond blastp -k 0 --ultra-sensitive -p 6 -e 1e-3 --max-hsps 0 -f 6 -q 7378.fa -d db_test.fa -o diamond_results.txt

Thanks in advance for your help,

Nicolas
[fasta.zip](https://github.com/bbuchfink/diamond/files/13498608/fasta.zip)

**Comment by bbuchfink** [comment]
It will not work if the target ranges of the HSPs are the same because the target range of the first HSP is masked. It should work if you reverse query and target.

**Comment by gandarath** [comment]
The other way around would have the same issue, that you caughd well: as you are masking the first HSP you won't be able to detect any domain repeats.

**Comment by bbuchfink** [comment]
The HSP is only masked in the target, so it should work the other way round.

**Comment by bbuchfink** [comment]
The other HSP is culled due to overlapping query ranges. You can get both using `--culling-overlap 101`.

**Comment by gandarath** [comment]
Thanks, indeed with this combination of options it finally provide the expected results, great!
Even if I do not well understand the 101 value for culling-overlap parameter

diamond blastp -k 0 --ultra-sensitive --culling-overlap 101 --max-hsps 0 -p 6 -e 1e-3 -f 6 qseqid sseqid pident qstart qend qlen sstart send slen evalue score stitle -q 7378.fa -d db_test.fa -o diamond_results_test.txt

7378    7378_duplicated    100    1    469    469    470    938    938    0.0    2557    7378_duplicated
7378    7378_duplicated    100    1    469    469    1    469    938    0.0    2557    7378_duplicated

**Comment by bbuchfink** [comment]
> Even if I do not well understand the 101 value for culling-overlap parameter

It's the minimum overlap% for a hit to be deleted, anything above 100 means not to delete any hit.
