### ISSUE TITLE
 how to make a diamond-formatted KEGG database with taxonomic information from NCBI and KEGG brite?

### ISSUE THREAD

**Issue by terancehhwong** [bbuchfink/diamond#765]
Hi there,

Sorry if it sounds like a stupid question, as I am new to bioinformatics. I really wonder how to make a diamond-formatted KEGG database with taxonomic information from NCBI and KEGG brite (which is defined as a collection of hierarchical classification systems capturing functional hierarchies of various biological objects based on its website) included into the command? Thanks!!

Best regards,
Terance

**Comment by bbuchfink** [comment]
The only way to add taxonomic information to a Diamond database is to use NCBI-formatted taxonomy files (see Wiki). You would probably have to create such a file manually for KEGG.
