### ISSUE TITLE
dmnd to fasta?

### ISSUE THREAD

**Issue by aipolly** [bbuchfink/diamond#77]
I'm wondering how to do the opposite processing of makedb，is't possible? thanks in advance ！

**Comment by bbuchfink** [comment]
Yes, in the latest version you can use `diamond getseq -d <file>`.

**Comment by aipolly** [comment]
very useful, thank you!

**Comment by enjoypolly** [comment]
@bbuchfink still can't do it on early version diamond formated database

**Comment by bbuchfink** [comment]
I would recommend using the latest version then. It's hard for me to add
features to old versions.
