### ISSUE TITLE
Diamond Windows Installation

### ISSUE THREAD

**Issue by parsanayyara** [bbuchfink/diamond#775]
Hello!

I've been trying to install diamond in windows but I ended up getting the same error: "package unavailable in the channel"

I have tried:

1. using conda install -c bioconda -c conda-forge diamond and conda install -c bioconda diamond
2. using mamba instead of conda: mamba install diamond
3. installing directly from https://github.com/bbuchfink/diamond/releases, diamond.exe refuses to run

Has anyone else been getting similar issues? Any thoughts on what the issue may be?

**Comment by bbuchfink** [comment]
There is no Windows version available on conda. What do you mean by "refuses to run"?

**Comment by parsanayyara** [comment]
Nothing pops out or gets installed when I run diamond.exe

**Comment by bbuchfink** [comment]
It's a command line app without a user interface, you have to run it from the command prompt (cmd.exe).

**Comment by parsanayyara** [comment]
Right, that worked for me. Thank you!
