### ISSUE TITLE
--top not behaving as expected

### ISSUE THREAD

**Issue by jwasmuth** [bbuchfink/diamond#78]
Hi,
I want DIAMOND to report the top alignment based on bit score, if their are multiple hsps with the same score, those should all be reported. I set --top 0.1 and get noticed the following result:

ERR391911.199_1	    nDv.1.0.1.t02483	    93.8	     32    	2    	0    	99    	4    	36    	67    	8.5e-11    	60.8
ERR391911.199_1	    nDv.1.0.1.t02483	    100.0	   18	    0	    0	    57	    4	    2	      19    	1.6e-04    40.0

There are other examples of this. Curiously, if I put only the one sequence read in the query file, this goes away. I don't know if this is evalue related. I set --evalue 10. I've in
[Diamond.zip](https://github.com/bbuchfink/diamond/files/516558/Diamond.zip)
clude the query and db files. I am using v 0.8.22.84.

Thanks

James

**Comment by bbuchfink** [comment]
Hi James,
the second hsp is reported because it's contained in the same subject sequence as the first. To suppress this you can use the option --single-domain.

Benjamin

**Comment by jwasmuth** [comment]
Yes! Thank you.
James
