### ISSUE TITLE
ERROR: : double free or corruption (!prev) and  free(): corrupted unsorted chunks

### ISSUE THREAD

**Issue by hans-vg** [bbuchfink/diamond#780]
Version: diamond v2.1.8.162  installed from bioconda
Database: NR downloaded from ncbi 2023/07/28
database was built using the makedb command and providing taxon files.

`$diamond makedb --threads 32 --in $db --db /common_references/ncbi_nr/nr_20230728/ --taxonmap $taxid/prot.accession2taxid.FULL --taxonnodes $taxid/nodes.dmp --taxonnames $taxid/names.dmp`

Diamond blastx command:
`diamond blastx -p 64 -d /data/gpfs/assoc/inbre/projects/common_references/ncbi_nr/nr_20230728/nr -q ../trinity_out.Trinity.95.fasta -o nr_matches_test.diamond.tsv --outfmt 6 qseqid qlen sseqid slen evalue bitscore stitle qtitle sscinames sskingdoms skingdoms sphylums staxids`

Resources: 64 threads/ 220GB of RAM

Tail Error Log:
```

Processing query block 1, reference block 118/118, shape 2/2, index chunk 4/4.
Building reference seed array...  [0.107s]
Building query seed array...  [0.134s]
Computing hash join...  [0.076s]
Masking low complexity seeds...  [0.01s]
Searching alignments...  [0.046s]
Deallocating memory...  [0s]
Deallocating buffers...  [0.002s]
Clearing query masking...  [0.052s]
Opening temporary output file...  [0s]
Computing alignments... Loading trace points...  [0.219s]
Sorting trace points...  [0.029s]
Computing alignments...  [1.955s]
Deallocating buffers...  [0.001s]
Loading trace points...  [0s]
 [2.224s]
Deallocating reference...  [0.001s]
Loading reference sequences...  [0s]
Deallocating buffers...  [0s]
Joining output blocks... Loading dictionary...  [35.079s]
Joining output blocks... Error: std::exception
Error: std::exceptionError: std::exception
Error: Error: std::exception
*** Error in `/data/gpfs/home/hvasquezgross/bin/diamond': double free or corruption (!prev): 0x000000000232a110 ***
Error: std::exception
Error: std::exception
Error: std::exception
Error: std::exception
Error: std::exception
Error: std::exception
std::exception

Error: std::exception
Error: std::exception
Error: std::exception
Error: Error: std::exception
Error: std::exception
Error: std::exception
Error: std::exception
Error: std::exception
std::exception
Error: std::exception
Error: *** Error in `/data/gpfs/home/hvasquezgross/bin/diamond': free(): corrupted unsorted chunks: 0x0000000002326d20 ***
std::exception
Error: std::exception
Error: std::exception
Error: *** Error in `/data/gpfs/home/hvasquezgross/bin/diamond': double free or corruption (!prev): 0x0000000002326d20 ***
*** Error in `/data/gpfs/home/hvasquezgross/bin/diamond': double free or corruption (!prev): 0x0000000002326d20 ***
Error: /cm/local/apps/slurm/var/spool/job4892077/slurm_script: line 43: 54558 Segmentation fault      (core dumped) /data/gpfs/home/hvasquezgross/bin/diamond blastx -p 64 -d /data/gpfs/assoc/inbre/projects/common_references/ncbi_nr/nr_20230728/nr -q ../trinity_out.Trinity.95.fasta -o nr_matches_test.diamond.tsv --outfmt 6 qseqid qlen sseqid slen evalue bitscore stitle qtitle sscinames sskingdoms skingdoms sphylums staxids
```

For other (smaller) databases, diamond works fine. Is this an issue with the taxon information I tried to load into the nr database?  I tried the prebuilt NR database from NCBI but using the `prepdb` command, but getting taxon information did not work. I proceeded with following the instructions to make the database myself.

**Comment by bbuchfink** [comment]
I tried to reproduce this using swissprot but it works fine, will try full nr now.

**Comment by bbuchfink** [comment]
I could not reproduce the error using the nr database either. Would it be possible to send me your query file?

**Comment by hans-vg** [comment]
I never could get nr to build with the provided command.  I did follow the process outlined here (https://blobtoolkit.genomehubs.org/install/ ) to setup uniprot which worked fine though.  I'm using nt and uniprot data now for loading hits.

It could possibly be my nr file didn't fully download. I'll try redownloading and reindexing with diamond.

**Comment by bbuchfink** [comment]
I will close this for now, let me know in case the problem persists.
