### ISSUE TITLE
Question about min-orf change for blastx in v2.1.0

### ISSUE THREAD

**Issue by Stikus** [bbuchfink/diamond#781]
Hello, thanks for great tool.

We are using https://github.com/humanlongevity/HLA in our pipelines, and it provides great results but is unmaintained, unfortunately.

One of it [scripts](https://github.com/humanlongevity/HLA/blob/master/bin/align.pl#L63) use `diamond blastx`:
```pl
open(IN, "diamond blastx -t . -C 20000 --index-mode 1 --seg no --min-score 10 --top 20 -c 1 -d $root/data/hla -q $fastq_file -f tab --quiet -o /dev/stdout |") or die $!;
```

We changed this command according to this issue https://github.com/bbuchfink/diamond/issues/140#issuecomment-627441290:
```pl
open(IN, "diamond blastx -t . --sensitive --masking 0 --min-score 10 --top 20 -c 1 -d $root/data/hla -q $fastq_file -f tab --quiet -o /dev/stdout |") or die $!;
```

But after [DIAMOND 2.1.0 change](https://github.com/bbuchfink/diamond/releases/tag/v2.1.0):

> The `blastx` mode will now mask any open reading frame below the minimum required length as specified by `--min-orf`.  
> The `blastx` mode will only count unmasked letters towards the block size.

Results changed.

According to [wiki](https://github.com/bbuchfink/diamond/wiki/3.-Command-line-options#input-options)

> `--min-orf/-l #`
>
> Ignore translated sequences that do not contain an open reading frame of at least this length. By default this feature is disabled for sequences of length below 30, set to 20 for sequences of length below 100, and set to 40 otherwise. Setting this option to `1` will disable this feature.

We can add `--min-orf 1` to command. We tested it and it brings back old results. But should we? Can anyone give us advice?

**Comment by bbuchfink** [comment]
Using this will produce more accurate results at the expense of longer runtime. So you should probably use it if run time is not an issue.

**Comment by Stikus** [comment]
@bbuchfink results with `--min-orf 1` are more accurate, correct? Thanks for fast answer!

**Comment by bbuchfink** [comment]
>@bbuchfink results with --min-orf 1 are more accurate, correct?

yes

**Comment by Stikus** [comment]
Thanks, closing issue
