### ISSUE TITLE
The lengths of sseq and qseq in the output results of diamond blastp are inconsistent

### ISSUE THREAD

**Issue by graa4** [bbuchfink/diamond#783]
Hello! Sorry to bother you!
I want to know why the lengths of sseq and qseq in the output results of diamond blastp are inconsistent? If the result is obtained using blastp, it will be filled with -, and the length of sseq and qseq are the same. The example is as follows:
```python
sseq:
FGVFNNFYSTDFALLAPPNPGILRELPSDNALGWA-HW------RAGYRCYELPRNAKTQLDIDTPGELQLLSCSPGLPPELAAVLSGMPRARAEVLLEILVSPGKNLFLVGRISGHLLRFLERTSACRTQALIEGRGMKAEGL
qseq:
FGFHFRVKSQFFQ*LSQHNPG--GQLCQGKSNGFADEWNGPRGARVDFEDENLPV-LQSELDVHQPDDPQFLRQQPGLPPDLFLDASGDAHGR------------QNAGTVSRMDSGLLDMLHDSAHHGHRAVADGVHIDLDGI
``` 
The following are the results of diamond:
```python
sseq:YLNLDSLSLHRLTDHHAGRDLRERLTGRLADKRHGTRGARIHFENVDLRVLGVGVLHGELHIHEALHLQRLSKESRLTLDLFNKLRAEAVRRKRARRVARVNAGLLDMLHDAADPDFVAVTHSVNVHFHRVIQEPIKE
qseq:HFRVKSQFFQXLSQHNPGGQLCQGKSNGFADEWNGPRGARVDFEDENLPVLQSELDVHQPDDPQFLRQQPGLPPDLFLDASGDAHGRQNAGTVSRMDSGLLDMLHDSAHHGHRAVADGVHIDLDGILEELVDQ
``` 
I want to know how to get sseq and qseq with the same length? And I found that diamond replaced the amino acid 'U' with 'X'. Will there be any impact?
Looking forward to your answer, thank you!

**Comment by bbuchfink** [comment]
You can use `qseq_gapped` and `sseq_gapped` for this. Replacing U with X can't be avoided right now.

**Comment by graa4** [comment]
> You can use `qseq_gapped` and `sseq_gapped` for this. Replacing U with X can't be avoided right now.
Ok! Thank u!
It means not
```python
 --outfmt 6 qseq sseq
``` , but use
```python
--outfmt 6 qseq_gapped  sseq_gapped
```  
, right?

**Comment by bbuchfink** [comment]
Yes

**Comment by graa4** [comment]
> Yes

I got it, Thanks!
