### ISSUE TITLE
Diamond view throws segmentation fault (core dumped) error

### ISSUE THREAD

**Issue by SaimMomin12** [bbuchfink/diamond#796]
Hi,

I have a Diamond DAA file (ultimately small in size) which was the ouput from Diamond blastx tool using the lastest version.

When I try to convert the DAA file to XML file using the following command, I get **segmentation fault(core dumped)** error.

`diamond view --threads 8 --daa results.daa --outfmt 5  --max-target-seqs 1 --out result.xml`

Error traceback as follows

#CPU threads: 8
Scoring parameters: (Matrix=blosum62 Lambda=0.267 K=0.041 Penalties=11/1)
DB sequences = 2
DB sequences used = 2
DB letters = 568
#Target sequences to report alignments for: 1
Segmentation fault (core dumped)

Any suggestions how can this be solved?

**Comment by bbuchfink** [comment]
This should be fixed in the latest release.
