### ISSUE TITLE
Error: Invalid parameter count for option '--tmpdir'

### ISSUE THREAD

**Issue by lhxaurora** [bbuchfink/diamond#803]
Greeting!

I am trying to run Diamond (version=2.1.9) via the cluster, I smoothly created the database, but cannot avoid  "Error: Invalid parameter count for option '--tmpdir'" problem no matter how did I set this parameter. here is the command I have tried:

diamond blastp -threads 20 -q C0_6_aa.fasta -d nr.dmnd -o C0_6_aa_vs_nr_blt.txt --max-target-seqs 10 -evalue 1e-5 --outfmt 6 qseqid qlen sseqid stitle slen pident length mismatch gapopen qstart qend sstart send evalue bitscore -t ./tmp
diamond blastp -threads 20 -q C0_6_aa.fasta -d nr.dmnd -o C0_6_aa_vs_nr_blt.txt --max-target-seqs 10 -evalue 1e-5 --outfmt 6 qseqid qlen sseqid stitle slen pident length mismatch gapopen qstart qend sstart send evalue bitscore
diamond blastp -threads 20 -q C0_6_aa.fasta -d nr.dmnd -o C0_6_aa_vs_nr_blt.txt --max-target-seqs 10 -evalue 1e-5 --outfmt 6 qseqid qlen sseqid stitle slen pident length mismatch gapopen qstart qend sstart send evalue bitscore -t /dev/shm

I have already checked that for each of the dictionary, there are enough space (>100G), could anyone kindly help me with solving this problem, thanks so much!

**Comment by bbuchfink** [comment]
The problem is -evalue should be --evalue

**Comment by LvbBo** [comment]
diamond blastp -threads 120 -q OM-RGC-Scs-Wpo-Mala_pro.fa -d /data3/durui/database/nr_db/nr.dmnd -o nr-dmnd-OM-RGC-Scs-Wpo-Mala.txt --max-target-seqs 10 --evalue 1e-5 --outfmt 6 qseqid qlen sseqid stitle slen pident length mismatch gapopen qstart qend sstart send evalue bitscore --tmpdir ./tmp                                                                                                                   
    same question i encountered;  who can help me ? please!!!!!!!!!!

**Comment by LvbBo** [comment]
> The problem is -evalue should be --evalue

unfunctional/not working

**Comment by LvbBo** [comment]
> Greeting!
> 
> I am trying to run Diamond (version=2.1.9) via the cluster, I smoothly created the database, but cannot avoid "Error: Invalid parameter count for option '--tmpdir'" problem no matter how did I set this parameter. here is the command I have tried:
> 
> diamond blastp -threads 20 -q C0_6_aa.fasta -d nr.dmnd -o C0_6_aa_vs_nr_blt.txt --max-target-seqs 10 -evalue 1e-5 --outfmt 6 qseqid qlen sseqid stitle slen pident length mismatch gapopen qstart qend sstart send evalue bitscore -t ./tmp diamond blastp -threads 20 -q C0_6_aa.fasta -d nr.dmnd -o C0_6_aa_vs_nr_blt.txt --max-target-seqs 10 -evalue 1e-5 --outfmt 6 qseqid qlen sseqid stitle slen pident length mismatch gapopen qstart qend sstart send evalue bitscore diamond blastp -threads 20 -q C0_6_aa.fasta -d nr.dmnd -o C0_6_aa_vs_nr_blt.txt --max-target-seqs 10 -evalue 1e-5 --outfmt 6 qseqid qlen sseqid stitle slen pident length mismatch gapopen qstart qend sstart send evalue bitscore -t /dev/shm
> 
> I have already checked that for each of the dictionary, there are enough space (>100G), could anyone kindly help me with solving this problem, thanks so much!

The problem is -d nr.dmnd,  you should not use nr.dmnd directly, you can use that like this:  /data3/durui/database/nr_db/nr(right)；nor /data3/durui/database/nr_db/nr.dmnd(wrong)

**Comment by LvbBo** [comment]
I have fixed this problem by downgrading the version of conda : conda install -c bioconda conda=24.3.0; Hope this method can be work for others!!!



在 2024-10-20 21:58:01，"Benjamin Buchfink" ***@***.***> 写道：

Closed #803 as completed.
