### ISSUE TITLE
Error: Error opening temporary file 24/diamond-tmp-YA0Xiz

### ISSUE THREAD

**Issue by JipengLuo** [bbuchfink/diamond#809]
I got this error with diamond version v2.1.9.163 when i tried to make the database using 'nr.gz' data,
the script like this: diamond makedb -t 24 --in nr.gz -d nr --taxonmap ./prot.accession2taxid.FULL.gz --taxonnodes ./nodes.dmp --no-unlink

diamond v2.1.9.163 (C) Max Planck Society for the Advancement of Science, Benjamin Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 128
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
Database input file: nr.gz
Opening the database file...  [0.177s]
Loading sequences...  [10.985s]
Masking sequences...  [2.148s]
Writing sequences...  [1.039s]
Writing accessions...  [2.469s]
Hashing sequences...  [0.272s]
Loading sequences...  [10.911s]
Masking sequences...  [2.028s]
Writing sequences...  [0.962s]
Writing accessions...  [2.481s]
Hashing sequences...  [0.27s]
Loading sequences...  [10.93s]
Masking sequences...  [2.116s]
Writing sequences...  [0.948s]
Writing accessions...  [2.421s]
Hashing sequences...  [0.27s]
Loading sequences...  [10.926s]
Masking sequences...  [2.185s]
Writing sequences...  [0.967s]
Writing accessions...  [2.511s]
Hashing sequences...  [0.271s]
Loading sequences...  [10.871s]
Masking sequences...  [2.127s]
Writing sequences...  [0.956s]
Writing accessions...  [2.421s]
Hashing sequences...  [0.283s]
Loading sequences...  [10.938s]
Masking sequences...  [2.036s]
Writing sequences...  [0.958s]
Writing accessions...  [2.414s]
Hashing sequences...  [0.271s]
Loading sequences...  [10.919s]
Masking sequences...  [2.132s]
Writing sequences...  [0.992s]
Writing accessions...  [2.407s]
Hashing sequences...  [0.29s]
Loading sequences...  [10.831s]
Masking sequences...  [2.142s]
Writing sequences...  [0.957s]
Writing accessions...  [2.631s]
Hashing sequences...  [0.308s]
Loading sequences...  [10.951s]
Masking sequences...  [1.981s]
Writing sequences...  [0.951s]
Writing accessions...  [2.419s]
Hashing sequences...  [0.269s]
Loading sequences...  [10.856s]
Masking sequences...  [2.122s]
Writing sequences...  [0.954s]
Writing accessions...  [2.422s]
Hashing sequences...  [0.27s]
Loading sequences...  [10.904s]
Masking sequences...  [2.083s]
Writing sequences...  [0.953s]
Writing accessions...  [2.411s]
Hashing sequences...  [0.299s]
Loading sequences...  [10.964s]
Masking sequences...  [2.002s]
Writing sequences...  [0.961s]
Writing accessions...  [2.418s]
Hashing sequences...  [0.271s]
Loading sequences...  [10.896s]
Masking sequences...  [2.171s]
Writing sequences...  [1.034s]
Writing accessions... No such file or directory
Error: Error opening temporary file 24/diamond-tmp-d8vkun
diamond v2.1.9.163 (C) Max Planck Society for the Advancement of Science, Benjamin Buchfink, University of Tuebingen
Documentation, support and updates available at http://www.diamondsearch.org
Please cite: http://dx.doi.org/10.1038/s41592-021-01101-x Nature Methods (2021)

#CPU threads: 128
Scoring parameters: (Matrix=BLOSUM62 Lambda=0.267 K=0.041 Penalties=11/1)
Temporary directory: No such file or directory
Error: Error opening temporary file 24/diamond-tmp-YA0Xiz

I have tried it by using different parameters such as '-no-unlink', but the same error occurred. Hope someone can help me solve this problem.

**Comment by bbuchfink** [comment]
You need to use `-p` instead of `-t` to specify the number of threads. This sets the temporary directory to `24` which does not exist.
