### ISSUE TITLE
It would be useful to be able to get a database subject by title

### ISSUE THREAD

**Issue by terrycojones** [bbuchfink/diamond#81]
I'm trying to upgrade a package that uses BLAST to also be able to use Diamond. In BLAST you can run `blastdbcmd -entry TITLE` to print information about a db subject. Diamond has `diamond getseq --seq N` but it looks like `N` has to be a number. That requires that the user already knows the numbers of the subjects in the database.  Would it be possible to support using a subject title in `getseq`?  I guess that would require either a slow lookup in the current db format or else the addition of a title to subject index and hence a db format change?

I could make some kind of title index file myself, using the assumption that the numbers diamond assigns are the order of the sequences in the original FASTA (I'm not sure if this is true), but it would be nice not to have to.

**Comment by bbuchfink** [comment]
Yes it would require either including a title index in the db or a slow search over the whole db, both of which would be possible for me to implement.

The numbers are the same as in the original FASTA file.

**Comment by terrycojones** [comment]
Thanks. I think I'll work around it for now.
