### ISSUE TITLE
Cannot include both --query_cover and --subject_cover in my search.

### ISSUE THREAD

**Issue by KPapac** [bbuchfink/diamond#812]
Hi there,

I am using diamond v2.1.9.163 which I downloaded from a tar.gz file following the [github instructions](https://github.com/bbuchfink/diamond/wiki) and I have made a custom database with Drosophilidae proteins to search against. I want to make a strict search, so I want to include only matches with both query coverage and subject coverage above 80%. For query coverage more than 80% I execute:

`/space/Software/diamond blastx -d '/space/Software/eggnog_5.0_drosophilids_DB/myDrosophila.dmnd' -q '/space/no_backup/Kostas/annotating_fly_genomes/unclustered.fna' --threads 30 -o '/space/no_backup/Kostas/annotating_fly_genomes/testing_unclustered.emapper.hits' --sensitive --iterate -e 1e-06 --query-cover 80.0 --top 3  --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore qcovhsp scovhsp`

and works as expected.

For subject coverage more than 80% I execute: 

`/space/Software/diamond blastx -d '/space/Software/eggnog_5.0_drosophilids_DB/myDrosophila.dmnd' -q '/space/no_backup/Kostas/annotating_fly_genomes/unclustered.fna' --threads 30 -o '/space/no_backup/Kostas/annotating_fly_genomes/testing_unclustered.emapper.hits' --sensitive --iterate -e 1e-06 --subject-cover 80.0 --top 3 --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore qcovhsp scovhsp`

and works as expected.

But when I add both flags --query-cover 80.0 and --subject-cover 80.0 like this:`
/space/Software/eggnog/bin/diamond blastx -d '/space/Software/eggnog_5.0_drosophilids_DB/myDrosophila.dmnd' -q '/space/no_backup/Kostas/annotating_fly_genomes/unclustered.fna' --threads 30 -o '/space/no_backup/Kostas/annotating_fly_genomes/testing_unclustered.emapper.hits' --sensitive --iterate -e 1e-06 --query-cover 80.0 --subject-cover 80.0 --top 3  --outfmt 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore qcovhsp scovhsp`

I get: `Error: vector::_M_range_check: __n (which is 8547) >= this->size() (which is 4095)`
4095 is the number of fasta sequences I have in my query file "unclustered.fna", but I don't recognise the 8547 number.

Any ideas what is going on?

Cheers,
Kostas

**Comment by bbuchfink** [comment]
This should be fixed in the latest release.
