### ISSUE TITLE
Conda/bioconda install - packages not found error

### ISSUE THREAD

**Issue by ryan-boobybiome** [bbuchfink/diamond#813]
I'm trying to install diamond via bioconda following the instructions on the wiki. I have created a new conda environment and then used:

`conda install -c bioconda -c conda-forge diamond`

I get a `PackagesNotFoundError`:

```
Channels:
 - bioconda
 - conda-forge
 - defaults
Platform: osx-arm64
Collecting package metadata (repodata.json): done
Solving environment: failed

PackagesNotFoundError: The following packages are not available from current channels:

  - diamond

Current channels:

  - https://conda.anaconda.org/bioconda
  - https://conda.anaconda.org/conda-forge
  - defaults

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

Does anyone know what the issue is?

**Comment by LotharukpongJS** [comment]
Dear @ryan-boobybiome ,

I came across a similar issue recently in my MacBook (M1 chip). I ended up installing `diamond` via homebrew (`brew install diamond`). This might be useful https://stackoverflow.com/questions/77441981/problems-installing-with-conda-under-macos-14-1-m1.

Best,
Sodai

**Comment by bbuchfink** [comment]
Conda support for Apple M1 is pending. I recommend to compile from source in the meantime.

**Comment by bbuchfink** [comment]
ARM64 binaries for macOS and Linux are now available on bioconda.
