### ISSUE TITLE
segmentation fault

### ISSUE THREAD

**Issue by juliayork** [bbuchfink/diamond#815]
I'm getting segmentation faults thrown with one transcriptome, tried running both blastx and blastp and both fail. See here for the files:
https://drive.google.com/file/d/1v2f7wH-6G4MvFERaaZ96aDeFJjTfRvqQ/view?usp=sharing
https://drive.google.com/file/d/1pGxMq9GdbskZvgicWR79EmSCmwKOM7WA/view?usp=sharing

Is there a way I can fix this? Thanks!

**Comment by bbuchfink** [comment]
Please provide the command line you used to run diamond and your version.

**Comment by juliayork** [comment]
The command was:
```
diamond blastp --query /path/ncor_cdhit.fasta.transdecoder_dir/longest_orfs.pep  \
    --db /data2/ref_seq_June2024/refseq_vertebrate_other.protein.dmnd  --max-target-seqs 1 \
    --outfmt 6 --out ncor_cdhit_td_blast
```
diamond version 2.1.9

let me know if you can reproduce the error or you need more information. Thanks for your help!

**Comment by juliayork** [comment]
Good point. When I go back to recreate the error, it occurred only when I was running diamond through EnTAP. Running diamond alone on the files completes correctly. Seems to be an error with EnTAP so I will post the issue there. Sorry for posting it in error here, I appreciate your follow up and help.

**Comment by juliayork** [comment]
Hmm ok doing some more testing I was able to reproduce the error outside of EnTAP. The command is: 

`diamond blastx -p 8 -o /path/similarity_search/DIAMOND/blastx_ncor_cdhit_final_refseq_vertebrate_other.out --very-sensitive --max-target-seqs 3 --evalue 0.000010 -f 6 qseqid sseqid pident length mismatch gapopen qstart qend sstart send evalue bitscore qcovhsp stitle --subject-cover 50.000000 --query-cover 50.000000 -q /path/transcriptomes/ncor_cdhit.fasta -d /data2/ref_seq_June2024/refseq_vertebrate_other.protein.dmnd 
`
If you run these parameters with the ncor_cdhit.fasta file do you also get an error? It seems to occur with blastx and blastp; diamond runs just fine with this database with other queries.

**Comment by bbuchfink** [comment]
I can reproduce this, it will be fixed in the next release. You can work around by not using a mutual coverage cutoff.

**Comment by juliayork** [comment]
Great, thanks so much! Just for my reference, what's the argument for turning off the mutual coverage cutoff?

**Comment by bbuchfink** [comment]
Use either `--query-cover` or `--subject-cover`, but not both. You can just filter the hits from the output file instead.

**Comment by juliayork** [comment]
Perfect, thanks so much for all your help!

**Comment by bbuchfink** [comment]
The crash should be fixed in the latest release.
