### ISSUE TITLE
paired-end diamond with local database

### ISSUE THREAD

**Issue by 2061574124** [bbuchfink/diamond#816]
With metagenome paired-end sequencing data, when I combined paired read1 and pared read2 into one read using flash2 or pandaseq, found that many pairs were not paired, that is, there was no overlap. I would like to ask if I can directly use paired-end sequencing data as two read for direct diamond analysis.

**Comment by bbuchfink** [comment]
Yes you can, you just need to be aware that diamond will always treat the reads separately.
