### ISSUE TITLE
It would be useful to be able to get the query title in output format 6

### ISSUE THREAD

**Issue by terrycojones** [bbuchfink/diamond#82]
There is a `stitle` option for output format 6 but no corresponding `qtitle`. It would be nice to have this because upstream tools sometimes introduce spaces in FASTA `>` lines (e.g., to show nucleotide offsets). Because you can't currently get this information out of DIAMOND, pre-processing is required to replace spaces in input FASTA, followed by post-processing to put them back.

To give a concrete example, I have code that reads DNA FASTA, makes the 6 translations, finds ORFs, and adds information to the `>` line about the direction, frame, and ORF offsets. It adds a space and then this information. Of course I can change it to not do that, but it would be convenient not to have to.

In any case, if DIAMOND unconditionally throws away the extra information it can make matching its output back to the original FASTA impossible (due also to the fact that in tabular format an input query that matches nothing will have no output at all). So, e.g., if two query sequences are given and their `>` lines are identical up to the first space and there is just one line of output, it may not be possible to tell which query sequence was involved in the match (the matched subsequence may tell you, but maybe not).

**Comment by bbuchfink** [comment]
Sure, I'll include this in the next version.

**Comment by terrycojones** [comment]
Thanks!

**Comment by terrycojones** [comment]
This has been done. Closing.
