### ISSUE TITLE
output parameter prevents diamond realign workflow

### ISSUE THREAD

**Issue by tag92-CornellUniv** [bbuchfink/diamond#820]
Hello!

Thank you so much for providing such a phenomenal analysis tool. I am currently attempting to run DIAMOND cluster on protein sequences pulled from NCBI (~370000). When running DIAMOND cluster, these sequences are arranged into unique clusters with representative sequences, but DIAMOND realign seems to not align these members to the centroid. Is this an issue with my analysis? I would like to generate Markov clusters to visualize the data. Please let me know if I am misunderstanding anything with DIAMOND. 

Edit: I have noticed that when the output parameter is removed, the realign analysis runs correctly.

**Comment by bbuchfink** [comment]
I could not reproduce the issue, please reopen in case it still persists.
