### ISSUE TITLE
option --memory-limit raises error

### ISSUE THREAD

**Issue by h836472** [bbuchfink/diamond#825]
The use of "--memory_limit" option with blastp raises error "_Error: Option is not permitted for this workflow: memory-limit_" when using current latest diamond version of **2.1.9**. Previous versions (for example 2.0.2 and 2.0.4) accept this option and perform the search without any issue. Has the memory_limit option been indeed removed from recent diamond releases? If so, why? Is there any plan to implement memory limitation with diamond blastp search in the future?

**Comment by bbuchfink** [comment]
The option never had an effect on the search workflows, it's only intended to be used for clustering.
