### ISSUE TITLE
ERROR [diamond_search()]

### ISSUE THREAD

**Issue by hysong0921** [bbuchfink/diamond#827]
hi，
INFO:
The PfamA profile DB was not found and will now be created.

###### PfamA profile DB creation and indexing ######
INFO:
It might take a few minutes,
and will be done only at the first run after the installation.
INFO:
Indexing the profile database, be patient...

Run START:      Mon Aug 19 10:10:22 2024
SonicParanoid 2.0.8 will be executed with the following parameters:
Run ID: roject
Input directory: /dt1/hysong/02.genome/wheat/test
Main output directory: /dt1/hysong/result-sonic
Run directory: /dt1/hysong/result-sonic/runs/roject
Input proteomes:        19
Alignment tool: diamond
Run mode:       default (Diamond [--very-sensitive])
Threads:        5
Minimum bitscore:       40
Max length difference for in-paralogs:  0.75
Ortholog merging threshold:     0.75
MCL inflation:  1.50
Alignments directory: /dt1/hysong/result-sonic/alignments/
Pairwise tables directory: /dt1/hysong/result-sonic/runs/roject/species_to_species_orthologs/
Directory with ortholog groups: /dt1/hysong/result-sonic/runs/roject/ortholog_groups/
Pairwise tables database directory: /dt1/hysong/result-sonic/orthologs_db
Perform only graph-based orthology:      False
Update run:     False
Create query database indexes:  False
Complete overwrite:     False
Re-create ortholog tables:      False
Memory per thread (Gigabytes):  403.10
Minimum memory per thread (Gigabytes):  1.00
Compress alignments:    True
Compression level:      5
SonicParanoid installation directory: /dt1/hysong/miniconda3/envs/sonicparanoid/lib/python3.11/site-packages/sonicparanoid
Installation type:      miniconda3
Python version: 3.11.0 | packaged by conda-forge | (main, Jan 14 2023, 12:27:40) [GCC 11.3.0]
Python executables: /dt1/hysong/miniconda3/envs/sonicparanoid/bin/python3.11
runID:  roject

For the 19 input species 171 combinations are possible.

361 Diamond alignments will be performed...
Creating 19 Diamond databases...

Diamond databases creation elapsed time (seconds):      32.323

ERROR [diamond_search()]: the Diamond DB
/dt1/hysong/result-sonic/seqs_dbs/19.dmnd
is missing.
Generate the DB before searching.
ERROR [diamond_search()]: the Diamond DB
/dt1/hysong/result-sonic/seqs_dbs/1.dmnd
is missing.
Generate the DB before searching.

all-vs-all alignments:  13%
how can i solve this problem? only 2 in 19,thanks

**Comment by bbuchfink** [comment]
This does not look like a diamond error. Please ask the downstream provider (SonicParanoid) for support.
