### ISSUE TITLE
qseq in outfmt 6 seems incorrect

### ISSUE THREAD

**Issue by terrycojones** [bbuchfink/diamond#83]
I've just been doing some simple experiments to make sure output formats and offsets etc., are as expected (and to look for tiny differences from BLAST output). I don't understand the `qseq` output in the following.

I make a database from this:

```sh
$ cat subject.fasta
>sbjct
APSTRSTKFNGM*PADTMQKDLPGITNSIEILK
```
and here's a DNA query (it matches the AA sequence above perfectly, when translated):
```sh
$ cat query-dna.fasta
>query
GCTCCGAGCACGAGATCAACGAAGTTTAACGGGATGTAGCCAGCGGACACAATGCAAAAAGACTTACCAGGAATTACTAACTCTATCGAAATACTGAAA
```
When I run `blastx` on it and ask for the query sequence to be printed, the output is as follows:
```sh
$ diamond blastx --db one.dmnd --query query-dna.fasta --outfmt 6 qseq
A G CG NCGR   AT  NTQ RD GGDKDQNQCACTCGQ RNGC NNN  KQQ QGN  YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
```

The query sequence is printing as 99 AAs (the length of the query is 99 nucleotides). The AAs don't match the translated (subject) sequence at all. The bitscore looks fine, so a match is happening:
```sh
diamond blastx --db one.dmnd --query query-dna.fasta --outfmt 6 bitscore qseq | tr '\011' _
67.8_A G CG NCGR   AT  NTQ RD GGDKDQNQCACTCGQ RNGC NNN  KQQ QGN  YYYYYYYYYYYYYYYYYYYYYYYYYYYYYYYY
```

(I replaced the TAB in the output with a `_` just to be sure).

It feels like there could be a memory problem here?  Or maybe I don't understand something?

```sh
$ diamond version
diamond version 0.8.24
```

**Comment by bbuchfink** [comment]
Ok this is a bug for the blastx mode, will fix in the next version.

**Comment by terrycojones** [comment]
OK, thanks!

**Comment by terrycojones** [comment]
Hi Benjamin

Do you have any kind of release schedule / expectation for a next release?  Maybe I can help to fix these small issues if you give me a few pointers. My C++ is almost non-existent, though I wrote C for many years (and only very little C++). I can probably manage, though.  Thanks!

**Comment by bbuchfink** [comment]
I should be able to do it until tomorrow night. It's probably going to be easier if I do it.

**Comment by terrycojones** [comment]
OK, great. Let me know if I can help. BTW, is there a test suite? I could write some tests if so. Thanks!

**Comment by bbuchfink** [comment]
There is no test suite, but it would certainly make sense to have one.

**Comment by bbuchfink** [comment]
I fixed this and also added the qtitle field. The changes are commited although no new release yet.

**Comment by terrycojones** [comment]
OK, both look like they work. Thanks!  No need for a release from me, I can use the git HEAD. Closing.
