### ISSUE TITLE
Minimum query length in diamond blastp

### ISSUE THREAD

**Issue by bucongfan** [bbuchfink/diamond#832]
I noticed that Diamond fails to produce output when the query sequence is too short, even if an identical sequence exists in the database.

For example, with the following test FASTA:

\>a
MVSVQLVCSRK

I tried using the --sensitive, --more-sensitive, and --ultra-sensitive modes, as well as adjusting parameters like evalue and max-hsps, but none of these approaches resulted in an output.

Is there a specific parameter that can ensure Diamond provides a comprehensive output, particularly for short sequences? For instance, in an all-against-all alignment, I would expect at least the query to align with itself.

Thanks.

**Comment by mrazkiya** [comment]
I have same issues using uniref90.fasta. Whenever I try to run the diamond, the result will be 0 queries aligned.

**Comment by bbuchfink** [comment]
A number of internal cutoffs need to be changed for this. I was able to get the self-alignment for your sequence using `--very-sensitive --shape-mask 11111 --id2 1 --ungapped-evalue 0 --gapped-filter-evalue 0`. Note that `--ungapped-evalue` is currently only available when compiling with `-DEXTRA=ON`, I will make in available in the next release. You probably need to play around with these cutoffs and others (see command line help) to get optimal behaviour for your application.

**Comment by bucongfan** [comment]
@bbuchfink Many thanks!
