### ISSUE TITLE
SIGBUS when running diamond blastx on Mac OS X

### ISSUE THREAD

**Issue by terrycojones** [bbuchfink/diamond#84]
I have OS X 10.10.5 gcc 4.9.3 and am getting a SIGBUS when running blastx.

Here are two FASTA files:

``` sh
$ cat /tmp/subject.fasta
>sbjct
GC*DLGHDH*IVMRGQNDDKVRAAAVRYMHPV*

$ cat /tmp/query-rc2dna.fasta
>id
CAAACCGGATGCATATAGCGGACTGCCGCTGCTCGCACTTTATCGTCATTTTGTCCCCGCATCACGATCTAGTGGTCATGACCGAGGTCCTAACAACCG
```

Make a database from the subject file:

``` sh
$ diamond makedb --in /tmp/subject.fasta --db /tmp/one
diamond v0.8.24.86 | by Benjamin Buchfink <buchfink@gmail.com>
Check http://github.com/bbuchfink/diamond for updates.

#CPU threads: 8
Database file: /tmp/subject.fasta
Opening the database file...  [0.000144s]
Loading sequence data (0 sequences processed)...  [1.2e-05s]
Writing trailer...  [4e-06s]
Closing the database file...  [9.4e-05s]
Processed 1 sequences, 33 letters.
Total time = 0.000299s
```

Running `diamond blastx` results in a SIGBUS:

``` sh
$ diamond blastx --db /tmp/one.dmnd --query /tmp/query-rc2-dna.fasta
fish: Job 2, '~/s/net/diamond/bin/diamond blastx --db /tmp/one.dmnd --query /tmp/query-rc2-dna.fasta' terminated by signal SIGBUS (Misaligned address error)
```

**Comment by bbuchfink** [comment]
I ran the same on a Mac with version 10.11.6 and didn't get the error. Unfortunately, that makes it hard to track down the problem. I'll have to think about it.

**Comment by bbuchfink** [comment]
Can you run this with option --log and show me the console output?

**Comment by terrycojones** [comment]
Argh.... I must have gotten the files wrong somehow. I run the above and the error no longer happens. I'm not imagining things though :-)  See screenshot. I'll watch for it again & be more careful to make sure I can reproduce it (I thought I tested the above
![screen shot 2016-10-19 at 8 22 32 pm](https://cloud.githubusercontent.com/assets/132978/19534020/04665dc0-963a-11e6-9c0d-924223c84bad.png)
).

**Comment by terrycojones** [comment]
I just saw it again, and can now see what I must have been doing. If you run `diamond blastx` and give the name of a query file that doesn't exist you get the error above. E.g.,

```sh
$ diamond blastx --db /tmp/one.dmnd --query xxxxxxx
fish: Job 2, 'diamond blastx --db /tmp/one.dmnd --query xxxxxxx' terminated by signal SIGBUS (Misaligned address error)

$ ls xxxxxxx
ls: xxxxxxx: No such file or directory
```

**Comment by bbuchfink** [comment]
Ok I get the same problem, I'll look into it.

**Comment by bbuchfink** [comment]
This should be fixed in the latest version.

**Comment by terrycojones** [comment]
Yes, confirmed fixed. Closing.

**Comment by terrycojones** [comment]
And, thanks :-)
