### ISSUE TITLE
some regions of some sequences were converted to Xs after exporting unaligned queries with --un in diamond blastp

### ISSUE THREAD

**Issue by permia** [bbuchfink/diamond#843]
Hi, I try to use `-un` to export unaligned sequences directly and find that some sequences were converted to Xs. e.g.

The input sequence:
>k141_1964_flag1_multi6_len1661.p2
MITELGIAFFSIVILVSSLARIMSIPAPLTSSVAGVLFSATVDLVVFLVVPSLTLGTLNYVVICTRFLPPSFIIILLVTFIIFLVIFVGSPFWIIVALRPLIILWLVILWLLRVIVGFAVLIPRTCTKAGFSIVLLITRACTTSRITFVLFLIRVCPAPCVAVILLLIRISPTSRSSIIPTARISSPTTGIVIVVLSIGV*

The unaligned sequences exported by diamond:
>k141_1964_flag1_multi6_len1661.p2
MITELGIAFFSIVILVSSLARIMSIPAPLTSSVAGVLFSATVDLVVFLVVPSLTLGTLNYVVICTRFLPPSFIIILLVTFIIFLVIFVGSPFWIIVALRPLIILWLVILWLLRVIVGFAVLIPRTCTKAGFSIVLXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXSRSSIIPTARISSPTTGIVIVVLSIGV

The commond I used. (diamond version v2.1.9)
```
    $DIAMOND blastp \
    --threads "${threads}" \
    --db "${db}" \
    --query "${input_fasta}" \
    --out "${output_dir}"/"${input_bn}"_diamond_"${db_name}"_tmp.txt \
    --un "${output_dir}"/"${input_bn}"_diamond_unaligned.faa \
    --outfmt 6 qseqid qlen sseqid slen stitle length pident ppos qstart qend sstart send evalue bitscore \
    --ultra-sensitive \
    --max-target-seqs 1 \
    --evalue 0.001
```

**Comment by bbuchfink** [comment]
The only way to fix this at the moment is to use `--masking 0`, but that means the repeat masking will also not be applied during alignment. It should be ok to do this when also using `--soft-masking tantan`.

**Comment by permia** [comment]
> The only way to fix this at the moment is to use `--masking 0`, but that means the repeat masking will also not be applied during alignment. It should be ok to do this when also using `--soft-masking tantan`.

Thanks for your kindly reply. I got it, now.
