### ISSUE TITLE
It would be good to be able to see gaps in the query and subject

### ISSUE THREAD

**Issue by terrycojones** [bbuchfink/diamond#85]
In the `qseq` and `sseq` sequences produced for `--outfmt 6` gaps introduced in the matching are not shown in either the query or the subject. There are `gaps` and `gapopen` directives, but these are not specific to the query or subject. (The `gaps` directive seems to report number of gaps at the AA level, even if a gap is opened up in a nucleotide query.)

It would be very useful to be able to see the gaps in the query and/or subject. That way it's possible to tell how the alignment went. Without that information it's necessary to re-examine the `qseq` and `sseq` sequences to try to figure it out yourself - which is error prone, and besides the work has just been done by DIAMOND. So there could be `qseqwithgaps` and `sseqwithgaps` directives, if that's not too hard. The caller could then count the (e.g.) hyphens in those sequences to see how many gaps there were in each, etc. My use case is that I create visualizations of matches, showing how queries align to a subject. It's not possible to do that accurately unless I know where the gaps are in the query.

A possible half-measure would be just being able to know the gap counts for the query and subject separately.

How does that sound?  Thanks! :-)

**Comment by bbuchfink** [comment]
Blast has the btop field for this purpose, see here: https://www.ncbi.nlm.nih.gov/books/NBK279682/
So it would probably be best to do it the same way as blast.

**Comment by terrycojones** [comment]
Thanks - I didn't know about the `btop` directive. It seems straightforward for nucleotide-nucleotide matches. But for nucleotide-protein it wouldn't be so simple. A "gap" in the query to make it align with the subject might be 3 nucleotides, which isn't supported by btop. Maybe you'd need to have a btop string like `7(AC)K30` using parens to show what was in the query to match the `K` (in this example) in the subject.  That might get a bit messy, but maybe not.

Anyway, is there one of these kinds of approaches that is easier in terms of implementation? If I knew more about what DIAMOND does internally I'd have a better idea of what to suggest, and could try doing it. Sorry to be such a useless user... :-(

**Comment by bbuchfink** [comment]
I guess blast will use the translated amino acid in case of the blastx mode, so I don't see a problem there.

Btw these sequence strings including gaps are already contained in the xml format, the only disadvantage is that the format takes more space in general.

**Comment by bbuchfink** [comment]
I have now implemented the btop field and commited the changes.

**Comment by terrycojones** [comment]
Great :-)  Thank you!  Will you close this ticket or should I?
