### ISSUE TITLE
Bizarre results

### ISSUE THREAD

**Issue by pad1989** [bbuchfink/diamond#86]
Hi,

I've been looking at the outputs I've received.

My options were:

`diamond` blastx --query ma_2.fasta --db diamond_protdb.dmnd --threads 30 --max-target-seqs 10 --outfmt 6 --evalue 0.00001 `--sensitive`

I am getting hits to the same sequence, however the values are changing for it.

`aal_253085t1 tr|A0A0S3RZ45|A0A0S3RZ45_PHAAN  31.0    71      48      1       195     404     345     415     1.7e-03 50.8

aal_253085t1 tr|A0A0S3RZ45|A0A0S3RZ45_PHAAN  35.7    70      44      1       210     416     385     454     2.2e-03 50.4

aal_253085t1 tr|A0A0S3RZ45|A0A0S3RZ45_PHAAN  35.9    64      40      1       216     404     422     485     1.9e-02 47.4

aal_253085t1 tr|A0A0S3RZ45|A0A0S3RZ45_PHAAN  27.9    111     73      3       57      386     480     584     7.1e-02 45.4
`

I'm also getting a majority of negative e values; however I'm getting the odd value which is : 1.4e+03 for example. I set the e-value threshold... This is puzzling me. Any help?

**Comment by pad1989** [comment]
I've been doing some digging and looking at the results closer.

It seems that this may be due to several existing HSP segments existing in one matching sequence, as such DIAMOND prints them all, but limits to 10 sequences in total( with several HSPs reported for each sequence). Would that be correct?

If so, how does it still report positive e-values when a threshold has been determined? Thanks.

**Comment by bbuchfink** [comment]
Yes diamond will always report hits contained in the same target sequence regardless of their score, as long as the top hit for the target sequence is below the score treshold.

**Comment by pad1989** [comment]
Hi @bbuchfink  thank you very much for the reply. So just to clarify, even if I am getting positive e-values for some of them hits contained in the results (presumably due to how poor they are), as long as my filtered top hit for that query and target sequence is under 1x10-5 I'm fine

I'm using the command to extract;

sort -k1,1 -k12,12gr -k11,11g -k3,3gr genome_hits.txt | sort -u -k1,1 --merge > besthits_genome

This is fine?

Thanks for the software, I was shocked at how incredibly fast it is :-)

**Comment by bbuchfink** [comment]
Yes that should be fine. But I can't tell you if that command line works (not an expert on this).
