### ISSUE TITLE
More information could be provided when throwing file_format_exception

### ISSUE THREAD

**Issue by terrycojones** [bbuchfink/diamond#87]
In `guess_format` in `src/util/seq_file_format.cpp` a `file_format_exception` can be thrown. It would be good if the error message indicated the file name, the unrecognized character that was read, and the file offset.

I'm seeing some `Error: Invalid input file format` messages printed from DIAMOND runs and I'm not sure why. With no information printed about why that exception is raised it's hard to figure out what's going wrong.  I am providing a gzipped FASTQ query file whose first byte is an `@`:

``` sh
$ zcat file.fastq.gz | head -n 2 | od -a
0000000   @   H   I   S   E   Q   :   1   1   7   :   C   8   0   C   2
0000020   A   N   X   X   :   6   :   1   1   0   1   :   1   4   7   7
0000040   :   2   1   8   1  nl   C   G   A   T   G   A   G   C   G   A
0000060   C   G   C   G   C   C   G   A   G   C   A   C   C   T   T   G
0000100   A   G   A   T   C   G   G   A   A   G   A   G   C   A   C   A
0000120   C   G   T   C   T   G   A   A   C   T   C   C   A   G   T   C
0000140   A   C  nl
0000143
```

So I don't understand how this error can be happening.

**Comment by bbuchfink** [comment]
Could you try this again with the latest commit?

**Comment by terrycojones** [comment]
I don't have a way to reproduce this, but I will keep an eye out for it.
