### ISSUE TITLE
Error reading temporary file could be more informative

### ISSUE THREAD

**Issue by terrycojones** [bbuchfink/diamond#88]
Attempting to reproduce #87 I just did a DIAMOND run and got a different error:

``` sh
diamond blastx --threads 3 --query file.fastq.gz --db protein.dmnd --outfmt 6 qtitle stitle bitscore evalue qframe qseq qstart qend sseq sstart send slen
Error: Error reading temporary file: diamond-581fbfb4-2.tmp
```

It would be good if the error message said what was wrong with the file. Also, from `load` in `src/util/async_buffer.h` it looks like the file is removed - might be better not to remove it, but to print its path and leave it in the case of an error.  Is the `f.read` in that function supposed to read the entire query file? My query file is 158,467,015 bytes compressed, 772,955,810 uncompressed.

**Comment by bbuchfink** [comment]
I will look into making the error message more elaborate. I don't think leaving the temp file would be useful, the user won't be able to do anything with it. The f.read function there does not read the query file, it reads the temp file into memory.
