### ISSUE TITLE
Incorrect length of output sequences?

### ISSUE THREAD

**Issue by terrycojones** [bbuchfink/diamond#89]
Maybe I'm not understanding something here, but it seems DIAMOND `blastx` can print query and subject sequences that are of different lengths (i.e., the protein sequence is not 3 times the length of the DNA sequence). Here's some output:

```sh
$ diamond blastx --query file.fastq.gz --db protein.dmnd --outfmt 6 qtitle stitle bitscore evalue qframe qseq qstart qend sseq sstart send slen > diamond-debug
```

Look for the line that's causing me problems:

```sh
$ grep GCCGTCTTTGCTGACGTAGCCGTCGGTGTCCAGAAGTCCAGCGAGTAGGTCCCGGCGCTGCCG diamond-debug
HISEQ:117:C80C2ANXX:8:1301:19052:15017	gi|734475547|ref|WP_034086638.1| DNA helicase [Salmonella phage SETP7]	30.8	6.1e-04	-1	GCCGTCTTTGCTGACGTAGCCGTCGGTGTCCAGAAGTCCAGCGAGTAGGTCCCGGCGCTGCCG	69	7	RQRLELLAGLLDSDGYGDLSKAG	219	241	793
```

The DNA query sequence is 63 nucleotides = 21 AAs:

```sh
$ echo -n GCCGTCTTTGCTGACGTAGCCGTCGGTGTCCAGAAGTCCAGCGAGTAGGTCCCGGCGCTGCCG | wc -c
63
```

But the AA subject is 23 AAs:

```sh
$ echo -n RQRLELLAGLLDSDGYGDLSKAG | wc -c
23
```

The lengths of these two agree with the `qstart qend sstart send` numbers in the grep output.

I can supply the input database and FASTQ if this is indeed a bug. If not, I guess I don't understand what DIAMOND is supposed to be printing here.

**Comment by bbuchfink** [comment]
If there are gaps in the alignment then the sequences will not be the same length, that is to be expected.

**Comment by terrycojones** [comment]
OK, thank you. Looks like I'll need to parse that `btop` field :-)  Closing.
