### ISSUE TITLE
Input file is a DAA file (possibly related to issue - blastx error writing file)

### ISSUE THREAD

**Issue by agrier04** [bbuchfink/diamond#9]
Diamond runs without error with a small number of query sequences < ~30.  See issue "blastx error writing file."  However, the resulting daa files are not readable by view.  This is the error:

Error: Input file is not a DAA file.

This is the verbose output:

.diamond view -a out.daa -o out.tsv -v
diamond v0.7.9.58
# Threads = 16

Scoring matrix = blosum62
Lambda = 0.267
K = 0.041
Gap open penalty = 11
Gap extension penalty = 1
Seg masking = 0
SSSE3 enabled.
Error: Input file is not a DAA file.

I could provide an example of one of these files if you suggest a method to do so.

**Comment by bbuchfink** [comment]
Could you run the program with option --log and send me the resulting
diamond.log file?

Am Donnerstag, 30. April 2015 schrieb agrier04 :

**Comment by agrier04** [comment]
Here is the complete log:

Command line: ../diamond view -a matches.daa -o matches.tsv --log 
diamond v0.7.9.58
#Threads = 16
Scoring matrix = blosum62
Lambda = 0.267
K = 0.041
Gap open penalty = 11
Gap extension penalty = 1
Seg masking = 0
SSSE3 enabled.
/etc/issue
Error: Input file is not a DAA file.

There were no errors or warnings in the verbose output of the blastx that produced that daa file.  I've also e-mailed you the actual daa file.

**Comment by agrier04** [comment]
Resolved.

See issue #8: blastx error writing file.
