### ISSUE TITLE
runtime_error is not a member of std

### ISSUE THREAD

**Issue by terrycojones** [bbuchfink/diamond#90]
On a freshly git pulled repo, I see a build error that hasn't been there in previous versions:

```sh
$ bash build_simple.sh
In file included from src/util/zstr.hpp:17:0,
                 from src/util/compressed_stream.h:24,
                 from src/util/seq_file_format.h:26,
                 from src/util/seq_file_format.cpp:19:
src/util/strict_fstream.hpp: In static member function ‘static void strict_fstream::detail::static_method_holder::check_open(std::ios*, const string&, std::ios_base::openmode)’:
src/util/strict_fstream.hpp:94:10: error: ‘runtime_error’ is not a member of ‘std’
    throw std::runtime_error("");
          ^
```

The compilation fails and a new `diamond` executable is not made. This is OS X 10.10.5

It would be nice to have a `Makefile`. Shall I create one & send a pull request?

**Comment by bbuchfink** [comment]
I just commited an update that should fix this.

Cmake is the recommended way to compile diamond, it auto generates makefiles.

**Comment by terrycojones** [comment]
Hmmm... I've never used `cmake`. Running it by itself isn't very helpful & the man page doesn't really tell me what to do.  I just guessed `cmake -G 'Unix Makefiles'` and got a `Makefile`. `make` then works.

A building section could be added to the README. I'm happy to do it if you like. Or maybe people are just expected to know how to use `cmake`.

**Comment by bbuchfink** [comment]
There's a section in the manual that explains building.

**Comment by terrycojones** [comment]
Aha! :-)  Sorry to be so dense / slow. Thanks. I'll close this.
