### ISSUE TITLE
Failed to allocate sufficient memory. Please refer to the readme for instructions on memory usage.

### ISSUE THREAD

**Issue by raw937** [bbuchfink/diamond#91]
Don't see anything in the manual or readme. It runs for days and I have 63GB of ram. But, I have no idea why it would take so much memory?

error:
Failed to allocate sufficient memory. Please refer to the readme for instructions on memory usage.

**Comment by bbuchfink** [comment]
Hi,
can you tell me about your query data (what size, sequence lengths etc.), your database, your system specs and parameters of diamond?

**Comment by raw937** [comment]
Hello Brian,

24 threads, 63 GB per node. RefSeq78 = 23 GB size database. The blastp is
with a .faa of 1.2GB.

Cheers
Rick

**Comment by uqaleu** [comment]
Hello Brian

I seem to have the same issue when i was running diamond view. Here is a strace output:
strace diamond view -a U_6808                                                           5_genomic.faaVSimg.diamondblastp.daa -o U_68085_genomic.faaVSimg.diamondblastp
execve("/srv/sw/diamond/0.8.27/diamond", ["diamond", "view", "-a", "U_68085_genomic.faaVS                                                           img.diamond"..., "-o", "U_68085_genomic.faaVSimg.diamond"...], [/* 31 vars */]) = 0
uname({sys="Linux", node="curtin", ...}) = 0
brk(0)                                  = 0xb28000
brk(0xb292c0)                           = 0xb292c0
arch_prctl(ARCH_SET_FS, 0xb28980)       = 0
set_tid_address(0xb28c50)               = 35608
set_robust_list(0xb28c60, 0x18)         = 0
rt_sigaction(SIGRTMIN, {0x480c70, [], SA_RESTORER|SA_SIGINFO, 0x48b9b0}, NULL, 8) = 0
rt_sigaction(SIGRT_1, {0x480d00, [], SA_RESTORER|SA_RESTART|SA_SIGINFO, 0x48b9b0}, NULL,                                                            8) = 0
rt_sigprocmask(SIG_UNBLOCK, [RTMIN RT_1], NULL, 8) = 0
getrlimit(RLIMIT_STACK, {rlim_cur=8192*1024, rlim_max=RLIM_INFINITY}) = 0
readlink("/proc/self/exe", "/srv/sw/diamond/0.8.27/diamond", 4096) = 30
brk(0xb4a2c0)                           = 0xb4a2c0
brk(0xb4b000)                           = 0xb4b000
futex(0x94919c, FUTEX_WAKE_PRIVATE, 2147483647) = 0
futex(0x9491a8, FUTEX_WAKE_PRIVATE, 2147483647) = 0
brk(0xb4a000)                           = 0xb4a000
fstat(1, {st_mode=S_IFCHR|0620, st_rdev=makedev(136, 0), ...}) = 0
write(1, "diamond v0.8.27.89 | by Benjamin"..., 63diamond v0.8.27.89 | by Benjamin Buchfi                                                           nk <buchfink@gmail.com>
) = 63
write(1, "Check http://github.com/bbuchfin"..., 55Check http://github.com/bbuchfink/diamo                                                           nd for updates.
) = 55
write(1, "\n", 1
)                       = 1
time(NULL)                              = 1481256981
open("/sys/devices/system/cpu/online", O_RDONLY|O_CLOEXEC) = 3
read(3, "0-39\n", 8192)                 = 5
close(3)                                = 0
write(1, "#CPU threads: 40\n", 17#CPU threads: 40
)      = 17
open("U_68085_genomic.faaVSimg.diamondblastp.daa", O_RDONLY) = 3
fstat(3, {st_mode=S_IFREG|0664, st_size=655360, ...}) = 0
brk(0xb72000)                           = 0xb72000
read(3, "k\343>mGS\16<\0\0\0\0\0\0\0\0ph\372\0\375\177\0\0\2\0\0\0\0\0\0\0"..., 65536) =                                                            65536
lseek(3, 4294967296, SEEK_SET)          = 4294967296
read(3, "", 65536)                      = 0
lseek(3, 2448, SEEK_CUR)                = 4294969744
mmap(NULL, 1125796958912512, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = -1                                                            ENOMEM (Cannot allocate memory)
brk(0x3ffe8088a6000)                    = 0xb72000
mmap(NULL, 1125796959047680, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = -1                                                            ENOMEM (Cannot allocate memory)
mmap(NULL, 134217728, PROT_NONE, MAP_PRIVATE|MAP_ANONYMOUS|MAP_NORESERVE, -1, 0) = 0x7fb9                                                           d5cff000
munmap(0x7fb9d5cff000, 36704256)        = 0
munmap(0x7fb9dc000000, 30404608)        = 0
mprotect(0x7fb9d8000000, 135168, PROT_READ|PROT_WRITE) = 0
mmap(NULL, 1125796958912512, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = -1                                                            ENOMEM (Cannot allocate memory)
futex(0x94ad60, FUTEX_WAKE_PRIVATE, 2147483647) = 0
write(2, "Failed to allocate sufficient me"..., 98Failed to allocate sufficient memory. P                                                           lease refer to the manual for instructions on memory usage.) = 98
write(2, "\n", 1
)                       = 1
exit_group(1)                           = ?


This has happened to me a couple of times already. Thanks.

**Comment by bbuchfink** [comment]
Hi,
how big is your DAA file? Does the problem occur on a small file that you could send me?

**Comment by uqaleu** [comment]
Hello again


Here you go. I have the file attached. 

[U_68085_genomic.faaVSimg.diamondblastp.zip](https://github.com/bbuchfink/diamond/files/643559/U_68085_genomic.faaVSimg.diamondblastp.zip)

**Comment by bbuchfink** [comment]
I think this problem occured because the diamond run has not completed successfully. Please upgrade to the latest version of diamond and rerun the alignment, it should produce a better error message now in case it fails.

**Comment by Unode** [comment]
@bbuchfink I'm still seeing this error message in a situation caused by an incomplete database indexing.
Using version: v0.8.34.96

The problem was caused by an incomplete indexing that went by unnoticed. The indexing itself failed due to a sequence having 0 length. The process aborted and left an incomplete index (.dmnd) in place.
Subsequent uses of this index lead to the error: _Failed to allocate sufficient memory. Please refer to the manual for instructions on memory usage_.

Questions:
* Would it be possible for diamond to detect that the index is corrupt/incomplete and produce a more informative error?
* If indexing `makedb` fails due to some error, should diamond remove the incomplete index? It's useless as is anyway.

**Comment by bbuchfink** [comment]
That's a good idea, I'll see to include it in the next release.

**Comment by bbuchfink** [comment]
This has been added to the latest version.

**Comment by ErisonChen** [comment]
Hi,there 
 i've caught the same failure.

My  dmnd db is 40G, 
and the alignment seq is 200K with 650 PE150 reads.

errors:
 Failed to allocate sufficient memory. Please refer to the readme for instructions on memory usage.

**Comment by bbuchfink** [comment]
Hi,
what's your diamond version, your command line, your operating system, and
how much memory does your computer have?

**Comment by ErisonChen** [comment]
@bbuchfink  Thanks 。I found that the error came from the incomplete indexing.

**Comment by sfpravelo** [comment]
May I know how was this problem fixed? Thanks!
