### ISSUE TITLE
reported % identities are lower than those of BLASTX

### ISSUE THREAD

**Issue by eead-csic-compbio** [bbuchfink/diamond#92]
Hi, 
I've been trying diamond v0.8.25 and I'm quite impressed with it. 
In my hands, the (more-sensitive) alignment coordinates eturned are largely identical to those produced with ncbi-blast-2.2.30+/bin/blastx. However, in some cases the computed identities are significantly lower. I show my point with one example. 

Diamond output:
query1 Q5XF36.1 63.6 88 32 0 434 697 18 105 4.3e-24 112.8
BLASTX:
query1 Q5XF36.1 96.5 88 3 0 434 697 18 105 4e-27 111

Is there an explanation for that?
Thanks,
Bruno

**Comment by bbuchfink** [comment]
The reason in this case is probably the SEG masking (low complexity filter). Blast counts the masked residues as identical and diamond does not. It is something I plan to change in a future version.

**Comment by eead-csic-compbio** [comment]
Ok thanks, that would be helpful, great work!
