### ISSUE TITLE
diamond makedb: File format error: sequence of length 0

### ISSUE THREAD

**Issue by moskalenko** [bbuchfink/diamond#93]
0.8.25 doesn't build a database from md5nr.fa. It exits with the 

Loading sequence data (35400000 sequences processed)...  [0.564902s]
Loading sequence data (35500000 sequences processed)...  [0.740178s]
Loading sequence data (35600000 sequences processed)...  [0.581567s]
Loading sequence data (35700000 sequences processed)...  [0.138271s]
Error: File format error: sequence of length 

error without specifying the problematic sequence, which leaves a million sequences to verify. The error message should specify the sequence.

**Comment by bbuchfink** [comment]
Ok, I'll provide a fix for this shortly.

**Comment by moskalenko** [comment]
Thanks! I'd like to test 0.8.25 before proceeding with additional debugging of why 0.8.5 blastx on a fastq file against the md5nr db segfaults.

**Comment by bbuchfink** [comment]
I just commited a patch that will include the line number in the error message.

**Comment by moskalenko** [comment]
Thank you for the quick response. With the empty entry located and removed diamond makedb completed successfully.

Best wishes,

Alex
