### ISSUE TITLE
Error: Incompatible database version

### ISSUE THREAD

**Issue by danshu** [bbuchfink/diamond#94]
Hi,

When I tried to run the latest version of diamond using the nr database created using an earlier diamond version, I have this error message "Error: Incompatible database version". Do I need to create a new nr database or there is a more convenient solution?

Best,
Quan

**Comment by bbuchfink** [comment]
Hi,
you need to create a new database, but that's only going to take a couple of minutes.

**Comment by danshu** [comment]
@bbuchfink Thanks!
