### ISSUE TITLE
Error: Invalid character (P/80) in sequence

### ISSUE THREAD

**Issue by frcamacho** [bbuchfink/diamond#95]
Hi there, 

I am trying to run a diamond blastx but I seem to be getting this error: Error: Invalid character (P/80) in sequence. From reading up I see 80 is the Ascii value for P. However, I am unsure why would P be an invalid character? 
Thanks.

**Comment by bbuchfink** [comment]
Hi Francine,
if you run diamond blastx your input is DNA sequences, so the only valid characters would be ACGTN. Diamond also accepts MRWSYKVHDBX because these encode ambiguous nucleotides, but to my knowledge P is not a valid letter in DNA sequences.

Best regards,
Benjamin

**Comment by frcamacho** [comment]
Thanks Benjamin. Was wondering why blastx could accept MRWSYKVHDBX but not P.

**Comment by bbuchfink** [comment]
If your DNA sequences do have P's for some reason I guess you need to replace them with N's before running diamond. I could also provide an option to have the program ignore them if that's more convenient.

**Comment by frcamacho** [comment]
That is alright I converted to N's since it wasn't many. By the way, is there an option to tell the output to include the query sequence that match to the database similarly to BLAST (qseq; Aligned part of query sequence)? Thanks for your help! I appreciate it!

**Comment by bbuchfink** [comment]
Yes, the diamond tabular output format can be customized in the same way as blast, see section 6.2 in the manual.
