### ISSUE TITLE
Adding an option for identity filtering?

### ISSUE THREAD

**Issue by wdingx** [bbuchfink/diamond#96]
The percentage of sequence identity and the alignment coverage have been widely used in pan-genome studies to identify orthologous relationship.
In diamond, the alignment coverage can be adjusted via --query-cover, whereas something like --identity has not yet been included in the parameter options.
It would be very useful to add an option like --identity to report only matches above the given percentage of identity.
Thank you for your consideration.

**Comment by bbuchfink** [comment]
There is an option --id to filter alignments below a certain identity%. For some reason it is not contained in the manual, sorry I need to fix that.

**Comment by wdingx** [comment]
Many thanks for your prompt reply.

**Comment by wdingx** [comment]
In some stringent filtering procedures, one needs not only query-cover, but also query-and-subject cover.
Could a new parameter be added for minimum alignment coverage percentage for both sequences?
Many thanks!

**Comment by bbuchfink** [comment]
Sure, I'll add this to the next version.

**Comment by wdingx** [comment]
Thanks! I am looking forward to using the new option.

**Comment by wdingx** [comment]
I have some additional questions on the DIAMOND's performance using -fast and -sensitive.
1. DIAMOND-sensitive uses 16 seed shapes. Could you provide some information on --more-sensitive mode?
2. In Figure 1 part c of your paper, matches recovered (%) for assembly ORFs is around 55% with fast mode and circa. 85% with sensitive mode.
Do you probably have some statistics on the range of assembly ORF length (protein length in my case) that is preferred when using fast or sensitive mode?
If the hybrid of both would work, one could potentially separate all-against-all protein alignment on large database into 2 parts with short proteins using -fast and long ORFs proteins using -sensitive or even -more-sensitive. That might help?
3. In the supplementary Table 1,  e-value below 0.00001 seems to outperform e-value below 0.001. Why is 0.001 used by default?

Thank you for your time.

**Comment by bbuchfink** [comment]
1. This mode uses the same shape configuration. The difference is that it will include more of the very frequent seeds in the search so it's more sensitive.
2. If the database contains a lot of very short proteins this could work, but I think for sequences longer than 70-80aa you probably need the sensitive mode for good sensitivity. I don't have any statistics for that.
3. I didn't want to use a very tight cutoff as default, 0.001 allows some more hits but it's really very application dependent what the best cutoff is.

**Comment by wdingx** [comment]
Thank you for your clear explanation.

**Comment by bbuchfink** [comment]
An option --subject-cover has now been added to the latest version.

2016-12-16 14:50 GMT+01:00 Wei Ding <notifications@github.com>:

**Comment by wdingx** [comment]
That's terrific!  Many thanks!
