### ISSUE TITLE
Error reading temporary file

### ISSUE THREAD

**Issue by andreyurch** [bbuchfink/diamond#97]
Deallocating buffers...  [0.04423s]
Opening temporary output file...  [0.545202s]
Computing alignments...  [14.6198s]
Deallocating reference...  [0.009504s]
Loading reference sequences...  [0.001587s]
Deallocating buffers...  [0.002634s]
Joining output blocks... Error: Error reading file /export/home/aay2c/PROJECTS/mac_annotation/diamond-58590c40-1f4.tmp
terminate called after throwing an instance of 'File_read_exception'
  what():  Error reading file /export/home/aay2c/PROJECTS/mac_annotation/diamond-58590c40-1f4.tmp
Aborted

**Comment by bbuchfink** [comment]
Hi,
does that always happen when you run diamond or just this once?

**Comment by andreyurch** [comment]
Never with swissprot, but always with Uniref50.  I have the newest version of diamond.

**Comment by bbuchfink** [comment]
What are your computer specs? (OS, CPU, RAM) Is that a network or local drive that contains the temp file?

**Comment by andreyurch** [comment]
Red Hat, cluster, 14 Dell Poweredge 6145 with Quad 16 core AMD Opteron 6376 and 512GB RAM per node
Local drive

**Comment by bbuchfink** [comment]
Please try to run the program with parameter `-t /dev/shm` and see if you get the same error.

**Comment by andreyurch** [comment]
It has finished without problems with this option :)
