### ISSUE TITLE
issue on e_value reports

### ISSUE THREAD

**Issue by wdingx** [bbuchfink/diamond#98]
DIAMOND uses 0.001 as default e-value cutoff, whereas the following hit with e-value > 0.001 has been observed .
NATL1A|02094    NATL1A|00083    37.8    45      25      1       7       48      445     489     1.2e+00 30.8

Test (all-against-all protein alignment on 2 different strains in strain2.faa):
diamond makedb -p 64 --in strain2.faa -d nr_smalltest
diamond blastp --sensitive -p 64 -d nr_smalltest -q strain2.faa -o query_matches_smalltest.m8 -t ./
(faa is not supported for uploading. strain2.faa.TXT is equal to strain2.faa )

[strain2.faa.TXT](https://github.com/bbuchfink/diamond/files/676171/strain2.faa.TXT)

**Comment by bbuchfink** [comment]
Can you try again using the option --single-domain please.

**Comment by wdingx** [comment]
Yes. Thanks! Using --single-domain ignores those hits with e-value > 0.001. But, does the option indicate that secondary domains within one target sequence will be discarded even if the e-value is < 0.001? What if one wants to keep them?

**Comment by bbuchfink** [comment]
Yes that means they will be discarded. You can't have it any other way right now but if this is relevant to you I can change it in the next version.

**Comment by wdingx** [comment]
Thanks. OK, that's just out of curiosity and does not need to be added now. (If secondary domains within one target sequence could have decent hits, they might contain some valuable information.)
So, if correctly understood, --single-domain outputs only the best hit with best e-value?

**Comment by bbuchfink** [comment]
Yes, correct.

**Comment by wdingx** [comment]
Many thanks!

**Comment by bbuchfink** [comment]
The --single-domain option is now the default behaviour, as this seems to
be confusing to a lot of users.

**Comment by wdingx** [comment]
Thank you very much for informing me. Alles Gute für 2017!
