### ISSUE TITLE
option for filtering self-against-self hits?

### ISSUE THREAD

**Issue by wdingx** [bbuchfink/diamond#99]
When using DIAMOND for all-against-all protein alignment, is it possible to ignore self-against-self hits (a new option like --no-self-hits)?

**Comment by bbuchfink** [comment]
There's no such option but I'll include it in the next release.

**Comment by bbuchfink** [comment]
This has now been added.

**Comment by wdingx** [comment]
It works well now. Thanks. Einen guten Rutsch ins neue Jahr!
